---
sidebar: sidebar 
permalink: hu-aix-70.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.0, netapp, ontap 
summary: Las utilidades de host AIX le ayudan a gestionar el almacenamiento de ONTAP conectado a un host AIX. 
---
= Instale AIX Host Utilities 7,0
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las utilidades de host AIX le ayudan a gestionar el almacenamiento de ONTAP conectado a un host AIX.

Las utilidades de host de AIX admiten los siguientes protocolos:

* FC
* FCoE
* ISCSI


Las utilidades de host de AIX son compatibles con los siguientes entornos:

* AIX Microsoft Multipath I/O (MPIO) (SO nativo)
* PowerVM
+
Para obtener más información acerca de PowerVM, consulte el libro rojo de movilidad de particiones activas de IBM PowerVM.



.Antes de empezar
* Para lograr un funcionamiento fiable, verifique que toda la configuración de iSCSI, FC o FCoE sea compatible.
+
Puede utilizar el https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar la configuración.

* El seguimiento dinámico debe estar habilitado para todos los iniciadores de FC y FCoE.



NOTE: El paquete de software de utilidades de host AIX de NetApp está disponible en en link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["Sitio de soporte de NetApp"^]un `tar.gz file` . Debe instalar el kit de utilidades del host AIX mientras usa AIX MPIO con almacenamiento de ONTAP.

.Pasos
. Inicie sesión en el host.
+
** En un host AIX, inicie sesión como *root*.
** En un host de PowerVM, inicie sesión como *padmin* y, a continuación, introduzca el `oem_setup_env` comando para convertirse en un usuario root.


. Vaya al https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.0["Sitio de soporte de NetApp"^] y descargue el archivo comprimido que contiene las utilidades de host en un directorio del host.
. Vaya al directorio que contiene la descarga.
. Descomprima el archivo y extraiga el paquete de software del kit de herramientas SAN:
+
`# tar -xvf ntap_aix_host_utilities_7.0.tar.gz`

+
El siguiente directorio se crea al descomprimir el archivo `ntap_aix_host_utilities_7.0`: . Este directorio contiene uno de los siguientes subdirectorios: MPIO, NON_MPIO o SAN_Tool_Kit.

. Instale el MPIO de AIX:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Instalación del kit DE herramientas SAN:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_7.0/SAN_Tool_Kit/NetApp.SAN_toolkit`

. Reinicie el host.
. Compruebe la instalación:
+
`# lslpp -l |grep -i netapp`

+
[listing]
----
NetApp.MPIO_Host_Utilities_Kit.config
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.fcp
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.iscsi
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
  NetApp.MPIO_Host_Utilities_Kit.pcmodm
                             7.0.0.0  COMMITTED  NetApp MPIO PCM Host Utilities
NetApp.SAN_toolkit.sanlun  7.0.0.0  COMMITTED  NetApp SAN Toolkit sanlun
----
. Confirme la versión de software:
+
`# sanlun version`

+
[listing]
----
7.0.725.3521
----
. Compruebe que el `lbp_enabled` parámetro SCSI UNMAP se ha agregado al ODM ejecutando los siguientes comandos:
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO" PdAt |grep  "lbp_enabled"`

+
[listing]
----
attribute = "lbp_enabled"
----
+
`# odmget -q "uniquetype=disk/fcp/NetAppMPIO and attribute=lbp_enabled" PdAt`

+
[listing]
----
PdAt:
        uniquetype = "disk/fcp/NetAppMPIO"
        attribute = "lbp_enabled"
        deflt = "true"
        values = "true,false"
        width = ""
        type = "R"
        generic = ""
        rep = "s"
        nls_index = 18
----




== Kit de herramientas SAN

AIX Host Utilities es un software de host NetApp que proporciona un kit de herramientas de línea de comandos en su host IBM AIX. El kit de herramientas se instala cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar los LUN y los adaptadores de bus de host (HBA). La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

*ejemplo*

En el siguiente ejemplo, la `sanlun lun show` Command muestra la información de la LUN.

[listing]
----
# sanlun lun show all
----
*Ejemplo de salida*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Este kit de herramientas es común en todas las configuraciones y protocolos de las utilidades de host. Como resultado, todos los componentes no se aplican a todas las configuraciones. Los componentes no utilizados no afectan al rendimiento del sistema. El kit de herramientas SAN es compatible con las versiones AIX y PowerVM/VIOS
