---
sidebar: sidebar 
permalink: hu-ol-810.html 
keywords: host utilities, oracle, linux, 8.10, netapp, ontap 
summary: Describe cómo usar Oracle Linux 8,10 con ONTAP 
---
= Utilice Oracle Linux 8,10 con ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host SAN de ONTAP para configurar Oracle Linux 8,10 con ONTAP como destino.



== Instale las utilidades unificadas de host de Linux

Es posible descargar el paquete de software de utilidades de host unificadas de NetApp como archivo 64-bit.rpm en el link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^].

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Pasos
. Descargue el paquete de software Linux Unified Host Utilities de 64 bits de https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] al host.
. Instale el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Kit de herramientas SAN

El kit de herramientas se instala automáticamente al instalar el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar los LUN y los adaptadores de bus de host (HBA). La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[listing]
----
# sanlun lun show all
----
.Resultado de ejemplo:
[listing]
----
controller(7mode/E-Series)/              device     host               lun
vserver(cDOT/FlashRay)  lun-pathname     filename   adapter  protocol  size   Product
-------------------------------------------------------------------------------------
data_vserver            /vol/vol1/lun1   /dev/sdb   host16   FCP       80.0g  cDOT
data_vserver            /vol/vol1/lun1   /dev/sdc   host15   FCP       80.0g  cDOT
data_vserver            /vol/vol2/lun2   /dev/sdd   host16   FCP       80.0g  cDOT
data_vserver            /vol/vol2/lun2   /dev/sde   host15   FCP       80.0g  cDOT
----


== Habilite el arranque SAN

Si decide utilizar el arranque SAN, debe ser compatible con su configuración.

.Antes de empezar
Utilice link:https://mysupport.netapp.com/matrix/imt.jsp?components=91863;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar que su sistema operativo, adaptador de bus de host, firmware de adaptador de bus de host, BIOS de arranque de HBA y versión de ONTAP sean compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo del host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

Para Oracle Linux 8,10, el `/etc/multipath.conf` archivo debe existir. No es necesario realizar cambios en este archivo porque Oracle Linux 8,10 se compila con la configuración necesaria para reconocer y gestionar correctamente los LUN de ONTAP.

En el caso de todas las configuraciones de cabina SAN (ASA) y que no son ASA, puede utilizar `multipath -ll` el comando para comprobar la configuración de una LUN de ONTAP, como se muestra en los ejemplos siguientes.


NOTE: Una única LUN no debería necesitar más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuraciones de ASA

En las configuraciones de ASA, todas las rutas a un LUN determinado son activas y optimizadas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

En el ejemplo siguiente se muestra la salida correcta de una LUN de ONTAP asignada a una persona de ASA:

[listing]
----
# multipath -ll
3600a098038314d79492b58306a727a6a dm-0 NETAPP,LUN C-Mode
size=180G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
  |- 11:0:7:6  sdbz 68:208  active ready running
  |- 11:0:11:6 sddn 71:80   active ready running
  |- 11:0:15:6 sdfb 129:208 active ready running
  |- 12:0:1:6  sdgp 132:80  active ready running
----


=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que son operadas por la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas solo se utilizan cuando las rutas optimizadas no están disponibles.

En el ejemplo siguiente se muestra el resultado correcto de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizada asignadas a una persona que no es ASA:

[listing]
----
# multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb	69:624	active ready running
| |- 16:0:5:35 sdun	66:752	active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj	66:48	active ready running
|- 15:0:1:35 sdbx	68:176	active ready running
----


== Configuración recomendada

El sistema operativo Oracle Linux 8,10 se compila para reconocer los LUN de ONTAP y definir automáticamente los parámetros de configuración correctos para las configuraciones ASA y no ASA. Además, se pueden utilizar las siguientes recomendaciones para optimizar aún más el rendimiento de la configuración del host:

 `multipath.conf`El archivo debe existir para que se inicie el daemon multivía. Si este archivo no existe, puede crear un archivo vacío de cero bytes con el `touch /etc/multipath.conf` comando.

La primera vez que crea el `multipath.conf` archivo, es posible que deba habilitar e iniciar los servicios multivía mediante los siguientes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
No es necesario agregar nada directamente al `multipath.conf` archivo a menos que tenga dispositivos que no desee que se gestionen con acceso multivía o que tenga una configuración existente que anule los valores predeterminados. Para excluir dispositivos no deseados, agregue la siguiente sintaxis al `multipath.conf` archivo y reemplace <DevId> por la cadena de identificador mundial (WWID) del dispositivo que desea excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
El siguiente ejemplo determina el WWID de un dispositivo y lo agrega al `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` Es el disco SCSI local que desea agregar a la lista negra.

. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Compruebe siempre el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para ver la configuración heredada que podría estar anulando la configuración predeterminada.

La siguiente tabla muestra `multipathd` los parámetros críticos de las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben corregirse mediante estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a las LUN de ONTAP. Sin esta corrección, es posible que las LUN de ONTAP no funcionen como se espera. Solo debe sobrescribir estos valores predeterminados en consulta con NetApp, el proveedor del sistema operativo o ambos, y solo cuando se comprenda completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | infinito 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | 2 pg_init_retries 50 


| flush_on_last_del | sí 


| manipulador_hardware | 0 


| no_path_retry | cola 


| comprobador_de_rutas | tur 


| política_agrupación_ruta | group_by_prio 


| selector_de_rutas | tiempo de servicio 0 


| intervalo_sondeo | 5 


| prioridad | ONTAP 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | uniforme 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
El siguiente ejemplo muestra cómo corregir un valor por defecto sustituido. En este caso, el `multipath.conf` archivo define valores para `path_checker` y `no_path_retry` que no son compatibles con las LUN de ONTAP. Si no pueden eliminarse debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una stanza de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----

NOTE: Para configurar el kernel compatible con Red Hat (RHCK) de Oracle Linux 8,10, utilice para link:hu_rhel_810.html#recommended-settings["configuración recomendada"]Red Hat Enterprise Linux (RHEL) 8,10.



== Configure los ajustes de KVM

No es necesario configurar ajustes para una máquina virtual basada en kernel porque la LUN está asignada al hipervisor.



== Problemas conocidos

No existen problemas conocidos para la versión Oracle Linux 8,10 con ONTAP.
