---
sidebar: sidebar 
permalink: hu-veritas-7x.html 
keywords: host utilities, veritas, infoscale, 7, netapp, ontap, sanhost, iscsi, red, hat linux, oracle, linux 
summary: Proporciona orientación sobre los ajustes de configuración del host SAN de ONTAP para el lanzamiento de la serie Veritas Infoscale 7 
---
= Configurar Veritas Infoscale 7 para FC, FCoE e iSCSI con almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software Linux Host Utilities proporciona herramientas de administración y diagnóstico para los hosts Linux que están conectados al almacenamiento ONTAP . Utilice las utilidades de host de Linux con Veritas Infoscale 7 para hosts Oracle Linux (basado en kernel compatible con Red Hat), Red Hat Enterprise Linux (RHEL) y SUSE Linux Enterprise Server para respaldar la administración de operaciones de protocolo FC, FCoE e iSCSI con LUN de ONTAP .



== Paso 1: Opcionalmente, habilite el arranque SAN

Puede configurar su host para que utilice el arranque SAN y simplificar la puesta en marcha y mejorar la escalabilidad.

.Antes de empezar
* Utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Linux, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.
* Consulte el Portal de soporte de Veritas (Matriz de productos, Búsqueda de plataforma y Matriz HCL) para verificar la compatibilidad de la configuración de arranque de SAN y los problemas conocidos.


.Pasos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Cree un LUN de arranque SAN y asígnelo al host"^].
. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Compruebe que la configuración se haya realizado correctamente. Para ello, reinicie el host y verifique que el sistema operativo esté activo y en ejecución.




== Paso 2: Instale las utilidades del host de Linux

NetApp recomienda encarecidamente link:hu-luhu-release-notes.html["Instalación de las utilidades de host de Linux"] para respaldar la administración de LUN de ONTAP y ayudar al soporte técnico con la recopilación de datos de configuración.


NOTE: La instalación de Linux Host Utilities no cambia ninguna configuración de tiempo de espera del host en el host Linux.



== Paso 3: Confirme la configuración de Veritas Dynamic Multipathing para su host

Utilice Veritas Dynamic Multipathing (VxDMP) con Veritas Infoscale 7 para administrar LUN de ONTAP .

Para asegurarse de que VxDMP esté configurado correctamente para su host, debe verificar la configuración de VxDMP y verificar la configuración de la Biblioteca de soporte de matriz (ASL) y del Módulo de política de matriz (APM). Los paquetes ASL y APM para los sistemas de almacenamiento NetApp se instalan durante la instalación del software Veritas.


NOTE: Para entornos multirruta heterogéneos, incluidos Veritas Infoscale, Linux Native Device Mapper y el administrador de volúmenes LVM, consulte la documentación de administración de productos de Veritas para conocer los ajustes de configuración.

.Antes de empezar
Asegúrese de que su configuración cumpla con los requisitos del sistema. Ver el link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] y la Matriz HCL de Veritas.

.Pasos
. Verifique que la matriz de destino ONTAP esté conectada a la ruta múltiple VxDMP:
+
[source, cli]
----
vxdmpadm
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
====
. Verifique la configuración de los paquetes ASL y APM. NetApp recomienda que utilice los últimos paquetes compatibles que aparecen en el portal de soporte de Veritas.
+
.Mostrar ejemplo de configuración de ASL y APM
[%collapsible]
====
[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so                  vm-8.0.0-rev-1   8.0

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----
====
. Para una configuración óptima del sistema en operaciones de conmutación por error de almacenamiento, verifique que tenga los siguientes parámetros ajustables de Veritas VxDMP:
+
[cols="2*"]
|===
| Parámetro | Ajuste 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval | 60 
|===
. Establezca los parámetros configurables de DMP en línea:
+
[source, cli]
----
# vxdmpadm settune dmp_tunable=value
----
. Verifica que la configuración de tunables es correcta:
+
[source, cli]
----
# vxdmpadm gettune
----
+
El siguiente ejemplo muestra los parámetros ajustables VxDMP efectivos en un host SAN.

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----
====
. Configure los valores de tiempo de espera del protocolo:
+
[role="tabbed-block"]
====
.FC/FCoE
--
Utilice los valores de tiempo de espera predeterminados para FC y FCoE.

--
.iSCSI
--
Establezca el `replacement_timeout` valor del parámetro a 120.

El iSCSI `replacement_timeout` El parámetro controla cuánto tiempo debe esperar la capa iSCSI a que una ruta o sesión agotada se restablezca antes de que falle cualquier comando en ella. NetApp recomienda establecer el valor de `replacement_timeout` a 120 en el archivo de configuración iSCSI.

[source, cli]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----
--
====
. Establezca los valores "udev rport" del host para los hosts de las series RHEL 8 y 9 para admitir el entorno de Veritas Infoscale en escenarios de conmutación por error de almacenamiento.
+
Configure los valores de "udev rport" creando el archivo `/etc/udev/rules.d/40-rport.rules` con el siguiente contenido de archivo:

+
[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----
+

NOTE: Consulte la documentación estándar del producto Veritas Infoscale para conocer todas las demás configuraciones específicas de Veritas.

. Compruebe la configuración de parámetros y el estado de la ruta de sus LUN de ONTAP:
+
En configuraciones AFF, FAS o ASA , un solo LUN de ONTAP no debería requerir más de cuatro rutas. Más de cuatro rutas pueden causar problemas durante una falla de almacenamiento.

+
Los siguientes ejemplos muestran la configuración de parámetros y el estado de ruta correctos para los LUN de ONTAP en una configuración ASA, AFF o FAS .

+
[role="tabbed-block"]
====
.Configuración de ASA
--
Una configuración de ASA optimiza todas las rutas a una LUN determinada para mantenerlas activas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED (A)    Active/Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A) Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED (A)    Active/Optimized c14   SFRAC       sfrac0     -
----
=====
--
.Configuración de AFF o FAS
--
Una configuración de AFF o FAS debe tener dos grupos de rutas con prioridades superiores e inferiores. La controladora donde se encuentra el agregado ofrece rutas activas/optimizadas de mayor prioridad. Las rutas de prioridad más baja están activas pero no optimizadas debido a que se sirven con una controladora diferente. Las rutas no optimizadas solo se usan cuando las rutas optimizadas no están disponibles.

En el siguiente ejemplo, se muestra el resultado de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizada:

.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----
=====
--
====




== Paso 4: Problemas conocidos

No hay problemas conocidos.



== El futuro

* link:hu-luhu-command-reference.html["Obtenga más información sobre el uso de la herramienta Linux Host Utilities"] .

