---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_powervm_vscsi.html 
keywords: host utilities, aix, powervm, 7.2 netapp, ontap, luns, configure, discover, configuring, discovering 
summary: Describe cómo utilizar la detección y configuración de LUN con PowerVM vSCSI 
---
= (PowerVM vSCSI) detectar y configurar LUN
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cuando utiliza servidores PowerVM vSCSI y VIO, debe utilizar el inicio de sesión padmin y los comandos apropiados para configurar y detectar LUN.

.Pasos
. Inicie sesión en el host como padmin.
. En el host AIX, introduzca el siguiente comando para detectar las LUN recién creadas:
+
`cfgdev`

+
El comando cfgdev provoca:

+
** Los iniciadores que desea iniciar sesión en la estructura.
** El sistema para comprobar si hay dispositivos nuevos.
** El sistema para crear nuevas entradas del dispositivo donde se asignan las nuevas LUN como dispositivos MPIO con el PCM predeterminado.


. Para verificar que se han creado los dispositivos hdisk MPIO, introduzca el siguiente comando:
+
`lsdev -type disk`

+
Los LUN aparecen en el host como discos. Puede utilizar estos discos de la misma manera que utiliza discos locales en el host.

+
Anote los números de instancia de hdisk. Los utiliza cuando realiza la configuración de ruta.

+
La `lsdev -type disk` el comando genera el siguiente tipo de salida. El resultado de este ejemplo se ha truncado.

+
[listing]
----
vioserver$ lsdev -type disk NetApp
name     status      description
hdisk0   Available   16 Bit LVD SCSI Disk Drive
hdisk1   Available   16 Bit LVD SCSI Disk Drive
hdisk2   Available   MPIO NetApp FCP Default PCM Disk
hdisk3   Available   MPIO NetApp FCP Default PCM Disk
hdisk4   Available   MPIO NetApp FCP Default PCM Disk
hdisk5   Available   MPIO NetApp FCP Default PCM Disk
hdisk6   Available   MPIO NetApp FCP Default PCM Disk
----
. Para obtener información sobre la configuración, introduzca el siguiente comando:
+
`lsdev -dev hdisk_name -attr`

+
La `lsdev -dev hdisk_name -attr` el comando genera la siguiente salida:

+
[listing]
----
vioserver$ lsdev -dev hdisk2 -attr
attribute value                   description                user-settable
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistent Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Si la configuración no admite ALUA, debe ejecutar la utilidad dotpaths para establecer las prioridades de la ruta. La utilidad dotpaths se instala al instalar Host Utilities. No utilice la utilidad dotpaths si ALUA está habilitado. Cambie a la `oem_setup_env` modo para ejecutar las dotpaths introduciendo el siguiente comando:
+
`oem_setup_env`

+
Cuando introduzca la `oem_setup_env` mode (modo), el símbolo de línea de comandos cambia de un signo de dólar a un símbolo de libra y permanece en `oem_setup_env` mode hasta que lo detenga introduciendo un comando como exit.

+
.Ejemplo
``# vioserver$ oem_setup_env`

. Si su configuración admite ALUA, puede usarlo para establecer la prioridad de ruta. Compruebe que ALUA está habilitado:
+
`lun igroup show -instance igroup_name`

+
.. Si ALUA no está habilitado, habilite:
+
`igroup set igroup_name alua yes`



. Si la configuración no admite ALUA, debe ejecutar la utilidad dotpaths para establecer las prioridades de la ruta. La utilidad dotpaths se instala al instalar Host Utilities. No utilice la utilidad dotpaths si ALUA está habilitado.
+
.. Para establecer la prioridad de todas las LUN de Data ONTAP, introduzca:
+
`dotpaths`

.. Para establecer la prioridad de un conjunto específico de discos, introduzca:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Utilice la `-v` opción para habilitar el modo detallado y mostrar todas las prioridades. Utilice la `-q` opción de consultar todas las prioridades de disco o individuales.

+
A continuación se muestra un ejemplo de uso de la utilidad dotpaths:

+
[listing]
----
vioserver# dotpaths -v
hdisk2 (path 0): Optimized path - Setting priority to 255
hdisk2 (path 1): Optimized path - Setting priority to 255
hdisk2 (path 2): Unoptimized path - Current priority of 1 is correct
hdisk2 (path 3): Unoptimized path - Current priority of 1 is correct
...
Path priority set and/or verified for 22 disks, 86 total paths.
vioserver#
----


. Para verificar que el host ha detectado las LUN, introduzca el siguiente comando:
+
`# sanlun lun show -p`

+
.Ejemplo
Este ejemplo muestra el resultado típico de `sanlun lun show -p` para una configuración de conexión directa. También incluye la `sanlun lun show -d hdisk9 -v` comando para mostrar información acerca de hdisk9. El resultado de este comando se ha truncado.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ------------- ----------
host      controller  AIX            controller    AIX MPIO
path      path        MPIO   host    target        path
state     type        path   adapter port          priority
--------- ----------- ------ ------- ------------- ----------
up        secondary   path0  fcs0    3b              1
up        primary     path1  fcs0    3a              1
up        secondary   path2  fcs0    3a              1
up        primary     path3  fcs0    3b              1
up        secondary   path4  fcs0    4b              1
up        secondary   path5  fcs0    4a              1
up        primary     path6  fcs0    4b              1
up        primary     path7  fcs0    4a              1
up        secondary   path8  fcs1    3b              1
up        primary     path9  fcs1    3a              1
up        secondary   path10 fcs1    3a              1
up        primary     path11 fcs1    3b              1
up        secondary   path12 fcs1    4b              1
up        secondary   path13 fcs1    4a              1
up        primary     path14 fcs1    4b              1
up        primary     path15 fcs1    4a              1
----
+
[listing]
----
sanlun lun show -vd hdisk10
                                                                      device          host                  lun
vserver              lun-pathname                                     filename        adapter    protocol   size    mode
------------------------------------------------------------------------------------------------------------------------
GPFS_p520_FC         /vol/GPFS_p520_FC_FlexVol_2/GPFS_p520_FC_LUN_2_4 hdisk10         fcs3       FCP        100g    C
             LUN Serial number: 1k/yM$-ia5HC
         Controller Model Name: N5600
          Vserver FCP nodename: 200200a0980c892f
          Vserver FCP portname: 200a00a0980c892f
              Vserver LIF name: GPFS_p520_FC_2
            Vserver IP address: 10.225.121.100
           Vserver volume name: GPFS_p520_FC_FlexVol_2  MSID::0x00000000000000000000000080000420
         Vserver snapshot name:
----

