---
sidebar: sidebar 
permalink: hu_aix_72_sanbooting_aix.html 
keywords: host utilities, aix, netapp, ontap, configure, discover, configuring, discovering 
summary: Describe cómo detectar y configurar LUN con AIX 
---
= (AIX MPIO sin PowerVM) detectar y configurar LUN con AIX
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Cuando está utilizando AIX sin PowerVM, utilice el comando cfgmgr para obtener el host para detectar las LUN. No es necesario reiniciar el host para detectar los LUN. Para confirmar que el host ha detectado LAS LUN, puede utilizar la utilidad sanlun.


NOTE: Los pasos siguientes no se aplican a un host que ejecuta un entorno PowerVM.

.Pasos
. Inicie sesión como root en el host.
. En el host AIX, introduzca el siguiente comando para detectar las LUN recién creadas:
+
`cfgmgr`

+
La `cfgmgr` el comando ayuda con lo siguiente:

+
** Los iniciadores que desea iniciar sesión en la estructura.
** El sistema para comprobar si hay dispositivos nuevos.
** El sistema para crear nuevas entradas de dispositivo.


. Para mostrar todos los discos AIX, incluidas las LUN de NetApp, introduzca el siguiente comando:
+
`lsdev -Cc disk`

+
Los LUN aparecen en el host como discos. Puede utilizar estos discos de la misma manera que utiliza discos locales en el host. La configuración del host ODM que se instala como parte de las utilidades de host hace que los LUN se muestren como discos FCP de NetApp.

+
Anote los números de instancia de hdisk. Los utiliza cuando realiza la configuración de ruta.

+
A continuación, se muestra el tipo de salida que genera el comando lsdev -cc disk en un entorno que utiliza FC.

+
[listing]
----
# lsdev -Cc disk
hdisk0 Available 08-08-00-5,0 16 Bit LVD SCSI Disk Drive
hdisk1 Available 08-08-00-8,0 16 Bit LVD SCSI Disk Drive
hdisk2 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk3 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk4 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
hdisk5 Available 04-08-02  MPIO NetApp FCP Default PCM Disk
----
. Escriba el siguiente comando para obtener información sobre su configuración:
+
`lsattr -El hdisk_name`

+
Este comando genera el siguiente resultado.

+
[listing]
----
# lsattr -El hdisk65
PCM   PCM/friend/NetApp   PCM Path Control Module          False
PR_key_value    none                             Persistant Reserve Key Value            True
algorithm       round_robin                      Algorithm                               True
clr_q           no                               Device CLEARS its Queue on error        True
dist_err_pcnt   0                                Distributed Error Sample Time           True
dist_tw_width   50                               Distributed Error Sample Time           True
hcheck_cmd      inquiry                          Health Check Command                    True
hcheck_interval 30                               Health Check Interval                   True
hcheck_mode     nonactive                        Health Check Mode                       True
location                                         Location Label                          True
lun_id          0x2000000000000                  Logical Unit Number ID                  False
lun_reset_spt   yes                              LUN Level Reset                         True
max_transfer    0x100000                         Maximum TRANSFER Size                   True
node_name       0x500a0980894ae0e0               FC Node Name                            False
pvid            00067fbad453a1da0000000000000000 Physical volume identifier              False
q_err           yes                              Use QERR bit                            True
q_type          simple                           Queuing TYPE                            True
qfull_dly       2                                Delay in seconds for SCSI TASK SET FULL True
queue_depth     64                               Queue DEPTH                             True
reassign_to     120                              REASSIGN time out value                 True
reserve_policy  no_reserve                       Reserve Policy                          True
rw_timeout      30                               READ/WRITE time out value               True
scsi_id         0xd10001                         SCSI ID                                 False
start_timeout   60                               START unit time out value               True
ww_name         0x500a0984994ae0e0               FC World Wide Name                      False
----
. Si su configuración admite ALUA, puede usarlo para establecer la prioridad de ruta. Compruebe que ALUA está habilitado:
+
`lun igroup show -instance igroup_name`

+
.. Si ALUA no está habilitado, habilite:
+
`igroup set igroup_name alua yes`



. Si la configuración no admite ALUA, debe ejecutar la utilidad dotpaths para establecer las prioridades de la ruta. La utilidad dotpaths se instala al instalar Host Utilities. No utilice la utilidad dotpaths si ALUA está habilitado.
+
.. Para establecer la prioridad de todas las LUN de Data ONTAP, introduzca:
+
`dotpaths`

.. Para establecer la prioridad de un conjunto específico de discos, introduzca:
+
`dotpaths [-hqv] [hdiskN ...]`

+
Utilice la `-v` opción para habilitar el modo detallado y mostrar todas las prioridades. Utilice la `-q` opción de consultar todas las prioridades de disco o individuales.



. Para verificar que el host ha detectado las LUN, introduzca el siguiente comando:
+
`# sanlun lun show`

+
.Ejemplo
Este ejemplo muestra el resultado típico de `sanlun lun show` En un entorno multivía MPIO.

+
[listing]
----
sanlun lun show -p

                    ONTAP Path: fas3170-aix03:/vol/ibmbc_aix01b14_fcp_vol8/ibmbc-aix01b14_fcp_lun0
                           LUN: 8
                      LUN Size: 3g
           Controller CF State: Cluster Enabled
            Controller Partner: fas3170-aix04
                   Host Device: hdisk9
                          Mode: 7
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
--------- ----------- ------ ------- ---------------------------------------------- ----------
host      controller  AIX            controller                                     AIX MPIO
path      path        MPIO   host    target                                         path
state     type        path   adapter port                                           priority
--------- ----------- ------ ------- ---------------------------------------------- ----------
up        secondary   path0  fcs0    3b                                             1
up        primary     path1  fcs0    3a                                             1
up        secondary   path2  fcs0    3a                                             1
up        primary     path3  fcs0    3b                                             1
up        secondary   path4  fcs0    4b                                             1
up        secondary   path5  fcs0    4a                                             1
up        primary     path6  fcs0    4b                                             1
up        primary     path7  fcs0    4a                                             1
up        secondary   path8  fcs1    3b                                             1
up        primary     path9  fcs1    3a                                             1
up        secondary   path10 fcs1    3a                                             1
up        primary     path11 fcs1    3b                                             1
up        secondary   path12 fcs1    4b                                             1
up        secondary   path13 fcs1    4a                                             1
up        primary     path14 fcs1    4b                                             1
up        primary     path15 fcs1    4a                                             1
----

