---
sidebar: sidebar 
permalink: hu_aix_71.html 
keywords: host utilities, aix, 7.1 netapp, ontap 
summary: Describe cómo utilizar IBM AIX 7.1 con ONTAP 
---
= Utilice IBM AIX 7,1 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host SAN de ONTAP para configurar IBM AIX 7,1 con ONTAP como destino.



== Instale AIX Host Utilities

Debe instalar el kit de utilidades de host de AIX mientras utiliza AIX MPIO con almacenamiento ONTAP de NetApp.

Puede descargar el archivo comprimido que contiene los paquetes de software de Utilidades de host en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Sitio de soporte de NetApp"^]. Después de tener el archivo, debe extraerlo para obtener los dos paquetes de software que necesita para instalar Host Utilities.

.Pasos
. Inicie sesión en el host.
+
** En un host AIX, inicie sesión como *root*.


. Descargue una copia del archivo comprimido que contiene las utilidades de host del sitio de soporte de NetApp en un directorio del host.
. Vaya al directorio que contiene la descarga.
. Descomprimir el archivo y extraer el paquete DE software DE SAN Toolkit.
+
`tar -xvf ntap_aix_host_utilities_6.1.tar.tgz`

+
Al descomprimir el archivo se crea el siguiente directorio: `ntap_aix_host_utilities_6.1`. Este directorio tendrá uno de los siguientes subdirectorios: MPIO, NON_MPIO o SAN_Tool_Kit.

. Instale el MPIO de AIX:
+
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Instalación del kit DE herramientas SAN:
`installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`
. Reinicie el host.




== Kit de herramientas SAN

El kit de herramientas se instala automáticamente al instalar el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[listing]
----
#sanlun lun show

controller(7mode)/                  device      host       lun
vserver(Cmode)    lun-pathname     filename    adapter   protocol   size   mode
--------------------------------------------------------------------------------
data_vserver      /vol/vol1/lun1    hdisk0      fcs0       FCP       60g    C
data_vserver      /vol/vol2/lun2    hdisk0      fcs0       FCP       20g    C
data_vserver      /vol/vol3/lun3    hdisk11     fcs0       FCP       20g    C
data_vserver      /vol/vol4/lun4    hdisk14     fcs0       FCP       20g    C

----


== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=71102;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

El arranque SAN es el proceso de configurar un disco conectado a UNA SAN (un LUN) como dispositivo de arranque para un host AIX. Puede configurar un LUN de arranque SAN para que funcione en un entorno AIX MPIO que ejecute las utilidades del host AIX con el protocolo FC o FCoE. El método que utiliza para crear un LUN de arranque SAN e instalar una nueva imagen de sistema operativo en un entorno AIX MPIO puede variar en función del protocolo que utilice.



== Accesos múltiples

La función multivía le permite configurar varias rutas de red entre el host y el sistema de almacenamiento. Si una ruta falla, el tráfico continúa en las rutas restantes. El entorno AIX de Host Utilities utiliza la solución multivía nativa de AIX, MPIO.

Para AIX, el módulo de control de rutas (PCM) es responsable de controlar varias rutas. PCM es un código del proveedor de almacenamiento que gestiona la gestión de rutas. Esto se instala y se habilita como parte de la instalación de utilidades de host.



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con las mayores prioridades son activo/optimizado, lo que significa que la controladora donde se encuentra el agregado es la que presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1

----


=== Configuraciones de cabinas All SAN

En todas las configuraciones de cabinas SAN (ASA), todas las rutas a un LUN determinado se mantienen activas y optimizadas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra la salida correcta de una LUN de ONTAP:


NOTE: Todas las configuraciones de cabinas SAN (ASA) son compatibles a partir de ONTAP 9.8 para hosts AIX.

[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----


== Configuración recomendada

A continuación se muestran algunas configuraciones de parámetros recomendadas para las LUN de ONTAP.  Los parámetros críticos para las LUN de ONTAP se establecen automáticamente después de instalar el kit de utilidades de host de NetApp.

[cols="4*"]
|===
| Parámetro | Entorno Oracle | Valor para AIX | Nota 


| algoritmo | MPIO | round_robin | Establezca Host Utilities 


| hcheck_cmd | MPIO | consulta | Establezca Host Utilities 


| hcheck_interval | MPIO | 30 | Establezca Host Utilities 


| hcheck_mode | MPIO | no activo | Establezca Host Utilities 


| lun_reset_spt | MPIO/sin MPIO | sí | Establezca Host Utilities 


| transferencia máx | MPIO/sin MPIO | LUN de FC: 0x100000 bytes | Establezca Host Utilities 


| qfull_dly | MPIO/sin MPIO | retraso de 2 segundos | Establezca Host Utilities 


| queue_depth | MPIO/sin MPIO | 64 | Establezca Host Utilities 


| política_de_reserva | MPIO/sin MPIO | no_reserva | Establezca Host Utilities 


| tiempo de espera (disco) | MPIO/sin MPIO | 30 segundos | Utiliza valores predeterminados del SO 


| dintrik | MPIO/sin MPIO | Sí | Utiliza valores predeterminados del SO 


| fc_err_recov | MPIO/sin MPIO | Fast_fail | Utiliza valores predeterminados del SO 


| q_type | MPIO/sin MPIO | sencillo | Utiliza valores predeterminados del SO 


| núm_cmd_elems | MPIO/sin MPIO | 1024 para AIX | FC EN1B, FC EN1C 


| núm_cmd_elems | MPIO/sin MPIO | 500 para AIX (independiente/físico) 200 para VIOC | FC EN0G 
|===


== Configuración recomendada para MetroCluster

De forma predeterminada, el sistema operativo AIX aplica un tiempo de espera de I/o más corto cuando no hay rutas a una LUN disponibles. Esto puede suceder en configuraciones que incluyen una estructura SAN de switch único y configuraciones de MetroCluster que experimentan recuperaciones tras fallos no planificadas. Para obtener información adicional y los cambios recomendados en la configuración predeterminada, consulte link:https://kb.netapp.com/app/answers/answer_view/a_id/1001318["KB1001318 de NetApp"^]



== Compatibilidad de AIX con sincronización activa de SnapMirror

A partir de ONTAP 9.11.1, AIX es compatible con la sincronización activa de SnapMirror. Con una configuración AIX, el clúster primario es el clúster "activo".

En una configuración AIX, las recuperaciones tras fallos son disruptivas. Con cada conmutación al nodo de respaldo, deberá realizar un nuevo análisis en el host para que se reanuden las operaciones de I/O.

Para configurar AIX para SM-BC, consulte el artículo de la base de conocimientos link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_configure_an_AIX_host_for_SnapMirror_Business_Continuity_(SM-BC)["Cómo configurar un host AIX para la sincronización activa de SnapMirror"^].



== Problemas conocidos

No hay problemas conocidos.
