---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Describe cómo utilizar IBM AIX 7.2 y/o PowerVM VIOS 3.1 con ONTAP 
---
= Instale AIX Host Utilities 6,1 para almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las utilidades de host AIX le ayudan a administrar el almacenamiento ONTAP conectado a un host AIX.  NetApp recomienda encarecidamente instalar AIX Host Utilities para mejorar la administración del almacenamiento de ONTAP y ayudar al soporte de NetApp a recopilar información sobre su configuración.

AIX Host Utilities 6.1 admite los siguientes protocolos de transporte y entornos AIX:

* FC, FCoE e iSCSI
* E/S de rutas múltiples de Microsoft AIX (MPIO)
* PowerVM
+
Para obtener más información acerca de PowerVM, consulte el libro rojo de movilidad de particiones activas de IBM PowerVM.



.Acerca de esta tarea
* Debe instalar el kit de herramientas SAN de AIX Host Utilities con AIX MPIO para administrar el almacenamiento ONTAP conectado a un host AIX.
* Cuando instala AIX Host Utilities, no modifican ninguna configuración en su host AIX.


.Antes de empezar
* Utilice ellink:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que su sistema operativo AIX, su protocolo y la versión de ONTAP admitan el arranque SAN.
* Habilite el seguimiento dinámico para todos los iniciadores FC y FCoE ejecutando el `chdev -l <fscsi_device> -a dyntrk=ye` comando en el host AIX.


.Pasos
. Inicie sesión en el host.
+
[role="tabbed-block"]
====
.AIX
--
En un host AIX, inicie sesión como *root*.

--
.PowerVM
--
En un host PowerVM:

.. Inicie sesión como *padmin*.
.. Conviértete en usuario root:
+
[source, cli]
----
oem_setup_env
----


--
====
. Vaya a la https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Sitio de soporte de NetApp"^] Y descargue el archivo comprimido que contiene las utilidades de host en un directorio del host.
. Vaya al directorio que contiene la descarga.
. Descomprimir el archivo y extraer el paquete DE software DE SAN Toolkit.
+
[source, cli]
----
tar -xvf ntap_aix_host_utilities_6.1.tar.gz
----
+
Al descomprimir el archivo se crea el siguiente directorio: `ntap_aix_host_utilities_6.1`. Este directorio tendrá uno de los siguientes subdirectorios: MPIO, NON_MPIO o SAN_Tool_Kit.

. Instale el MPIO de AIX:
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit
----
. Instalación del kit DE herramientas SAN:
+
[source, cli]
----
installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit
----
. Reinicie el host.
. Compruebe la instalación:
+
[source, cli]
----
sanlun version
----




== El futuro

link:hu-aix-san-toolkit.html["Obtenga más información sobre el kit de herramientas SAN de AIX"] .
