---
sidebar: sidebar 
permalink: hu_aix_61_cmd.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2, 7.0, netapp, ontap 
summary: Puede usar la referencia de comando de muestra de AIX Host Utilities para una validación integral de la configuración del almacenamiento de NetApp mediante la herramienta Host Utilities. 
---
= Ejemplo de referencia de comandos de AIX Host Utilities
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede usar la referencia de comando de muestra de AIX Host Utilities para una validación integral de la configuración del almacenamiento de NetApp mediante la herramienta Host Utilities.



== Enumere todos los iniciadores de hosts asignados al host

Puede recuperar una lista de iniciadores de host asignados a un host.

[source, cli]
----
# sanlun fcp show adapter -v
----
*Ejemplo de salida*

[listing]
----
bash-3.2# sanlun fcp show adapter -v
adapter name: fcs0
WWPN: 100000109b22e143
WWNN: 200000109b22e143
driver name: /usr/lib/drivers/pci/emfcdd
model: df1000e31410150
model description: FC Adapter
serial number: YA50HY79S117
hardware version: Not Available
driver version: 7.2.5.0
firmware version: 00012000040025700027
Number of ports: 1
port type: Fabric
port state: Operational
supported speed: 16 GBit/sec
negotiated speed: Unknown
OS device name: fcs0
adapter name: fcs1
WWPN: 100000109b22e144
WWNN: 200000109b22e144
driver name: /usr/lib/drivers/pci/emfcdd
model: df1000e31410150
model description: FC Adapter
serial number: YA50HY79S117
hardware version: Not Available
driver version: 7.2.5.0
firmware version: 00012000040025700027
Number of ports: 1
port type: Fabric
port state: Operational
supported speed: 16 GBit/sec
negotiated speed: Unknown
OS device name: fcs1
bash-3.2#
----


== Enumere todas las LUN asignadas al host

Puede recuperar una lista de todas las LUN asignadas a un host.

[source, cli]
----
# sanlun lun show -p -v all
----
*Ejemplo de salida*

[listing]
----
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver  AIX   AIX MPIO
path    path     MPIO  host      vserver      path
state   type     path  adapter   LIF          priority
-----------------------------------------------------
up     primary   path0   fcs0    fc_aix_1     1
up     primary   path1   fcs1    fc_aix_2     1
up     secondary path2   fcs0    fc_aix_3     1
up     secondary path3   fcs1    fc_aix_4     1
----


== Enumere todas las LUN asignadas al host desde una SVM determinada

Puede recuperar una lista de todas las LUN asignadas a un host de una SVM especificada.

[source, cli]
----
# sanlun lun show -p -v sanboot_unix
----
*Ejemplo de salida*

[listing]
----
ONTAP Path: sanboot_unix:/vol/aix_205p2_boot_0/boot_205p2_lun
LUN: 0
LUN Size: 80.0g
Host Device: hdisk85
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host    vserver    AIX   AIX MPIO
path    path       MPIO  host    vserver    path
state   type       path  adapter LIF        priority
-------------------------------------------------
up      primary    path0 fcs0    sanboot_1   1
up      primary    path1 fcs1    sanboot_2   1
up      secondary  path2 fcs0    sanboot_3   1
up      secondary  path3 fcs1    sanboot_4   1
----


== Enumere todos los atributos de una LUN asignada al host

Puede recuperar una lista de todos los atributos de una LUN especificada asignada a un host.

[source, cli]
----
# sanlun lun show -p -v vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
----
*Ejemplo de salida*

[listing]
----
ONTAP Path: vs_aix_clus:/vol/gpfs_205p2_207p1_vol_0_8/aix_205p2_207p1_lun
LUN: 88
LUN Size: 15g
Host Device: hdisk9
Mode: C
Multipath Provider: AIX Native
Multipathing Algorithm: round_robin

host     vserver   AIX   AIX MPIO
path     path      MPIO  host     vserver   path
state    type      path  adapter  LIF       priority
---------------------------------------------------------
up       primary   path0 fcs0    fc_aix_1   1
up       primary   path1 fcs1    fc_aix_2   1
up       secondary path2 fcs0    fc_aix_3   1
up       secondary path3 fcs1    fc_aix_4   1
----


== Muestra los atributos de los LUN de ONTAP por nombre de archivo del dispositivo host

Puede recuperar una lista de atributos de LUN de ONTAP especificando un nombre de archivo de dispositivo host.

[source, cli]
----
#sanlun lun show -d /dev/hdisk1
----
*Ejemplo de salida*

[listing]
----
controller(7mode)/
device host lun
vserver(Cmode)     lun-pathname
-----------------------------------------------------------------------------
vs_aix_clus       /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun

filename adapter protocol size mode
-----------------------------------
hdisk1    fcs0    FCP     15g  C
----


== Enumere todos los WWPN de LIF de destino de SVM asociados al host

Puede recuperar una lista de todos los WWPN de LIF de destino de SVM que están conectados a un host.

[source, cli]
----
# sanlun lun show -wwpn
----
*Ejemplo de salida*

[listing]
----
controller(7mode)/
target device host lun
vserver(Cmode)          wwpn            lun-pathname
--------------------------------------------------------------------------------

vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_0/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_0_9/aix_205p2_207p1_lun
vs_aix_clus          203300a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_0/aix_205p2_207p1_lun_en
vs_aix_clus          202f00a098ba7afe  /vol/gpfs_205p2_207p1_vol_en_0_1/aix_205p2_207p1_lun_en

filename     adapter    size  mode
-----------------------------------
hdisk1       fcs0       15g    C
hdisk10      fcs0       15g    C
hdisk11      fcs0       15g    C
hdisk12      fcs0       15g    C
----