---
sidebar: sidebar 
permalink: hu_aix_71.html 
keywords: host utilities, aix, 7.1 netapp, ontap 
summary: Describe cómo utilizar IBM AIX 7.1 con ONTAP 
---
= Configurar AIX 7.1 para FCP e iSCSI con almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software AIX Host Utilities proporciona herramientas de administración y diagnóstico para los hosts AIX que están conectados al almacenamiento ONTAP .  Cuando instala las utilidades de host de AIX en un host de AIX 7.1, puede usarlas para ayudarlo a administrar las operaciones de protocolo FCP e iSCSI con LUN de ONTAP .



== Paso 1: Opcionalmente, habilite el arranque SAN

Puede configurar su host para utilizar el arranque SAN para simplificar la implementación y mejorar la escalabilidad.  Si su configuración no admite el arranque SAN, puede utilizar un arranque local.

[role="tabbed-block"]
====
.Arranque SAN
--
El arranque SAN es el proceso de configurar un disco conectado a SAN (un LUN) como dispositivo de arranque para un host AIX/PowerVM.  Puede configurar un LUN de arranque SAN para que funcione en un entorno AIX Multipath I/O (MPIO) que utilice el protocolo FC y ejecute AIX Host Utilities con el protocolo FC o FCoE.  El método que utiliza para crear un LUN de arranque SAN e instalar una nueva imagen del sistema operativo en un entorno AIX MPIO depende del protocolo que esté utilizando.

.Pasos
. Utilice ellink:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que su sistema operativo AIX, su protocolo y la versión de ONTAP admitan el arranque SAN.
. Siga las mejores prácticas para configurar un arranque SAN en la documentación del proveedor.


--
.Arranque local
--
Realice un arranque local instalando el sistema operativo AIX en el disco duro local, por ejemplo, en un SSD, SATA o RAID.

--
====


== Paso 2: Instalar las utilidades del host AIX

NetApp recomienda encarecidamente instalar AIX Host Utilities para respaldar la administración de LUN de ONTAP y ayudar al soporte técnico con la recopilación de datos de configuración.  El paquete MPIO de Host Utilities proporciona soporte MPIO para AIX y VIOS.


NOTE: La instalación de AIX Host Utilities proporciona configuraciones de tiempo de espera adicionales en su host AIX.

link:hu_aix_61.html["Instalar AIX Host Utilities 6.1"] .



== Paso 3: Confirme la configuración multivía del host

Puede utilizar rutas múltiples con un host AIX 7.1 para administrar LUN de ONTAP .

La función de múltiples rutas le permite configurar múltiples rutas de red entre el host y el sistema de almacenamiento.  Si una ruta falla, el tráfico continúa con las rutas restantes.  Los entornos AIX y PowerVM de Host Utilities utilizan la solución de múltiples rutas nativa de AIX (MPIO).

El módulo de control de ruta (PCM) es responsable de controlar múltiples rutas para un host AIX.  El PCM es un código suministrado por el proveedor de almacenamiento que maneja la administración de rutas y se instala y habilita durante la instalación de Host Utilities.

Para garantizar que la función de rutas múltiples esté configurada correctamente para su host, verifique que tenga configuradas las configuraciones recomendadas de NetApp para sus LUN de ONTAP .

.Pasos
. Las utilidades de host de AIX cargan las siguientes configuraciones de parámetros para los LUN de ONTAP .
+
.Muestra la configuración de los parámetros
[%collapsible]
====
[cols="4*"]
|===
| Parámetro | Entorno Oracle | Valor para AIX | Nota 


| algoritmo | MPIO | round_robin | Establezca Host Utilities 


| hcheck_cmd | MPIO | consulta | Establezca Host Utilities 


| hcheck_interval | MPIO | 30 | Establezca Host Utilities 


| hcheck_mode | MPIO | no activo | Establezca Host Utilities 


| lun_reset_spt | MPIO/sin MPIO | sí | Establezca Host Utilities 


| transferencia máx | MPIO/sin MPIO | LUN de FC: 0x100000 bytes | Establezca Host Utilities 


| qfull_dly | MPIO/sin MPIO | retraso de 2 segundos | Establezca Host Utilities 


| queue_depth | MPIO/sin MPIO | 64 | Establezca Host Utilities 


| política_de_reserva | MPIO/sin MPIO | no_reserva | Establezca Host Utilities 


| tiempo de espera (disco) | MPIO/sin MPIO | 30 segundos | Utiliza valores predeterminados del SO 


| dintrik | MPIO/sin MPIO | Sí | Utiliza valores predeterminados del SO 


| fc_err_recov | MPIO/sin MPIO | Fast_fail | Utiliza valores predeterminados del SO 


| q_type | MPIO/sin MPIO | sencillo | Utiliza valores predeterminados del SO 


| núm_cmd_elems | MPIO/sin MPIO | 1024 para AIX | FC EN1B, FC EN1C 


| núm_cmd_elems | MPIO/sin MPIO | 500 para AIX (independiente/físico) 200 para VIOC | FC EN0G 
|===
====
. Si su configuración de almacenamiento incluye sincronización activa de MetroCluster o SnapMirror , cambie la configuración predeterminada:
+
[role="tabbed-block"]
====
.MetroCluster
--
De forma predeterminada, el sistema operativo AIX aplica un tiempo de espera de E/S más corto cuando no hay rutas disponibles a un LUN.  Esto podría ocurrir en configuraciones que incluyen una estructura SAN de un solo conmutador y en configuraciones de MetroCluster que experimentan conmutaciones por error no planificadas.  Para obtener información adicional y cambios recomendados en la configuración predeterminada, consulte el artículo de la Base de conocimientoslink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["¿Cuáles son las consideraciones de soporte de host AIX en una configuración de MetroCluster ?"^] .

--
.Sincronización activa de SnapMirror
--
A partir de ONTAP 9.11.1, la sincronización activa de SnapMirror es compatible con un host AIX.  El clúster principal en una configuración AIX es el clúster "activo".

En una configuración AIX, las conmutaciones por error son disruptivas.  Con cada conmutación por error, es necesario volver a realizar un escaneo en el host para que se reanuden las operaciones de E/S.

Consulte el artículo de la base de conocimientoslink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Cómo configurar un host AIX para la sincronización activa de SnapMirror"^] .

--
====
. Verifique el estado de la ruta para los LUN de ONTAP :
+
[source, cli]
----
sanlun lun show
----
+
Los siguientes ejemplos de salida muestran el estado de ruta correcto para los LUN de ONTAP en una configuración ASA, AFF o FAS .

+
[role="tabbed-block"]
====
.Configuraciones de ASA
--
Una configuración ASA optimiza todas las rutas a un LUN determinado, manteniéndolas activas ("principales").  Esto mejora el rendimiento al atender operaciones de E/S a través de todas las rutas al mismo tiempo.

.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------ ------- ------ ------- --------- ----------
host   vserver  AIX                      AIX MPIO
path   path     MPIO   host    vserver     path
state  type     path   adapter LIF       priority
------ ------- ------ ------- --------- ----------
up     primary  path0  fcs0    fc_aix_1     1
up     primary  path1  fcs0    fc_aix_2     1
up     primary  path2  fcs1    fc_aix_3     1
up     primary  path3  fcs1    fc_aix_4     1
----
=====
--
.Configuración de AFF o FAS
--
Una configuración de AFF o FAS debe tener dos grupos de rutas con prioridades superiores e inferiores. La controladora donde se encuentra el agregado ofrece rutas activas/optimizadas de mayor prioridad. Las rutas de prioridad más baja están activas pero no optimizadas debido a que se sirven con una controladora diferente. Las rutas no optimizadas solo se usan cuando las rutas optimizadas no están disponibles.

El siguiente ejemplo muestra la salida correcta para un LUN de ONTAP con dos rutas activas/optimizadas ("principales") y dos rutas activas/no optimizadas ("secundarias"):

.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
# sanlun lun show -p |grep -p hdisk78
                    ONTAP Path: vs_aix_clus:/vol/chataix_205p2_vol_en_1_7/jfs_205p2_lun_en
                           LUN: 37
                      LUN Size: 15g
                   Host Device: hdisk78
                          Mode: C
            Multipath Provider: AIX Native
        Multipathing Algorithm: round_robin
------- ---------- ------ ------- ---------- ----------
host    vserver    AIX                        AIX MPIO
path    path       MPIO   host    vserver         path
state   type       path   adapter LIF         priority
------- ---------- ------ ------- ---------- ----------
up      secondary  path0  fcs0    fc_aix_1        1
up      primary    path1  fcs0    fc_aix_2        1
up      primary    path2  fcs1    fc_aix_3        1
up      secondary  path3  fcs1    fc_aix_4        1
----
=====
--
====




== Paso 4: Revisar los problemas conocidos

La versión AIX 7.1 con almacenamiento ONTAP no tiene problemas conocidos.



== El futuro

link:hu-aix-command-reference.html["Obtenga información sobre el uso de la herramienta Utilidades de host de AIX"] .
