---
sidebar: sidebar 
permalink: hu_aix_61.html 
keywords: host utilities, aix, powervm, vios, 3.1, 7.2 netapp, ontap 
summary: Describe cómo utilizar IBM AIX 7.2 y/o PowerVM VIOS 3.1 con ONTAP 
---
= Instale AIX Host Utilities 6,1 para almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las utilidades de host AIX le ayudan a gestionar el almacenamiento de ONTAP conectado a un host AIX.

Las utilidades de host de AIX admiten los siguientes protocolos:

* FC
* FCoE
* ISCSI


Las utilidades de host de AIX son compatibles con los siguientes entornos:

* AIX Microsoft Multipath I/O (MPIO) (SO nativo)
* PowerVM
+
Para obtener más información acerca de PowerVM, consulte el libro rojo de movilidad de particiones activas de IBM PowerVM.



.Antes de empezar
* Para lograr un funcionamiento fiable, verifique que toda la configuración de iSCSI, FC o FCoE sea compatible.
+
Puede utilizar el link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar la configuración.

* Habilite el seguimiento dinámico para todos los iniciadores FC y FCoE.



NOTE: El paquete de software de utilidades de host AIX de NetApp está disponible en en link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Sitio de soporte de NetApp"^]un `tar.gz file` . Debe instalar el kit de utilidades del host AIX mientras usa AIX MPIO con almacenamiento de ONTAP.

.Pasos
. Inicie sesión en el host.
+
** En un host AIX, inicie sesión como *root*.
** En un host de PowerVM, inicie sesión como *padmin* y, a continuación, introduzca el `oem_setup_env` comando para convertirse en un usuario root.


. Vaya a la https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.1/downloads["Sitio de soporte de NetApp"^] Y descargue el archivo comprimido que contiene las utilidades de host en un directorio del host.
. Vaya al directorio que contiene la descarga.
. Descomprimir el archivo y extraer el paquete DE software DE SAN Toolkit.
+
`# tar -xvf ntap_aix_host_utilities_6.1.tar.gz`

+
Al descomprimir el archivo se crea el siguiente directorio: `ntap_aix_host_utilities_6.1`. Este directorio tendrá uno de los siguientes subdirectorios: MPIO, NON_MPIO o SAN_Tool_Kit.

. Instale el MPIO de AIX:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/MPIO NetApp.MPIO_Host_Utilities_Kit`

. Instalación del kit DE herramientas SAN:
+
`# installp -aXYd /var/tmp/ntap_aix_host_utilities_6.1/SAN_Tool_Kit NetApp.SAN_toolkit`

. Reinicie el host.
. Compruebe la instalación:
+
[listing]
----
# sanlun version
----




== Kit de herramientas SAN

AIX Host Utilities es un software de host NetApp que proporciona un kit de herramientas de línea de comandos en su host IBM AIX. El kit de herramientas se instala al instalar el paquete de utilidades de host. Este kit proporciona la `sanlun` utilidad, que le ayuda a gestionar los LUN y los adaptadores de bus de host (HBA). El `sanlun` comando muestra información acerca de las LUN asignadas al host, la multivía y la información necesaria para crear iGroups.

*ejemplo*

En el siguiente ejemplo, la `sanlun lun show` Command muestra la información de la LUN.

[listing]
----
# sanlun lun show all
----
*Ejemplo de salida*

[listing]
----
controller(7mode)/ device host lun

vserver(Cmode) lun-pathname filename adapter protocol size mode
----------------------------------------------------------------
data_vserver   /vol/vol1/lun1 hdisk0 fcs0    FCP      60g C
data_vserver   /vol/vol2/lun2 hdisk0 fcs0    FCP      20g C
data_vserver   /vol/vol3/lun3 hdisk11 fcs0   FCP      20g C
data_vserver   /vol/vol4/lun4 hdisk14 fcs0   FCP      20g C
----

NOTE: Este kit de herramientas es común en todas las configuraciones y protocolos de las utilidades de host. Como resultado, todos los componentes no se aplican a todas las configuraciones. Los componentes no utilizados no afectan al rendimiento del sistema. El kit de herramientas SAN es compatible con las versiones AIX y PowerVM/VIOS
