---
sidebar: sidebar 
permalink: hu_citrix_8x.html 
keywords: host utilities, citrix, hypervisor, 8.0, 8.1, 8.2, netapp, ontap, sanhost 
summary: Describe cómo usar Citrix Hypervisor 8.x con ONTAP 
---
= Uso del hipervisor Citrix con ONTAP de NetApp
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Introducción

En este documento se ofrecen directrices sobre los ajustes de configuración de host SAN de ONTAP para las versiones de sistema operativo del hipervisor Citrix serie 8 con protocolos FC, FCoE e iSCSI.



== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se haya realizado correctamente.




== Accesos múltiples

Para Citrix Hypervisor (CH) 8.x el `/etc/multipath.conf` el archivo debe existir, pero no es necesario realizar cambios específicos en el archivo. CH 8.x se compila con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP. Puede utilizar el `/sbin/mpathutil` Comando de estado para comprobar la configuración de sus LUN de ONTAP. En las siguientes secciones se proporciona muestra la salida multivía para una LUN asignada a ASA personas.



=== Configuración de cabina All SAN (ASA)

Para la configuración de cabina All SAN (ASA) debe haber un grupo de rutas con prioridades únicas. Todas las rutas son activas/optimizadas, lo que significa que la controladora recibe servicio y que se envían I/o en todas las rutas activas.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con cuatro rutas activas/optimizadas:

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
policy='service-time 0' prio=50 status=active
  |- 11:0:7:1    sdfi   130:64   active ready running
  |- 11:0:9:1    sdiy  8:288     active ready running
  |- 11:0:10:1  sdml 69:464   active ready running
  |- 11:0:11:1  sdpt  131:304  active ready running
....

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de 4 rutas. Más de 8 rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuración no ASA

Para la configuración que no sea ASA debe haber dos grupos de rutas con prioridades diferentes. Las rutas con las mayores prioridades son activo/optimizado, lo que significa que la controladora donde se encuentra el agregado es la que presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas solo se usan cuando no hay rutas optimizadas disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizadas:

....
# mpathutil status
3600a09803830344674244a357579386a dm-13 NETAPP  ,LUN C-Mode
size=30G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
 |- 1:0:0:11   sde   8:64    active ready running
`- 12:0:8:11  sdua  66:544  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
   |- 1:0:9:11   sddo  71:96   active ready running
   `- 12:0:26:11 sdyt  129:720 active ready running
....

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



== Configuración recomendada

El sistema operativo Citrix Hypervisor 8.x se compila con todas las opciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP. Para Citrix Hypervisor 8.x, un zerobite vacío `/etc/multipath.conf` el archivo debe existir, pero no es necesario realizar cambios específicos en el archivo.

Active el servicio de acceso múltiple desde *XenCenter Management Portal* y compruebe que el servicio de acceso múltiple está activado y en ejecución.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
No hay ningún requisito para agregar contenido al `/etc/multipath.conf` archivo, a menos que tenga dispositivos que no desea gestionar mediante multivía o que tenga la configuración existente que anula los valores predeterminados. Puede agregar la siguiente sintaxis al archivo multipath.conf para excluir los dispositivos no deseados.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Sustituya *<DevID>* por la cadena WWID del dispositivo que desea excluir.

.Ejemplo
En este ejemplo para Citrix Hypervisor 8.x, `sda` Es el disco SCSI local que necesitamos agregar a la lista negra.

. Ejecute el siguiente comando para determinar el WWID:
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Añada este WWID a la sección de la lista negra del `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Consulte la configuración de parámetro multivía en tiempo de ejecución mediante el `$multipathd show config` comando. Siempre debe comprobar la configuración en ejecución de los valores heredados que podrían ser la configuración predeterminada, especialmente en la sección valores predeterminados.

En la siguiente tabla se muestran los parámetros críticos *multipathd* para las LUN ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben ser corregidos por stanzas posteriores en *multipath.conf* que se apliquen específicamente a las LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Los siguientes valores predeterminados solo se deben anular consultando con NetApp o con el proveedor de sistemas operativos, y únicamente cuando se haya comprendido completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| `detect_prio` | sí 


| `dev_loss_tmo` | "infinito" 


| `failback` | inmediata 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | "sí" 


| `hardware_handler` | "0" 


| `path_checker` | "tur" 


| `path_grouping_policy` | "group_by_prio" 


| `path_selector` | "tiempo de servicio 0" 


| `polling_interval` | 5 


| `prio` | "ONTAP" 


| `product` | LUN.* 


| `retain_attached_hw_handler` | sí 


| `rr_weight` | "uniforme" 


| `user_friendly_names` | no 


| `vendor` | NETAPP 
|===
.Ejemplo
El ejemplo siguiente ilustra cómo corregir un valor predeterminado anulado. En este caso, el archivo *multipath.conf* define los valores para *path_checker* y *Detect_prio* que no son compatibles con los LUN de ONTAP. Si no se pueden quitar debido a otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix Hypervisor recomienda el uso de las herramientas de Citrix VM para todos los equipos virtuales invitados basados en Linux y Windows para una configuración compatible.



== Problemas y limitaciones conocidos

[cols="4*"]
|===
| ID de error de NetApp | Título | Descripción | ID de Citrix Tracker 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1242343["1242343"^] | Interrupción del kernel en Citrix Hypervisor 8.0 con QLogic QLE2742 FC de 32 GB durante las operaciones de conmutación por error del almacenamiento | Puede producirse la interrupción del kernel durante las operaciones de conmutación por error del almacenamiento en el kernel Citrix Hypervisor 8.0 (4.19.0+1) con QLogic QLE2742 32 GB HBA. Este problema provoca un reinicio del sistema operativo y la interrupción de las aplicaciones. Si se configura kdump, la interrupción del kernel genera un archivo vmcore en el directorio /var/crash/. Puede usar el archivo vmcore para comprender la causa del error. Tras la interrupción del kernel, puede recuperar el sistema operativo reiniciando el sistema operativo host y reiniciando la aplicación. | link:https://tracker.citrix.com/browse/NETAPP-98["NETAPP-98"^] 
|===