---
sidebar: sidebar 
permalink: hu_citrix_7x.html 
keywords: host utilities, citrix, XenServer, 7 series, netapp, ontap, san, boot 
summary: Describe cómo usar Citrix XenServer 7.x con ONTAP 
---
= Utilice Citrix XenServer con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede configurar las opciones de configuración del host SAN ONTAP para versiones del sistema operativo Citrix XenServer serie 7 con protocolos FC, FCoE e iSCSI.



== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=91241;&solution=236&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

La compatibilidad con varias rutas en Citrix XenServer se basa en los componentes de Device Mapper Multipathd. Los nodos de asignación de dispositivos no se crean automáticamente para todas las LUN presentadas a XenServer y solo se aprovisionan cuando el nivel de gestión de almacenamiento (API) utiliza los LUN de forma activa. El complemento de API de Citrix XenServer Storage Manager controla la activación y desactivación de nodos multivía automáticamente.

Debido a las incompatibilidades de la arquitectura de gestión multivía integrada, Citrix recomienda utilizar la aplicación Citrix XenCenter para gestionar la configuración de almacenamiento. Si es necesario consultar el estado de las tablas de Device Mapper manualmente o enumerar los nodos multivía activos del asignador de dispositivos en el sistema, puede utilizar el `/sbin/mpathutil status` Comando para verificar la configuración de las LUN de ONTAP. Para obtener más información, consulte la documentación estándar del proveedor para Citrix XenServer.



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que son operadas por la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
|-+- policy='service-time 0' prio=10 status=enabled
  |- 2:0:0:0   sda   8:0     active ready running
  |- 2:0:1:0   sdb   8:16    active ready running
  |- 12:0:3:0  sd1   8:176   active ready running
  `-12:0:6:0   sdo   8:224   active ready running
[root@sanhost ~]#
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuración de cabina All SAN

En las configuraciones de cabina All SAN (ASA), todas las rutas a una unidad lógica (LUN) dada están activas y optimizadas. Esto significa que la I/o se puede ofrecer a través de todas las rutas al mismo tiempo y, de este modo, se mejora el rendimiento.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con las cuatro rutas activas/optimizadas:

[listing]
----
# mpathutil status
show topology
3600a098038303458772450714535317a dm-0 NETAPP  , LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 2:0:2:0   sdc   8:32    active ready running
| |- 12:0:5:0  sdn   8:208   active ready running
| |- 2:0:6:0   sdg   8:96    active ready running
| `- 12:0:0:0  sdi   8:128   active ready running
[root@sanhost ~]#
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuración recomendada

El sistema operativo Citrix XenServer 7.x se compila con todas las opciones necesarias para reconocer y administrar correctamente las LUN de ONTAP. Para Citrix XenServer 7.x, un zerobite vacío `/etc/multipath.conf` el archivo debe existir, pero no es necesario realizar cambios específicos en el archivo.

Active el servicio de acceso múltiple desde *XenCenter Management Portal* y compruebe que el servicio de acceso múltiple está activado y en ejecución.

[listing]
----
# systemct1 status multipathd
multipathd.service - Device-Mapper Multipath Device Controller
  Loaded:  load (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
 Drop-In:  /etc/systemd/system/multipathd.service.d
             slice.config
  Active:  active (running) since Fri YYYY-MM-DD 00:00:26 IST; 1 month 9 days ago
Main PID:  3789 (multipathd)
  CGroup:  /control.slice/multipathd.service
            3789  /sbin/multipathd
----
No es necesario agregar contenido al `/etc/multipath.conf` archivo, a menos que tenga dispositivos que no desea que se gestionen con acceso multivía o que tenga una configuración existente que anule los valores predeterminados. Puede agregar la siguiente sintaxis al `multipath.conf` archivo para excluir los dispositivos no deseados.

[listing]
----
# cat /etc/multipath.conf
blacklist {
     wwid    <DevId>
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----

NOTE: Sustituya *<DevID>* por la cadena WWID del dispositivo que desea excluir.

.Ejemplo
En el siguiente ejemplo para Citrix XenServer 7.x, `sda` es el disco SCSI local que desea agregar a la lista negra.

. Ejecute el siguiente comando para determinar el WWID:
+
[listing]
----
# lib/udev/scsi_id -gud /dev/sda
3600a098038303458772450714535317a
----
. Añada este WWID a la sección de la lista negra del `/etc/multipath.conf`:
+
[listing]
----
#cat /etc/multipath.conf
blacklist {
  wwid    3600a098038303458772450714535317a
  devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9*]"
  devnode "^hd[a-z]"
  devnode "^cciss.*"
}
----


Consulte la configuración de parámetro multivía en tiempo de ejecución mediante el `$multipathd show config` comando. Siempre debe comprobar la configuración en ejecución de los valores heredados que podrían ser la configuración predeterminada, especialmente en la sección valores predeterminados.

En la siguiente tabla se muestran los parámetros críticos *multipathd* para las LUN ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben ser corregidos por stanzas posteriores en *multipath.conf* que se apliquen específicamente a las LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Los siguientes valores predeterminados solo se deben anular consultando con NetApp o con el proveedor de sistemas operativos, y únicamente cuando se haya comprendido completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| `detect_prio` | sí 


| `dev_loss_tmo` | "infinito" 


| `failback` | inmediata 


| `fast_io_fail_tmo` | 5 


| `features` | "3 queue_if_no_path pg_init_retries 50" 


| `flush_on_last_del` | "sí" 


| `hardware_handler` | "0" 


| `path_checker` | "tur" 


| `path_grouping_policy` | "group_by_prio" 


| `path_selector` | "tiempo de servicio 0" 


| `polling_interval` | 5 


| `prio` | "ONTAP" 


| `product` | LUN.* 


| `retain_attached_hw_handler` | sí 


| `rr_weight` | "uniforme" 


| `user_friendly_names` | no 


| `vendor` | NETAPP 
|===
.Ejemplo
El ejemplo siguiente ilustra cómo corregir un valor predeterminado anulado. En este caso, el archivo *multipath.conf* define los valores para *path_checker* y *Detect_prio* que no son compatibles con los LUN de ONTAP. Si no se pueden quitar debido a otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
# cat /etc/multipath.conf
defaults {
  path_checker readsector0
  detect_prio no
}
devices{
        device{
                vendor "NETAPP "
                product "LUN.*"
                path_checker tur
                detect_prio yes
        }
}
----

NOTE: Citrix XenServer recomienda el uso de las herramientas de Citrix VM para todos los equipos virtuales invitados basados en Linux y Windows para una configuración compatible.



== Problemas conocidos

No existen problemas conocidos para el lanzamiento de Citrix XenServer con ONTAP.
