---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Describe cómo usar las utilidades unificadas de host de Linux 7.1 con ONTAP 
---
= HP-UX Host Utilities 6.0
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Las utilidades unificadas de host de HP-UX le ayudan a gestionar el almacenamiento de NetApp ONTAP conectado a un host de HP-UX.



== Kit de herramientas SAN

HP-UX Host Utilities es un software host de NetApp que proporciona un kit de herramientas de línea de comandos en su host HP-UX. El kit de herramientas se instala cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad que le ayuda a gestionar las LUN y los HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra la información de la LUN.

[listing]
----
# sanlun lun show all

controller(7mode)/ device host lun
vserver(Cmode)           lun-pathname                   filename          adapter    protocol   size   mode
------------------------------------------------------------------------------------------------------------
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c34t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c23t0d0  fclp1      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c12t0d0  fclp0      FCP        150g    C
sanboot_unix         /vol/hpux_boot/boot_hpux_lun      /dev/rdsk/c81t0d0  fclp0      FCP        150g    C

----

NOTE: Este kit de herramientas es común en todas las configuraciones y protocolos de Host Utilities. Como resultado, parte de su contenido se aplica a una configuración, pero no a otra. El hecho de tener componentes sin utilizar no afecta al rendimiento del sistema.



== Instalación de HP-UX Host Utilities

El paquete de software HP-UX Host Utilities de NetApp está disponible en la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] en un archivo comprimido.

Puede descargar el archivo comprimido que contiene los paquetes de software de Utilidades de host en la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^]. Después de descargar el archivo, debe descomprimirlo antes de instalarlo.

.Pasos
. Inicie sesión en el host.
. Descargue el archivo HP-UX Host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` desde la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] Al host HP-UX.
. Descomprimir el `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` file introduciendo el comando siguiente:
+
`# gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz`

+
El sistema coloca el software extraído en el directorio en el que descomprimió el archivo de almacén.

. Instale el software introduciendo el siguiente comando:
+
`# swinstall -s /depot_path`

+
`depot_path` proporciona la ruta y el nombre del archivo del almacén.

+
La `swinstall` Ejecuta una secuencia de comandos de instalación que comprueba el estado de la instalación de HP-UX. Si el sistema cumple los requisitos, este script instala el `sanlun` scripts de utilidad y diagnóstico en `/opt/NetApp/santools/bin` directorio.

. Compruebe la instalación:
+
`sanlun version`


