---
sidebar: sidebar 
permalink: hu_hpux_60.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Describe cómo usar HP-UX Host Utilities 6,0 con almacenamiento ONTAP 
---
= Instale HP-UX Host Utilities 6,0 para almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las utilidades de host HP-UX le ayudan a administrar el almacenamiento ONTAP conectado a un host HP-UX.  NetApp recomienda encarecidamente instalar HP-UX Host Utilities, pero no es obligatorio.  Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre su configuración.

Las utilidades de host HP-UX admiten los siguientes entornos:

* I/O multivía nativa de Microsoft (MPIO)
* Accesos múltiples dinámicos (DMP) de Veritas


.Antes de empezar
Para un funcionamiento confiable, utilice el https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que su configuración iSCSI, FC o FCoE sea compatible.

.Pasos
. Inicie sesión en su host HP-UX.
. Descargue el archivo HP-UX Host Utilities `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` desde la link:https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^] Al host HP-UX.
. Descomprimir el `netapp_hpux_host_utilities_6.0_ia_pa.depot.gz` archivo:
+
[source, cli]
----
gunzip netapp_hpux_host_utilities_6.0_ia_pa.depot.gz
----
+
El sistema coloca el software extraído en el directorio en el que descomprimió el archivo de almacén.

. Instale el software:
+
[source, cli]
----
swinstall -s /depot_path
----
+
`depot_path` proporciona la ruta y el nombre del archivo del almacén.

+
La `swinstall` Ejecuta una secuencia de comandos de instalación que comprueba el estado de la instalación de HP-UX. Si el sistema cumple los requisitos, este script instala el `sanlun` scripts de utilidad y diagnóstico en `/opt/NetApp/santools/bin` directorio.

. Compruebe la instalación:
+
[source, cli]
----
sanlun version
----




== El futuro

link:hu-hpux-sanlun-toolkit.html["Obtenga más información sobre el kit de herramientas SAN"] .
