---
sidebar: sidebar 
permalink: hu_hpux_11iv3.html 
keywords: host utilities, hp_ux, 11iv3, netapp, ontap 
summary: Instale Linux Host Utilities en un host HP-UX 11i v3 para administrar operaciones de protocolo FCP e iSCSI con LUN de ONTAP . 
---
= Configurar HP-UX 11i v3 para FCP e iSCSI con almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software HP-UX Host Utilities proporciona herramientas de administración y diagnóstico para los hosts HP-UX que están conectados al almacenamiento ONTAP .  Al instalar las utilidades de host HP-UX en un host HP-UX 11i v3, puede usar las utilidades de host para ayudarlo a administrar las operaciones de protocolo FCP e iSCSI con LUN de ONTAP .



== Paso 1: Opcionalmente, habilite el arranque SAN

Configure su host para utilizar el arranque SAN para simplificar la implementación y mejorar la escalabilidad.  El arranque SAN es el proceso de configurar un disco conectado a SAN (un LUN) como dispositivo de arranque para un host HP-UX.  Las utilidades de host admiten el arranque SAN con protocolos FC y FCoE en entornos HP-UX.

.Pasos
. Utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Linux, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.
. Siga las mejores prácticas para configurar un arranque SAN en la documentación del proveedor de HP-UX.




== Paso 2: Instalar las utilidades de host HP-UX

NetApp recomienda encarecidamente instalar HP-UX Host Utilities para respaldar la administración de LUN de ONTAP y ayudar al soporte técnico con la recopilación de datos de configuración.

link:hu_hpux_60.html["Instale HP-UX Host Utilities 6,0"]



== Paso 3: Confirme la configuración multivía del host

Utilice rutas múltiples con HP-UX 11i v3 para administrar LUN de ONTAP .  La función de múltiples rutas le permite configurar múltiples rutas de red entre el host y el sistema de almacenamiento.  Si una ruta falla, el tráfico continúa por las rutas restantes.

Después de instalar HP-UX Host Utilities, verifique que tenga configuradas las configuraciones recomendadas de NetApp para sus LUN de ONTAP .

.Acerca de esta tarea
Las utilidades de host HP-UX admiten E/S multiruta nativa de Microsoft (MPIO) y multiruta dinámica de Veritas.  Los siguientes pasos son para la solución MPIO nativa.

.Pasos
. Cuando instala HP-UX Host Utilities, las siguientes configuraciones predeterminadas recomendadas se cargan automáticamente para los LUN de ONTAP .
+
.Muestra la configuración de los parámetros
[%collapsible]
====
[cols="2*"]
|===
| Parámetro | Utiliza el valor predeterminado 


| segundos_transitorios | 120 


| leg_mpath_enable | VERDADERO 


| max_q_depth | 8 


| path_fail_secs | 120 


| load_bal_policy | Round_robin 


| lua_enabled | VERDADERO 


| esd_segundos | 30 
|===
====
. Compruebe la configuración de parámetros y el estado de la ruta de sus LUN de ONTAP:
+
[source, cli]
----
sanlun lun show
----
+
Los parámetros multiruta predeterminados admiten configuraciones ASA, AFF y FAS .  Los siguientes ejemplos de salida muestran la configuración de parámetros y el estado de ruta correctos para los LUN de ONTAP en una configuración ASA, AFF o FAS .

+
[role="tabbed-block"]
====
.Configuración de ASA
--
Una configuración de ASA optimiza todas las rutas a una LUN determinada para mantenerlas activas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
# sanlun lun show -p vs39:/vol/hpux_vol_1_1/hpux_lun

                    ONTAP Path: vs39:/vol/hpux_vol_1_1/hpux_lun
                           LUN: 2
                      LUN Size: 30g
                   Host Device: /dev/rdisk/disk25
                          Mode: C
            Multipath Provider: None
-------- ---------- -------------------- ------- --------------
host     vserver    /dev/dsk
path     path       filename             host    vserver
state    type       or hardware path     adapter LIF
-------- ---------- -------------------- ------- --------------
up       primary    /dev/dsk/c4t0d2      fcd0    248_1c_hp
up       primary    /dev/dsk/c6t0d2      fcd0    246_1c_hp
up       primary    /dev/dsk/c10t0d2     fcd1    246_1d_hp
up       primary    /dev/dsk/c8t0d2      fcd1    248_1d_hp
----
=====
--
.Configuración de AFF o FAS
--
Una configuración de AFF o FAS debe tener dos grupos de rutas con prioridades superiores e inferiores. La controladora donde se encuentra el agregado ofrece rutas activas/optimizadas de mayor prioridad. Las rutas de prioridad más baja están activas pero no optimizadas debido a que se sirven con una controladora diferente. Las rutas no optimizadas solo se usan cuando las rutas optimizadas no están disponibles.

En el siguiente ejemplo, se muestra el resultado de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizada:

.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
# sanlun lun show -p vs39:/vol/vol24_3_0/lun24_0
                    ONTAP Path: vs39:/vol/vol24_3_0/lun24_0
                           LUN: 37
                      LUN Size: 15g
                   Host Device: /dev/rdisk/disk942
                          Mode: C
              Multipath Policy: A/A
            Multipath Provider: Native
------- ---------- ------ ------- ---------- ---------- --------------
host    vserver     /dev/dsk                            HP A/A
path    path        filename          host    vserver   path failover
state   type        or hardware path adapter    LIF     priority
------- ---------- ------ ------- ---------- ---------- --------------
up       primary    /dev/dsk/c39t4d5   fcd0    hpux_3     0
up       primary    /dev/dsk/c41t4d5   fcd1    hpux_4     0
up       secondary  /dev/dsk/c40t4d5   fcd0    hpux_3     1
up       secondary  /dev/dsk/c42t4d5   fcd1    hpux_4     1
----
=====
--
====




== Paso 4: Revisar los problemas conocidos

La versión HP-UX 11i v3 con almacenamiento ONTAP tiene los siguientes problemas conocidos:

[cols="4*"]
|===
| ID de error de NetApp | Título | Descripción | ID de partner 


| 1447287 | El evento AUFO en el clúster maestro aislado de la configuración de sincronización activa de SnapMirror provoca una interrupción temporal en el host de HP-UX | Este problema se produce cuando hay un evento de conmutación por error automática no planificada (AUFO) en el clúster maestro aislado en la configuración de sincronización activa de SnapMirror. Se puede tardar más de 120 segundos en reanudar la actividad de I/o en el host HP-UX, pero esto puede no provocar ninguna interrupción de I/o o ni mensajes de error. Este problema provoca un fallo de evento doble porque se pierde la conexión entre el clúster primario y el secundario y también se pierde la conexión entre el clúster principal y el mediador. Esto se considera un evento raro, a diferencia de otros eventos de AUFO. | NA 


| 1344935 | El host HP-UX 11.31 informa intermitentemente del estado de la ruta de acceso de forma incorrecta en la instalación de ASA. | Problemas en la generación de informes de rutas con la configuración de ASA. | NA 


| 1306354 | La creación de LVM de HP-UX envía E/S del tamaño de bloque por encima de 1 MB | La longitud máxima de transferencia SCSI de 1 MB se aplica en la matriz All SAN de ONTAP. Para restringir la longitud máxima de transferencia de los hosts HP-UX cuando se conectan a la matriz All SAN de ONTAP, es necesario establecer el tamaño máximo de E/S permitido por el subsistema SCSI HP-UX en 1 MB. Consulte la documentación del proveedor de HP-UX para obtener más detalles. | NA 
|===


== ¿Qué sigue?

link:hu_hpux_60_cmd.html["Obtenga información sobre el uso de la herramienta HP-UX Host Utilities"] .
