---
sidebar: sidebar 
permalink: hu_luhu_71.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Describe cómo usar las utilidades unificadas de host de Linux 7.1 con ONTAP 
---
= Instale Linux Unified Host Utilities 7,1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Las utilidades unificadas de host de Linux le ayudan a gestionar el almacenamiento de NetApp ONTAP conectado a un host Linux. NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

Se admiten las siguientes distribuciones de Linux:

* Red Hat Enterprise Linux
* SUSE Linux Enterprise Server
* Oracle Linux
* Oracle VM
* Citrix XenServer


.Lo que necesitará
El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 bits o 64 bits.

* Para lograr un funcionamiento fiable, es necesario verificar que se admite toda la configuración de iSCSI, FC o FCoE.
+
Puede utilizar el https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar la configuración.

* Debe instalar los paquetes de gestión del adaptador de bus de host (HBA) disponibles en el sitio de soporte del proveedor.
+
El software de gestión permite que los comandos del kit de herramientas de SAN recopilen información acerca de los HBA de FC, como sus WWPN. Para la `sanlun fcp show adapter` comando para funcionar, compruebe que los siguientes paquetes están correctamente instalados:

+
** Marvell QLogic HBA: CLI de QConvergeConsole
** HBA de Broadcom Emulex: CLI de aplicación central de OneCommand Manager
** Marvell Brocade HBA – CLI de la utilidad de comandos de Brocade


* Los paquetes «libhbaapi» y «libhbalinux» disponibles para cada distribución de Linux deben instalarse en el sistema operativo host.



NOTE: El software Linux Unified Host Utilities no es compatible con los protocolos de host NVMe over Fibre Channel (NVMe/FC) y NVMe over TCP (NVMe/TCP).

.Pasos
. Si tiene una versión de Linux Unified Host Utilities instalada actualmente, utilice el siguiente comando para eliminarla:
+
[source, cli]
----
rpm -e netapp_linux_unified_host_utilities-7-1
----
+
Para versiones anteriores de Linux Host Utilities, vaya al directorio donde está instalado el software de la utilidad de host e introduzca el comando de desinstalación para eliminar el paquete instalado.

. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] al host.
. Vaya al directorio en el que ha descargado el paquete de software y utilice el comando siguiente para instalarlo:
+
[source, cli]
----
rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm
----
+
*Ejemplo de salida*

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Compruebe la instalación:
+
[source, cli]
----
sanlun version
----
+
*Ejemplo de salida*

+
[listing]
----
sanlun version 7.1.386.1644
----




== Configuración de controlador recomendada con el kernel de Linux

Cuando configura un entorno FC que utiliza controladores de bandeja de entrada nativos que se incluyen en el núcleo de Linux, puede utilizar los valores predeterminados para los controladores.



== Kit de herramientas SAN

Linux Unified Host Utilities es un software de host de NetApp que proporciona un kit de herramientas de línea de comandos para el host Linux.

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----
[NOTE]
====
* Este kit de herramientas es común en todas las configuraciones y protocolos de Host Utilities. Como resultado, parte de su contenido se aplica a una configuración, pero no a otra. El hecho de tener componentes sin utilizar no afecta al rendimiento del sistema.
* El kit DE herramientas SAN no es compatible con Citrix XenServer, Oracle VM y Red Hat Enterprise Virtualization Hypervisor.


====