---
sidebar: sidebar 
permalink: hu_luhu_71_rn.html 
keywords: host utilities, linux, 7.1, netapp, ontap, release, notes, linux 
summary: Notas de la versión de Linux Host Utilities 7,1 
---
= Notas de la versión de Linux Host Utilities 7,1
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
En las notas de la versión, se describen las nuevas funciones y mejoras, los problemas y limitaciones conocidos y las precauciones importantes para configurar y gestionar el host específico con el sistema de almacenamiento de ONTAP.

Para obtener información específica sobre las versiones y actualizaciones del sistema operativo que admiten las utilidades de host, consulte la link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^].



== Novedades

La versión de Linux Host Utilities 7,1 contiene las siguientes funciones y mejoras nuevas:

* Las utilidades de host de Linux ahora se denominan _Linux Unified Host Utilities_ porque son compatibles con los sistemas de almacenamiento E-Series de NetApp que ejecutan SANtricity, así como sistemas AFF, FAS y ASA que ejecutan ONTAP.
+

NOTE: Cualquier mención de utilidades de host o utilidades de host de Linux en este documento hace referencia a las utilidades de host unificadas de Linux.

* Ahora se admiten los siguientes sistemas operativos:
+
** SUSE Linux Enterprise Server serie 15
** Oracle VM serie 3.2
** Oracle Linux series 6 y 7
** Red Hat Enterprise Linux serie 6 y 7
** SUSE Linux Enterprise Server 11 SP4
** KVM y XEN, RHEV 6.4 y 6.5
** Citrix XenServer


* En hosts Red Hat Enterprise Linux (RHEL) 6 y RHEL 7, ahora se admite un paquete adaptado para configurar perfiles de servidor. Puede utilizar el `tuned-adm` comando para definir diferentes perfiles, según el entorno. Por ejemplo, también puede usar el perfil de invitado virtual como equipo virtual de invitado y puede usar el perfil de almacenamiento empresarial para configuraciones donde se utilizan las LUN de cabinas de almacenamiento empresarial. El uso de estos paquetes ajustados puede mejorar el rendimiento y la latencia en ONTAP.
* Añade compatibilidad con adaptadores FC de 32GB Gb de Broadcom Emulex y Marvell Qlogic.



NOTE: NetApp sigue trabajando con las utilidades de host para añadir compatibilidad con las funciones después de la versión inicial. Para obtener la información más reciente sobre las funciones admitidas y las nuevas características que se han agregado, consulte la link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^].



== Solucionados en esta versión

El problema de error intermitente del sistema operativo host que se produce al ejecutar `sanlun lun show -p` el comando en SUSE Linux Enterprise Server 12 SP1, OL 7,2, RHEL 7,2 y RHEL 6,8 se soluciona en esta versión.



== Problemas y limitaciones conocidos

La versión Linux Host Utilities 7,1 tiene los siguientes problemas y limitaciones conocidos.

[cols="10, 30, 30"]
|===
| ID de error de NetApp | Título | Descripción 


| 1457017 |  `sanlun` la instalación emite mensajes de advertencia relacionados con `libdevmapper.so` y.. `libnl.so` bibliotecas. Estas advertencias no afectan a la funcionalidad de `sanlun` kit. | Cuando ejecuta el comando CLI de utilidades del host de Linux - «sanlun fcp show adapter -v» en un host SAN, el comando falla con un mensaje de error que muestra que las dependencias de la biblioteca necesarias para una detección del adaptador de bus de host (HBA) no pueden encontrarse: 
`[root@hostname ~]# sanlun fcp show adapter -v
Unable to locate /usr/lib64/libHBAAPI.so library
Make sure the package installing the library is installed & loaded` Consulte NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1508554["1508554"^]. 
|===
link:https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] proporciona información completa sobre la mayoría de los problemas conocidos, incluidas las soluciones alternativas sugeridas cuando sea posible.
