---
sidebar: sidebar 
permalink: hu_ol_77.html 
keywords: host utilities, oracle, linux, 7.7, netapp, ontap 
summary: Instale Linux Host Utilities en un host Oracle Linux 7.7 para administrar operaciones de protocolo FCP e iSCSI con LUN de ONTAP. 
---
= Configurar Oracle Linux 7.7 para FCP e iSCSI con almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software de utilidades de host Linux proporciona herramientas de gestión y diagnóstico para hosts Linux que se conectan al almacenamiento de ONTAP. Al instalar las utilidades de host de Linux en un host de Oracle Linux 7.7, puede usarlas para ayudarlo a administrar las operaciones de protocolo FCP e iSCSI con LUN de ONTAP.


NOTE: No es necesario configurar manualmente los ajustes de la máquina virtual basada en kernel (KVM) porque los LUN de ONTAP se asignan automáticamente al hipervisor.



== Paso 1: Opcionalmente, habilite el arranque SAN

Puede configurar su host para que utilice el arranque SAN y simplificar la puesta en marcha y mejorar la escalabilidad.

.Antes de empezar
Utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Linux, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.

.Pasos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Cree un LUN de arranque SAN y asígnelo al host"^].
. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Compruebe que la configuración se haya realizado correctamente. Para ello, reinicie el host y verifique que el sistema operativo esté activo y en ejecución.




== Paso 2: Instale las utilidades del host de Linux

NetApp recomienda la instalación de las utilidades del host Linux para admitir la gestión de las LUN de ONTAP y ayudar al soporte técnico con la recopilación de datos de configuración.

link:hu_luhu_71.html["Instale Linux Host Utilities 7,1"].


NOTE: La instalación de Linux Host Utilities no cambia ninguna configuración de tiempo de espera del host en el host Linux.



== Paso 3: Confirme la configuración multivía del host

Puede utilizar el acceso multivía con Oracle Linux 7,7 para gestionar los LUN de ONTAP.


NOTE: Puedes utilizar el link:hu_rhel_77.html#rhel-rhck["Configuración recomendada para Red Hat Enterprise Linux (RHEL) 7.7"] para configurar Red Hat Compatible Kernel para Oracle Linux 7.7.

Para garantizar que el acceso multivía esté configurado correctamente para el host, verifique que el `/etc/multipath.conf` archivo esté definido y que los ajustes recomendados de NetApp estén configurados para los LUN de ONTAP.

.Pasos
. Verifique que el `/etc/multipath.conf` archivo salga. Si el archivo no existe, cree un archivo vacío de cero bytes:
+
[source, cli]
----
touch /etc/multipath.conf
----
. La primera vez que `multipath.conf` se crea el archivo, es posible que deba habilitar e iniciar los servicios multivía para cargar la configuración recomendada:
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Cada vez que arranca el host, el archivo de cero bytes vacío `/etc/multipath.conf` carga automáticamente los parámetros multivía de host recomendados por NetApp como configuración predeterminada. No debería ser necesario realizar cambios en `/etc/multipath.conf` el archivo para el host ya que el sistema operativo está compilado con los parámetros multivía que reconocen y gestionan correctamente las LUN de ONTAP.
+
En la siguiente tabla se muestra la configuración del parámetro multivía compilado nativo del sistema operativo Linux para los LUN de ONTAP.

+
.Muestra la configuración de los parámetros
[%collapsible]
====
[cols="2"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "2 pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
====
. Compruebe la configuración de parámetros y el estado de la ruta de sus LUN de ONTAP:
+
[source, cli]
----
multipath -ll
----
+
Los parámetros multiruta predeterminados admiten configuraciones AFF y FAS . En estas configuraciones, un solo LUN de ONTAP no debería requerir más de cuatro rutas. Tener más de cuatro rutas puede causar problemas durante una falla de almacenamiento.

+
Una configuración de AFF o FAS debe tener dos grupos de rutas con prioridades superiores e inferiores. La controladora donde se encuentra el agregado ofrece rutas activas/optimizadas de mayor prioridad. Las rutas de prioridad más baja están activas pero no optimizadas debido a que se sirven con una controladora diferente. Las rutas no optimizadas solo se usan cuando las rutas optimizadas no están disponibles.

+
Los siguientes ejemplos de salida muestran la configuración de parámetros y el estado de ruta correctos para los LUN de ONTAP en una configuración AFF o FAS con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
====




== Paso 4: Opcionalmente, excluya un dispositivo de las rutas múltiples

Si es necesario, puede excluir un dispositivo del acceso múltiple agregando el WWID del dispositivo no deseado a la estrofa de la lista negra del `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
“sda” es el disco SCSI local que desea agregar a la lista negra.

+
Un ejemplo de WWID es `360030057024d0730239134810c0cb833`.

. Añada el WWID a la estrofa «blacklist»:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Paso 5: Personalice los parámetros multivía para las LUN de ONTAP

Si su host está conectado a LUN de otros proveedores y cualquiera de la configuración de parámetros multivía se ha anulado, debe corregirlos agregando estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a LUN de ONTAP. Si no hace esto, es posible que las LUN de ONTAP no funcionen como se espera.

Compruebe el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para ver los ajustes que podrían estar anulando el <<multipath-parameter-settings,configuración predeterminada para parámetros multivía>>.


CAUTION: No debe anular la configuración de parámetros recomendada para las LUN de ONTAP. Estos ajustes se requieren para el rendimiento óptimo de la configuración del host. Póngase en contacto con el soporte de NetApp, con su proveedor de SO o con ambos para obtener más información.

El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este ejemplo, el `multipath.conf` archivo define valores para `path_checker` y `no_path_retry` que no son compatibles con LUN de ONTAP, y no puede quitar estos parámetros porque las cabinas de almacenamiento ONTAP siguen conectadas al host. En su lugar, corrija los valores para `path_checker` y `no_path_retry` agregando una estrofa de dispositivo al `multipath.conf` archivo que se aplica específicamente a los LUN de ONTAP.

.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Paso 6: Revise los problemas conocidos

El host Oracle Linux 7.7 con almacenamiento ONTAP tiene los siguientes problemas conocidos:

[cols="3*"]
|===
| ID de error de NetApp | Título | Descripción 


| 1440718 | Si se desasigna o se asigna una LUN sin realizar una detección repetida de SCSI, es posible que se dañen los datos del host. | Cuando se establece el parámetro de configuración multivía "disable_change_wwids" en SÍ, se deshabilita el acceso al dispositivo de ruta en caso de que se produzca un cambio WWID. El acceso multivía deshabilitará el acceso al dispositivo de ruta hasta que el WWID de la ruta se restaure al WWID del dispositivo multivía. Para obtener más información, consulte link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de conocimientos de NetApp: Daño en el sistema de archivos del LUN de iSCSI en Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311575["1311575"^] | Los retrasos de I/O observados debido a las operaciones de lectura/escritura no pudieron cambiar a través de las rutas secundarias durante la conmutación por error del sistema de almacenamiento con Qlogic QLE2672(16G) | Es posible que las operaciones de I/o no se reanuden a través de rutas secundarias durante las operaciones de recuperación tras fallos de almacenamiento en el kernel de Oracle Linux 7.7 (5.4.17-2011.0.7.el7uek.x86_6) con HBA 16 G QLE2672 de QLogic. Si el progreso de I/o se detiene debido a rutas principales bloqueadas durante una conmutación al respaldo del almacenamiento, es posible que la operación de I/o no se reanude a través de rutas secundarias que provocan un retraso de I/O. La operación de I/o se reanuda solo después de que las rutas principales están en línea una vez que se completa la operación de devolución del fallo de almacenamiento. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311576["1311576"^] | Se han observado retrasos de I/O debido a un error en la operación de lectura/escritura al cambiar a través de vías secundarias durante la conmutación al nodo de respaldo del almacenamiento con Emulex LPe16002(16G) | Es posible que las operaciones de I/o no se reanuden a través de rutas secundarias durante las operaciones de recuperación tras fallos de almacenamiento en el kernel de Oracle Linux 7.7 (5.4.17-2011.0.7.el7uek.x86_6) con Emulex LPe16002 16 G HBA. Si el progreso de I/o se detiene debido a rutas principales bloqueadas durante una conmutación al respaldo del almacenamiento, es posible que la operación de I/o no se reanude a través de rutas secundarias que provocan un retraso de I/O. La operación de I/o se reanuda solo después de que las rutas principales están en línea una vez que se completa la operación de devolución del fallo de almacenamiento. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["1246134"^] | Se han observado retrasos de I/O y los informes pasan al estado bloqueado y NO PRESENTE durante la recuperación tras fallos del sistema de almacenamiento con Emulex LPe16002(16G) | Durante las operaciones de conmutación por error del almacenamiento en Oracle Linux 7.6 con el kernel UEK5U2 ejecutándose con un adaptador de bus de host (HBA) de Fibre Channel (FC) de 16 GB (Emulex LPe16002B-M6, el progreso de I/o podría detenerse debido a que los informes se bloquean. Los informes de la operación de conmutación al nodo de respaldo del almacenamiento cambian de estado en línea a estado "bloqueado", lo que provoca un retraso en las operaciones de lectura y escritura. Una vez que la operación se ha realizado correctamente, los informes no logran moverse de nuevo al estado "en línea" y siguen en estado "bloqueado". 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Se han observado retrasos de E/S y los puertos Rports se están moviendo al estado Bloqueado, NO PRESENTE durante la conmutación por error de almacenamiento con Qlogic QLE2672(16G) y QLE2742(32G) | Es posible que los puertos remotos Fibre Channel (FC) estén bloqueados en Red Hat Enterprise Linux (RHEL) 7.6 con el host de 16 G QLE2672 de QLogic durante las operaciones de conmutación por error de almacenamiento. Como las interfaces lógicas se reducen cuando un nodo de almacenamiento está inactivo, los puertos remotos establecen el estado del nodo de almacenamiento como bloqueado. Es posible que el progreso de I/O se detenga debido a los puertos bloqueados si se ejecuta tanto un host QLogic QLE2672 16G como un adaptador de bus de host (HBA) Fibre Channel (FC) de QLE2742 32GB Gb. Cuando el nodo de almacenamiento vuelve a su estado óptimo, las interfaces lógicas también se activa y los puertos remotos deben estar en línea. Sin embargo, es posible que los puertos remotos aún estén bloqueados. Este estado bloqueado se registra como defectuoso en LAS LUN, en la capa multivía. Puede comprobar el estado de los puertos remotos con el siguiente comando: # Cat /sys/class/fc_remote_ports/rport-*/Port_stat debería ver la siguiente salida: Bloqueado bloqueado bloqueado bloqueado en línea 
|===


== El futuro

* link:hu-luhu-command-reference.html["Obtenga más información sobre el uso de la herramienta Linux Host Utilities"] .
* Obtenga más información sobre la duplicación de ASM.
+
El mirroring de Gestión Automática de Almacenamiento (ASM) puede requerir cambios en la configuración de multivía de Linux para permitir que ASM reconozca un problema y realice el cambio a un grupo de fallos alternativo. La mayoría de las configuraciones de ASM de ONTAP utilizan redundancia externa, lo que significa que la protección de datos es proporcionada por la cabina externa y ASM no hace mirroring de los datos. Algunos sitios utilizan ASM con redundancia normal para proporcionar duplicación bidireccional, normalmente en diferentes sitios. Consulte link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bases de datos de Oracle en ONTAP"^] para obtener más información.


