---
sidebar: sidebar 
permalink: hu_ol_78.html 
keywords: host utilities, oracle, linux, 7.8, netapp, ontap 
summary: Describe cómo usar Oracle Linux 7.8 con ONTAP 
---
= Utilice Oracle Linux 7,8 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host SAN de ONTAP para configurar Oracle Linux 7,8 con ONTAP como destino.



== Instale las utilidades del host de Linux

El paquete de software de utilidades del host Linux de NetApp está disponible en link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^]un archivo .rpm de 32 bits y 64 bits. Si no sabe qué archivo es el adecuado para su configuración, utilice el link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de las utilidades del host Linux, pero no es obligatorio. Las utilidades no cambian ninguna configuración del host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

Si tiene Linux Host Utilities actualmente instaladas, debe actualizarla a la versión más reciente, o bien eliminarla y seguir estos pasos para instalar la versión más reciente.

.Pasos
. Descargue el paquete de software de Linux Host Utilities de 32 o 64 bits en el link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^]al host.
. Instale el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque San

.Antes de empezar
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^]para verificar que el sistema operativo, el HBA, el firmware del HBA y la versión de arranque del BIOS y ONTAP sean compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo del host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

Para Oracle Linux (OL) 7.8 debe existir el archivo /etc/multipath.conf, pero no es necesario realizar cambios específicos en el archivo. OL 7.8 se compila con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP.

Puede utilizar el `multipath -ll` Comando para verificar la configuración de las LUN de ONTAP.

En las siguientes secciones se proporcionan ejemplos de salidas multivía para una LUN asignada a personas que no son de ASA.



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que son operadas por la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas.

[listing]
----
# multipath -ll
3600a098038303634722b4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb 69:624 active ready running
| |- 16:0:5:35 sdun 66:752 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 15:0:0:35 sdaj 66:48 active ready running
|- 15:0:1:35 sdbx 68:176 active ready running

----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Tener más de cuatro rutas puede ocasionar problemas de ruta durante errores de almacenamiento.



== Configuración recomendada

El sistema operativo Oracle Linux 7,8 se compila para reconocer los LUN de ONTAP y definir automáticamente todos los parámetros de configuración correctamente.  `multipath.conf`El archivo debe existir para que se inicie el daemon multivía. Si este archivo no existe, puede crear un archivo vacío de cero bytes con el `touch /etc/multipath.conf` comando.

La primera vez que crea el `multipath.conf` archivo, es posible que deba habilitar e iniciar los servicios multivía mediante los siguientes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
No es necesario agregar nada directamente al `multipath.conf` archivo a menos que tenga dispositivos que no desee que se gestionen con acceso multivía o que tenga una configuración existente que anule los valores predeterminados. Para excluir dispositivos no deseados, agregue la siguiente sintaxis al `multipath.conf` archivo y reemplace <DevId> por la cadena de identificador mundial (WWID) del dispositivo que desea excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
El siguiente ejemplo determina el WWID de un dispositivo y lo agrega al `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` Es el disco SCSI local que desea agregar a la lista negra.

. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Compruebe siempre el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para ver la configuración heredada que podría estar anulando la configuración predeterminada.

La siguiente tabla muestra `multipathd` los parámetros críticos de las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben corregirse mediante estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a las LUN de ONTAP. Sin esta corrección, es posible que las LUN de ONTAP no funcionen como se espera. Solo debe sobrescribir estos valores predeterminados en consulta con NetApp, el proveedor del sistema operativo o ambos, y solo cuando se comprenda completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` archivo define valores para `path_checker` y `detect_prio` que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Para configurar el kernel compatible con Red Hat (RHCK) de Oracle Linux 7,8, utilice para link:hu_rhel_78.html#recommended-settings["configuración recomendada"]Red Hat Enterprise Linux (RHEL) 7,8.



== Problemas conocidos

La versión Oracle Linux 7,8 con ONTAP tiene los siguientes problemas conocidos:

[cols="3*"]
|===
| ID de error de NetApp | Título | Descripción 


| 1440718 | Si se desasigna o se asigna una LUN sin realizar una detección repetida de SCSI, es posible que se dañen los datos del host. | Cuando se establece el parámetro de configuración multivía "disable_change_wwids" en SÍ, se deshabilita el acceso al dispositivo de ruta en caso de que se produzca un cambio WWID. El acceso multivía deshabilitará el acceso al dispositivo de ruta hasta que el WWID de la ruta se restaure al WWID del dispositivo multivía. Para obtener más información, consulte link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de conocimientos de NetApp: Daño en el sistema de archivos del LUN de iSCSI en Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311575["1311575"^] | Los retrasos de I/O observados debido a las operaciones de lectura/escritura no pudieron cambiar a través de las rutas secundarias durante la conmutación por error del sistema de almacenamiento con Qlogic QLE2672(16G) | Es posible que las operaciones de I/o no se reanuden a través de rutas secundarias durante las operaciones de recuperación tras fallos de almacenamiento en el kernel de Oracle Linux 7.7 (5.4.17-2011.0.7.el7uek.x86_6) con HBA 16 G QLE2672 de QLogic. Si el progreso de I/o se detiene debido a rutas principales bloqueadas durante una conmutación al respaldo del almacenamiento, es posible que la operación de I/o no se reanude a través de rutas secundarias que provocan un retraso de I/O. La operación de I/o se reanuda solo después de que las rutas principales están en línea una vez que se completa la operación de devolución del fallo de almacenamiento. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1311576["1311576"^] | Se han observado retrasos de I/O debido a un error en la operación de lectura/escritura al cambiar a través de vías secundarias durante la conmutación al nodo de respaldo del almacenamiento con Emulex LPe16002(16G) | Es posible que las operaciones de I/o no se reanuden a través de rutas secundarias durante las operaciones de recuperación tras fallos de almacenamiento en el kernel de Oracle Linux 7.7 (5.4.17-2011.0.7.el7uek.x86_6) con Emulex LPe16002 16 G HBA. Si el progreso de I/o se detiene debido a rutas principales bloqueadas durante una conmutación al respaldo del almacenamiento, es posible que la operación de I/o no se reanude a través de rutas secundarias que provocan un retraso de I/O. La operación de I/o se reanuda solo después de que las rutas principales están en línea una vez que se completa la operación de devolución del fallo de almacenamiento. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["1246134"^] | Se han observado retrasos de I/O y los informes pasan al estado bloqueado y NO PRESENTE durante la recuperación tras fallos del sistema de almacenamiento con Emulex LPe16002(16G) | Durante las operaciones de conmutación por error del almacenamiento en Oracle Linux 7.6 con el kernel UEK5U2 ejecutándose con un adaptador de bus de host (HBA) de Fibre Channel (FC) de 16 GB (Emulex LPe16002B-M6, el progreso de I/o podría detenerse debido a que los informes se bloquean. Los informes de la operación de conmutación al nodo de respaldo del almacenamiento cambian de estado en línea a estado "bloqueado", lo que provoca un retraso en las operaciones de lectura y escritura. Una vez que la operación se ha realizado correctamente, los informes no logran moverse de nuevo al estado "en línea" y siguen en estado "bloqueado". 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | Se han observado retrasos de E/S y los puertos Rports se están moviendo al estado Bloqueado, NO PRESENTE durante la conmutación por error de almacenamiento con Qlogic QLE2672(16G) y QLE2742(32G) | Es posible que los puertos remotos Fibre Channel (FC) estén bloqueados en Red Hat Enterprise Linux (RHEL) 7.6 con el host de 16 G QLE2672 de QLogic durante las operaciones de conmutación por error de almacenamiento. Como las interfaces lógicas se reducen cuando un nodo de almacenamiento está inactivo, los puertos remotos establecen el estado del nodo de almacenamiento como bloqueado. Es posible que el progreso de I/O se detenga debido a los puertos bloqueados si se ejecuta tanto un host QLogic QLE2672 16G como un adaptador de bus de host (HBA) Fibre Channel (FC) de QLE2742 32GB Gb. Cuando el nodo de almacenamiento vuelve a su estado óptimo, las interfaces lógicas también se activa y los puertos remotos deben estar en línea. Sin embargo, es posible que los puertos remotos aún estén bloqueados. Este estado bloqueado se registra como defectuoso en LAS LUN, en la capa multivía. Puede comprobar el estado de los puertos remotos con el siguiente comando: # Cat /sys/class/fc_remote_ports/rport-*/Port_stat debería ver la siguiente salida: Bloqueado bloqueado bloqueado bloqueado en línea 
|===