---
sidebar: sidebar 
permalink: hu_ol_64.html 
keywords: host utilities, oracle, linux, 6.4, netapp, ontap 
summary: Describe cómo usar Oracle Linux 6.4 con ONTAP 
---
= Utilice Oracle Linux 6,4 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host SAN de ONTAP para configurar Oracle Linux 6,4 con ONTAP como destino.



== Instale las utilidades unificadas de host de Linux

El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 y 64 bits. Si no sabe cuál es el archivo adecuado para su configuración, utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Lo que necesitará
Si tiene una versión de Linux Unified Host Utilities instalada actualmente, debe actualizarla o, debe eliminarla y seguir los pasos siguientes para instalar la versión más reciente.

. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] Sitio a su anfitrión.
. Use el siguiente comando para instalar el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se haya realizado correctamente.




== Accesos múltiples

Para Oracle Linux 6.4 debe existir el archivo /etc/multipath.conf, pero no es necesario realizar cambios específicos en el archivo. Oracle Linux 6.4 se ha compilado con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP. Para habilitar ALUA Handler, realice los siguientes pasos:

.Pasos
. Cree una copia de seguridad de la imagen initrd.
. Para que ALUA y no ALUA funcionen, anexe el siguiente valor del parámetro al kernel:
`rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. Utilice la `mkinitrd` comando para volver a crear la imagen initrd. Las versiones 6x y posteriores de Oracle utilizan el comando: `mkinitrd -f /boot/ initrd-"uname -r".img uname -r`O el comando: `dracut -f`
. Reinicie el host.
. Compruebe el resultado del `cat /proc/cmdline` comando para garantizar que la configuración se ha completado. Puede utilizar el `multipath -ll` Comando para verificar la configuración de las LUN de ONTAP. Debería haber dos grupos de caminos con prioridades diferentes. Las rutas con las mayores prioridades son activo-optimizado, lo que significa que la controladora donde se encuentra el agregado presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas solo se usan cuando no hay rutas optimizadas disponibles.


.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizadas:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 0:0:26:37 sdje 8:384   active ready running
| |- 0:0:25:37 sdik 135:64  active ready running
|-+- policy='round-robin 0' prio=10 status=enabled
  |- 0:0:18:37 sdda 70:128  active ready running
  |- 0:0:19:37 sddu 71:192  active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



== Configuración recomendada

El sistema operativo Oracle Linux 6.4 se compila para reconocer las LUN de ONTAP y establecer automáticamente todos los parámetros de configuración correctamente.

La `multipath.conf` el archivo debe existir para que se inicie el daemon multivía, pero puede crear un archivo vacío de cero bytes mediante el siguiente comando:

`touch /etc/multipath.conf`.

La primera vez que se crea este archivo, es posible que deba habilitar e iniciar los servicios multivía.

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
* No es necesario añadir nada directamente al `multipath.conf` archivo a menos que tenga dispositivos que no desee gestionar la función de acceso multivía o que tenga una configuración existente que anula los valores predeterminados.
* Puede añadir la siguiente sintaxis al `multipath.conf` archivo para excluir los dispositivos no deseados:
+
** Reemplace la <DevId> por la cadena WWID del dispositivo que desea excluir:
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




.Ejemplo
En este ejemplo: `sda` Es el disco SCSI local que necesitamos agregar a la lista negra.

.Pasos
. Ejecute el siguiente comando para determinar el WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. Añada este WWID a la estrofa de la lista negra `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Siempre debe comprobar su `/etc/multipath.conf` archivo para configuraciones heredadas, especialmente en la sección de valores predeterminados, que podría estar anulando los valores predeterminados.

La siguiente tabla demuestra lo crítico `multipathd` Parámetros para las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben corregirse con estrofas más adelante en el `multipath.conf` Archivo que se aplica específicamente a las LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Solo debe anular estos valores predeterminados en consulta con NetApp y/o el proveedor de SO y solo cuando comprenda completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "operación por turnos 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `detect_prio` Que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Para configurar Oracle Linux 6,4 Red Hat Enterprise Kernel (RHCK), utilice para link:hu_rhel_64.html#recommended-settings["configuración recomendada"]Red Hat Enterprise Linux (RHEL) 6,4.



== Problemas conocidos

La versión Oracle Linux 6,4 con ONTAP tiene los siguientes problemas conocidos:

[cols="4*"]
|===
| ID de error de NetApp | Título | Descripción | ID Bugzilla 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=713555["713555"^] | Los restablecimientos del adaptador QLogic se ven en OL6.4 y OL5.9 con UEK2 en errores de la controladora, como la toma de control/devolución y el reinicio | Los restablecimientos del adaptador de QLogic se ven en hosts OL6.4 con UEK2 (kernel-uek-2.6.39-400.17.1.el6uek) o OL5.9 con hosts UEK2 (kernel-uek-2.6.39 400.17.1.el5uek) cuando se producen fallos de controladora (como la toma de control, la restauración y los reinicios). Estos reajustes son intermitentes. Cuando se restablece este adaptador, es posible que se produzca una interrupción de I/o prolongada (en ocasiones, más de 10 minutos) hasta que el adaptador se restablece correctamente y el estado de las rutas se actualiza mediante dm-multipath. En /var/log/messages, se ven mensajes similares a los siguientes cuando se produce un fallo: Kernel: Ql2xxx [0000:11:00.0]-8018:0: ADAPTADOR RESET EMITIDO nexus=0:2:13. Esto se observa con la versión kernel: On OL6.4: Kernel-uek-2.6.39-400.17.1.el6uek en OL5.9: Kernel-uek-2.6.39-400.17.1.el5uek | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=13999["13999"^] 


| link:htthttps://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=715217["715217"^] | El retraso en la recuperación de rutas en hosts OL6.4 o OL5.9 con UEK2 puede provocar una reanudación de la I/o en fallos de la controladora o de la estructura | Cuando se produce un fallo de la controladora (conmutación al nodo de respaldo o retorno del almacenamiento, reinicios, etc.) o un error de estructura (habilitación o deshabilitación de puerto de FC) con I/o en hosts de Oracle Linux 6.4 o Oracle Linux 5.9 con kernel UEK2, la recuperación de rutas por DM-Multipath tarda mucho (4 minutos. a 10 min). A veces, durante las rutas que se recuperan al estado activo, también se ven los siguientes errores del controlador lpfc: Kernel: sd 0:0:8:3: [sdlt] Resultado: Hostbyte=DID_ERROR driverbyte=DRIVER_OK debido a este retraso en la recuperación de la ruta durante los eventos de fallo, la E/S también retrasa la reanudación. OL 6.4 versiones: Device-mapper-1.02.77-9.el6 device-mapper-multipath-0.4.9-64.0.1.el6 kernel-uek-2.6.39-400.17.1.el6uek 5.9 versiones: Device-mapper-1.02.77-9.el5 device-mapper-multipath-0.4.9-64.0.1.el5 kernel-uek-2.6.elek-39.400.17.1 | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=14001["14001"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=709911["709911"^] | DM Multipath en OL6.4 y OL5.9 iSCSI con kernel UEK2 tarda mucho en actualizar el estado de la ruta de LUN después de un fallo de almacenamiento | En sistemas que ejecutan Oracle Linux 6 Update 4 y Oracle Linux 5 Update 9 iSCSI con Unbreakable Enterprise Kernel Release 2 (UEK2), se ha observado un problema durante los eventos de fallo del almacenamiento en los que DM Multipath (DMMP) tarda unos 15 minutos en actualizar el estado de la ruta de los dispositivos (DM) de Device Mapper (LUN). Si ejecuta el comando "multipath -ll" durante este intervalo, el estado de la ruta se muestra como "failed ready running" (error en ejecución) para ese dispositivo DM (LUN). El estado de la ruta finalmente se actualiza como "activo Ready running". Este problema se ve con la siguiente versión: Oracle Linux 6 Update 4: UEK2 Kernel: 2.6.39-400.17.1.el6uek.x86_64 Multipath: Device-mapper-multipath-0.4.9-64.0.el6.x86_64 iSCSI: iscsi-initiator-6.2.0.873-2.0.1.el6.x86_64_5-9_39-9_400.17.1_2.6-6.2_64.0_64_0.872_0.4-_host: Multipath_-64--.16.0--.---__Linux_----.0---.0 | link:http://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=13984["13984"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=739909["739909"^] | La llamada del sistema SG_IO ioctl falla en dispositivos dm-multipath después de un error de FC en hosts OL6.x y OL5.x con UEK2 | Se observa un problema en los hosts Oracle Linux 6.x con el kernel UEK2 y los hosts Oracle Linux 5.x con kernel UEK2. Los comandos sg_* de un dispositivo multipath fallan con el código de error EAGAIN (errno) después de un error de estructura que hace que todas las rutas del grupo de rutas activas se desencuentren. Este problema solo se observa cuando no se producen operaciones de I/o en los dispositivos multivía. El siguiente es un ejemplo: # sg_inq -v /dev/mapper/3600a098041764937303f436c75324370 consulta cdb: 12 00 00 00 24 00 ioctl(SG_IO v3) falló con os_err (errno) = 11 consulta: Pase a través de error de sistema operativo: El recurso temporalmente no está disponible HDIO_GET_iocl IDENTIDAD falló: El recurso no está disponible temporalmente [11] tanto LA CONSULTA SCSI como la recuperación de la información ATA han fallado en las llamadas /dev/mapper/3600a098041764937303f436c75324370 # este problema se produce porque la conmutación del grupo de rutas a otros grupos activos no se activa durante las llamadas de ioctl() cuando no se produce ninguna E/S en el dispositivo DM-Multipath. El problema se ha observado en las siguientes versiones de kernel-uek y Device-mapper-multipath packages: OL6.4 Versions: Kernel-uek-2.6.39-400.17.1.el6uek device-mapper-multipath-0.4.9-64.0.1.el6 OL5.9: Kernel-uek-2.6.39-400.17.1.el5uek-Device-0.4.9-64.0.el5--.el5uek-multipath-..1..el5- | link:https://bugzilla.oracle.com/bugzilla/show_bug.cgi?id=14082["14082"^] 
|===

NOTE: Para ver los problemas conocidos de Oracle Linux (kernel compatible con Red Hat), consulte link:hu_rhel_64.html#known-problems-and-limitations["problemas conocidos"] Para Red Hat Enterprise Linux (RHEL) 6.4.
