---
sidebar: sidebar 
permalink: hu_ol_76.html 
keywords: host utilities, oracle, linux, 7.6, netapp, ontap 
summary: Describe cómo usar Oracle Linux 7.6 con ONTAP 
---
= Utilice Oracle Linux 7,6 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host SAN de ONTAP para configurar Oracle Linux 7,6 con ONTAP como destino.



== Instale las utilidades unificadas de host de Linux

El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 y 64 bits. Si no sabe cuál es el archivo adecuado para su configuración, utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

Si tiene una versión de Linux Unified Host Utilities instalada, debe actualizarla o quitarla y seguir estos pasos para instalar la versión más reciente.

.Pasos
. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] Sitio a su anfitrión.
. Use el siguiente comando para instalar el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=86309;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

Para Oracle Linux 7.6 debe existir el archivo /etc/multipath.conf, pero no es necesario realizar cambios específicos en el archivo. Oracle Linux 7.6 se ha compilado con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP.

Puede utilizar `multipath -ll` el comando para comprobar la configuración de sus LUN de ONTAP. Debería haber dos grupos de caminos con prioridades diferentes. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que la controladora donde se encuentra el agregado presta servicio. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizadas:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Tener más de cuatro rutas puede ocasionar problemas de ruta durante errores de almacenamiento.



== Configuración recomendada

El sistema operativo Oracle Linux 7,6 se compila para reconocer los LUN de ONTAP y definir automáticamente todos los parámetros de configuración correctamente.  `multipath.conf`El archivo debe existir para que se inicie el daemon multivía. Si este archivo no existe, puede crear un archivo vacío de cero bytes con el `touch /etc/multipath.conf` comando

La primera vez que crea el `multipath.conf` archivo, es posible que deba habilitar e iniciar los servicios multivía mediante los siguientes comandos:

`# chkconfig multipathd on`
`# /etc/init.d/multipathd start`

No es necesario agregar nada directamente al `multipath.conf` archivo a menos que tenga dispositivos que no desee que se gestionen con acceso multivía o que tenga una configuración existente que anule los valores predeterminados. Para excluir los dispositivos no deseados, agregue la siguiente sintaxis al `multipath.conf` archivo, reemplazando <DevId> por la cadena WWID del dispositivo que desea excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
El siguiente ejemplo determina el WWID de un dispositivo y lo agrega al `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Es el disco SCSI local que desea agregar a la lista negra.

. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Siempre debe comprobar el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para configuraciones heredadas que pueden anular la configuración predeterminada.

En la siguiente tabla se muestran los parámetros críticos `multipathd` de las LUN de ONTAP y la configuración necesaria. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben corregirse mediante estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a las LUN de ONTAP. Sin esta corrección, es posible que las LUN de ONTAP no funcionen como se espera. Solo debe sobrescribir estos valores predeterminados en consulta con NetApp, el proveedor del sistema operativo o ambos, y solo cuando se comprenda completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `detect_prio` Que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Para configurar Oracle Linux 7,6 Red Hat Enterprise Kernel (RHCK), utilice para link:hu_rhel_76.html#recommended-settings["configuración recomendada"]Red Hat Enterprise Linux (RHEL) 7,6.



== Problemas conocidos

La versión Oracle Linux 7,6 con ONTAP tiene los siguientes problemas conocidos:

[cols="3*"]
|===
| ID de error de NetApp | Título | Descripción 


| 1440718 | Si se desasigna o se asigna una LUN sin realizar una detección repetida de SCSI, es posible que se dañen los datos del host. | Cuando se establece el parámetro de configuración multivía "disable_change_wwids" en SÍ, se deshabilita el acceso al dispositivo de ruta en caso de que se produzca un cambio WWID. El acceso multivía deshabilitará el acceso al dispositivo de ruta hasta que el WWID de la ruta se restaure al WWID del dispositivo multivía. Para obtener más información, consulte link:https://kb.netapp.com/Advice_and_Troubleshooting/Flash_Storage/AFF_Series/The_filesystem_corruption_on_iSCSI_LUN_on_the_Oracle_Linux_7["Base de conocimientos de NetApp: Daño en el sistema de archivos del LUN de iSCSI en Oracle Linux 7"^]. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1202736["1202736"^] | Es posible que los LUN no estén disponibles durante la detección del host debido al estado "no presente" de los puertos remotos en un host OL7U6 con el adaptador QLE2742 de QLogic | Durante la detección del host, el estado de los puertos remotos Fibre Channel (FC) en un host OL7U6 con un adaptador QLogic QLE2742 podría introducir el estado "no presente". Los puertos remotos con el estado "no presente" pueden hacer que las rutas a las LUN no estén disponibles. Durante la conmutación del almacenamiento, es posible que se reduzca la redundancia de la ruta y se produzca una interrupción de I/O. Puede comprobar el estado del puerto remoto introduciendo el siguiente comando: # Cat /sys/class/fc_remote_ports/rport-*/Port_state el siguiente es un ejemplo de la salida que se muestra: Online no presente en línea 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204078["1204078"^] | Se produce la interrupción del kernel en Oracle Linux 7.6 con HBA FC de 16 GB Qlogic(QLE2672) durante las operaciones de conmutación al nodo de respaldo de almacenamiento | En las operaciones de conmutación por error del almacenamiento en Oracle Linux 7.6 con un adaptador de bus de host (HBA) Qlogic QLE2672 Fibre Channel (FC), se produce una interrupción del kernel debido a una situación de pánico en el kernel. El pánico del kernel hace que Oracle Linux 7.6 se reinicie, lo que provoca una interrupción de la aplicación. Si el mecanismo kdump está habilitado, el evento de alerta del kernel genera un archivo vmcore ubicado en el directorio /var/crash/. Puede analizar el archivo vmcore para determinar la causa del pánico. Tras la interrupción del kernel, puede reiniciar el sistema operativo host y recuperar el sistema operativo; a continuación, puede reiniciar las aplicaciones según sea necesario. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204351["1204351"^] | Puede producirse la interrupción del kernel en Oracle Linux 7.6 que se ejecuta con Qlogic(QLE2742) 32 GB FC HBA durante las operaciones de conmutación por error del almacenamiento | Durante las operaciones de conmutación por error del almacenamiento en Oracle Linux 7.6 con un adaptador de bus de host (HBA) Qlogic QLE2742 Fibre Channel (FC), es posible que se produzca una interrupción del kernel debido a una caída del kernel. El pánico del kernel hace que Oracle Linux 7.6 se reinicie, lo que provoca una interrupción de la aplicación. Si el mecanismo kdump está habilitado, el evento de alerta del kernel genera un archivo vmcore ubicado en el directorio /var/crash/. Puede analizar el archivo vmcore para determinar la causa del pánico. Tras la interrupción del kernel, puede reiniciar el sistema operativo host y recuperar el sistema operativo; a continuación, puede reiniciar las aplicaciones según sea necesario. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1204352["1204352"^] | Puede producirse la interrupción del kernel en Oracle Linux 7.6 ejecutado con un HBA FC de 32 GB Emulex (LPe32002-m2)durante las operaciones de conmutación por error de almacenamiento | Durante las operaciones de recuperación tras fallos del almacenamiento en Oracle Linux 7.6 con un adaptador de bus de host (HBA) Fibre Channel (FC) Emulex LPe32002-m2, es posible que se produzca una interrupción del kernel debido a una situación inesperada en el kernel. El pánico del kernel hace que Oracle Linux 7.6 se reinicie, lo que provoca una interrupción de la aplicación. Si el mecanismo kdump está habilitado, el evento de alerta del kernel genera un archivo vmcore ubicado en el directorio /var/crash/. Puede analizar el archivo vmcore para determinar la causa del pánico. Tras la interrupción del kernel, puede reiniciar el sistema operativo host y recuperar el sistema operativo; a continuación, puede reiniciar las aplicaciones según sea necesario. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246134["11246134"^] | No hay progreso de I/o en Oracle Linux 7.6 con el kernel UEK5U2, ejecutándose con un HBA FC de 16 GB LPe16002B-M6 de Emulex durante las operaciones de conmutación por error del almacenamiento | Durante las operaciones de conmutación por error del almacenamiento en Oracle Linux 7.6 con el kernel UEK5U2 ejecutándose con un adaptador de bus de host (HBA) de Fibre Channel (FC) de 16 GB (Emulex LPe16002B-M6, el progreso de I/o podría detenerse debido a que los informes se bloquean. Los informes de la operación de conmutación al nodo de respaldo del almacenamiento cambian de estado "en línea" a un estado "bloqueado", lo que provoca un retraso en las operaciones de lectura y escritura. Una vez que la operación se ha realizado correctamente, los informes no logran moverse de nuevo al estado "en línea" y siguen estando en estado "bloqueado". 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1246327["1246327"^] | El estado del puerto remoto en el host de 16 G de QLogic QLE2672 bloqueado durante las operaciones de conmutación al nodo de respaldo de almacenamiento | Es posible que los puertos remotos Fibre Channel (FC) estén bloqueados en Red Hat Enterprise Linux (RHEL) 7.6 con el host de 16 G QLE2672 de QLogic durante las operaciones de conmutación por error de almacenamiento. Como las interfaces lógicas se reducen cuando un nodo de almacenamiento está inactivo, los puertos remotos establecen el estado del nodo de almacenamiento como bloqueado. El progreso de I/o puede detenerse debido a los puertos bloqueados si se está ejecutando un host QLE2672 16G de QLogic QLE2672 y un adaptador de bus de host (FC) QLE2742 de 32 GB Fibre Channel (HBA). Cuando el nodo de almacenamiento vuelve a su estado óptimo, las interfaces lógicas también se activa y los puertos remotos deben estar en línea. Sin embargo, es posible que los puertos remotos aún estén bloqueados. Este estado bloqueado se registra como defectuoso en LAS LUN, en la capa multivía. Puede comprobar el estado de los puertos remotos con el siguiente comando: # Cat /sys/class/fc_remote_ports/rport-*/Port_stat debería ver la siguiente salida: Bloqueado bloqueado bloqueado bloqueado en línea 
|===