---
sidebar: sidebar 
permalink: hu_ol_70.html 
keywords: host utilities, oracle, linux, 7.0, netapp, ontap 
summary: Describe cómo usar Oracle Linux 7.0 con ONTAP 
---
= Utilice Oracle Linux 7,0 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host SAN de ONTAP para configurar Oracle Linux 7,0 con ONTAP como destino.



== Instale las utilidades del host de Linux

El paquete de software de utilidades del host Linux de NetApp está disponible en link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^]un archivo .rpm de 32 bits y 64 bits. Si no sabe qué archivo es el adecuado para su configuración, utilice el link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de las utilidades del host Linux, pero no es obligatorio. Las utilidades no cambian ninguna configuración del host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

Si tiene Linux Host Utilities actualmente instaladas, debe actualizarla a la versión más reciente, o bien eliminarla y seguir estos pasos para instalar la versión más reciente.

.Pasos
. Descargue el paquete de software de Linux Host Utilities de 32 o 64 bits en el link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^]al host.
. Instale el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración proporcionados en este procedimiento para configurar los clientes de nube conectados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^]



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque San

.Antes de empezar
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^]para verificar que el sistema operativo, el HBA, el firmware del HBA y la versión de arranque del BIOS y ONTAP sean compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

Para Oracle Linux 7.0 debe existir el archivo /etc/multipath.conf, pero no es necesario realizar cambios específicos en el archivo. Oracle Linux 7.0 se ha compilado con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP. Para habilitar ALUA Handler, realice los siguientes pasos:

. Cree una copia de seguridad de la imagen initrd.
. Para que ALUA y no ALUA funcionen, anexe el siguiente valor del parámetro al kernel:
`rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. Vuelva a crear la imagen initrd con `dracut -f` comando.
. Reinicie el host.
. Compruebe el resultado del `cat /proc/cmdline` comando para garantizar que la configuración se ha completado.


Puede utilizar `multipath -ll` el comando para comprobar la configuración de sus LUN de ONTAP. Debería haber dos grupos de caminos con prioridades diferentes. Las rutas con prioridades más altas son Active-Optimized. Esto significa que reciben servicio de la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
|-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Tener más de cuatro rutas puede ocasionar problemas de ruta durante errores de almacenamiento.



== Configuración recomendada

El sistema operativo Oracle Linux 7.0 se compila para reconocer las LUN de ONTAP y establecer automáticamente todos los parámetros de configuración correctamente.

 `multipath.conf`El archivo debe existir para que se inicie el daemon multivía. Si este archivo no existe, puede crear un archivo vacío de cero bytes con el `touch /etc/multipath.conf` comando.

La primera vez que crea el `multipath.conf` archivo, es posible que deba habilitar e iniciar los servicios multivía mediante los siguientes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
No es necesario agregar nada directamente al `multipath.conf` archivo a menos que tenga dispositivos que no desee que se gestionen con acceso multivía o que tenga una configuración existente que anule los valores predeterminados. Para excluir dispositivos no deseados, agregue la siguiente sintaxis al `multipath.conf` archivo y reemplace <DevId> por la cadena de identificador mundial (WWID) del dispositivo que desea excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
El siguiente ejemplo determina el WWID de un dispositivo y lo agrega al `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` Es el disco SCSI local que desea agregar a la lista negra.

. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Compruebe siempre el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para ver la configuración heredada que podría estar anulando la configuración predeterminada.

La siguiente tabla muestra `multipathd` los parámetros críticos de las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben corregirse mediante estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a las LUN de ONTAP. Sin esta corrección, es posible que las LUN de ONTAP no funcionen como se espera. Solo debe sobrescribir estos valores predeterminados en consulta con NetApp, el proveedor del sistema operativo o ambos, y solo cuando se comprenda completamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `detect_prio` Que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 detect_prio no
 }
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 path_checker tur
 detect_prio yes
 }
}
----

NOTE: Para configurar el kernel compatible con Red Hat (RHCK) de Oracle Linux 7,0, utilice para link:hu_rhel_70.html#recommended-settings["configuración recomendada"]Red Hat Enterprise Linux (RHEL) 7,0.



== Duplicación de ASM

El mirroring de Gestión Automática de Almacenamiento (ASM) puede requerir cambios en la configuración de multivía de Linux para permitir que ASM reconozca un problema y realice el cambio a un grupo de fallos alternativo. La mayoría de las configuraciones de ASM de ONTAP utilizan redundancia externa, lo que significa que la protección de datos es proporcionada por la cabina externa y ASM no hace mirroring de los datos. Algunos sitios utilizan ASM con redundancia normal para proporcionar duplicación bidireccional, normalmente en diferentes sitios. Consulte link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bases de datos de Oracle en ONTAP"^] para obtener más información.



== Problemas conocidos

La versión Oracle Linux 7,0 con ONTAP tiene los siguientes problemas conocidos:

[cols="3*"]
|===
| ID de error de NetApp | Título | Descripción 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=901558["901558"^] | OL7.0 : el host pierde todas las rutas a la lun y se bloquea debido al error "RSCN timeout" en OL 7.0 UEK r3U5 Beta en el host Emulex 8G(LPe12002) | Es posible que observe que el host Emulex 8G(LPe12002) se bloquea y hay una alta interrupción de I/o durante las operaciones de recuperación tras fallos de almacenamiento con I/O. Es posible que observe las rutas que no se están recuperando, lo cual es un resultado del tiempo de espera RSCN, debido al cual el host pierde todas las rutas y se bloquea. La probabilidad de golpear este problema es alta. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=901557["901557"^] | OL 7,0: Interrupción de alta I/O observada en host SAN QLogic 8G FC (QLE2562) durante las operaciones de recuperación tras fallos del almacenamiento con I/O. | Es posible observar una interrupción elevada de I/O en el host QLogic 8G FC (QLE2562) durante las operaciones de conmutación por error de almacenamiento con I/O. Aborta y el dispositivo restablece manifiestos como interrupción de E/S en el host. La probabilidad de alcanzar esta interrupción de I/O es alta. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=894766["894766"^] | OL7.0: Dracut no incluye el módulo scsi_dh_alua.ko en initramfs en UEKR3U5 alfa | Es posible que el módulo scsi_dh_alua no se cargue incluso después de agregar el parámetro "rdloaddriver=scsi_dh_alua" en la línea de comandos del kernel y crear Dracut. Como resultado, ALUA no está habilitado para los LUN de NetApp tal como se recomienda. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=894796["894796"^] | Anaconda muestra un mensaje de error de inicio de sesión iSCSI aunque los inicios de sesión se han realizado correctamente durante la instalación de OL 7.0 OS | Cuando está instalando OL 7.0, la pantalla de instalación de anaconda muestra que se ha producido un error en el inicio de sesión iSCSI en varias IP de destino cuando los inicios de sesión iSCSI se han realizado correctamente. Anaconda muestra el siguiente mensaje de error: "Error de inicio de sesión de nodo". Este error solo se observa cuando se seleccionan varias IP de destino para el inicio de sesión iSCSI. Puede continuar con la instalación del sistema operativo haciendo clic en el botón "Aceptar". Este error no afecta negativamente a iSCSI ni a la instalación de OL 7.0 OS. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=894771["894771"^] | OL7.0 : Anaconda no agrega argumento bootdev en la línea cmd del kernel para establecer la dirección IP para la instalación de iSCSI SANboot OS | Anaconda no añade un argumento bootdev en la línea de comandos del kernel donde se establece la dirección IPv4 durante la instalación del sistema operativo OL 7.0 en un LUN multivía iSCSI. Por este motivo, no se pueden asignar direcciones IP a ninguna de las interfaces Ethernet configuradas para establecer sesiones iSCSI con el subsistema de almacenamiento durante el arranque OL 7.0. Dado que no se establecen las sesiones iSCSI, el LUN raíz no se detecta cuando se inicia el sistema operativo y, por lo tanto, se produce un error en el arranque del sistema operativo. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=916501["916501"^] | Se observó un fallo del kernel de host FCoE (QLE8152) de QLogic 10G durante las operaciones de conmutación por error de almacenamiento con I/O. | Es posible que observe un bloqueo del núcleo en el módulo de controlador Qlogic en el host 10G FCoE Qlogic (QLE8152). El bloqueo se produce durante las operaciones de conmutación al nodo de respaldo de almacenamiento con I/O. La probabilidad de golpear este bloqueo es alta, lo que provoca una interrupción de I/O más prolongada en el host. 
|===