---
sidebar: sidebar 
permalink: hu_rhel_69.html 
keywords: host utilities, red hat, rhel, linux, 6.9, netapp, ontap 
summary: Describe cómo utilizar Red Hat Enterprise Linux 6.9 con ONTAP 
---
= Utilice Red Hat Enterprise Linux 6,9 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Instale las utilidades unificadas de host de Linux

El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 y 64 bits. Si no sabe cuál es el archivo adecuado para su configuración, utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Lo que necesitará
Si tiene una versión de Linux Unified Host Utilities instalada actualmente, debe actualizarla o, debe eliminarla y seguir los pasos siguientes para instalar la versión más reciente.

. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Sitio de soporte de NetApp"^] Sitio a su anfitrión.
. Use el siguiente comando para instalar el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[listing]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=77603;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se haya realizado correctamente.




== Accesos múltiples

Para Red Hat Enterprise Linux (RHEL) 6.9 debe existir el archivo /etc/multipath.conf, pero no es necesario realizar cambios específicos en el archivo. RHEL 6.9 se ha compilado con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP. Para habilitar ALUA Handler, realice los siguientes pasos:

.Pasos
. Cree una copia de seguridad de la imagen initrd.
. Para que ALUA y no ALUA funcionen, anexe el siguiente valor del parámetro al kernel:
`rdloaddriver=scsi_dh_alua`
+
....
kernel /vmlinuz-2.6.32-358.6.1.el6.x86_64 ro root=/dev/mapper/ vg_ibmx355021082-lv_root rd_NO_LUKS rd_LVM_LV=vg_ibmx355021082/ lv_root LANG=en_US.UTF-8 rd_LVM_LV=vg_ibmx355021082/lv_swap rd_NO_MD SYSFONT=latarcyrheb-sun16 crashkernel=auto KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
....
. Utilice la `mkinitrd` comando para volver a crear la imagen initrd. RHEL 6x y versiones posteriores utilizan el comando: `mkinitrd -f /boot/ initrd-"uname -r".img uname -r`O el comando: `dracut -f`
. Reinicie el host.
. Compruebe el resultado del `cat /proc/cmdline` comando para garantizar que la configuración se ha completado.


Puede utilizar el `multipath -ll` Comando para verificar la configuración de las LUN de ONTAP. Las siguientes secciones proporcionan una salida multivía de muestra para una LUN asignada a personas ASA y no ASA.



=== Configuraciones de cabinas All SAN

En las configuraciones de ASA, todas las rutas a un LUN determinado son activas y optimizadas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra la salida correcta de una LUN de ONTAP:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
|- 1:0:8:1  sdb 8:16 active ready running
|- 2:0:8:1  sdd 8:48 active ready running
|- 1:0:9:1  sdc 8:32 active ready running
|- 2:0:9:1  sde 8:64 active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuración no ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con las mayores prioridades son activo/optimizado, lo que significa que la controladora donde se encuentra el agregado es la que presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas solo se usan cuando no hay rutas optimizadas disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 1:0:8:1  sdb 8:16 active ready running
| `- 2:0:8:1  sdd 8:48 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 1:0:9:1  sdc 8:32 active ready running
  `- 2:0:9:1  sde 8:64 active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



== Configuración recomendada

El sistema operativo RHEL 6.9 se compila para reconocer las LUN de ONTAP y establecer automáticamente todos los parámetros de configuración correctamente para la configuración tanto de ASA como de terceros.

La `multipath.conf` el archivo debe existir para que se inicie el daemon multivía, pero puede crear un archivo vacío de cero bytes mediante el siguiente comando:

`touch /etc/multipath.conf`

La primera vez que cree este archivo, es posible que deba habilitar e iniciar los servicios multivía:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* No es necesario añadir nada directamente al `multipath.conf` archivo, a menos que tenga dispositivos que no desea gestionar mediante multivía o que tenga la configuración existente que anula los valores predeterminados.
* Para excluir dispositivos no deseados, agregue la siguiente sintaxis a la `multipath.conf` archivo .
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
Sustituya el `<DevId>` con la `WWID` cadena del dispositivo que desea excluir.



.Ejemplo
En este ejemplo: `sda` Es el disco SCSI local que necesitamos agregar a la lista negra.

.Pasos
. Ejecute el siguiente comando para determinar el WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Siempre debe comprobar su `/etc/multipath.conf` archivo para configuraciones heredadas, especialmente en la sección de valores predeterminados, que podría sustituir la configuración predeterminada.

La siguiente tabla demuestra lo crítico `multipathd` Parámetros para las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y alguno de estos parámetros se anula, deberán corregirse posteriormente stanzas en el `multipath.conf` Archivo que se aplica específicamente a las LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Estos valores predeterminados solo se deben anular en consulta con NetApp o un proveedor de SO y solo cuando se comprenda plenamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "3 queue_if_no_path pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "operación por turnos 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `no_path_retry` Que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}

devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


=== Configuración de KVM

También puede utilizar los ajustes recomendados para configurar la máquina virtual basada en kernel (KVM). No es necesario realizar cambios para configurar KVM a medida que la LUN está asignada al hipervisor.



== Problemas y limitaciones conocidos

[cols="4*"]
|===
| ID de error de NetApp | Título | Descripción | ID Bugzilla 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1067272["1067272"^] | El estado del puerto remoto en el host Emulex LPe32002 podría estar en estado "bloqueado" durante las operaciones de conmutación por error del almacenamiento | Durante las operaciones de conmutación por error del almacenamiento, es posible que determinados Estados del puerto remoto del host RHEL 6.9 con el adaptador LPe32002 tengan el estado "bloqueado". Como las interfaces lógicas se reducen cuando un nodo de almacenamiento está inactivo, el puerto remoto establece el estado del nodo de almacenamiento en "bloqueado". Sin embargo, cuando el nodo de almacenamiento vuelve a estar en estado óptimo, las interfaces lógicas también se activa y se espera que el estado del puerto remoto sea "en línea". Pero, en cierta ocasión, el puerto remoto sigue estando "bloqueado". Este estado se manifiesta como "defectuoso" en LAS LUN de la capa multivía. | link:https://bugzilla.redhat.com/show_bug.cgi?id=1427496["427496"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1076584["1076584"^] | Se producen volcados de firmware en el HBA QE8362 de Red Hat Enterprise Linux 6.9 QLogic durante las operaciones de conmutación por error de almacenamiento | Pueden producirse volcados de firmware durante las operaciones de conmutación al nodo de respaldo del almacenamiento en hosts Red Hat Enterprise Linux (RHEL) 6.9 con adaptadores de bus de host (HBA) QLE8362 de QLogic. Ocasionalmente se observan volcados de firmware. Los volcados de firmware pueden manifestarse como interrupción de la actividad de I/o en el host, que puede durar hasta 1200 segundos. Una vez que el adaptador finaliza el volcado de los núcleos del firmware, la operación I/o se reanuda con normalidad. No se requiere ningún otro procedimiento de recuperación en el host. Para indicar el volcado de firmware, se muestra el siguiente mensaje en /var/log/ archivo de mensaje: Kernel: Qlast2xxx [0000:0c:00.3]-d001:3: Volcado de firmware guardado en búfer temporal (3/ffffc90018b01000), indicadores de estado de volcado (0x3f) | link:https://bugzilla.redhat.com/show_bug.cgi?id=1438711["1438711"^] 
|===