---
sidebar: sidebar 
permalink: hu_sles_15SP4.html 
keywords: host utilities, suse linux enterprise server 15 sp3, suse, linux, 15 sp3, netapp, ontap 
summary: Describe cómo utilizar SUSE Linux Enterprise Server 15 SP3 con ONTAP 
---
= Utilice SUSE Linux Enterprise Server 15 SP4 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Puede utilizar los ajustes de configuración del host SAN de ONTAP para configurar SUSE Linux Enterprise Server 15 SP4 con ONTAP como destino.



== Instale las utilidades unificadas de host de Linux

El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 y 64 bits. Si no sabe cuál es el archivo adecuado para su configuración, utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Lo que necesitará
Si tiene una versión de Linux Unified Host Utilities instalada actualmente, debe actualizarla o, debe eliminarla y seguir los pasos siguientes para instalar la versión más reciente.

. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] Sitio a su anfitrión.
. Use el siguiente comando para instalar el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque SAN

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=84067;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se haya realizado correctamente.




== Accesos múltiples

Para SUSE Linux Enterprise Server 15 SP4, la `/etc/multipath.conf` el archivo debe existir, pero no es necesario realizar cambios específicos en el archivo. SUSE Linux Enterprise Server 15 SP4 se compila con toda la configuración necesaria para reconocer y gestionar correctamente las LUN de ONTAP.

Puede utilizar el `multipath -ll` Comando para verificar la configuración de las LUN de ONTAP. Las siguientes secciones proporcionan una salida multivía de muestra para una LUN asignada a personas ASA y no ASA.



=== Configuraciones de cabinas All SAN

En todas las configuraciones de cabinas SAN (ASA), todas las rutas a un LUN determinado se mantienen activas y optimizadas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra la salida correcta de una LUN de ONTAP:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con las mayores prioridades son activo/optimizado, lo que significa que la controladora donde se encuentra el agregado es la que presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas solo se usan cuando no hay rutas optimizadas disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



== Configuración recomendada

SUSE Linux Enterprise Server 15 SP4 OS se compila para reconocer las LUN de ONTAP y establecer automáticamente todos los parámetros de configuración correctamente para la configuración de ASA y de otro tipo.

La `multipath.conf` el archivo debe existir para que se inicie el daemon multivía, pero puede crear un archivo vacío de cero bytes con el comando:
`touch /etc/multipath.conf`.

La primera vez que se crea este archivo, es posible que deba habilitar e iniciar los servicios multivía.

No es necesario añadir nada directamente al `multipath.conf` archivo, a menos que tenga dispositivos que no desea gestionar mediante multivía o que tenga la configuración existente que anula los valores predeterminados.

Puede añadir la siguiente sintaxis al `multipath.conf` archivo para excluir los dispositivos no deseados.

Sustituya `<DevId>` con la `WWID` cadena del dispositivo que desea excluir. Utilice el siguiente comando para determinar la `WWID`:

.Ejemplo
En este ejemplo: `sda` Es el disco SCSI local que necesitamos agregar a la lista negra.

.Pasos
. Ejecute el comando siguiente para determinar la `WWID`:
+
[listing]
----
# /usr/lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
. Añada el `WWID` valor de la estrofa de la lista negra en la `/etc/multipath.conf` archivo:
+
[listing]
----
blacklist {
wwid	360030057024d0730239134810c0cb833
devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*" devnode "^hd[a-z]"
devnode "^cciss.*"
}
----


Siempre debe comprobar su `/etc/multipath.conf` archivo para configuraciones heredadas, especialmente en la sección de valores predeterminados, que podría estar anulando los valores predeterminados.

La siguiente tabla muestra los parámetros multivía esenciales de las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y alguno de estos parámetros se anula, deberán corregirse posteriormente stanzas en `multipath.conf` Que se aplican específicamente a LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Estos valores predeterminados solo se deben anular consultando con NetApp o con el proveedor de sistemas operativos y únicamente cuando se haya comprendido completamente el impacto.

[cols="2"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "2 pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `no_path_retry` Que no son compatibles con las LUN de ONTAP. Si estos parámetros no se pueden quitar porque otras cabinas SAN todavía están conectadas al host, en su lugar se pueden corregir específicamente para LUN de ONTAP con un dispositivo estropeado.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}
devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


== Problemas conocidos

No existen problemas conocidos para la versión SUSE Linux Enterprise Server 15 SP4 con ONTAP.
