---
sidebar: sidebar 
permalink: hu_sles_15SP6.html 
keywords: host utilities, suse linux enterprise server 15 sp6, suse, linux, 15 sp6, netapp, ontap 
summary: Describe cómo utilizar SUSE Linux Enterprise Server 15 SP6 con ONTAP 
---
= Utilice SUSE Linux Enterprise Server 15 SP6 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar los ajustes de configuración del host SAN de ONTAP para configurar SUSE Linux Enterprise Server 15 SP6 con ONTAP como destino.



== Instale las utilidades unificadas de host de Linux

El paquete de software de utilidades de host unificadas Linux de NetApp está disponible en link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^]un archivo .rpm de 32 bits y 64 bits. Si no sabe qué archivo es el adecuado para su configuración, utilice el link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar cuál necesita.

NetApp recomienda la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración del host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

Si tiene Linux Unified Host Utilities instalado actualmente, debe actualizarla a la versión más reciente o quitarla y seguir estos pasos para instalar la versión más reciente.

.Pasos
. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] al host.
. Instale el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
------------------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque SAN

.Lo que necesitará
Su configuración admite arranque SAN. Consulte link:https://mysupport.netapp.com/matrix/imt.jsp?components=84067;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^]el para comprobar que el sistema operativo, el adaptador de bus de host, el firmware del adaptador de bus de host y el BIOS de arranque del adaptador de bus de host y la versión de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo del host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

Para SUSE Linux Enterprise Server 15 SP6, el `/etc/multipath.conf` archivo debe existir. No es necesario realizar cambios en este archivo porque SUSE Linux Enterprise Server 15 SP6 se compila con todas las configuraciones necesarias para reconocer y gestionar correctamente los LUN de ONTAP.

Puede utilizar el `multipath -ll` Comando para verificar la configuración de las LUN de ONTAP.

En las siguientes secciones se proporcionan ejemplos de salidas multivía para una LUN asignada a personas ASA y no ASA.



=== Configuraciones de cabinas All SAN

Las configuraciones de cabinas All SAN (ASA) optimizan todas las rutas para un LUN determinado, manteniéndolas activas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra el resultado correcto de una LUN de ONTAP.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Tener más de cuatro rutas puede ocasionar problemas de ruta durante errores de almacenamiento.



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que son operadas por la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Tener más de cuatro rutas puede ocasionar problemas de ruta durante errores de almacenamiento.



== Configuración recomendada

El sistema operativo SUSE Linux Enterprise Server 15 SP6 reconoce los LUN de ONTAP y establece automáticamente todos los parámetros de configuración correctamente para ASA configuraciones de ASA y de terceros. Puede optimizar aún más el rendimiento de la configuración del host con los siguientes ajustes recomendados.

 `multipath.conf`El archivo debe existir para que se inicie el daemon multivía. Si este archivo no existe, puede crear un archivo vacío de cero bytes con el `touch /etc/multipath.conf` comando.

La primera vez que crea el `multipath.conf` archivo, es posible que deba habilitar e iniciar los servicios multivía mediante los siguientes comandos:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
No es necesario agregar dispositivos directamente al `multipath.conf` archivo, a menos que tenga dispositivos que no desea que se gestionen mediante rutas múltiples o que tenga configuraciones existentes que anulen los valores predeterminados. Puede excluir los dispositivos no deseados agregando la siguiente sintaxis al `multipath.conf` archivo, reemplazando <DevId> por la cadena WWID del dispositivo que desea excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
En el siguiente ejemplo, determina el WWID de un dispositivo y agrega el dispositivo al `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
360030057024d0730239134810c0cb833
----
+
`sda` Es el disco SCSI local que desea agregar a la lista negra.

. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Siempre debe comprobar el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para los ajustes heredados que podrían estar anulando los valores predeterminados.

La siguiente tabla muestra `multipathd` los parámetros críticos de las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deberán corregirse posteriormente mediante estrofas en `multipath.conf` el archivo aplicables específicamente a las LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Solo debe anular estos valores predeterminados en consulta con NetApp y/o un proveedor de SO y solo cuando comprenda completamente el impacto.

[cols="2"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "2 pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `no_path_retry` Que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
   path_checker      readsector0
   no_path_retry      fail
}
devices {
   device {
      vendor         "NETAPP  "
      product         "LUN.*"
      no_path_retry     queue
      path_checker      tur
   }
}
----


== Problemas conocidos

No existen problemas conocidos para la versión SUSE Linux Enterprise Server 15 SP6 con ONTAP.
