---
sidebar: sidebar 
permalink: hu_solaris_62_cmd.html 
keywords: host utilities, unified, solaris, 6.2, netapp, ontap 
summary: Describe cómo usar Solaris Host Utilities 6,2 con ONTAP 
---
= Referencia de comandos de Solaris Host Utilities 6,2
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede usar la referencia de comandos de ejemplo de Solaris Host Utilities 6,2 para una validación integral de la configuración de almacenamiento de NetApp mediante la herramienta Utilidades de host.



== Enumere todos los iniciadores de hosts asignados al host

Puede recuperar una lista de todos los iniciadores de host asignados a un host.

[source, cli]
----
# sanlun fcp show adapter -v
----
*Ejemplo de salida*

[listing]
----
adapter name:      qlc3
WWPN:              21000024ff17a301
WWNN:              20000024ff17a301
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   1 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  32 GBit/sec
OS device name:    /dev/cfg/c7

adapter name:      qlc2
WWPN:              21000024ff17a300
WWNN:              20000024ff17a300
driver name:       qlc
model:             7335902
model description: 7115462, Oracle Storage Dual-Port 32 Gb Fibre Channel PCIe HBA
serial number:     463916R+1720333838
hardware version:  Not Available
driver version:    210226-5.10
firmware version:  8.08.04
Number of ports:   2 of 2
port type:         Fabric
port state:        Operational
supported speed:   8 GBit/sec, 16 GBit/sec, 32 GBit/sec
negotiated speed:  16 GBit/sec
OS device name:    /dev/cfg/c6
----


== Enumere todas las LUN asignadas al host

Puede recuperar una lista de todas las LUN asignadas a un host.

[source, cli]
----
# sanlun lun show -p -v all
----
*Ejemplo de salida*

[listing]
----

                    ONTAP Path: data_vserver:/vol1/lun1
                           LUN: 1
                      LUN Size: 10g
                   Host Device: /dev/rdsk/c0t600A0980383044485A3F4E694E4F775Ad0s2
                          Mode: C
            Multipath Provider: Sun Microsystems
              Multipath Policy: Native

----


== Enumerar todas las LUN asignadas a un host desde una SVM determinada/ enumerar todos los atributos de una LUN asignada al host

Puede recuperar una lista de todas las LUN asignadas a un host de una determinada SVM.

[source, cli]
----
# sanlun lun show -p -v sanboot_unix`
----
*Ejemplo de salida*

[listing]
----
ONTAP Path: sanboot_unix:/vol/sol_boot/sanboot_lun
                           LUN: 0
                      LUN Size: 180.0g

----


== Muestra los atributos de los LUN de ONTAP por nombre de archivo del dispositivo host

Puede recuperar una lista de todos los atributos de LUN de ONTAP especificando un nombre de archivo de dispositivo host.

[source, cli]
----
# sanlun lun show all
----
*Ejemplo de salida*

[listing]
----
controller(7mode/E-Series)/                                         device
vserver(cDOT/FlashRay)       lun-pathname                           filename
---------------------------------------------------------------------------------------------------------------
sanboot_unix                 /vol/sol_193_boot/chatsol_193_sanboot /dev/rdsk/c0t600A098038304437522B4E694E4A3043d0s2

host adapter    protocol lun size   product
---------------------------------------------
qlc3            FCP      180.0g     cDOT
----