---
sidebar: sidebar 
permalink: hu_solaris_62_rn.html 
keywords: host utilities, solaris, 6.2 netapp, ontap 
summary: Notas de la versión de Solaris Host Utilities 6.2 
---
= Notas de la versión de Solaris Host Utilities 6.2
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
En las notas de la versión se describen las nuevas funciones y mejoras, los problemas solucionados en la versión actual, los problemas y limitaciones conocidos y las precauciones importantes relacionadas con la configuración y gestión del host de Solaris específico con el sistema de almacenamiento de ONTAP.

Para obtener información específica acerca de las versiones del sistema operativo y las actualizaciones que admiten las utilidades de host, consulte link:https://mysupport.netapp.com/matrix/imt.jsp?components=85803;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^].



== Problemas y limitaciones conocidos

Debe conocer los siguientes problemas y limitaciones conocidos que pueden afectar el rendimiento en el host específico.

[cols="3"]
|===
| ID. De error | Título | Descripción 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1385189["1385189"^] | Cambios de enlace de controladores FC Solaris 11.4 requeridos en HUK 6.2 | Recomendaciones de Solaris 11,4 y HUK:
Se ha cambiado el enlace al controlador FC de `ssd(4D)` para `sd(4D)`. Mover la configuración que tiene en `ssd.conf` para `sd.conf` Tal como se menciona en Oracle (ID de documento 2595926.1). El comportamiento varía en los sistemas y sistemas Solaris 11,4 recién instalados actualizados desde versiones 11,3 o anteriores. 
|===
link:https://mysupport.netapp.com/site/["NetApp Bugs Online"^] proporciona información completa sobre la mayoría de los problemas conocidos, incluidas las soluciones alternativas sugeridas cuando sea posible. Algunas combinaciones de palabras clave y tipos de errores que puede que desee utilizar son los siguientes:

* FCP General: Muestra los errores de FC y del adaptador de bus de host (HBA) que no están asociados con un host específico.
* FCP Solaris

