---
sidebar: sidebar 
permalink: hu_solaris_62.html 
keywords: host utilities, unified, oracle, linux, 7.1, netapp, ontap 
summary: Describe cómo usar Solaris Host Utilities 6,2 con ONTAP 
---
= Instale Solaris Host Utilities 6,2 para el almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las utilidades de host de Solaris le ayudan a administrar el almacenamiento ONTAP conectado a un host de Solaris y ayudan al soporte técnico a recopilar datos de configuración.

Las utilidades de host de Solaris admiten varios entornos Solaris y múltiples protocolos de transporte.  Estos son los entornos principales de Solaris Host Utilities:

* El sistema operativo nativo con MPxIO y el protocolo Fibre Channel (FC) o iSCSI en un sistema que utiliza un procesador SPARC o un procesador x86/64.
* Rutas dinámicas múltiples de Veritas (DMP) con el protocolo FC o iSCSI en un sistema con un procesador SPARC, o el protocolo iSCSI en un sistema que utilice un procesador x86/64.


Las utilidades de host de Solaris 6.2 admiten las siguientes series de Solaris:

* Solaris 11.x
* Solaris 10.x


.Antes de empezar
Verifique que su configuración iSCSI, FC o FCoE sea compatible.  Puedes utilizar ellink:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar su configuración.

.Pasos
. Inicie sesión en su host como root.
. Descargue una copia del archivo comprimido que contiene las utilidades del host desdelink:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/6.2/downloads["Sitio de soporte de NetApp"^] a un directorio en su host Solaris:
+
[role="tabbed-block"]
====
.CPU SPARC
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
--
.CPU x86/x64
--
[source, cli]
----
netapp_solaris_host_utilities_6_2_amd.tar.gz
----
--
====
. Vaya al directorio en su host Solaris que contiene la descarga.
. Descomprima el archivo con el `gunzip` comando:
+
[source, cli]
----
gunzip netapp_solaris_host_utilities_6_2_sparc.tar.gz
----
. Extraiga el archivo usando el `tar xvf` dominio:
+
[source, cli]
----
tar xvf netapp_solaris_host_utilities_6_2_sparc.tar
----
. Añade los paquetes que extrajiste del archivo tar a tu host
+
[source, cli]
----
pkgadd
----
+
Los paquetes se agregan a la `/opt/NTAP/SANToolkit/bin` directorio.

+
En el siguiente ejemplo se utiliza `pkgadd` el comando para instalar el paquete de instalación de Solaris:

+
[source, cli]
----
pkgadd -d ./NTAPSANTool.pkg
----
. Confirme que el kit de herramientas se instaló correctamente utilizando uno de los siguientes comandos:
+
[source, cli]
----
pkginfo
----
+
[source, cli]
----
ls - al
----
+
.Mostrar ejemplos de salidas
[%collapsible]
====
[listing]
----
# ls -alR /opt/NTAP/SANToolkit
/opt/NTAP/SANToolkit:
total 1038
drwxr-xr-x   3 root     sys            4 Jul 22  2019 .
drwxr-xr-x   3 root     sys            3 Jul 22  2019 ..
drwxr-xr-x   2 root     sys            6 Jul 22  2019 bin
-r-xr-xr-x   1 root     sys       432666 Sep 13  2017 NOTICES.PDF

/opt/NTAP/SANToolkit/bin:
total 7962
drwxr-xr-x   2 root     sys            6 Jul 22  2019 .
drwxr-xr-x   3 root     sys            4 Jul 22  2019 ..
-r-xr-xr-x   1 root     sys      2308252 Sep 13  2017 host_config
-r-xr-xr-x   1 root     sys          995 Sep 13  2017 san_version
-r-xr-xr-x   1 root     sys      1669204 Sep 13  2017 sanlun
-r-xr-xr-x   1 root     sys          677 Sep 13  2017 vidpid.dat

# (cd /usr/share/man/man1; ls -al host_config.1 sanlun.1)
-r-xr-xr-x   1 root     sys        12266 Sep 13  2017 host_config.1
-r-xr-xr-x   1 root     sys         9044 Sep 13  2017 sanlun.1
----
====
. Configure los parámetros del host para su entorno MPxIO o Veritas DMP:
+
[source, cli]
----
/opt/NTAP/SANToolkit/bin/host_config
----
. Compruebe la instalación:
+
[source, cli]
----
sanlun version
----




== El futuro

link:hu-solaris-san-toolkit.html["Obtenga más información sobre el kit de herramientas SAN"] .
