---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Describe cómo utilizar SUSE Linux Enterprise Server 12 SP3 con ONTAP 
---
= Utilice SUSE Linux Enterprise Server 12 SP3 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede utilizar los ajustes de configuración del host SAN de ONTAP para configurar SUSE Linux Enterprise Server 12 SP3 con ONTAP como destino.



== Instale las utilidades unificadas de host de Linux

El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 y 64 bits. Si no sabe cuál es el archivo adecuado para su configuración, utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad de NetApp"^] para verificar cuál necesita.

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Lo que necesitará
Si tiene una versión de Linux Unified Host Utilities instalada actualmente, debe actualizarla o, debe eliminarla y seguir los pasos siguientes para instalar la versión más reciente.

. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits del link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] Sitio a su anfitrión.
. Use el siguiente comando para instalar el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`




NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Kit de herramientas SAN

El kit de herramientas se instala automáticamente cuando instala el paquete de utilidades de host de NetApp. Este kit proporciona la `sanlun` Utilidad, que le ayuda a gestionar LUN y HBA. La `sanlun` Comando muestra información acerca de las LUN asignadas a su host, multivía e información necesaria para crear iGroups.

.Ejemplo
En el siguiente ejemplo, la `sanlun lun show` Command muestra información de LUN.

[source, cli]
----
# sanlun lun show all
----
Resultado de ejemplo:

[listing]
----
controller(7mode/E-Series)/            device     host               lun
vserver(cDOT/FlashRay)   lun-pathname  filename   adapter  protocol  size    Product
-------------------------------------------------------------------------
data_vserver          /vol/vol1/lun1   /dev/sdb   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol1/lun1   /dev/sdc   host15   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sdd   host16   FCP       120.0g  cDOT
data_vserver          /vol/vol2/lun2   /dev/sde   host15   FCP       120.0g  cDOT
----


== Arranque San

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://mysupport.netapp.com/matrix/imt.jsp?components=80043;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se haya realizado correctamente.




== Accesos múltiples

Para SUSE Linux Enterprise Server 12 SP3, debe existir el archivo /etc/multipath.conf, pero no es necesario realizar cambios específicos en el archivo. SUSE Linux Enterprise Server 12 SP3 se compila con todas las configuraciones necesarias para reconocer y gestionar correctamente las LUN de ONTAP.

Puede utilizar el `multipath -ll` Comando para verificar la configuración de las LUN de ONTAP. Las siguientes secciones proporcionan una salida multivía de muestra para una LUN asignada a personas ASA y no ASA.



=== Configuraciones de cabinas All SAN

En todas las configuraciones de cabinas SAN (ASA), todas las rutas a un LUN determinado se mantienen activas y optimizadas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra la salida correcta de una LUN de ONTAP:

[listing]
----
# multipath -ll
3600a0980383034466b2b4a3775474859 dm-3 NETAPP,LUN C-Mode
size=20G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handle' hwhandler='1 alua' wp=rw
|-+- policy='round-robin 0' prio=50 status=active
| |- 1:0:8:1  sdb 8:16 active ready running
| `- 2:0:8:1  sdd 8:48 active ready running
`-+- policy='round-robin 0' prio=10 status=enabled
  |- 1:0:9:1  sdc 8:32 active ready running
  `- 2:0:9:1  sde 8:64 active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con las mayores prioridades son activo/optimizado, lo que significa que la controladora donde se encuentra el agregado es la que presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas solo se usan cuando no hay rutas optimizadas disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='4 queue_if_no_path pg_init_retries 50 retain_attached_hw_handler' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 11:0:1:0 sdj 8:144 active ready running
| |- 11:0:2:0 sdr 65:16 active ready running
`-+- policy='service-time 0' prio=10 status=enabled
|- 11:0:0:0 sdb 8:i6 active ready running
|- 12:0:0:0 sdz 65:144 active ready running
----

NOTE: No utilice un número excesivo de rutas a una única LUN. No se necesitan más de cuatro rutas. Más de ocho rutas pueden causar problemas de ruta durante fallos de almacenamiento.



== Configuración recomendada

SUSE Linux Enterprise Server 12 SP3 OS se compila para reconocer los LUN de ONTAP y definir automáticamente todos los parámetros de configuración correctamente.
La `multipath.conf` el archivo debe existir para que se inicie el daemon multivía, pero puede crear un archivo vacío de cero bytes mediante el siguiente comando:

`touch /etc/multipath.conf`

La primera vez que cree este archivo, es posible que deba habilitar e iniciar los servicios multivía:

[listing]
----
# systemctl enable multipathd
# systemctl start multipathd
----
* No es necesario añadir nada directamente al `multipath.conf` archivo, a menos que tenga dispositivos que no desea gestionar mediante multivía o que tenga la configuración existente que anula los valores predeterminados.
* Para excluir dispositivos no deseados, agregue la siguiente sintaxis a la `multipath.conf` archivo .
+
[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
+
Sustituya el `<DevId>` con la `WWID` cadena del dispositivo que desea excluir.

+
.Ejemplo
En este ejemplo, vamos a determinar el WWID de un dispositivo y agregar al `multipath.conf` archivo.

+
.Pasos
.. Ejecute el siguiente comando para determinar el WWID:
+
[listing]
----
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
----
+
`sda` Es el disco SCSI local que necesitamos para agregarlo a la lista negra.

.. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[listing]
----
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----




Siempre debe comprobar su `/etc/multipath.conf` archivo para configuraciones heredadas, especialmente en la sección de valores predeterminados, que podría sustituir la configuración predeterminada.

La siguiente tabla demuestra lo crítico `multipathd` Parámetros para las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y alguno de estos parámetros se anula, deberán corregirse posteriormente stanzas en el `multipath.conf` Archivo que se aplica específicamente a las LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Estos valores predeterminados solo se deben anular en consulta con NetApp o un proveedor de SO y solo cuando se comprenda plenamente el impacto.

[cols="2*"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "2 pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN.* 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
.Ejemplo
El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este caso, el `multipath.conf` el archivo define los valores para `path_checker` y.. `no_path_retry` Que no son compatibles con las LUN de ONTAP. Si no se pueden quitar debido a que aún hay otras cabinas SAN conectadas al host, estos parámetros pueden corregirse específicamente para LUN de ONTAP con una sección de dispositivo.

[listing]
----
defaults {
 path_checker readsector0
 no_path_retry fail
}
devices {
 device {
 vendor "NETAPP "
 product "LUN.*"
 no_path_retry queue
 path_checker tur
 }
}
----


== Problemas conocidos

La versión SLES 15 SP3 con ONTAP tiene los siguientes problemas conocidos:

[cols="4*"]
|===
| ID de error de NetApp | Título | Descripción | ID Bugzilla 


| link:https://https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Se observaron interrupciones en el kernel en la versión SLES12 SP3 de kernel con Emulex LPe16002 16 GB FC durante la conmutación por error de almacenamiento | Puede producirse una interrupción del kernel durante las operaciones de conmutación por error del almacenamiento en la versión de kernel SLES12 SP3 con Emulex LPe16002 HBA. La interrupción del kernel solicita un reinicio del sistema operativo, lo que a su vez provoca una interrupción de la aplicación. Si se configura kdump, la interrupción del kernel genera un archivo vmcore en /var/crash/directory. Puede investigar la causa del error en el archivo vmcore. Ejemplo: En el caso observado, se observó la interrupción del núcleo en el módulo “lpfc_sli_ringtxcmpl_put+51” y se registra en el archivo vmcore – Exception RIP: Lpfc_sli_ringtxcmpl_put+51. Recupere el sistema operativo después de la interrupción del kernel reiniciando el sistema operativo del host y reiniciando la aplicación. | link:http://bugzilla.suse.com/show_bug.cgi?id=1042847["1042847"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Se observaron interrupciones en el kernel en la versión SLES12 SP3 de kernel con Emulex LPe32002 32 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Puede producirse una interrupción del kernel durante las operaciones de conmutación por error del almacenamiento en la versión de kernel SLES12 SP3 con Emulex LPe32002 HBA. La interrupción del kernel solicita un reinicio del sistema operativo, lo que a su vez provoca una interrupción de la aplicación. Si se configura kdump, la interrupción del kernel genera un archivo vmcore en /var/crash/directory. Puede investigar la causa del error en el archivo vmcore. Ejemplo: En el caso observado, se observó la interrupción del núcleo en el módulo “lpfc_sli_free_hbq+76” y se registra en el archivo vmcore – Exception RIP: Lpfc_sli_free_hbq+76. Recupere el sistema operativo después de la interrupción del kernel reiniciando el sistema operativo del host y reiniciando la aplicación. | link:http://bugzilla.suse.com/show_bug.cgi?id=1042807["1042807"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Se observó una interrupción del kernel en SLES12SP3 con QLogic QLE2562 8 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Durante las operaciones de conmutación por error del almacenamiento en el kernel Sles12sp3 (kernel-default-4.4.82-6.3.1) con QLogic QLE2562 HBA, se observó una interrupción del kernel debido a una caída del kernel. La alerta del kernel lleva a un reinicio del sistema operativo, lo que provoca una interrupción de la aplicación. El error de alerta del kernel genera el archivo vmcore en el directorio /var/crash/ si se configura kdump. Tras la alerta de kernel, puede usarse el archivo vmcore para comprender la causa del error. Ejemplo: En este caso, se observó el pánico en el módulo “blk_finish_request+289”. Se registra en el archivo vmcore con la siguiente cadena: "Exception RIP: blk_find_request+289" después de la interrupción del kernel, puede recuperar el sistema operativo reiniciando el sistema operativo host. Puede reiniciar la aplicación según sea necesario. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062496["1062496"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Se observa una interrupción del kernel en SLES12SP3 con Qlogic QLE2662 16 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Durante las operaciones de recuperación tras fallos de almacenamiento en el kernel Sles12sp3 (kernel-default-4.4.82-6.3.1) con HBA Qlogic QLE2662, es posible que observe la interrupción del kernel. Esto indica un reinicio del sistema operativo que provoca la interrupción de la aplicación. La interrupción del kernel genera un archivo vmcore en el directorio /var/crash/ si se configura kdump. El archivo vmcore se puede usar para comprender la causa del fallo. Ejemplo: En este caso, se observó la interrupción del kernel en el módulo "dirección desconocida o no válida" y se registra en el archivo vmcore con la siguiente cadena: Exception RIP: Dirección desconocida o no válida. Tras la interrupción del kernel, se puede recuperar el sistema operativo reiniciando el sistema operativo host y reiniciando la aplicación según sea necesario. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062508["1062508"^] 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Se observó una interrupción del kernel en SLES12SP3 con Emulex LPe16002 16 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Durante las operaciones de conmutación por error del almacenamiento en el kernel Sles12sp3 (kernel-default-4.4.87-3.1) con HBA Emulex LPe16002, es posible que observe una interrupción del kernel. Esto indica un reinicio del sistema operativo que provoca la interrupción de la aplicación. La interrupción del kernel genera un archivo vmcore en el directorio /var/crash/ si se configura kdump. El archivo vmcore se puede usar para comprender la causa del fallo. Ejemplo: En este caso, se observó una interrupción del núcleo en el módulo “RAW_spin_lock_irqsave+30” y se registra en el archivo vmcore con la siguiente cadena: – Exception RIP: _RAW_spin_lock_irqsave+30. Tras la interrupción del kernel, se puede recuperar el sistema operativo reiniciando el sistema operativo host y reiniciando la aplicación según sea necesario. | link:http://bugzilla.suse.com/show_bug.cgi?id=1062514["1062514"^] 
|===