---
sidebar: sidebar 
permalink: hu_sles_12SP3.html 
keywords: host utilities, suse linux enterprise server 12 SP3, suse, linux, 12 SP3, netapp, ontap 
summary: Instale Linux Host Utilities en un SUSE Linux Enterprise Server 12 SP3 para administrar operaciones de protocolo FCP e iSCSI con LUN de ONTAP. 
---
= Configure SUSE Linux Enterprise Server 12 SP3 para FCP e iSCSI con almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El software de utilidades de host Linux proporciona herramientas de gestión y diagnóstico para hosts Linux que se conectan al almacenamiento de ONTAP. Al instalar las utilidades del host de Linux en un host SUSE Linux Enterprise Server 12 SP3, puede utilizar las utilidades del host para ayudarle a administrar las operaciones del protocolo FCP e iSCSI con LUN de ONTAP.


NOTE: No es necesario configurar manualmente los ajustes de la máquina virtual basada en kernel (KVM) porque los LUN de ONTAP se asignan automáticamente al hipervisor.



== Paso 1: Opcionalmente, habilite el arranque SAN

Puede configurar su host para que utilice el arranque SAN y simplificar la puesta en marcha y mejorar la escalabilidad.

.Antes de empezar
Utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Linux, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.

.Pasos
. link:https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["Cree un LUN de arranque SAN y asígnelo al host"^].
. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Compruebe que la configuración se haya realizado correctamente. Para ello, reinicie el host y verifique que el sistema operativo esté activo y en ejecución.




== Paso 2: Instale las utilidades del host de Linux

NetApp recomienda la instalación de las utilidades del host Linux para admitir la gestión de las LUN de ONTAP y ayudar al soporte técnico con la recopilación de datos de configuración.

link:hu_luhu_71.html["Instale Linux Host Utilities 7,1"].


NOTE: La instalación de Linux Host Utilities no cambia ninguna configuración de tiempo de espera del host en el host Linux.



== Paso 3: Confirme la configuración multivía del host

Puede utilizar accesos múltiples con SUSE Linux Enterprise Server 12 SP3 para gestionar los LUN de ONTAP.

Para garantizar que el acceso multivía esté configurado correctamente para el host, verifique que el `/etc/multipath.conf` archivo esté definido y que los ajustes recomendados de NetApp estén configurados para los LUN de ONTAP.

.Pasos
. Compruebe que el `/etc/multipath.conf` archivo existe:
+
[source, cli]
----
ls /etc/multipath.conf
----
+
Si el archivo no existe, cree un archivo vacío de cero bytes:

+
[source, cli]
----
touch /etc/multipath.conf
----
. La primera vez que `multipath.conf` se crea el archivo, es posible que deba habilitar e iniciar los servicios multivía para cargar la configuración recomendada:
+
[source, cli]
----
systemctl enable multipathd
----
+
[source, cli]
----
systemctl start multipathd
----
. Cada vez que arranca el host, el archivo de cero bytes vacío `/etc/multipath.conf` carga automáticamente los parámetros multivía de host recomendados por NetApp como configuración predeterminada. No debería ser necesario realizar cambios en `/etc/multipath.conf` el archivo para el host ya que el sistema operativo del host está compilado con los parámetros multivía que reconocen y gestionan correctamente las LUN de ONTAP.
+
En la siguiente tabla se muestra la configuración de los parámetros multivía compilados por el sistema operativo Linux nativo para los LUN de ONTAP.

+
.Muestra la configuración de los parámetros
[%collapsible]
====
[cols="2"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "2 pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
====
. Compruebe la configuración de parámetros y el estado de la ruta de sus LUN de ONTAP:
+
[source, cli]
----
multipath -ll
----
+
Los parámetros multiruta predeterminados admiten configuraciones ASA, AFF y FAS . En estas configuraciones, un solo LUN de ONTAP no debería requerir más de cuatro rutas. Tener más de cuatro rutas puede causar problemas durante una falla de almacenamiento.

+
En el siguiente ejemplo, se muestran los ajustes de parámetros y el estado de la ruta correctos para las LUN de ONTAP en una configuración de ASA, AFF o FAS.

+
[role="tabbed-block"]
====
.Configuración de ASA
--
Una configuración de ASA optimiza todas las rutas a una LUN determinada para mantenerlas activas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
`-+- policy='service-time 0' prio=50 status=active
  |- 3:0:7:9    sdco 69:192  active ready running
  |- 3:0:8:9    sddi 71:0    active ready running
  |- 14:0:8:9   sdjq 65:320  active ready running
  `- 14:0:7:9   sdiw 8:256   active ready running
----
--
.Configuración de AFF o FAS
--
Una configuración de AFF o FAS debe tener dos grupos de rutas con prioridades superiores e inferiores. La controladora donde se encuentra el agregado ofrece rutas activas/optimizadas de mayor prioridad. Las rutas de prioridad más baja están activas pero no optimizadas debido a que se sirven con una controladora diferente. Las rutas no optimizadas solo se usan cuando las rutas optimizadas no están disponibles.

En el siguiente ejemplo, se muestra el resultado de una LUN de ONTAP con dos rutas activa/optimizada y dos rutas activa/no optimizada:

[listing]
----
# multipath -ll
3600a09803831347657244e527766394e dm-5 NETAPP,LUN C-Mode
size=80G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 3:0:3:0    sdd  8:48    active ready running
| |- 3:0:4:0    sdx  65:112  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 14:0:2:0   sdfk 130:96  active ready running
  `- 14:0:5:0   sdgz 132:240 active ready running
----
--
====




== Paso 4: Opcionalmente, excluya un dispositivo de las rutas múltiples

Si es necesario, puede excluir un dispositivo del acceso múltiple agregando el WWID del dispositivo no deseado a la estrofa de la lista negra del `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[source, cli]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
“sda” es el disco SCSI local que desea agregar a la lista negra.

+
Un ejemplo de WWID es `360030057024d0730239134810c0cb833`.

. Añada el WWID a la estrofa «blacklist»:
+
[source, cli]
----
blacklist {
	     wwid   360030057024d0730239134810c0cb833
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----




== Paso 5: Personalice los parámetros multivía para las LUN de ONTAP

Si su host está conectado a LUN de otros proveedores y cualquiera de la configuración de parámetros multivía se ha anulado, debe corregirlos agregando estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a LUN de ONTAP. Si no hace esto, es posible que las LUN de ONTAP no funcionen como se espera.

Compruebe el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para ver los ajustes que podrían estar anulando el <<multipath-parameter-settings,configuración predeterminada para parámetros multivía>>.


CAUTION: No debe anular la configuración de parámetros recomendada para las LUN de ONTAP. Estos ajustes se requieren para el rendimiento óptimo de la configuración del host. Póngase en contacto con el soporte de NetApp, con su proveedor de SO o con ambos para obtener más información.

El ejemplo siguiente muestra cómo corregir un valor predeterminado anulado. En este ejemplo, el `multipath.conf` archivo define valores para `path_checker` y `no_path_retry` que no son compatibles con LUN de ONTAP, y no puede quitar estos parámetros porque las cabinas de almacenamiento ONTAP siguen conectadas al host. En su lugar, corrija los valores para `path_checker` y `no_path_retry` agregando una estrofa de dispositivo al `multipath.conf` archivo que se aplica específicamente a los LUN de ONTAP.

.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
defaults {
   path_checker      *readsector0*
   no_path_retry     *fail*
}

devices {
   device {
      vendor          "NETAPP"
      product         "LUN"
      no_path_retry   *queue*
      path_checker    *tur*
   }
}
----
====


== Paso 6: Revise los problemas conocidos

La versión SUSE Linux Enterprise Server 12 SP3 con almacenamiento ONTAP presenta los siguientes problemas conocidos:

[cols="3*"]
|===
| ID de error de NetApp | Título | Descripción 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089555["1089555"^] | Se observaron interrupciones en el kernel en la versión SLES12 SP3 de kernel con Emulex LPe16002 16 GB FC durante la conmutación por error de almacenamiento | Puede producirse una interrupción del kernel durante las operaciones de conmutación por error del almacenamiento en la versión de kernel SLES12 SP3 con Emulex LPe16002 HBA. La interrupción del kernel solicita un reinicio del sistema operativo, lo que a su vez provoca una interrupción de la aplicación. Si se configura kdump, la interrupción del kernel genera un archivo vmcore en /var/crash/directory. Puede investigar la causa del error en el archivo vmcore. Ejemplo: En el caso observado, se observó la interrupción del núcleo en el módulo “lpfc_sli_ringtxcmpl_put+51” y se registra en el archivo vmcore – Exception RIP: Lpfc_sli_ringtxcmpl_put+51. Recupere el sistema operativo después de la interrupción del kernel reiniciando el sistema operativo del host y reiniciando la aplicación. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1089561["1089561"^] | Se observaron interrupciones en el kernel en la versión SLES12 SP3 de kernel con Emulex LPe32002 32 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Puede producirse una interrupción del kernel durante las operaciones de conmutación por error del almacenamiento en la versión de kernel SLES12 SP3 con Emulex LPe32002 HBA. La interrupción del kernel solicita un reinicio del sistema operativo, lo que a su vez provoca una interrupción de la aplicación. Si se configura kdump, la interrupción del kernel genera un archivo vmcore en /var/crash/directory. Puede investigar la causa del error en el archivo vmcore. Ejemplo: En el caso observado, se observó la interrupción del núcleo en el módulo “lpfc_sli_free_hbq+76” y se registra en el archivo vmcore – Exception RIP: Lpfc_sli_free_hbq+76. Recupere el sistema operativo después de la interrupción del kernel reiniciando el sistema operativo del host y reiniciando la aplicación. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117248["1117248"^] | Se observó una interrupción del kernel en SLES12SP3 con QLogic QLE2562 8 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Durante las operaciones de conmutación por error del almacenamiento en el kernel Sles12sp3 (kernel-default-4.4.82-6.3.1) con QLogic QLE2562 HBA, se observó una interrupción del kernel debido a una caída del kernel. La alerta del kernel lleva a un reinicio del sistema operativo, lo que provoca una interrupción de la aplicación. El error de alerta del kernel genera el archivo vmcore en el directorio /var/crash/ si se configura kdump. Tras la alerta de kernel, puede usarse el archivo vmcore para comprender la causa del error. Ejemplo: En este caso, se observó el pánico en el módulo “blk_finish_request+289”. Se registra en el archivo vmcore con la siguiente cadena: "Exception RIP: blk_find_request+289" después de la interrupción del kernel, puede recuperar el sistema operativo reiniciando el sistema operativo host. Puede reiniciar la aplicación según sea necesario. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117261["1117261"^] | Se observa una interrupción del kernel en SLES12SP3 con Qlogic QLE2662 16 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Durante las operaciones de recuperación tras fallos de almacenamiento en el kernel Sles12sp3 (kernel-default-4.4.82-6.3.1) con HBA Qlogic QLE2662, es posible que observe la interrupción del kernel. Esto indica un reinicio del sistema operativo que provoca la interrupción de la aplicación. La interrupción del kernel genera un archivo vmcore en el directorio /var/crash/ si se configura kdump. El archivo vmcore se puede usar para comprender la causa del fallo. Ejemplo: En este caso, se observó la interrupción del kernel en el módulo "dirección desconocida o no válida" y se registra en el archivo vmcore con la siguiente cadena: Exception RIP: Dirección desconocida o no válida. Tras la interrupción del kernel, se puede recuperar el sistema operativo reiniciando el sistema operativo host y reiniciando la aplicación según sea necesario. 


| link:https://mysupport.netapp.com/NOW/cgi-bin/bol?Type=Detail&Display=1117274["1117274"^] | Se observó una interrupción del kernel en SLES12SP3 con Emulex LPe16002 16 GB FC durante las operaciones de recuperación tras fallos de almacenamiento | Durante las operaciones de conmutación por error del almacenamiento en el kernel Sles12sp3 (kernel-default-4.4.87-3.1) con HBA Emulex LPe16002, es posible que observe una interrupción del kernel. Esto indica un reinicio del sistema operativo que provoca la interrupción de la aplicación. La interrupción del kernel genera un archivo vmcore en el directorio /var/crash/ si se configura kdump. El archivo vmcore se puede usar para comprender la causa del fallo. Ejemplo: En este caso, se observó una interrupción del núcleo en el módulo “RAW_spin_lock_irqsave+30” y se registra en el archivo vmcore con la siguiente cadena: – Exception RIP: _RAW_spin_lock_irqsave+30. Tras la interrupción del kernel, se puede recuperar el sistema operativo reiniciando el sistema operativo host y reiniciando la aplicación según sea necesario. 
|===


== El futuro

* link:hu-luhu-command-reference.html["Obtenga más información sobre el uso de la herramienta Linux Host Utilities"] .
* Obtenga más información sobre la duplicación de ASM.
+
El mirroring de Gestión Automática de Almacenamiento (ASM) puede requerir cambios en la configuración de multivía de Linux para permitir que ASM reconozca un problema y realice el cambio a un grupo de fallos alternativo. La mayoría de las configuraciones de ASM de ONTAP utilizan redundancia externa, lo que significa que la protección de datos es proporcionada por la cabina externa y ASM no hace mirroring de los datos. Algunos sitios utilizan ASM con redundancia normal para proporcionar duplicación bidireccional, normalmente en diferentes sitios. Consulte link:https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html["Bases de datos de Oracle en ONTAP"^] para obtener más información.


