---
sidebar: sidebar 
permalink: hu_vsphere_6.html 
keywords: host utilities, veritas, infoscale, 6.5. 6.7, netapp, ontap 
summary: Describe cómo utilizar Veritas Infocale 6.5 y 6.7 para Linux con ONTAP 
---
= Utilice VMware vSphere 6,5 y 6,7 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible usar las opciones de configuración del host de SAN de ONTAP para las versiones vSphere 6,5.x y 6,7.x con los protocolos FC, FCoE y iSCSI.



== Arranque SAN de hipervisores

.Antes de empezar
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^]para verificar que el sistema operativo, el HBA, el firmware del HBA y la versión de arranque del BIOS y ONTAP sean compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo del host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

ESXi proporciona un módulo multivía ampliable llamado complemento nativo multivía (NMP) que gestiona los subplugins, los complementos de tipo de cabina de almacenamiento (SATP) y los complementos de selección de rutas (PSP). Estas reglas SATP están disponibles de forma predeterminada en ESXi.

Para el almacenamiento de ONTAP, el complemento «VMW_SATP_ALUA» se utiliza de forma predeterminada con «VMW_PSP_RR» como política de selección de rutas (PSP). Puede ejecutar el siguiente comando para confirmar PSP:

*`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`*

[listing]
----
Name           Device  Vendor    Model     Driver  Transport  Options
-------------  ------  ------    -------   ------  ---------  -------
VMW_SATP_ALUA           LSI      INF-01-00                reset_on_attempted_reserve
VMW_SATP_ALUA           NETAPP                            reset_on_attempted_reserve

Rule Group  Claim Options  Default PSP  PSP Options  Description
----------  -------------  -----------  -----------  ------------
system        tpgs_on         VMW_PSP_MRU       NetApp E-Series arrays with ALUA support
system        tpgs_on          MW_PSP_RR 	      NetApp arrays with ALUA support

----


=== Configuraciones de cabinas All SAN

Las configuraciones de cabinas All SAN (ASA) optimizan todas las rutas para un LUN determinado, manteniéndolas activas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra el resultado correcto de una LUN de ONTAP.

*`esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453`*

[listing]
----
fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:204a00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=6,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201d00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201b00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:201e00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
En el ejemplo anterior, se ha asignado la LUN del almacenamiento de NetApp con 4 rutas (4 activas-optimizadas).



=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que son operadas por la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas.

*`esxcli storage nmp path list -d naa.600a098038313530772b4d673979372f`*

[listing]
----
fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200b00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=29,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200700a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=25,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200800a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=26,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200c00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=30,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----
En el ejemplo anterior, se ha asignado la LUN del almacenamiento de NetApp con 4 rutas (2 activas-optimizadas y 2 activas-desoptimizadas).



== VVol

Virtual Volumes (vVols) es un tipo de objeto de VMware que corresponde a un disco de máquina virtual (VM), así como a sus snapshots y clones rápidos.

Las herramientas de ONTAP para VMware vSphere incluyen el proveedor VASA para ONTAP, que proporciona el punto de integración para que una instancia de VMware vCenter aproveche el almacenamiento basado en vVols. Cuando se pone en marcha el OVA de las herramientas de ONTAP, se registra automáticamente en vCenter Server y se habilita el proveedor de VASA.

Cuando se crea un almacén de datos vVols mediante la interfaz de usuario de vCenter, este guía para crear FlexVols como almacenamiento de backup para el almacén de datos. Los vVols dentro de un almacén de datos vVols acceden a través de hosts ESXi con un extremo de protocolo (PE). En entornos SAN, se crea un LUN de 4MB TB en cada volumen FlexVol volume del almacén de datos para usarlo como PE. UNA SAN PE es una unidad lógica administrativa (ALU); los vVols son unidades lógicas subsidiarias (PLUS).

Al usar vVols, se aplican los requisitos estándar y las prácticas recomendadas para los entornos SAN que incluyen (pero sin limitarse a ellos):

. Cree al menos un LIF SAN en cada nodo por SVM que desee utilizar. La práctica recomendada es crear al menos dos por nodo, pero no más del necesario.
. Elimine cualquier punto único de fallo. Utilice varias interfaces de red de VMkernel en distintas subredes de la red que utilizan la agrupación de NIC cuando se utilizan varios switches virtuales o utilizan varias NIC físicas conectadas a varios switches físicos para proporcionar alta disponibilidad y un mayor rendimiento.
. Configurar la división en zonas y/o VLAN como sea necesario para la conectividad de host.
. Asegúrese de que todos los iniciadores necesarios hayan iniciado sesión en las LIF de destino en la SVM deseada.



NOTE: Para habilitar el proveedor VASA, debe implementar herramientas de ONTAP para VMware vSphere. VASA Provider gestionará todas las configuraciones de los igroups por usted, por lo que no es necesario crear ni gestionar iGroups en un entorno vVols.

NetApp no recomienda cambiar ninguna configuración predeterminada de vVols en este momento.

Consulte el https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para obtener versiones específicas de las herramientas de ONTAP o el proveedor VASA heredado para obtener versiones específicas de vSphere y ONTAP.

Para obtener información detallada sobre el aprovisionamiento y la gestión de vVols, consulte la documentación sobre las herramientas de ONTAP para VMware vSphere, así https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597"^] como la y. link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400."^]



== Configuración recomendada



=== Bloqueo ATS

El bloqueo ATS es *obligatorio* para almacenamiento compatible con VAAI y VMFS5 actualizado, y es necesario para obtener una interoperabilidad adecuada y un rendimiento de E/S de almacenamiento compartido VMFS óptimo con LUN de ONTAP. Consulte la documentación de VMware para obtener más información sobre cómo habilitar el bloqueo ATS.

[cols="4*"]
|===
| Configuración | Predeterminado | ONTAP recomendado | Descripción 


| HardwaraceleradoLocking | 1 | 1 | Ayuda a habilitar el uso de bloqueo de prueba atómica y ajuste (ATS) 


| IOPS de disco | 1000 | 1 | Límite de IOPS: Round Robin PSP establece de forma predeterminada un límite de IOPS de 1000. En este caso predeterminado, se utiliza una nueva ruta después de que se epide 1000 operaciones de E/S. 


| Disco/QFullSampleSize | 0 | 32 | El recuento de condiciones DE COLA LLENA o DE ACTIVIDAD que se tarda antes de que ESXi comience a tope. 
|===

NOTE: Habilite la configuración Space-alloc para que funcione LA FUNCIÓN UNMAP en todas las LUN asignadas a VMware vSphere. Para obtener información detallada, consulte https://docs.netapp.com/ontap-9/index.jsp["Documentación de ONTAP"^].



=== Tiempos de espera del sistema operativo invitado

Puede configurar manualmente las máquinas virtuales con los ajustes del sistema operativo invitado recomendados. Tras actualizar los ajustes, deberá reiniciar el invitado para que las actualizaciones surtan efecto.

*Valores de tiempo de espera de GOS:*

[cols="2*"]
|===
| Tipo de SO invitado | Tiempos de espera 


| Variantes de Linux | tiempo de espera del disco = 60 


| Windows | tiempo de espera del disco = 60 


| Solaris | tiempo de espera del disco = 60 reintento ocupado = 300 reintento no preparado = 300 reintento de reinicio = 30 max.acelerador = 32 min.acelerador = 8 
|===


=== Valide el ajuste de vSphere

Utilice el siguiente comando para comprobar el `HardwareAcceleratedLocking` ajuste:

*`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`*

[listing]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: 1
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Valide la configuración de IOPS del disco

Utilice el siguiente comando para verificar la configuración de IOPS:

*`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`*

[listing]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Valide la configuración QFullSampleSize

Utilice el siguiente comando para verificar QFullSampleSize:

*`esxcli system settings  advanced list --option /Disk/QFullSampleSize`*

[listing]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: 32
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Problemas conocidos

La versión de VMware vSphere 6,5 y 6,7 con ONTAP tiene los siguientes problemas conocidos:

[cols="21%,20%,14%,27%"]
|===
| *Versión del SO* | *ID de error de NetApp* | *Título* | *Descripción* 


| ESXi 6.5 y ESXi 6.7.x | 1413424 | Las lun de RDM de WFC fallan durante la prueba | La asignación de dispositivos sin formato de clúster de conmutación al nodo de respaldo de Windows entre máquinas virtuales de Windows como Windows 2019, Windows 2016 y Windows 2012 en el host VMware ESXi falló durante las pruebas de conmutación por error del almacenamiento en todas las controladoras de clústeres en C-mode y 7-mode. 


| ESXi 6.5.x y ESXi 6.7.x | 1256473 | Se ha observado un problema de PLOGI durante la prueba de adaptadores Emulex |  
|===
.Información relacionada
* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere con ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Compatibilidad de VMware vSphere 5.x, 6.x y 7.x con MetroCluster de NetApp (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["NetApp ONTAP con SnapMirror de NetApp sincronización activa con VMware vSphere Metro Storage Cluster (VMSC)"^]

