---
sidebar: sidebar 
permalink: hu_vsphere_7.html 
keywords: host utilities, veritas, infoscale, 7.3. 7.3.1, netapp, ontap 
summary: Describe cómo utilizar Veritas Infocale 7.3 para Linux con ONTAP 
---
= Uso de VMware vSphere 7.x con ONTAP de NetApp
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Introducción

En este documento se ofrecen directrices sobre los ajustes de configuración de host DE SAN ONTAP para la versión vSphere 7.x con los protocolos FC, FCoE e iSCSI.



== Arranque SAN de hipervisores

.Lo que necesitará
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para verificar si el sistema operativo, el HBA, el firmware del HBA y la BIOS de arranque del HBA y las versiones de ONTAP son compatibles.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se haya realizado correctamente.




== Accesos múltiples

ESXi proporciona un módulo multivía extensible llamado complemento nativo multivía (NMP) que gestiona los complementos Tipo de cabina de almacenamiento (SATPS) y los complementos de selección de ruta (PSP). Estas reglas SATP están disponibles de forma predeterminada en ESXi.

En el caso del almacenamiento ONTAP de NetApp, el complemento VMW_SATP_ALUA se utiliza de forma predeterminada con VMW_PSP_RR como política de selección de rutas (PSP). Esto se puede confirmar mediante el comando siguiente.

*`esxcli storage nmp satp rule list -s VMW_SATP_ALUA`*

[listing]
----
Name           Device  Vendor    Model         Driver  Transport  Options
-------------  ------  --------  ------------  ------  ---------  --------------------------
VMW_SATP_ALUA          NETAPP                                     reset_on_attempted_reserve


Rule Group  Claim Options  Default PSP  PSP Options     Description
 ----------  -------------  -----------  --------------  -----------
system      tpgs_on        VMW_PSP_RR                   NetApp arrays with ALUA support
----


=== Configuración no ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con las mayores prioridades son activo/optimizado, lo que significa que la controladora donde se encuentra el agregado es la que presta servicio. Las rutas con las prioridades más bajas están activas, pero no optimizadas porque se ofrecen desde otra controladora. Las rutas no optimizadas solo se usan cuando no hay rutas optimizadas disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

*`esxcli storage nmp device list -d naa.600a098038313530772b4d673979372f`*

[listing]
----
naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=AO}{TPG_id=1001,TPG_state=ANO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=1: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba3:C0:T3:L21, vmhba4:C0:T2:L21
   Is USB: false
----
*`esxcli storage nmp path list -d naa.600a098038313530772b4d673979372f`*

[listing]
----
fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200b00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=29,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8e:10000090fae0ec8e-fc.201000a098dfe3d1:200700a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba3:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=25,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200800a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T2:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=26,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000090fae0ec8f:10000090fae0ec8f-fc.201000a098dfe3d1:200c00a098dfe3d1-naa.600a098038313530772b4d673979372f
   Runtime Name: vmhba4:C0:T3:L21
   Device: naa.600a098038313530772b4d673979372f
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038313530772b4d673979372f)
   Group State: active unoptimized
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=ANO,RTP_id=30,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


=== Configuraciones de cabinas All SAN

En las configuraciones de ASA, todas las rutas a un LUN determinado son activas y optimizadas. Esto mejora el rendimiento, ya que sirve operaciones de I/O en todas las rutas al mismo tiempo.

.Ejemplo
En el ejemplo siguiente se muestra la salida correcta de una LUN de ONTAP:

*`esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453`*

[listing]
----
naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1001,TPG_state=AO}{TPG_id=1000,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=2: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L9, vmhba3:C0:T1:L9, vmhba3:C0:T0:L9, vmhba4:C0:T1:L9
   Is USB: false
----
*`esxcli storage nmp device list -d naa.600a098038304759563f4e7837574453`*

[listing]
----
fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:204a00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=6,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201d00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=3,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d36:21000024ff171d36-fc.202300a098ea5e27:201b00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba3:C0:T0:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1000,TPG_state=AO,RTP_id=1,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.

fc.20000024ff171d37:21000024ff171d37-fc.202300a098ea5e27:201e00a098ea5e27-naa.600a098038304759563f4e7837574453
   Runtime Name: vmhba4:C0:T1:L9
   Device: naa.600a098038304759563f4e7837574453
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304759563f4e7837574453)
   Group State: active
   Array Priority: 0
   Storage Array Type Path Config: {TPG_id=1001,TPG_state=AO,RTP_id=4,RTP_health=UP}
   Path Selection Policy Path Config: PSP VMW_PSP_RR does not support path configuration.
----


== VVol

Virtual Volumes (vVols) es un tipo de objeto de VMware que corresponde a un disco de máquina virtual (VM), así como a sus snapshots y clones rápidos.

Las herramientas de ONTAP para VMware vSphere incluyen el proveedor VASA para ONTAP, que proporciona el punto de integración para que una instancia de VMware vCenter aproveche el almacenamiento basado en vVols. Cuando se pone en marcha el OVA de las herramientas de ONTAP, se registra automáticamente en vCenter Server y se habilita el proveedor de VASA.

Cuando se crea un almacén de datos vVols con la interfaz de usuario de vCenter, le guía para crear FlexVols como almacenamiento de backup para el almacén de datos. Los vVols de un almacén de datos vVols acceden a través de hosts ESXi mediante un extremo de protocolo (PE). En entornos SAN, se crea un LUN de 4 MB sobre cada FlexVol en el almacén de datos para su uso como PE. UNA San PE es una unidad lógica administrativa (ALU). Los vVols son unidades lógicas subsidiarias (PLUS).

Al usar vVols, se aplican los requisitos estándar y las prácticas recomendadas para los entornos SAN que incluyen (pero sin limitarse a ellos):

. Cree al menos un LIF SAN en cada nodo por SVM que desee utilizar. La práctica recomendada es crear al menos dos por nodo, pero no más del necesario.
. Elimine cualquier punto único de fallo. Utilice varias interfaces de red de VMkernel en subredes de red diferentes que utilicen la agrupación de NIC cuando se utilicen varios switches virtuales. O bien utilice varias NIC físicas conectadas a varios switches físicos para proporcionar alta disponibilidad y mayor rendimiento.
. Configurar la división en zonas y/o VLAN como sea necesario para la conectividad de host.
. Asegúrese de que todos los iniciadores necesarios hayan iniciado sesión en las LIF de destino en la SVM deseada.



NOTE: Para habilitar el proveedor VASA, debe implementar herramientas de ONTAP para VMware vSphere. El proveedor VASA gestionará toda su configuración de igroup, por lo que no es necesario crear o gestionar grupos en un entorno vVols.

NetApp no recomienda cambiar los ajustes de vVols de los predeterminados en este momento.

Consulte la https://mysupport.netapp.com/matrix/imt.jsp?components=65623;64703;&solution=1&isHWU&src=IMT["Herramienta de matriz de interoperabilidad de NetApp"^] Para conocer las versiones específicas de las herramientas de ONTAP o el proveedor VASA heredado para las versiones específicas de vSphere y ONTAP.

Para obtener información detallada sobre el aprovisionamiento y la gestión de vVols, consulte también la documentación sobre herramientas de ONTAP para VMware vSphere link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere con ONTAP"^] y.. link:https://www.netapp.com/pdf.html?item=/media/13555-tr4400pdf.pdf["TR-4400"^].



== Configuración recomendada



=== Bloqueo ATS

El bloqueo ATS es *obligatorio* para el almacenamiento compatible con VAAI y VMFS5 actualizado, y es necesario para obtener una interoperabilidad adecuada y un rendimiento de E/S óptimo del almacenamiento compartido VMFS con LUN de ONTAP. Consulte la documentación de VMware para obtener más información sobre cómo habilitar el bloqueo ATS.

[cols="4*"]
|===
| Configuración | Predeterminado | ONTAP recomendado | Descripción 


| HardwaraceleradoLocking | 1 | 1 | Ayuda a habilitar el uso de bloqueo de prueba atómica y ajuste (ATS) 


| IOPS de disco | 1000 | 1 | Límite de IOPS: Round Robin PSP establece de forma predeterminada un límite de IOPS de 1000. En este caso predeterminado, se utiliza una nueva ruta después de que se epide 1000 operaciones de E/S. 


| Disco/QFullSampleSize | 0 | 32 | El recuento de condiciones DE COLA LLENA o DE ACTIVIDAD que se tarda antes de que ESXi comience a tope. 
|===

NOTE: Habilite la configuración Space-alloc para que funcione LA FUNCIÓN UNMAP en todas las LUN asignadas a VMware vSphere. Para obtener más información, consulte la documentación de ONTAP.



=== Tiempos de espera del sistema operativo invitado

Puede configurar manualmente las máquinas virtuales con los ajustes del sistema operativo invitado recomendados. Tras actualizar los ajustes, deberá reiniciar el invitado para que las actualizaciones surtan efecto.

*Valores de tiempo de espera de GOS:*

[cols="2*"]
|===
| Tipo de SO invitado | Tiempos de espera 


| Variantes de Linux | tiempo de espera del disco = 60 


| Windows | tiempo de espera del disco = 60 


| Solaris | tiempo de espera del disco = 60 reintento ocupado = 300 reintento no preparado = 300 reintento de reinicio = 30 max.acelerador = 32 min.acelerador = 8 
|===


=== Validación del valor ajustable de vSphere

Utilice el siguiente comando para verificar la configuración de HardwareAcceleratedLocking.

*`esxcli system settings  advanced list --option /VMFS3/HardwareAcceleratedLocking`*

[listing]
----
   Path: /VMFS3/HardwareAcceleratedLocking
   Type: integer
   Int Value: 1
   Default Int Value: 1
   Min Value: 0
   Max Value: 1
   String Value:
   Default String Value:
   Valid Characters:
   Description: Enable hardware accelerated VMFS locking (requires compliant hardware). Please see http://kb.vmware.com/kb/2094604 before disabling this option.
----


=== Validación del valor de Disk IOPS

Utilice el siguiente comando para comprobar la configuración de IOPS.

*`esxcli storage nmp device list -d naa.600a098038304731783f506670553355`*

[listing]
----
naa.600a098038304731783f506670553355
   Device Display Name: NETAPP Fibre Channel Disk (naa.600a098038304731783f506670553355)
   Storage Array Type: VMW_SATP_ALUA
   Storage Array Type Device Config: {implicit_support=on; explicit_support=off; explicit_allow=on; alua_followover=on; action_OnRetryErrors=off; {TPG_id=1000,TPG_state=ANO}{TPG_id=1001,TPG_state=AO}}
   Path Selection Policy: VMW_PSP_RR
   Path Selection Policy Device Config: {policy=rr,iops=1,bytes=10485760,useANO=0; lastPathIndex=0: NumIOsPending=0,numBytesPending=0}
   Path Selection Policy Device Custom Config:
   Working Paths: vmhba4:C0:T0:L82, vmhba3:C0:T0:L82
   Is USB: false
----


=== Validando QFullSampleSize

Utilice el siguiente comando para verificar QFullSampleSize

*`esxcli system settings  advanced list --option /Disk/QFullSampleSize`*

[listing]
----
   Path: /Disk/QFullSampleSize
   Type: integer
   Int Value: 32
   Default Int Value: 0
   Min Value: 0
   Max Value: 64
   String Value:
   Default String Value:
   Valid Characters:
   Description: Default I/O samples to monitor for detecting non-transient queue full condition. Should be nonzero to enable queue depth throttling. Device specific QFull options will take precedence over this value if set.
----


== Problemas conocidos

No hay problemas conocidos.



== Enlaces relacionados

* link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597-VMware vSphere con ONTAP"^]
* link:https://kb.vmware.com/s/article/2031038["Compatibilidad de VMware vSphere 5.x, 6.x y 7.x con MetroCluster de NetApp (2031038)"^]
* link:https://kb.vmware.com/s/article/83370["ONTAP de NetApp con continuidad empresarial de SnapMirror de NetApp (SM-BC) con VMware vSphere Metro Storage Cluster (VMSC)"^]

