---
sidebar: sidebar 
permalink: hu_veritas_6x.html 
keywords: host utilities, veritas, infoscale, 6.x, netapp, ontap, san, lun, multipathing, iscsi 
summary: Proporciona orientación sobre los ajustes de configuración del host SAN de ONTAP para el lanzamiento de la serie Veritas Infoscale 6 
---
= Utilice Veritas Storage Foundation 6 para Linux con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede usar los ajustes de configuración del host de SAN de ONTAP para la versión de la serie Veritas Storage Foundation 6 para plataformas Red Hat Enterprise Linux y Oracle Linux (compatible con kernel Red Hat) con protocolos FC, FCoE e iSCSI.



== Instale las utilidades del host de Linux

Puede descargar el paquete de software de utilidades del host de Linux de NetApp como un archivo 64-bit.rpm en la link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^].

NetApp recomienda encarecidamente la instalación de las utilidades del host Linux, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Pasos
. Descargue el paquete de software de utilidades de host de Linux de 64 bits desde https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] el en el host.
. Instale el paquete de software:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_64`





== Kit de herramientas SAN

La instalación del paquete de utilidades de host de NetApp instala automáticamente el kit de herramientas. Este kit proporciona la `sanlun` utilidad, que le ayuda a gestionar los LUN y los adaptadores de bus de host (HBA). El `sanlun` comando muestra información acerca de las LUN asignadas al host, la multivía y la información necesaria para crear iGroups.

.Ejemplo
En la siguiente ilustración, el `sanlun show` Command muestra información de LUN.

[listing]
----
# sanlun show -p -v SFRAC:/vol/fen1/lun1

              ONTAP Path: SFRAC:/vol/fen1/lun1
                     LUN: 0
                LUN Size: 10g
                 Product: cDOT
                DMP NODE: sfrac0_47
      Multipath Provider: Veritas
----------  ------  ---------  ------  -------------------------------------
Veritas     host    vserver    host:
path        path    path     /dev/   chan:     vserver           major:
state       state   type     node    id:lun    LIF                   minor
----------  ------  ---------  ------  -------------------------------------
enabled     up      active/non-optimized sdea   14:0:1:0   lif_10    128:32
enabled (a) up      active/optimized     sdcj   14:0:0:0   lif_2      69:112
enabled (a) up      active/optimized     sdb    13:0:0:0   lif_1       8:16
enabled     up      active/non-optimized sdas   13:0:1:0   lif_9      66:192
----


== Arranque San

.Antes de empezar
Si decide utilizar el arranque SAN, debe ser compatible con su configuración. Puede utilizar el link:https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^]para verificar que el sistema operativo, el HBA, el firmware del HBA y la versión de arranque del BIOS y ONTAP sean compatibles.

Consulte el portal de soporte de Veritas (matriz de productos, búsqueda de plataformas, matriz de HCL) para verificar la compatibilidad de la configuración DE arranque SAN y las advertencias conocidas.

.Pasos
. Asignar el LUN de arranque SAN al host.
. Verifique que haya varias rutas disponibles.
+

NOTE: Una vez que el sistema operativo del host está activo y en ejecución en las rutas, hay varias rutas disponibles.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente.




== Accesos múltiples

Debe verificar que la configuración cumple los requisitos del sistema. Si quiere más información, consulte la https://imt.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] matriz de HCL de Veritas y.

.Ejemplo
En el siguiente ejemplo, el `vxdmpadm` comando se utiliza para verificar que VxDMP Multipath tiene la cabina de destino de ONTAP conectada.

[listing]
----
# vxdmpadm listenclosure
ENCLR_NAME   ENCLR_TYPE  ENCLR_SNO     STATUS      ARRAY_TYPE    LUN_COUNT    FIRMWARE
=====================================================================================
sfrac0       SFRAC       804Xw$PqE52h  CONNECTED   ALUA          43           9800
----
[listing]
----
# vxdmpadm getdmpnode
NAME       STATE    ENCLR-TYPE  PATHS  ENBL  DSBL ENCLR-NAME
===================================================================
sfrac0_47  ENABLED  SFRAC       4      4     0    sfrac0
----
Con Veritas Dynamic Multipathing (VxDMP), debe realizar tareas de configuración para reclamar las LUN de NetApp como dispositivos Veritas Multipath. Debe tener instalados la Biblioteca de soporte de cabinas (ASL) y los paquetes de módulo de políticas de cabinas (APM) que Veritas proporciona para los sistemas de almacenamiento de NetApp. Aunque la instalación del software Veritas carga los paquetes ASL APM predeterminados junto con el producto, se recomienda utilizar los paquetes admitidos más recientes que se enumeran en el portal de asistencia de Veritas.

.Ejemplo
En el siguiente ejemplo se muestra la biblioteca de soporte de Veritas (ASL) y la configuración del módulo de políticas de matriz (APM).

[listing]
----
# vxdmpadm list dmpnode dmpnodename=sfrac0_47 | grep asl
asl        = libvxnetapp.so
----
[listing]
----
# vxddladm listversion |grep libvxnetapp.so
libvxnetapp.so              vm-7.4-rev-1    6.1

# rpm -qa |grep VRTSaslapm
VRTSaslapm-x.x.x.0000-RHEL8.X86_64
----
[listing]
----
vxddladm listsupport libname=libvxnetapp.so
ATTR_NAME   ATTR_VALUE
=========================================
LIBNAME     libvxnetapp.so
VID         NETAPP
PID         All
ARRAY_TYPE  ALUA, A/A
----


=== Configuraciones que no son ASA

En el caso de configuraciones que no sean ASA, debe haber dos grupos de rutas con distintas prioridades. Las rutas con prioridades más altas son activas/optimizadas, lo que significa que son operadas por la controladora donde se encuentra el agregado. Las rutas con prioridades más bajas están activas pero no están optimizadas porque se ofrecen desde una controladora diferente. Las rutas no optimizadas sólo se utilizan cuando las rutas optimizadas no están disponibles.

.Ejemplo
En el siguiente ejemplo, se muestra la salida correcta de una LUN de ONTAP con dos rutas activas/optimizadas y dos rutas activas/no optimizadas.

[listing]
----
# vxdmpadm getsubpaths dmpnodename-sfrac0_47
NAME  STATE[A]   PATH-TYPE[M]   CTLR-NAME   ENCLR-TYPE  ENCLR-NAME  ATTRS  PRIORITY
===================================================================================
sdas  ENABLED     Active/Non-Optimized c13   SFRAC       sfrac0     -      -
sdb   ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdcj  ENABLED(A)  Active/Optimized     c14   SFRAC       sfrac0     -      -
sdea  ENABLED     Active/Non-Optimized c14   SFRAC       sfrac0     -      -
----

NOTE: Una única LUN no debería necesitar más de cuatro rutas. Tener más de cuatro rutas puede ocasionar problemas de ruta durante errores de almacenamiento.



=== Configuración recomendada



==== Configuración de Veritas Multipath

NetApp recomienda los siguientes ajustes de Veritas VxDMP para obtener una configuración óptima del sistema en las operaciones de conmutación por error del almacenamiento.

[cols="2*"]
|===
| Parámetro | Ajuste 


| dmp_lun_retry_timeout | 60 


| dmp_path_age | 120 


| dmp_restore_interval | 60 
|===
Los ajustes de DMP se establecen en línea mediante el `vxdmpadm` comando de la siguiente manera:

`# vxdmpadm settune dmp_tunable=value`

Los valores de estos ajustables pueden verificarse dinámicamente mediante el uso `#vxdmpadm gettune`.

.Ejemplo
En el ejemplo siguiente se muestran los elementos optimizables de VxDMP eficaces en el host SAN.

[listing]
----
# vxdmpadm gettune

Tunable                    Current Value    Default Value
dmp_cache_open                      on                on
dmp_daemon_count                    10                10
dmp_delayq_interval                 15                15
dmp_display_alua_states             on                on
dmp_fast_recovery                   on                on
dmp_health_time                     60                60
dmp_iostats_state              enabled           enabled
dmp_log_level                        1                 1
dmp_low_impact_probe                on                on
dmp_lun_retry_timeout               60                30
dmp_path_age                       120               300
dmp_pathswitch_blks_shift            9                 9
dmp_probe_idle_lun                  on                on
dmp_probe_threshold                  5                 5
dmp_restore_cycles                  10                10
dmp_restore_interval                60               300
dmp_restore_policy         check_disabled   check_disabled
dmp_restore_state              enabled           enabled
dmp_retry_count                      5                 5
dmp_scsi_timeout                    20                20
dmp_sfg_threshold                    1                 1
dmp_stat_interval                    1                 1
dmp_monitor_ownership               on                on
dmp_monitor_fabric                  on                on
dmp_native_support                 off               off
----


==== Configuración por protocolo

* Para FC/FCoE únicamente: Utilice los valores de tiempo de espera predeterminados.
* Solo para iSCSI: Configure el `replacement_timeout` valor del parámetro a 120.
+
ISCSI `replacement_timeout` Parámetro controla cuánto tiempo debe esperar la capa iSCSI a que se restablezca una ruta de tiempo de espera o una sesión antes de que falle ningún comando. Ajuste del valor de `replacement_timeout` Se recomienda utilizar el valor 120 en el archivo de configuración iSCSI.



.Ejemplo
[listing]
----
# grep replacement_timeout /etc/iscsi/iscsid.conf
node.session.timeo.replacement_timeout = 120
----


==== Configuración por plataformas de sistema operativo

Para las series Red Hat Enterprise Linux 7 y 8, debe configurar `udev rport` Valores para respaldar el entorno de Veritas Infocale en situaciones de recuperación tras fallos de almacenamiento. Cree el archivo `/etc/udev/rules.d/40-rport.rules` con el siguiente contenido del archivo:

[listing]
----
# cat /etc/udev/rules.d/40-rport.rules
KERNEL=="rport-*", SUBSYSTEM=="fc_remote_ports", ACTION=="add", RUN+=/bin/sh -c 'echo 20 > /sys/class/fc_remote_ports/%k/fast_io_fail_tmo;echo 864000 >/sys/class/fc_remote_ports/%k/dev_loss_tmo'"
----

NOTE: Para cualquier otra configuración específica de Veritas, consulte la documentación estándar sobre el producto Veritas Infoscale.



== Coexistencia de múltiples rutas

Si dispone de un entorno multivía heterogéneo que incluye Veritas Infoscale, Linux Native Device Mapper y LVM Volume Manager, consulte la documentación de Administración del producto de Veritas para conocer los ajustes de configuración.



== Problemas conocidos

No existen problemas conocidos para la versión de Veritas Storage Foundation 6 para Linux con ONTAP.
