---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: wuhu, 7.2, host utilities, SAN, windows, unified 
summary: Las utilidades del host unificadas de Windows incluyen un programa de instalación que establece los parámetros del registro de Windows y del HBA necesarios para que el host Windows controle correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series de NetApp. 
---
= Windows Unified Host Utilities 7,2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




== Acerca de utilidades de host de Windows

Las utilidades del host unificadas de Windows incluyen un programa de instalación que establece los parámetros del registro de Windows y del HBA necesarios para que el host Windows controle correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series de NetApp.

Al instalar el software de utilidades de host, el instalador establece los parámetros necesarios del Registro de Windows y HBA.

Los siguientes programas y archivos se instalan en el equipo host de Windows. El directorio predeterminado es `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programa | Específico 


| `emulexhba.reg` | Programa de solución de problemas; ejecute este programa solo si el personal de soporte técnico le indica hacerlo. 


| `\NetAppQCLI\fcconfig.exe` | Utilizado por el programa de instalación para establecer los parámetros del HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilizado por el programa de instalación para establecer los parámetros del HBA. 


| `\NetAppQCLI\*.*` | Lo utiliza el programa de instalación para configurar los parámetros de HBA FC de QLogic. 


| `san_version.exe` | Muestra la versión de las utilidades del host y de los HBA de FC. 
|===


== Configuraciones compatibles con las utilidades host

Las utilidades de host admiten diferentes configuraciones de host, protocolos y opciones multivía de Windows. Para obtener más información, consulte https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].



== Verificar la configuración del host y del sistema de almacenamiento

Antes de instalar las utilidades de host, debe comprobar que la versión de utilidades del host sea compatible con la configuración del host y del sistema de almacenamiento para que el software se instale correctamente.

.Pasos
. Compruebe la configuración compatible en la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].
. Compruebe las revisiones necesarias para el host correspondiente en el link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentación para Windows del host SAN"].
+

NOTE: link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Uso de Windows Server 2022 con ONTAP"] proporciona instrucciones sobre link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Instalación de revisiones de Windows"] Para Windows Server 2022. Consulte los documentos de Windows en la categoría de configuraciones de host para encontrar la información de revisiones relevante para versiones anteriores de Windows Server.

. Añada la licencia iSCSI, FCP o NVMe-oF e inicie el servicio de destino.
+
Los protocolos FC e iSCSI no requieren licencias en los sistemas de almacenamiento E-Series que utilizan Storage Manager de SANtricity.

. Compruebe el cableado.
+
Consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["Guía de configuración de SAN"^] Para la versión de ONTAP o el https://mysupport.netapp.com/ecm/ecm_get_file/ECMLP2773533["Guía de cableado de hardware E-Series"^] para obtener información detallada sobre el cableado y la configuración.





== Configurar switches y HBA de FC

Instale y configure uno o más adaptadores de bus de host (HBA) FC compatibles para las conexiones FC al sistema de almacenamiento.

El instalador de Windows Host Utilities establece los ajustes de FC HBA requeridos.


CAUTION: No cambie la configuración del adaptador de bus de host manualmente.

.Pasos
. Instalar uno o más HBA FC compatibles según las instrucciones proporcionadas por el proveedor de HBA.
. Obtenga los controladores HBA admitidos y las utilidades de administración e instálelos según las instrucciones proporcionadas por el proveedor de HBA.
. Conecte los HBA a sus switches FC o directamente al sistema de almacenamiento.
. Cree zonas en el switch FC según la documentación del switch FC.
. Para ONTAP, divida el switch por el WWPN. Asegúrese de utilizar el nombre de puerto WWPN de las interfaces lógicas (LIF) y no el nombre de puerto WWPN de los puertos físicos en las controladoras de almacenamiento. Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["Guía de configuración de SAN"^].




== Instale las utilidades del host

El programa de instalación instala el paquete de utilidades del host y establece el registro de Windows y los ajustes del HBA.

Debe especificar si desea incluir la compatibilidad con multivía al instalar el paquete de software de Windows Unified Host Utilities. Installer le solicita las siguientes opciones. También puede ejecutar una instalación silenciosa (desatendida) desde el símbolo del sistema de Windows.

.Compatibilidad con accesos múltiples
* Seleccione `MPIO` Si tiene más de una ruta desde el host o la máquina virtual de Windows al sistema de almacenamiento.
* Seleccione `no MPIO` únicamente si utiliza una ruta única al sistema de almacenamiento.


La selección MPIO no está disponible para los sistemas Windows XP y Windows Vista; las operaciones de I/o multivía no son compatibles con estos sistemas operativos invitados. Para los huéspedes de Hyper-V, los discos sin formato (de paso) no aparecen en el sistema operativo invitado si elige compatibilidad con accesos múltiples. Puede usar discos sin configurar o MPIO, pero no es posible usar ambos en el sistema operativo invitado.

[role="tabbed-block"]
====
.Instalar las utilidades del host de forma interactiva
--
Para instalar el paquete de software de utilidades del host de forma interactiva, debe ejecutar el programa de instalación de utilidades del host y seguir las indicaciones.

.Pasos
. Descargue el archivo ejecutable de la https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^].
. Cambie al directorio en el que descargó el archivo ejecutable.
. Ejecute el `netapp_windows_host_utilities_7.2_x64` archivar y seguir las instrucciones en pantalla.
. Reinicie el host de Windows cuando se le solicite.


--
.Instale las utilidades del host desde una línea de comandos
--
Puede realizar una instalación silenciosa (desatendida) de las utilidades del host introduciendo los comandos apropiados en el símbolo del sistema de Windows. El paquete de instalación de utilidades del host debe estar en una ruta a la que pueda acceder el host de Windows.

Siga las instrucciones para instalar las utilidades del host de forma interactiva para obtener el paquete de instalación. El sistema se reinicia automáticamente cuando finaliza la instalación.

.Pasos
. Introduzca el siguiente comando en el símbolo del sistema de Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` es el nombre de `.msi` Archivo para su arquitectura de CPU.
** MULTIPATHING especifica si está instalado la compatibilidad con MPIO. Los valores permitidos son “0” para NO y “1” para sí.
** `inst_path` es la ruta donde se instalan los archivos de utilidades host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En el símbolo del sistema de Windows. Por ejemplo, la `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` el comando muestra la información de registro.

--
====


== Actualice las utilidades del host

El nuevo paquete de instalación de utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows. Siga las instrucciones para instalar las utilidades del host de forma interactiva para actualizar el paquete de instalación.

[role="tabbed-block"]
====
.Actualice las utilidades del host de forma interactiva
--
Para actualizar el paquete de software de utilidades del host de forma interactiva, debe ejecutar el programa de instalación de utilidades del host y seguir las indicaciones.

.Pasos
. Cambie al directorio en el que descargó el archivo ejecutable.
. Ejecute el archivo ejecutable y siga las instrucciones que aparecen en pantalla.
. Reinicie el host de Windows cuando se le solicite.
. Cuando se complete el reinicio, compruebe la versión de la utilidad host:
+
.. Abra *Panel de control*.
.. Vaya a *Programa y funciones* y compruebe la versión de la utilidad del sistema principal.




--
.Actualice las utilidades del host desde una línea de comandos
--
Puede realizar una actualización silenciosa (desatendida) de las nuevas utilidades de host introduciendo los comandos apropiados en el símbolo del sistema de Windows.

El nuevo paquete de instalación de utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows. Siga las instrucciones para instalar las utilidades del host de forma interactiva para actualizar el paquete de instalación.

.Pasos
. Introduzca el siguiente comando en el símbolo del sistema de Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` es el nombre de `.msi` Archivo para su arquitectura de CPU.
** MULTIPATHING especifica si está instalado la compatibilidad con MPIO. Los valores permitidos son “0” para NO y “1” para sí.
** `inst_path` es la ruta donde se instalan los archivos de utilidades host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En el símbolo del sistema de Windows. Por ejemplo, la `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` el comando muestra la información de registro.

El sistema se reinicia automáticamente cuando finaliza la instalación.

--
====


== Reparar y eliminar utilidades de host de Windows

Puede utilizar la opción *Repair* del programa de instalación de utilidades del host para actualizar la configuración del registro de HBA y Windows. Puede eliminar las utilidades de host por completo, ya sea de forma interactiva o desde la línea de comandos de Windows.

[role="tabbed-block"]
====
.Repare o quite Windows Host Utilities de forma interactiva
--
La opción *Repair* actualiza el registro de Windows y los HBA FC con la configuración requerida. También puede quitar por completo las utilidades de host.

.Pasos
. Abra Windows *Programas y características* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 y Windows 2022).
. Seleccione *NetApp Windows Unified Host Utilities*.
. Selecciona *Cambiar*.
. Seleccione *Repair* o *Remove*, según sea necesario.
. Siga las instrucciones que aparecen en pantalla.


--
.Repare o quite Windows Host Utilities de la línea de comandos
--
La opción *Repair* actualiza el registro de Windows y los HBA FC con la configuración requerida. También puede quitar las utilidades del host por completo desde una línea de comandos de Windows.

.Pasos
. Introduzca el siguiente comando en la línea de comandos de Windows para reparar Windows Host Utilities:
+
`msiexec /f installer.msi [/quiet]`

+
** `/f` repara la instalación.
** `installer.msi` Es el nombre del programa de instalación de Windows Host Utilities del sistema.
** `/quiet` suprime todos los comentarios y reinicia el sistema automáticamente sin preguntar cuando finaliza el comando.




--
====


== Información general de la configuración que utilizan las utilidades de host

Las utilidades de host requieren determinada configuración del registro y de los parámetros para verificar que el host Windows controle correctamente el comportamiento del sistema de almacenamiento.

Las utilidades de host de Windows configuran los parámetros que afectan a la forma en que el host de Windows responde a una demora o pérdida de datos. Se han seleccionado valores particulares para verificar que el host Windows maneja correctamente eventos como la conmutación por error de una controladora del sistema de almacenamiento a su controladora asociada.

No todos los valores se aplican al administrador de almacenamiento de DSM para SANtricity; sin embargo, cualquier superposición de valores definidos por las utilidades de host y los definidos por el administrador de almacenamiento de DSM para SANtricity no genera conflictos.

Los HBA FC, NVMe/FC e iSCSI también tienen parámetros que deben configurarse para garantizar el mejor rendimiento y para gestionar correctamente los eventos del sistema de almacenamiento.

El programa de instalación suministrado con Windows Unified Host Utilities establece los parámetros de Windows, FC y NVMe/FC HBA en los valores admitidos.

Debe establecer manualmente los parámetros de HBA de iSCSI.

El instalador establece diferentes valores según si especifica compatibilidad de I/O multivía (MPIO) al ejecutar el programa de instalación.

No debe cambiar estos valores a menos que el soporte técnico le indique que lo haga.



== Valores del Registro definidos por Windows Unified Host Utilities

El instalador de Windows Unified Host Utilities establece automáticamente valores de Registro que se basan en las opciones que realice durante la instalación. Debe tener en cuenta estos valores de registro y la versión del sistema operativo.

El instalador de Windows Unified Host Utilities establece los siguientes valores. Todos los valores son decimales a menos que se indique lo contrario.


NOTE: HKLM es la abreviatura de `HKEY_LOCAL_MACHINE`.

[cols="20,20,30"]
|===
| Clave de registro | Valor | Cuando se haya configurado 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters \DsmMaximumRetryTimeDuringStateTransitition | 120 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, Windows Server 2016 y Windows 2019, o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet \Services\msdsm\Parameters \DsmMaximumStateTransitionTime | 120 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, o Windows Server 2016, Windows 2019 o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters\DsmSupportedDeviceList | «NETAPP LUN», «NETAPP LUN C- Mode», «NVMe NetApp ONTAO Con» | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {ISCSI_DRIVER_GUID}\ instance_ID \Parameters \IPSecConfigTimeout | 60 | Siempre 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {ISCSI_DRIVER_GUID}\ INSTANCE_ID \Parámetros \LinkDownTime | 10 | Siempre 


| HKLM\SYSTEM\CurrentControlSet\Services \ClusDisk \Parameters\ManageDisksOnSystemBuses | 1 | Siempre 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {ISCSI_DRIVER_GUID}\ Instance_ID \Parameters \MaxRequestHoldTime | 120 | Cuando no se selecciona ninguna compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\ {ISCSI_DRIVER_GUID}\ Instance_ID \Parameters \MaxRequestHoldTime | 30 | Siempre 


| HKLM\SYSTEM\CurrentControlSet\Control \MPDEV\MPIOSupportedDeviceList | «NETAPP LUN», «NETAPP LUN C- Mode», «NVMe NetApp ONTAO Con» | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PathRecoveryInterval | 30 | Cuando el servidor es Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PathVerifyEnabled | 1 | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters\PathVerifyEnabled | 1 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services \vnetapp\Parameters\PathVerifyEnabled | 0 | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services \mpio\Parameters\PDORemovePeriod | 130 | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\PDORemovePeriod | 130 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, Windows Server 2016 , Windows Server 2019 o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetapp \Parameters\PDORemovePeriod | 130 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\RetryCount | 6 | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\RetryCount | 6 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\RetryInterval | 1 | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\RetryInterval | 1 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 o Windows Server 2022 


| HKLM\SYSTEM\CurrentControlSet\Services\vNetApp \Parameters\RetryInterval | 1 | Cuando se especifica la compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services \disk\TimeOutValue | 120 | Cuando no se selecciona ninguna compatibilidad con MPIO 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\UseCustomPathRecoveryInterval | 1 | Si se especifica la compatibilidad con MPIO y el servidor es Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 o Windows Server 2022 
|===
.Información relacionada
Consulte los documentos de Microsoft para obtener los detalles de los parámetros del Registro.



== Parámetros de NVMe

Los siguientes parámetros del controlador NVMe Emulex se actualizan al instalar WUHU 7,2:

* EnableNVMe = 1
* NVMEMode = 0
* LimTransferSize=1




== Valores de FC HBA establecidos por Windows Host Utilities

En sistemas que utilizan FC, el instalador de utilidades host establece los valores de tiempo de espera necesarios para los HBA de Emulex y QLogic FC.

Para los HBA FC de Emulex, el instalador establece los siguientes parámetros:

[role="tabbed-block"]
====
.Cuando se selecciona MPIO
--
|===
| Tipo de propiedad | Valor de propiedad 


| LinkTimeOut | 1 


| NodeTimeOut | 10 
|===
--
.Cuando no se selecciona MPIO
--
|===
| Tipo de propiedad | Valor de propiedad 


| LinkTimeOut | 30 


| NodeTimeOut | 120 
|===
--
====
Para los HBA de QLogic FC, el instalador establece los siguientes parámetros:

[role="tabbed-block"]
====
.Cuando se selecciona MPIO
--
|===
| Tipo de propiedad | Valor de propiedad 


| LinkDownTimeOut | 1 


| PortDownRetryCount | 10 
|===
--
.Cuando no se selecciona MPIO
--
|===
| Tipo de propiedad | Valor de propiedad 


| LinkDownTimeOut | 30 


| PortDownRetryCount | 120 
|===
--
====

NOTE: Los nombres de los parámetros pueden variar ligeramente según el programa. Por ejemplo, en el programa QConverteConsole de QLogic, el parámetro se muestra como `Link Down Timeout`. Las utilidades del host `fcconfig.ini` file muestra este parámetro como cualquiera de los dos `LinkDownTimeOut` o. `MpioLinkDownTimeOut`, Dependiendo de si se especifica MPIO. Sin embargo, todos estos nombres hacen referencia al mismo parámetro HBA.

.Información relacionada
Consulte el sitio de Emulex o QLogic para obtener más información acerca de los parámetros de tiempo de espera.



== Resolución de problemas

Es posible utilizar las técnicas generales de solución de problemas para utilidades de host de Windows. No olvide consultar las notas de la versión más recientes para ver los problemas conocidos y las soluciones.



=== Diferentes áreas para identificar los posibles problemas de interoperabilidad

* Para identificar posibles problemas de interoperabilidad, debe confirmar que las utilidades de host admiten la combinación de software del sistema operativo host, hardware de host, software ONTAP y hardware del sistema de almacenamiento.
* Debe comprobar el http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].
* Debe verificar que dispone de la configuración de iSCSI correcta.
* Si los LUN iSCSI no están disponibles después de un reinicio, debe verificar que el destino se muestra como persistente en la pestaña *Destinos persistentes* de la GUI del iniciador iSCSI de Microsoft.
* Si las aplicaciones que utilizan las LUN muestran errores al iniciar, debe comprobar que las aplicaciones están configuradas para que dependan del servicio iSCSI.
* Para las rutas de FC a controladoras de almacenamiento que ejecutan ONTAP, debe comprobar que los switches de FC están divididos mediante los WWPN de las LIF de destino, no los WWPN de los puertos físicos del nodo.
* Debe revisar el link:hu_wuhu_71_rn.html["Notas de la versión"] Para las utilidades de host de Windows que compruebe los problemas conocidos. Las notas de la versión incluyen una lista de problemas conocidos y limitaciones.
* Debe revisar la información de solución de problemas en la Guía de administración de SAN para la versión de ONTAP.
* Debe buscar https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] para problemas descubiertos recientemente.
+
** En el campo Tipo de error en Búsqueda avanzada, debe seleccionar *iSCSI - Windows* y luego seleccionar *Ir*. Debe repetir la búsqueda de Bug Type *FCP -Windows*.


* Debe recopilar información sobre el sistema.
* Registre los mensajes de error que se muestran en el host o la consola del sistema de almacenamiento.
* Recoja los archivos de registro del host y del sistema de almacenamiento.
* Registre los síntomas del problema y todos los cambios realizados en el host o el sistema de almacenamiento justo antes de que se apareciera el problema.
* Si no puede resolver el problema, póngase en contacto con el soporte técnico de NetApp para obtener ayuda.




=== Comprender los cambios de utilidades del host en la configuración del controlador HBA FC

Durante la instalación de los controladores Emulex o QLogic HBA necesarios en un sistema FC se comprueban varios parámetros y, en algunos casos, se modifican.

Las utilidades del host establecen valores para los siguientes parámetros:

* LinkTimeOut: Define la cantidad de tiempo en segundos que el puerto de host espera antes de reanudar las operaciones de E/S después de que un enlace físico cae.
* NodeTimeOut: Define el tiempo en segundos antes de que el puerto de host reconozca que una conexión con el dispositivo de destino está inactiva.


Al solucionar problemas de HBA, verifique que estos ajustes tengan los valores correctos. Los valores correctos dependen de dos factores:

* El proveedor de HBA
* Si utiliza MPIO


Puede corregir la configuración del HBA ejecutando la opción *Repair* del instalador de Windows Host Utilities.

[role="tabbed-block"]
====
.Comprobar la configuración del controlador de HBA Emulex en sistemas FC
--
Si tiene un sistema FC, debe comprobar la configuración del controlador de HBA Emulex. Estos ajustes deben existir para cada puerto en el HBA.

.Pasos
. Abra el Administrador de OnCommand.
. Seleccione el HBA adecuado de la lista y seleccione la pestaña *Parámetros del controlador*.
+
Aparecen los parámetros del conductor.

. Si utiliza el software MPIO, compruebe que tiene los siguientes ajustes de controlador:
+
** LinkTimeOut - 1
** NodeTimeOut - 10


. Si no utiliza el software MPIO, compruebe que tiene los siguientes ajustes de controlador:
+
** LinkTimeOut - 30
** NodeTimeOut - 120




--
.Comprobar la configuración del controlador HBA QLogic en sistemas FC
--
En los sistemas FC, es necesario comprobar la configuración del controlador de HBA de QLogic. Estos ajustes deben existir para cada puerto en el HBA.

.Pasos
. Abra QConvergeConsole y luego seleccione *Connect* en la barra de herramientas.
+
Aparece el cuadro de diálogo * Conectarse al host *.

. Seleccione el host apropiado de la lista y, a continuación, seleccione *Connect*.
+
Aparecerá una lista de los HBA en el panel HBA de FC.

. Seleccione el puerto HBA adecuado de la lista y, a continuación, seleccione la pestaña *Configuración*.
. Seleccione *Configuración avanzada del puerto HBA* en la sección *Seleccionar configuración*.
. Si utiliza el software MPIO, compruebe que tiene los siguientes ajustes de controlador:
+
** Tiempo de espera de enlace abajo (linkdwnto) - 1
** Número de reintentos de bajada de puerto (portdwnrc) - 10


. Si no utiliza el software MPIO, compruebe que tiene los siguientes ajustes de controlador:
+
** Tiempo de espera de enlace abajo (linkdwnto) - 30
** Número de reintentos de bajada de puerto (portdwnrc) - 120




--
====