---
sidebar: sidebar 
permalink: hu_wuhu_repair_remove.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilities incluye un programa de instalación que establece los parámetros de registro de Windows y HBA necesarios para que el host Windows controle correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series. 
---
= Reparar y eliminar las utilidades de host de Windows para el almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice la opción *Reparar* en el programa de instalación de Host Utilities para actualizar el adaptador de bus de host (HBA) y la configuración del registro de Windows.  También puede eliminar las Utilidades de Host por completo, ya sea de forma interactiva o desde la línea de comandos de Windows.

[role="tabbed-block"]
====
.Repare o elimine de forma interactiva
--
La opción *Repair* actualiza el registro de Windows y los HBA FC con la configuración requerida. También puede quitar completamente las utilidades de host.

.Pasos
. Abra Windows *Programas y características* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019 y Windows 2022).
. Seleccione * Utilidades del host de Windows de NetApp*.
. Selecciona *Cambiar*.
. Seleccione *Repair* o *Remove*, según sea necesario.
. Siga las instrucciones que aparecen en pantalla.


--
.Reparar o eliminar de forma no interactiva
--
La opción *Repair* actualiza el registro de Windows y los HBA FC con la configuración requerida. También puede quitar todas las utilidades de host de una línea de comandos de Windows.

.Pasos
. Reparar utilidades del host de Windows:
+
[source, cli]
----
msiexec /f installer.msi [/quiet]
----
+
** `/f` repara la instalación.
** `installer.msi` Es el nombre del programa de instalación de Windows Host Utilities del sistema.
** `/quiet` suprime todos los comentarios y reinicia el sistema automáticamente sin preguntar cuando finaliza el comando.




--
====