---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilities incluye un programa de instalación que establece los parámetros de registro de Windows y HBA necesarios para que el host Windows controle correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series. 
---
= Actualizar las utilidades de host de Windows para el almacenamiento ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Puede actualizar el software Windows Host Utilities en su configuración de almacenamiento de ONTAP siguiendo las instrucciones de instalación de forma interactiva o utilizando la línea de comandos de Windows.  Debe instalar el nuevo software de instalación de Windows Host Utilities en una ruta que sea accesible para el host de Windows.

[role="tabbed-block"]
====
.Actualice de forma interactiva
--
Actualice el software Windows Host Utilities de forma interactiva ejecutando el programa de instalación Host Utilities y siguiendo las instrucciones.

.Pasos
. Cambie al directorio en el que descargó el archivo ejecutable.
. Ejecute el archivo ejecutable y siga las instrucciones que aparecen en pantalla.
. Reinicie el host de Windows cuando se le solicite.
. Cuando se complete el reinicio, compruebe la versión de la utilidad host:
+
.. Abra *Panel de control*.
.. Vaya a *Programa y funciones* y compruebe la versión de la utilidad del sistema principal.




--
.Actualizar de forma no interactiva
--
Realice una actualización del software de utilidades de host de Windows no interactiva mediante la línea de comandos de Windows.

.Pasos
. Introduzca el siguiente comando en el símbolo del sistema de Windows:
+
[source, cli]
----
msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]
----
+
** `installer` es el nombre de `.msi` Archivo para su arquitectura de CPU.
** MULTIPATH especifica si está instalada la compatibilidad con Microsoft Multipath I/O (MPIO). Los valores permitidos son “0” para NO y “1” para sí.
** `inst_path` Es la ruta en la que se instalan los archivos de utilidades de host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En el símbolo del sistema de Windows. Por ejemplo, la `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` el comando muestra la información de registro.

El sistema se reinicia automáticamente cuando finaliza la instalación.

--
====