---
sidebar: sidebar 
permalink: hu_wuhu_71.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Las utilidades unificadas de host de Windows incluyen un programa de instalación que establece el registro de Windows y los parámetros de HBA necesarios para que el host de Windows gestione correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series de NetApp. 
---
= Utilidades unificadas de host de Windows 7.1
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content




== Qué es Windows Host Utilities

Windows Unified Host Utilities incluye un programa de instalación que establece los parámetros necesarios para el registro y el adaptador de bus de host (HBA) de Windows de modo que el host de Windows gestione correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series de NetApp.

Al instalar el software de Host Utilities, el instalador establece los parámetros necesarios del registro de Windows y del adaptador de bus de host (HBA).

Los siguientes programas y archivos se instalan en el equipo host de Windows. El directorio predeterminado es `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programa | Específico 


| `emulexhba.reg` | Programa de solución de problemas; ejecute este programa solo si el personal de soporte técnico le indica hacerlo. 


| `\NetAppQCLI\fcconfig.exe` | Utilizado por el programa de instalación para ajustar los parámetros del HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilizado por el programa de instalación para ajustar los parámetros del HBA. 


| `\NetAppQCLI\*.*` | Lo utiliza el programa de instalación para establecer los parámetros del HBA Fibre Channel de QLogic. 


| `san_version.exe` | Muestra la versión de los HBA de Host Utilities y Fibre Channel. 
|===


== Configuraciones compatibles con Host Utilities

Las utilidades del host admiten distintas configuraciones de host de Windows, protocolos y opciones de múltiples rutas. Para obtener más información, consulte https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].



== Verificar la configuración del host y del sistema de almacenamiento

Antes de instalar las utilidades de host, debe comprobar que la versión de utilidades de host admite la configuración del sistema de almacenamiento y host para que el software se instale correctamente.

.Pasos
. Compruebe la configuración compatible en la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^].
. Compruebe las revisiones necesarias para el host correspondiente del link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentación para Windows del host SAN"].
+

NOTE: link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Uso de Windows Server 2022 con ONTAP"] proporciona instrucciones sobre link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Instalación de revisiones de Windows"] Para Windows Server 2022. Consulte los documentos de Windows de la categoría configuraciones de host para encontrar la información de revisión correspondiente para versiones anteriores de Windows Server.

. Añada la licencia iSCSI o FCP e inicie el servicio de destino.
+
Los protocolos Fibre Channel e iSCSI no requieren licencias en los sistemas de almacenamiento E-Series mediante el Administrador de almacenamiento de SANtricity.

. Compruebe el cableado
+
Consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["Guía de configuración de SAN"^] Para su versión de ONTAP o. https://mysupport.netapp.com/ecm/ecm_get_file/ECMLP2773533["Guía de cableado de hardware E-Series"^] para obtener información detallada sobre el cableado y la configuración.





== Configurar switches y HBA de FC

Instalar y configurar uno o varios adaptadores de bus de host (HBA) Fibre Channel compatibles para las conexiones Fibre Channel al sistema de almacenamiento.

El instalador de Windows Host Utilities establece los ajustes de HBA de Fibre Channel necesarios.


NOTE: No cambie manualmente la configuración de HBA.

.Pasos
. Instalar uno o varios adaptadores de bus de host (HBA) Fibre Channel admitidos según las instrucciones del proveedor de HBA.
. Obtenga los controladores HBA admitidos y las utilidades de administración e instálelos según las instrucciones proporcionadas por el proveedor de HBA.
. Conecte los HBA a los switches de Fibre Channel o directamente al sistema de almacenamiento.
. Cree zonas en el switch Fibre Channel de acuerdo con la documentación del switch Fibre Channel.
. Para ONTAP, dividir el switch de acuerdo con WWPN. Asegúrese de utilizar el WWPN de las LIF y no de los puertos físicos en las controladoras de almacenamiento. Para obtener más información, consulte https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanconf/home.html?cp=14_7["Guía de configuración de SAN"^].




== Instale las utilidades de host

El programa de instalación instala el paquete de utilidades de host y establece el registro de Windows y la configuración de HBA.

Debe especificar si desea incluir la compatibilidad con multivía al instalar el paquete de software de Windows Unified Host Utilities. El instalador le solicita la siguiente opción. También puede ejecutar una instalación silenciosa (desatendida) desde el símbolo del sistema de Windows.

.Compatibilidad con accesos múltiples
* Elija MPIO si tiene más de una ruta desde el host de Windows o la máquina virtual hasta el sistema de almacenamiento.
* Elija no MPIO solo si utiliza una única ruta para el sistema de almacenamiento.
* La selección MPIO no está disponible para los sistemas Windows XP y Windows Vista; las operaciones de I/o multivía no son compatibles con estos sistemas operativos invitados.
* Para los huéspedes de Hyper-V, los discos sin formato (de paso) no aparecen en el sistema operativo invitado si elige compatibilidad con accesos múltiples. Puede usar discos sin configurar o MPIO, pero no es posible usar ambos en el sistema operativo invitado.




=== Instale las utilidades de host de forma interactiva

Para instalar el paquete de software de Host Utilities de forma interactiva, debe ejecutar el programa de instalación de Host Utilities y seguir las instrucciones.

.Pasos
. Descargue el archivo ejecutable desde https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^].
. Cambie al directorio desde el que descargó el archivo ejecutable.
. Ejecute el `netapp_windows_host_utilities_7.1_x64` archivar y seguir las instrucciones en pantalla.
. Reinicie el host de Windows cuando se le solicite.




=== Instale las utilidades del host desde una línea de comandos

* Puede realizar una instalación silenciosa (desatendida) de las utilidades de host introduciendo los comandos apropiados en el símbolo del sistema de Windows.
* El paquete de instalación de utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows.
* Siga las instrucciones para instalar las utilidades de host de forma interactiva para obtener el paquete de instalación.
* El sistema se reinicia automáticamente cuando finaliza la instalación.


.Pasos
. Introduzca el siguiente comando en un símbolo del sistema de Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** donde instalador es el nombre de `.msi` Archivo para su arquitectura de CPU;
** MULTIPATHING especifica si está instalado la compatibilidad con MPIO. Los valores permitidos son 0 para no, 1 para yes
** `inst_path` Es la ruta en la que se instalan los archivos de utilidades de host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En un símbolo del sistema de Windows. Por ejemplo:
`msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1`



== Actualice las utilidades de host

El nuevo paquete de instalación de utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows. Siga las instrucciones para instalar las utilidades de host de forma interactiva para obtener el paquete de instalación.



=== Actualice las utilidades de host de forma interactiva

Para instalar el paquete de software de Host Utilities de forma interactiva, debe ejecutar el programa de instalación de Host Utilities y seguir las instrucciones.

.Pasos
. Cambie al directorio desde el que descargó el archivo ejecutable.
. Ejecute el archivo ejecutable y siga las instrucciones que aparecen en pantalla.
. Reinicie el host de Windows cuando se le solicite.
. Compruebe la versión de la utilidad de host después del reinicio:
+
.. Abra *Panel de control*.
.. Vaya a *Programa y funciones* y compruebe la versión de la utilidad del sistema principal.






=== Actualice las utilidades del host desde la línea de comandos

Puede realizar una instalación silenciosa (desatendida) de las nuevas utilidades de host introduciendo los comandos apropiados en el símbolo del sistema de Windows. El paquete de instalación de nuevas utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows. Siga las instrucciones para instalar las utilidades de host de forma interactiva para obtener el paquete de instalación.

.Pasos
. Introduzca el siguiente comando en un símbolo del sistema de Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** donde `installer` es el nombre de `.msi` Archivo para su arquitectura de CPU.
** MULTIPATHING especifica si está instalado la compatibilidad con MPIO. Los valores permitidos son 0 para no, 1 para yes
** `inst_path` Es la ruta en la que se instalan los archivos de utilidades de host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En un símbolo del sistema de Windows. Por ejemplo:
`msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1`

El sistema se reinicia automáticamente cuando finaliza la instalación.



== Reparar y quitar las utilidades de host de Windows

Puede utilizar la opción Repair del programa de instalación de Host Utilities para actualizar la configuración del Registro de Windows y HBA. Puede quitar completamente las utilidades de host, de forma interactiva o desde la línea de comandos de Windows.



=== Repare o quite Windows Host Utilities de forma interactiva

La opción Repair actualiza el registro de Windows y los HBA Fibre Channel con la configuración necesaria. También puede quitar completamente las utilidades de host.

.Pasos
. Abra Windows *programas y características* (Windows Server 2012 R2, Windows Server 2016, Windows Server 2019).
. Seleccione *NetApp Windows Unified Host Utilities*.
. Haga clic en *Cambiar*.
. Haga clic en *reparar* o en *Quitar*, según sea necesario.
. Siga las instrucciones que aparecen en pantalla.




=== Repare o quite Windows Host Utilities de la línea de comandos

La opción Repair actualiza el registro de Windows y los HBA Fibre Channel con la configuración necesaria. También puede quitar todas las utilidades de host de una línea de comandos de Windows.

.Pasos
. Introduzca el siguiente comando en la línea de comandos de Windows para reparar Windows Host Utilities:
+
`msiexec {/uninstall | /f]installer.msi [/quiet]`

+
** `/uninstall` Elimina completamente las utilidades de host.
** `/f` repara la instalación.
** `installer.msi` Es el nombre del programa de instalación de Windows Host Utilities del sistema.
** `/quiet` suprime todos los comentarios y reinicia el sistema automáticamente sin preguntar cuando finaliza el comando.






== Información general de la configuración que utilizan las utilidades de host

Las utilidades de host deben contar con cierta configuración de registro y parámetros para garantizar que el host de Windows gestione correctamente el comportamiento del sistema de almacenamiento.

Windows Host Utilities establece los parámetros que afectan a la forma en que el host de Windows responde a una demora o a una pérdida de datos. Se han seleccionado valores particulares para garantizar que el host Windows gestiona correctamente eventos como la conmutación por error de una controladora del sistema de almacenamiento a su otra controladora asociada.

No todos los valores se aplican al DSM para el Administrador de almacenamiento de SANtricity; sin embargo, la superposición de valores establecidos por las utilidades de host y los establecidos por DSM para el Administrador de almacenamiento de SANtricity no provoca conflictos. Los adaptadores de bus de host (HBA) Fibre Channel e iSCSI también tienen parámetros que se deben configurar para garantizar el mejor rendimiento y para tratar correctamente los eventos del sistema de almacenamiento.

El programa de instalación que se suministra con Windows Unified Host Utilities establece los parámetros de HBA de Windows y Fibre Channel a los valores admitidos.


NOTE: Debe configurar manualmente los parámetros de iSCSI HBA.

El instalador establece valores diferentes según si especifica la compatibilidad con I/o multivía (MPIO) al ejecutar el programa de instalación,

No debe cambiar estos valores a menos que el soporte técnico le indique que lo haga.



== Valores del Registro definidos por Windows Unified Host Utilities

El instalador de Windows Unified Host Utilities establece automáticamente los valores del Registro que se basan en las opciones que se toman durante la instalación. Debe conocer estos valores del Registro, la versión del sistema operativo. El instalador de Windows Unified Host Utilities establece los siguientes valores. Todos los valores son decimales a menos que se indique lo contrario. HKLM es la abreviatura de HKEY_LOCAL_MACHINE.

[cols="~, 10, ~"]
|===
| Clave de registro | Valor | Cuando se haya configurado 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters \DsmMaximumRetryTimeDuringStateTransitition | 120 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters \DsmMaximumStateTransitionTime | 120 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016, excepto si se detecta DSM de Data ONTAP 


.2+| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\DsmSupportedDeviceList | "NETAPP" | Cuando se especifica la compatibilidad con MPIO 


| "LUN DE NETAPP", "LUN C-MODE DE NETAPP" | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Control\Class \{iSCSI_driver_GUID}\ Instance_ID\Parameters \IPSecConfigTimeout | 60 | Siempre, excepto cuando se detecte DSM Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Control \Class\{iSCSI_driver_GUID} \ Instance_ID\Parameters\LinkDownTime | 10 | Siempre 


| HKLM\SYSTEM\CurrentControlSet\Services\ClusDisk \Parameters\ManageDisksOnSystemBuses | 1 | Siempre, excepto cuando se detecte DSM Data ONTAP 


.2+| HKLM\SYSTEM\CurrentControlSet\Control \Class\{iSCSI_driver_GUID} \ Instance_ID\Parameters\MaxRequestHoldTime | 120 | Cuando no se selecciona ninguna compatibilidad con MPIO 


| 30 | Siempre, excepto cuando se detecte DSM Data ONTAP 


.2+| HKLM\SYSTEM\CurrentControlSet \Control\MPDEV\MPIOSupportedDeviceList | "LUN DE NETAPP" | Cuando se especifica la compatibilidad con MPIO 


| "LUN DE NETAPP", "LUN C-MODE DE NETAPP" | Cuando se especifica que MPIO es compatible, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PathRecoveryInterval | 40 | Cuando el servidor es únicamente Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PathVerifyEnabled | 0 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\PathVerifyEnabled | 0 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters\PathVerifyEnabled | 0 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \msiscdsm\Parameters\PathVerifyEnabled | 0 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2003, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\vnetapp \Parameters\PathVerifyEnabled | 0 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\PDORemovePeriod | 130 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\PDORemovePeriod | 130 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\msiscdsm \Parameters\PDORemovePeriod | 130 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2003, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \vnetapp \Parameters\PDORemovePeriod | 130 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \mpio\Parameters\RetryCount | 6 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\msdsm \Parameters\RetryCount | 6 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \msiscdsm\Parameters\RetryCount | 6 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2003, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \vnetapp\Parameters\RetryCount | 6 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \mpio\Parameters\RetryInterval | 1 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \msdsm\Parameters\RetryInterval | 1 | Cuando se especifica la compatibilidad con MPIO y el servidor es Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services \vnetapp\Parameters\RetryInterval | 1 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


.2+| HKLM\SYSTEM\CurrentControlSet \Services\Disk\TimeOutValue | 120 | Cuando no se selecciona ninguna compatibilidad con MPIO, excepto si se detecta el DSM de Data ONTAP 


| 60 | Cuando se especifica la compatibilidad con MPIO, excepto si se detecta DSM de Data ONTAP 


| HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\UseCustomPathRecoveryInterval | 1 | Cuando el servidor es únicamente Windows Server 2008, Windows Server 2008 R2, Windows Server 2012, Windows Server 2012 R2 o Windows Server 2016 
|===
.Información relacionada
Consulte la https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/windows-registry-advanced-users["Documentos de Microsoft"^] para obtener los detalles de los parámetros del registro.



== Valores de FC HBA establecidos por Windows Host Utilities

En sistemas que utilizan Fibre Channel, el instalador de utilidades de host establece los valores de tiempo de espera necesarios para los HBA FC de Emulex y QLogic. Para los HBA Fibre Channel de Emulex, el instalador establece los siguientes parámetros cuando se selecciona MPIO:

|===
| Tipo de propiedad | Valor de propiedad 


| LinkTimeOut | 1 


| NodeTimeOut | 10 
|===
Para los HBA Fibre Channel de Emulex, el instalador establece los siguientes parámetros cuando no se selecciona MPIO:

|===
| Tipo de propiedad | Valor de propiedad 


| LinkTimeOut | 30 


| NodeTimeOut | 120 
|===
Para los HBA Fibre Channel de QLogic, el instalador establece los siguientes parámetros cuando se selecciona MPIO:

|===
| Tipo de propiedad | Valor de propiedad 


| LinkDownTimeOut | 1 


| PortDownRetryCount | 10 
|===
Para los HBA Fibre Channel de QLogic, el instalador establece los siguientes parámetros cuando no se selecciona MPIO:

|===
| Tipo de propiedad | Valor de propiedad 


| LinkDownTimeOut | 30 


| PortDownRetryCount | 120 
|===

NOTE: Los nombres de los parámetros pueden variar ligeramente según el programa. Por ejemplo, en el programa QConverteConsole de QLogic, el parámetro se muestra como `Link Down Timeout`. Las utilidades del host `fcconfig.ini` file muestra este parámetro como cualquiera de los dos `LinkDownTimeOut` o. `MpioLinkDownTimeOut`, Dependiendo de si se especifica MPIO. Sin embargo, todos estos nombres hacen referencia al mismo parámetro HBA.

.Información relacionada
Consulte https://www.broadcom.com/support/download-search["Emulex"^] o. https://driverdownloads.qlogic.com/QLogicDriverDownloads_UI/Netapp_search.aspx["QLogic"^] sitio para obtener más información acerca de los parámetros de tiempo de espera.



== Resolución de problemas

En esta sección se describen técnicas generales de solución de problemas para las utilidades de host de Windows. Asegúrese de consultar las notas de la versión más reciente para conocer problemas y soluciones conocidos.

.Diferentes áreas para identificar los posibles problemas de interoperabilidad
* Para identificar los posibles problemas de interoperabilidad, debe confirmar que las utilidades de host admiten su combinación de software de sistema operativo del host, hardware de host, software ONTAP y hardware de sistema de almacenamiento.
* Debe comprobar la matriz de interoperabilidad.
* Debe verificar que dispone de la configuración de iSCSI correcta.
* Si los LUN de iSCSI no están disponibles después de un reinicio, debe verificar que el destino aparece como persistente en la pestaña persistent Targets de la interfaz gráfica de usuario del iniciador de iSCSI de Microsoft.
* Si las aplicaciones que utilizan las LUN muestran errores al iniciar, debe comprobar que las aplicaciones están configuradas para que dependan del servicio iSCSI.
* Para las rutas Fibre Channel a las controladoras de almacenamiento que ejecutan ONTAP, debe comprobar que los switches FC se dividen mediante los WWPN de los LIF objetivo, no los WWPN de los puertos físicos del nodo.
* Debe revisar el link:https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71_rn.html["Notas de la versión de Windows Host Utilities"] para comprobar si hay problemas conocidos. Las notas de la versión incluyen una lista de problemas y limitaciones conocidos.
* Debe revisar la información para la solución de problemas en el https://docs.netapp.com/ontap-9/index.jsp["Guía de administración de SAN"^] Para su versión de ONTAP.
* Debe buscar https://mysupport.netapp.com/site/bugs-online/["Errores en línea"^] para problemas recientemente descubiertos.
* En el campo Bug Types en Advanced Search, debe seleccionar ISCSI - Windows y, a continuación, hacer clic en Go. Repita la búsqueda para Bug Type FCP -Windows.
* Debe recopilar información sobre el sistema.
* Registre los mensajes de error que se muestran en el host o la consola del sistema de almacenamiento.
* Recoja los archivos de registro del host y del sistema de almacenamiento.
* Registre los síntomas del problema y todos los cambios realizados en el host o el sistema de almacenamiento justo antes de que se apareciera el problema.
* Si no puede resolver el problema, puede ponerse en contacto con el soporte técnico de NetApp.


.Información relacionada
http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
https://mysupport.netapp.com/portal/documentation["Documentación de NetApp"^]
https://mysupport.netapp.com/NOW/cgi-bin/bol["NetApp Bugs Online"^]



=== Comprenda los cambios de las utilidades del host en la configuración del controlador de HBA de FC

Durante la instalación de los controladores HBA Emulex o QLogic necesarios en un sistema FC, se comprueban varios parámetros y, en algunos casos, se modifican.

Si se detecta MS DSM para Windows MPIO, las utilidades de host establecen valores para los siguientes parámetros:

* LinkTimeOut: Define el período de tiempo en segundos que el puerto de host espera antes de reanudar las operaciones de I/o después de que un enlace físico está inactivo.
* NodeTimeOut: Define el tiempo en segundos antes de que el puerto de host reconozca que una conexión al dispositivo de destino está inactiva.


Al solucionar problemas de HBA, compruebe que estos valores tengan los valores correctos. Los valores correctos dependen de dos factores:

* El proveedor de HBA
* Si utiliza software de accesos múltiples (MPIO)


Puede corregir la configuración de HBA ejecutando la opción Repair del instalador de utilidades de host de Windows.



==== Comprobar la configuración del controlador de HBA Emulex en sistemas FC

Si tiene un sistema Fibre Channel, debe comprobar los ajustes del controlador HBA Emulex. Estos ajustes deben existir para cada puerto en el HBA.

.Pasos
. Abra el Administrador de OnCommand.
. Seleccione el HBA adecuado de la lista y haga clic en la ficha *parámetros del controlador*.
+
Aparecen los parámetros del conductor.

. Si utiliza el software MPIO, asegúrese de tener las siguientes configuraciones del controlador:
+
** LinkTimeOut - 1
** NodeTimeOut - 10


. Si no utiliza el software MPIO, asegúrese de tener la siguiente configuración del controlador:
+
** LinkTimeOut - 30
** NodeTimeOut - 120






==== Comprobar la configuración del controlador HBA QLogic en sistemas FC

En sistemas FC, debe comprobar la configuración del controlador HBA QLogic. Estos ajustes deben existir para cada puerto en el HBA.

.Pasos
. Abra QConverteConsole y, a continuación, haga clic en *conectar* en la barra de herramientas.
+
Se muestra el cuadro de diálogo conectarse al host.

. Seleccione el host adecuado de la lista y, a continuación, haga clic en *conectar*.
+
Se muestra una lista de HBA en el panel FC HBA.

. Seleccione el puerto HBA adecuado de la lista y, a continuación, haga clic en la ficha *Configuración*.
. Seleccione *Configuración avanzada del puerto HBA* en la sección *Seleccionar configuración*.
. Si utiliza el software MPIO, asegúrese de tener las siguientes configuraciones del controlador:
+
** Tiempo de espera de enlace abajo (linkdwnto) - 1
** Número de reintentos de bajada de puerto (portdwnrc) - 10


. Si no utiliza el software MPIO, asegúrese de tener la siguiente configuración del controlador:
+
** Tiempo de espera de enlace abajo (linkdwnto) - 30
** Número de reintentos de bajada de puerto (portdwnrc) - 120



