---
sidebar: sidebar 
permalink: hu_wuhu_upgrade.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Las utilidades unificadas de host de Windows incluyen un programa de instalación que establece el registro de Windows y los parámetros de HBA necesarios para que el host de Windows gestione correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series de NetApp. 
---
= Actualice las utilidades de host unificadas de Windows
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
El nuevo paquete de instalación de utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows. Siga las instrucciones para instalar las utilidades de host de forma interactiva o desde la línea de comandos de Windows para actualizar el paquete de instalación.

[role="tabbed-block"]
====
.Actualice de forma interactiva
--
Para actualizar el paquete de software Host Utilities de forma interactiva, debe ejecutar el programa de instalación de Host Utilities y seguir las instrucciones.

.Pasos
. Cambie al directorio en el que descargó el archivo ejecutable.
. Ejecute el archivo ejecutable y siga las instrucciones que aparecen en pantalla.
. Reinicie el host de Windows cuando se le solicite.
. Cuando se complete el reinicio, compruebe la versión de la utilidad host:
+
.. Abra *Panel de control*.
.. Vaya a *Programa y funciones* y compruebe la versión de la utilidad del sistema principal.




--
.Actualice desde una línea de comandos
--
Puede realizar una actualización silenciosa (sin supervisión) de las nuevas utilidades de host introduciendo los comandos apropiados en el símbolo del sistema de Windows.

.Pasos
. Introduzca el siguiente comando en el símbolo del sistema de Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` es el nombre de `.msi` Archivo para su arquitectura de CPU.
** MULTIPATHING especifica si está instalado la compatibilidad con MPIO. Los valores permitidos son “0” para NO y “1” para sí.
** `inst_path` Es la ruta en la que se instalan los archivos de utilidades de host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En el símbolo del sistema de Windows. Por ejemplo, la `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` el comando muestra la información de registro.

El sistema se reinicia automáticamente cuando finaliza la instalación.

--
====