---
sidebar: sidebar 
permalink: hu_wuhu_troubleshoot.html 
keywords: windows, host, utilities, 7.1, hba, fibre, channel, SANtricity, netapp, san, host, e-series, platform 
summary: Windows Host Utilities incluye un programa de instalación que establece los parámetros de registro de Windows y HBA necesarios para que el host Windows controle correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series. 
---
= Solucionar problemas de utilidades de host de Windows con configuración de almacenamiento de ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilice las técnicas generales de solución de problemas para investigar problemas que puedan ocurrir con una configuración de almacenamiento de Windows Host Utilities con ONTAP .  También deberías comprobar ellink:hu-wuhu-release-notes.html["Notas de la versión de Windows Host Utilities"] para problemas conocidos y soluciones.

A continuación, se muestra una lista de las diferentes áreas que puede investigar en busca de posibles problemas de interoperabilidad:

* Para identificar posibles problemas de interoperabilidad, confirme que las utilidades de host admiten la combinación de software del sistema operativo de host, hardware de host, software ONTAP y hardware de sistema de almacenamiento. Consulte la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad"^] para obtener más información.
* Compruebe que tiene la configuración de iSCSI correcta.
* Si los LUN iSCSI no están disponibles después de un reinicio, verifique que el destino esté listado como persistente en la pestaña *Destinos persistentes* de la GUI del iniciador iSCSI de Microsoft.
* Si las aplicaciones que utilizan las LUN muestran errores al iniciar, compruebe que las aplicaciones estén configuradas para que dependan del servicio iSCSI.
* Para las rutas FC a controladoras de almacenamiento que ejecutan ONTAP, compruebe que las zonas de los switches FC están configuradas mediante los WWPN de las LIF de destino, no con los WWPN de los puertos físicos del nodo.
* Revisar ellink:hu-wuhu-release-notes.html["Notas de la versión"] para que las utilidades de host de Windows comprueben si hay problemas conocidos.  Las notas de la versión incluyen una lista de problemas y limitaciones conocidos.
* Consulte la información sobre solución de problemas en la https://docs.netapp.com/us-en/ontap/san-admin/index.html["Administración de SAN de ONTAP"^] documentación.
* Búsqueda https://mysupport.netapp.com/site/bugs-online/product["NetApp Bugs Online"^] para problemas descubiertos recientemente.
+
** En el campo Tipo de error en Búsqueda avanzada, seleccione *iSCSI - Windows* y luego seleccione *Ir*. Debe repetir la búsqueda de Bug Type *FCP -Windows*.


* Recopila información sobre tu sistema.
* Registre los mensajes de error que se muestran en el host o la consola del sistema de almacenamiento.
* Recoja los archivos de registro del host y del sistema de almacenamiento.
* Registre los síntomas del problema y todos los cambios realizados en el host o el sistema de almacenamiento justo antes de que se apareciera el problema.
* Si no puede resolver el problema, póngase en contacto con el soporte técnico de NetApp para obtener ayuda.

