---
sidebar: sidebar 
permalink: hu_wuhu_72.html 
keywords: windows, 7.2, host utilities, SAN, windows 
summary: Windows Host Utilities incluye un programa de instalación que establece los parámetros de registro de Windows y HBA necesarios para que el host Windows controle correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series. 
---
= Instale Windows Host Utilities 7,2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las utilidades de host de Windows permiten conectar un equipo host de Windows a sistemas de almacenamiento NetApp.

Las utilidades de host de Windows son compatibles con las siguientes versiones de Windows:

* Windows 2025
* Windows 2022
* Windows 2019
* Windows 2016
* Windows 2012R2
* Windows 2012


Windows Host Utilities incluye un programa de instalación que establece los parámetros necesarios del registro de Windows y del adaptador de bus de host (HBA) para que un host Windows pueda manejar correctamente los comportamientos del sistema de almacenamiento para las plataformas ONTAP y E-Series.

Cuando instala el software Host Utilities, el instalador establece los parámetros necesarios del Registro de Windows y del HBA.

Los siguientes programas y archivos se instalan en el equipo host de Windows. El directorio predeterminado es `C:\Program Files\NetApp\Windows Host Utilities`.

|===
| Programa | Específico 


| `emulexhba.reg` | Programa de solución de problemas; ejecute este programa solo si el personal de soporte técnico le indica hacerlo. 


| `\NetAppQCLI\fcconfig.exe` | Utilizado por el programa de instalación para establecer los parámetros del HBA. 


| `\NetAppQCLI\fcconfig.ini` | Utilizado por el programa de instalación para establecer los parámetros del HBA. 


| `\NetAppQCLI\*.*` | Lo utiliza el programa de instalación para configurar los parámetros de HBA FC de QLogic. 


| `san_version.exe` | Muestra la versión de las utilidades del host y de los HBA de FC. 
|===
Las utilidades de host admiten diferentes configuraciones de host, protocolos y opciones de multivía de Windows. Para obtener más información, consulte la https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad"^].



== Verificar la configuración del host y del sistema de almacenamiento

Antes de instalar las utilidades de host, debe comprobar que la versión de utilidades de host admite la configuración del sistema de almacenamiento y host para que el software se instale correctamente.

.Pasos
. Compruebe la configuración admitida en la http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad"^].
. Compruebe las revisiones necesarias para el host correspondiente en el link:https://docs.netapp.com/us-en/ontap-sanhost/index.html["Documentación para Windows del host SAN"].
+

NOTE: El link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html["Use Windows Server 2022 con ONTAP"] documento proporciona instrucciones en link:https://docs.netapp.com/us-en/ontap-sanhost/hu_windows_2022.html#installing-windows-hotfixes["Instalación de revisiones de Windows"] para Windows Server 2022. Consulte los documentos de Windows en la categoría de configuraciones de host para encontrar la información de revisiones relevante para versiones anteriores de Windows Server.

. Añada la licencia iSCSI, FCP o NVMe-oF e inicie el servicio de destino.
+

NOTE: Los protocolos FC e iSCSI no requieren licencias en los sistemas de almacenamiento E-Series que utilizan Storage Manager de SANtricity.

. Compruebe el cableado.
+
Consulte https://docs.netapp.com/us-en/ontap/san-config/index.html["Referencia para la configuración DE SAN"^] Documentación para la versión de ONTAP o. https://docs.netapp.com/us-en/e-series/install-hw-cabling/index.html["Cableado de hardware E-Series"^] para obtener información detallada sobre el cableado y la configuración.





== Configurar switches y HBA de FC

Instale y configure uno o más adaptadores de bus de host (HBA) FC compatibles para las conexiones FC al sistema de almacenamiento.

El instalador de Windows Host Utilities establece los ajustes de FC HBA requeridos.


CAUTION: No cambie la configuración del adaptador de bus de host manualmente.

.Pasos
. Instalar uno o más HBA FC compatibles según las instrucciones proporcionadas por el proveedor de HBA.
. Obtenga los controladores HBA admitidos y las utilidades de administración e instálelos según las instrucciones proporcionadas por el proveedor de HBA.
. Conecte los HBA a sus switches FC o directamente al sistema de almacenamiento.
. Cree zonas en el switch FC según la documentación del switch FC.
. Para ONTAP, divida el switch por el WWPN. Asegúrese de utilizar el nombre de puerto WWPN de las interfaces lógicas (LIF) y no el nombre de puerto WWPN de los puertos físicos en las controladoras de almacenamiento. Consulte https://docs.netapp.com/us-en/ontap/san-config/index.html["Referencia para la configuración DE SAN"^] documentación para obtener más información.




== Instale las utilidades de host

El programa de instalación instala el paquete de utilidades de host y establece el registro de Windows y la configuración de HBA.

Debe especificar si desea incluir soporte multivía al instalar el paquete de software de Windows Host Utilities. Installer le solicita las siguientes opciones. También puede ejecutar una instalación silenciosa (desatendida) desde el símbolo del sistema de Windows.

.Compatibilidad con accesos múltiples
* Seleccione `MPIO` Si tiene más de una ruta desde el host o la máquina virtual de Windows al sistema de almacenamiento.
* Seleccione `no MPIO` únicamente si utiliza una ruta única al sistema de almacenamiento.


La selección de Microsoft Multipath I/O (MPIO) no está disponible para los sistemas Windows XP y Windows Vista; los sistemas operativos invitados no admiten I/O multivía. Para los huéspedes de Hyper-V, los discos sin formato (de paso) no aparecen en el sistema operativo invitado si elige compatibilidad con accesos múltiples. Puede usar discos sin configurar o MPIO, pero no es posible usar ambos en el sistema operativo invitado.

Puede instalar las utilidades de host de forma interactiva o mediante la línea de comandos. El nuevo paquete de instalación de utilidades de host debe estar en una ruta a la que pueda acceder el host de Windows. Siga las instrucciones para instalar las utilidades de host de forma interactiva o desde la línea de comandos de Windows.

[role="tabbed-block"]
====
.Instalar de forma interactiva
--
Para instalar el paquete de software de Host Utilities de forma interactiva, debe ejecutar el programa de instalación de Host Utilities y seguir las instrucciones.

.Pasos
. Descargue el archivo ejecutable de la https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.2/downloads["Sitio de soporte de NetApp"^].
. Cambie al directorio en el que descargó el archivo ejecutable.
. Ejecute el `netapp_windows_host_utilities_7.2_x64` archivar y seguir las instrucciones en pantalla.
. Reinicie el host de Windows cuando se le solicite.


--
.Realice la instalación desde una línea de comandos
--
Puede realizar una instalación silenciosa (sin supervisión) de las utilidades de host introduciendo los comandos apropiados en el símbolo del sistema de Windows. El sistema se reinicia automáticamente cuando finaliza la instalación.

.Pasos
. Introduzca el siguiente comando en el símbolo del sistema de Windows:
+
`msiexec /i installer.msi /quiet MULTIPATHING= {0 | 1} [INSTALLDIR=inst_path]`

+
** `installer` es el nombre de `.msi` Archivo para su arquitectura de CPU.
** MULTIPATHING especifica si está instalado la compatibilidad con MPIO. Los valores permitidos son “0” para NO y “1” para sí.
** `inst_path` Es la ruta en la que se instalan los archivos de utilidades de host. La ruta predeterminada es `C:\Program Files\NetApp\Windows Host Utilities\`.





NOTE: Para ver las opciones estándar de Microsoft Installer (MSI) para el registro y otras funciones, introduzca `msiexec /help` En el símbolo del sistema de Windows. Por ejemplo, la `msiexec /i install.msi /quiet /l*v <install.log> LOGVERBOSE=1` el comando muestra la información de registro.

--
====