---
permalink: legal-notices.html 
sidebar: sidebar 
keywords: legal, notices, copyright, trademarks, patents 
summary: Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más. 
---
= Avisos legales
:allow-uri-read: 


[role="lead"]
Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más.

[role="lead"]
Los avisos legales proporcionan acceso a las declaraciones de copyright, marcas comerciales, patentes y mucho más.



== Derechos de autor

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marcas comerciales

NETAPP, el logotipo de NETAPP y las marcas enumeradas en la página de marcas comerciales de NetApp son marcas comerciales de NetApp, Inc. Los demás nombres de empresas y productos son marcas comerciales de sus respectivos propietarios.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Estadounidenses

Puede encontrar una lista actual de las patentes propiedad de NetApp en:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Política de privacidad

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Código abierto

Los archivos de notificación proporcionan información sobre los derechos de autor y las licencias de terceros que se utilizan en software de NetApp.

Proporciona información acerca de los derechos de autor y las licencias de terceros utilizados en este producto.

* link:./media/Notices-AIX61-2023.pdf["Aviso para AIX"^]
* link:./media/Linux_Unified_Host_Utilities.pdf["Aviso para Linux"^]
* link:./media/Solaris_Host_Utilities-2017.09.12-01.25.35.pdf["Aviso para Solaris"^]
* link:./media/Windows_Unified_Host_Utilities_(WUHU)Notice.pdf["Aviso para Windows"^]

