---
sidebar: sidebar 
permalink: nvme_rhel_88.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: Cómo configurar el host NVMe-oF para RHEL 8,8 con ONTAP 
---
= Configuración de host de NVMe-oF para RHEL 8,8 con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NVMe over Fabrics (NVMe-oF), incluido NVMe over Fibre Channel (NVMe/FC) y otros transportes, es compatible con Red Hat Enterprise Linux (RHEL) 8,8 con acceso asimétrico a espacio de nombres (ANA). En entornos de NVMe-oF, ANA es el equivalente a la multivía ALUA en entornos iSCSI y FC y se implementa con NVMe multivía en kernel.

Se ofrece la siguiente compatibilidad para la configuración del host de NVMe-oF para RHEL 8,8 con ONTAP:

* Compatibilidad para NVMe sobre TCP (NVMe/TCP) además de NVMe/FC. El plugin de NetApp en el paquete nvme-cli nativo muestra detalles de ONTAP para espacios de nombres NVMe/FC y NVMe/TCP.


Si quiere más información sobre las configuraciones compatibles, consulte link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].



== Limitaciones conocidas

* La multivía de NVMe en kernel está deshabilitada de forma predeterminada para los hosts RHEL 8,8 NVMe-oF. Por lo tanto, debe habilitarla manualmente.
* En los hosts RHEL 8,8, NVMe/TCP es una función de vista previa de tecnología debido a problemas abiertos.
* Actualmente no se admite el arranque SAN mediante el protocolo NVMe-oF.




== Habilite la multivía en kernel

Puede utilizar el siguiente procedimiento para habilitar la multivía in-kernal.

.Pasos
. Instale RHEL 8,8 en el servidor host.
. Una vez finalizada la instalación, compruebe que está ejecutando el kernel RHEL 8,8 especificado.
+
[listing]
----
# uname -r
----
+
*Ejemplo de salida*

+
[listing]
----
4.18.0-477.10.1.el8_8.x86_64
----
. Instale el paquete nvme-cli:
+
[listing]
----
rpm -qa|grep nvme-cli
----
+
*Ejemplo de salida*

+
[listing]
----
nvme-cli-1.16-7.el8.x86_64
----
. Habilitar multivía NVMe en kernel:
+
[listing]
----
# grubby --args=nvme_core.multipath=Y --update-kernel /boot/vmlinuz-4.18.0-477.10.1.el8_8.x86_64
----
. En el host, compruebe la cadena NQN del host en `/etc/nvme/hostnqn`:
+
[listing]
----
# cat /etc/nvme/hostnqn
----
+
*Ejemplo de salida*

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:f6517cae-3133-11e8-bbff-7ed30aef123f
----
. Compruebe que el `hostnqn` la cadena coincide con `hostnqn` Cadena para el subsistema correspondiente en la cabina de ONTAP:
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
*Ejemplo de salida*

+
[listing]
----
Vserver     Subsystem       Host NQN
----------- --------------- ----------------------------------------------------------
vs_nvme161 rhel_161_LPe32002    nqn.2014-08.org.nvmexpress:uuid:f6517cae-3133-11e8-bbff-7ed30aef123f
----
+

NOTE: Si las cadenas NQN del host no coinciden, puede usar el `vserver modify` Comando para actualizar la cadena NQN del host en el subsistema NVMe de ONTAP correspondiente para que coincidan con la cadena NQN del host `/etc/nvme/hostnqn` en el host.

. Reinicie el host.


[NOTE]
====
Si tiene intención de ejecutar el tráfico coexistente de NVMe y SCSI en el mismo host, NetApp recomienda utilizar el acceso multivía de NVMe in-kernel para espacios de nombres de ONTAP y dm-multipath para LUN de ONTAP respectivamente. Esto significa que los espacios de nombres ONTAP deben excluirse de dm-multipath para evitar que dm-multipath reclamen estos dispositivos de espacio de nombres. Esto se puede hacer agregando la `enable_foreign` ajuste en la `/etc/multipath.conf` archivo:

[listing]
----
# cat /etc/multipath.conf
defaults {
  enable_foreign  NONE
}
----
====


== Configure NVMe/FC

Puede configurar NVMe/FC para adaptadores Broadcom/Emulex o Marvell/Qlogic.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
.Pasos
. Compruebe que está utilizando el modelo de adaptador admitido:
+
[listing]
----
# cat /sys/class/scsi_host/host*/modelname
----
+
*Ejemplo de salida:*

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/modeldesc
----
+
*Ejemplo de salida:*

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----
. Compruebe que está utilizando la Broadcom recomendada `lpfc` firmware y controlador de bandeja de entrada:
+
[listing]
----
# cat /sys/class/scsi_host/host*/fwrev
14.0.639.18, sli-4:2:c
14.0.639.18, sli-4:2:c
----
+
[listing]
----
# cat /sys/module/lpfc/version
0:14.0.0.18
----
+
Para obtener la lista más actual de las versiones de firmware y controladores de adaptador compatibles, consulte link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].

. Compruebe que `lpfc_enable_fc4_type` se establece en `3`:
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
3
----
. Compruebe que los puertos del iniciador están en funcionamiento y que puede ver los LIF de destino:
+
[listing]
----
# cat /sys/class/fc_host/host*/port_name
0x100000109b1c1204
0x100000109b1c1205
----
+
[listing]
----
# cat /sys/class/fc_host/host*/port_state
Online
Online
----
+
[listing]
----
# cat /sys/class/scsi_host/host*/nvme_info NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x10000090fae0ec88 WWNN x20000090fae0ec88 DID x0a1300 ONLINE
NVME RPORT       WWPN x2049d039ea36a105 WWNN x2048d039ea36a105 DID x0a0c0a TARGET DISCSRVC ONLINE
NVME RPORT       WWPN x204bd039ea36a105 WWNN x2048d039ea36a105 DID x0a100a TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000134 Cmpl 0000000134 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000825e567 Issue 000000000825d7ed OutIO fffffffffffff286
abort 0000027c noxri 00000000 nondlp 00000a02 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000782 Err 000130fa

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x10000090fae0ec89 WWNN x20000090fae0ec89 DID x0a1200 ONLINE
NVME RPORT       WWPN x204ad039ea36a105 WWNN x2048d039ea36a105 DID x0a080a TARGET DISCSRVC ONLINE
NVME RPORT       WWPN x204cd039ea36a105 WWNN x2048d039ea36a105 DID x0a090a TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000134 Cmpl 0000000134 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000826ced5 Issue 000000000826c226 OutIO fffffffffffff351
        abort 0000029d noxri 00000000 nondlp 000008df qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00000821 Err 00012fcd

----


--
.Adaptador FC Marvell/QLogic para NVMe/FC
--
.Pasos
. El controlador de la bandeja de entrada nativa qla2xxx que se incluye en el kernel GA de RHEL 8,8 tiene las correcciones previas más recientes esenciales para admitir ONTAP. Compruebe que está ejecutando las versiones de firmware y controlador del adaptador compatibles:
+
[listing]
----
# cat /sys/class/fc_host/host*/symbolic_name
----
+
*Ejemplo de salida*

+
[listing]
----
QLE2772 FW:v9.10.11 DVR:v10.02.07.900-k-debug
QLE2772 FW:v9.10.11 DVR:v10.02.07.900-k-debug
----
. Compruebe que `ql2xnvmeenable` está configurado. Esto permite que el adaptador Marvell funcione como iniciador NVMe/FC:
+
[listing]
----
# cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
1
----


--
====


=== Habilitar 1MB I/O (opcional)

ONTAP informa de un MDT (tamaño de transferencia de MAX Data) de 8 en los datos Identify Controller. Esto significa que el tamaño máximo de solicitud de E/S puede ser de hasta 1MB TB. Para emitir solicitudes de I/O de tamaño 1 MB para un host Broadcom NVMe/FC, debe aumentar `lpfc` el valor `lpfc_sg_seg_cnt` del parámetro a 256 con respecto al valor predeterminado de 64.

.Pasos
. Defina el `lpfc_sg_seg_cnt` parámetro en 256:
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_sg_seg_cnt=256
----
. Ejecute `dracut -f` un comando y reinicie el host:
. Compruebe que `lpfc_sg_seg_cnt` es 256:
+
[listing]
----
# cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
256
----



NOTE: Esto no es aplicable a los hosts Qlogic NVMe/FC.



== Configure NVMe/TCP

NVMe/TCP no tiene la funcionalidad de conexión automática. Por lo tanto, si una ruta deja de funcionar y no se restablece en el tiempo de espera predeterminado de 10 minutos, no se puede volver a conectar automáticamente NVMe/TCP. Para evitar que se agote el tiempo de espera, debe definir el período de reintento para los eventos de conmutación por error en al menos 30 minutos.

.Pasos
. Compruebe que el puerto del iniciador pueda recuperar los datos de la página de registro de detección en las LIF NVMe/TCP admitidas:
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
*Ejemplo de salida:*

+
[listing]
----
# nvme discover -t tcp -w 192.168.111.79 -a 192.168.111.14

Discovery Log Number of Records 8, Generation counter 10
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  0
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.211.15
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.111.15
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: unrecognized
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:discovery
traddr:  192.168.211.14
sectype: none
..........
----
. Compruebe que las otras combinaciones de LIF iniciador-objetivo NVMe/TCP puedan recuperar correctamente los datos de la página del registro de detección:
+
[listing]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
*Ejemplo de salida:*

+
[listing]
----
# nvme	discover	-t   tcp    -w	192.168.111.79   -a	192.168.111.14
# nvme	discover	-t   tcp    -w	192.168.111.79   -a	192.168.111.15
# nvme	discover	-t   tcp    -w	192.168.211.79   -a	192.168.211.14
# nvme	discover	-t   tcp    -w	192.168.211.79   -a	192.168.211.15
----
. Ejecute el `nvme connect-all` Comando en todos los LIF de destino iniciador NVMe/TCP admitidos en los nodos y establezca el período de tiempo de espera de pérdida de la controladora durante al menos 30 minutos o 1800 segundos:
+
[listing]
----
nvme connect-all -t tcp -w host-traddr -a traddr -l 1800
----
+
*Ejemplo de salida:*

+
[listing]
----
# nvme	connect-all	-t	tcp	-w	192.168.111.79	-a	192.168.111.14	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.111.79	-a	192.168.111.15	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.211.79	-a	192.168.211.14	-l	1800
# nvme	connect-all	-t	tcp	-w	192.168.211.79	-a	192.168.211.15	-l	1800
----




== Valide NVMe-of

Puede usar el siguiente procedimiento para validar NVME-oF.

.Pasos
. Compruebe que la multivía NVMe en kernel esté habilitada:
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
Y
----
. Compruebe que la configuración de NVMe-of adecuada (como, `model` establezca en `NetApp ONTAP Controller` y equilibrio de carga `iopolicy` establezca en `round-robin`) Para los respectivos espacios de nombres ONTAP se refleja correctamente en el host:
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/model
NetApp ONTAP Controller
NetApp ONTAP Controller
----
+
[listing]
----
# cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
round-robin
round-robin
----
. Verifique que los espacios de nombres se hayan creado y detectado correctamente en el host:
+
[listing]
----
# nvme list
----
+
*Ejemplo de salida:*

+
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme3n1 81Gx7NSiKSQeAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
. Compruebe que el estado de la controladora de cada ruta sea activo y que tenga el estado de ANA correcto:
+
[role="tabbed-block"]
====
.NVMe/FC
--
[listing]
----
# nvme list-subsys /dev/nvme3n1
----
*Ejemplo de salida:*

[listing]
----
nvme-subsys3 - NQN=nqn.1992-08.com.netapp:sn.ab4fa6a5ba8b11ecbe3dd039ea359e4b:subsystem.rhel_161_Lpe32002
\
 +- nvme0 fc traddr=nn-0x2048d039ea36a105:pn-0x204cd039ea36a105 host_traddr=nn-0x20000090fae0ec89:pn-0x10000090fae0ec89 live non-optimized
 +- nvme1 fc traddr=nn-0x2048d039ea36a105:pn-0x204ad039ea36a105 host_traddr=nn-0x20000090fae0ec89:pn-0x10000090fae0ec89 live optimized
 +- nvme2 fc traddr=nn-0x2048d039ea36a105:pn-0x204bd039ea36a105 host_traddr=nn-0x20000090fae0ec88:pn-0x10000090fae0ec88 live non-optimized
 +- nvme4 fc traddr=nn-0x2048d039ea36a105:pn-0x2049d039ea36a105 host_traddr=nn-0x20000090fae0ec88:pn-0x10000090fae0ec88 live optimized
----
--
.NVMe/TCP
--
[listing]
----
# nvme list-subsys /dev/nvme0n1
----
*Ejemplo de salida:*

[listing]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:sn.154a5833c78c11ecb069d039ea359e4b:subsystem.rhel_tcp_165
\
 +- nvme0 tcp traddr=192.168.111.15 trsvcid=4420 host_traddr=192.168.111.79 live non-optimized
 +- nvme1 tcp traddr=192.168.111.14 trsvcid=4420 host_traddr=192.168.111.79 live optimized
 +- nvme2 tcp traddr=192.168.211.15 trsvcid=4420 host_traddr=192.168.211.79 live non-optimized
----
--
====
. Confirmar que el complemento de NetApp muestra los valores correctos para cada dispositivo de espacio de nombres ONTAP:
+
[role="tabbed-block"]
====
.Columna
--
[listing]
----
# nvme netapp ontapdevices -o column
----
*Ejemplo de salida:*

[listing]
----
Device        Vserver   Namespace Path
----------------------- ------------------------------
/dev/nvme0n1 vs_tcp           /vol/vol1/ns1



NSID       UUID                                   Size
------------------------------------------------------------
1          338d73ce-b5a8-4847-9cc9-b127c75d8855	21.47GB
----
--
.JSON
--
[listing]
----
# nvme netapp ontapdevices -o json
----
*Ejemplo de salida*

[listing]
----
{
  "ONTAPdevices" : [
    {
      "Device" : "/dev/nvme0n1",
      "Vserver" : "vs_tcp79",
      "Namespace_Path" : "/vol/vol1/ns1",
      "NSID" : 1,
      "UUID" : "338d73ce-b5a8-4847-9cc9-b127c75d8855",
      "Size" : "21.47GB",
      "LBA_Data_Size" : 4096,
      "Namespace_Size" : 5242880
    },
]

}

----
--
====




== Problemas conocidos

La configuración de host de NVMe-oF para RHEL 8,8 con la versión ONTAP tiene los siguientes problemas conocidos:

[cols="20,40,40"]
|===
| ID de error de NetApp | Título | Descripción 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1479047["1479047"] | Los hosts RHEL 8,8 NVMe-oF crean controladoras de detección persistente duplicadas | En los hosts NVMe over Fabrics (NVMe-of), es posible utilizar el comando "nvme Discover -p" para crear controladoras de detección persistente (PDCs). Cuando se utiliza este comando, sólo se debe crear un PDC por combinación iniciador-destino.  Sin embargo, si ejecuta Red Hat Enterprise Linux (RHEL) 8,8 en un host NVMe-oF, se crea un PDC duplicado cada vez que se ejecuta «nvme discover -p». Esto lleva a un uso innecesario de recursos tanto en el host como en el destino. 
|===