---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Cómo configurar el host NVMe/FC para AIX con ONTAP 
---
= Configuración de host NVMe/FC para AIX con ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible habilitar NVMe over Fibre Channel (NVMe/FC) en hosts IBM AIX y VIOS/PowerVM utilizando almacenamiento ONTAP como destino. Si quiere más información sobre las configuraciones compatibles, consulte link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].

La siguiente compatibilidad está disponible para la configuración de host de NVMe/FC para un host AIX con ONTAP:

* A partir de la versión 9.13.1 de ONTAP, se añade compatibilidad con NVMe/FC para las versiones IBM AIX 7,2 TL5 SP6, AIX 7,3 TL1 SP2 y VIOS 3.1.4.21 con compatibilidad con arranque SAN para pilas físicas y virtuales. Consulte la documentación de IBM para obtener más información sobre la configuración del soporte de arranque SAN.
* NVMe/FC es compatible con los servidores IBM Power9 y Power10.
* No se requiere ningún PCM (Módulo de control de ruta) separado, como Host Utilities para AIX compatibilidad con I/O multivía (MPIO), para los dispositivos NVMe.
* Se incluye la compatibilidad con la virtualización de NetApp (VIOS/PowerVM) con VIOS 3,1.4,21. Se admite _ONLY_ a través del modo de virtualización del almacenamiento NPIV (virtualización N_portID) utilizando el servidor IBM Power10.


.Lo que necesitará
* Compruebe que tiene 32GB adaptadores FC Emulex (EN1A, EN1B, EN1L, EN1M) o adaptadores FC de 64GB Gb (EN1N, EN1P) con firmware del adaptador 12.4.257.30 y versiones posteriores.
* Si tiene una configuración de MetroCluster, NetApp recomienda cambiar el tiempo de APD predeterminado de NVMe/FC de AIX para admitir eventos de conmutación no planificada de MetroCluster a fin de evitar que el sistema operativo AIX aplique un tiempo de espera de I/O más corto. Para obtener más información y los cambios recomendados en la configuración predeterminada, consulte NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* De forma predeterminada, el valor de tiempo de espera de transición de acceso al espacio de nombres asimétrico (ANATT) para el sistema operativo del host AIX es de 30 segundos. IBM proporciona una solución provisional (ifix) que limita el valor ANATT a 60 segundos; debe instalar un ifix desde el sitio web de IBM para asegurarse de que todos los flujos de trabajo de ONTAP no son disruptivos.
+

NOTE: Para la compatibilidad con NVMe/FC AIX, debe instalar un ifix en las versiones GA del sistema operativo AIX. Esto no es necesario para el sistema operativo VIOS/PowerVM.

+
Los detalles de ifix son los siguientes:

+
** Para AIX nivel 72-TL5-SP6-2320, instale el `IJ46710s6a.230509.epkg.Z` paquete.
** Para AIX nivel 73-TL1-SP2-2320, instale el `IJ46711s2a.230509.epkg.Z` paquete.
+
Para obtener más información sobre la gestión de ifixes, consulte link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Gestión de correcciones provisionales en AIX"^].

+

NOTE: Debe instalar los ifixes en una versión de AIX sin ifixes previamente instalados relacionados con `devices.pciex.pciexclass.010802.rte` en el sistema. Si estos ifixes están presentes, entrarán en conflicto con la nueva instalación.

+
En la siguiente tabla se muestran los HBA asignados a AIX LPAR (partición lógica de AIX) o a la pila física:

+
[cols="10,10,10,10,10"]
|===
| SO del host | Arco de potencia | Versión FW de alimentación | Modo | Comentarios 


.2+| AIX 7,2 TL5 SP6 | Power9 | FW 950 o posterior | Pila física | ifix disponible a través de TS012877410. 


| Power10 | FW 1010 o posterior | Pila física | Es compatible con arranque SAN. ifix disponible a través de TS012877410. 


.2+| AIX 7,3 TL1 SP2 | Power9 | FW 950 o posterior | Pila física | ifix disponible a través de TS012877410. 


| Power10 | FW 1010 o posterior | Pila física y virtual | ifix disponible a través de TS012877410. 
|===
+
En la siguiente tabla se muestran los HBA asignados a VIOS con compatibilidad con NPIV en modo virtualizado:

+
[cols="10,10,10,10,10"]
|===
| SO del host | Arco de potencia | Versión FW de alimentación | Modo | Comentarios 


| VIOS/PowerVM 3.1.4.21 | Power10 | FW 1010 o posterior | Pila virtual | El soporte comienza desde AIX 7,3 TL1 SP2 para VIOC 
|===






== Limitaciones conocidas

La configuración de host de NVMe/FC para AIX con ONTAP tiene las siguientes limitaciones conocidas:

* Los HBA FC de QLogic/Marvel 32G en un host AIX no admiten NVMe/FC.
* No se admite el arranque SAN para dispositivos NVMe/FC que utilizan el servidor IBM de Power9.




== Accesos múltiples

IBM MPIO (Multi Path I/O), que se utiliza para la multivía NVMe, se proporciona de forma predeterminada cuando se instala el sistema operativo AIX.

Puede utilizar el para comprobar que la multivía de NVMe está habilitada para un host AIX `lsmpio` comando:

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Ejemplo de salida*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== Configure NVMe/FC

Es posible usar el siguiente procedimiento para configurar NVMe/FC para adaptadores Broadcom/Emulex.

.Pasos
. Compruebe que está utilizando el adaptador compatible. Para obtener la lista más actual de adaptadores compatibles, consulte link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].
. De forma predeterminada, la compatibilidad con el protocolo NVMe/FC está habilitada en el FC físico; sin embargo, la compatibilidad con el protocolo NVMe/FC está deshabilitada en Virtual Fibre Channel (VFC) en Virtual I/O Server (VIOS).
+
Recupere una lista de adaptadores virtuales:

+
[listing]
----
$ lsmap -all -npiv
----
+
*Ejemplo de salida*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
. Habilite la compatibilidad con el protocolo NVMe/FC en un adaptador ejecutando el `ioscli vfcctrl` Comando en el VIOS:
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*Ejemplo de salida*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Compruebe que el soporte se ha activado en el adaptador:
+
[listing]
----
# lsattr -El vfchost0
----
+
*Ejemplo de salida*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. Habilitar el protocolo NVMe/FC para todos los adaptadores actuales o los adaptadores seleccionados:
+
.. Habilite el protocolo NVMe/FC para todos los adaptadores:
+
... Cambie el `dflt_enabl_nvme` valor de atributo de `viosnpiv0` pseudo dispositivo a. `yes`.
... Ajuste la `enable_nvme` valor de atributo a. `yes` Para todos los dispositivos host VFC.
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*Ejemplo de salida*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. Habilite el protocolo NVMe/FC para los adaptadores seleccionados cambiando el `enable_nvme` Valor del atributo de dispositivo host de VFC a. `yes`.


. Compruebe que `FC-NVMe Protocol Device` se ha creado en el servidor:
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
* Exmaple salida *

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Registre el NQN del host desde el servidor:
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*Ejemplo de salida*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*Ejemplo de salida*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
. Compruebe el NQN del host y compruebe que coincide con la cadena NQN del host correspondiente al subsistema correspondiente en la cabina de ONTAP:
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*Ejemplo de salida*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Compruebe que los puertos del iniciador están en funcionamiento y puede ver los LIF de destino.




== Valide NVMe/FC

Es necesario verificar que los espacios de nombres de las ONTAP se reflejen correctamente en el host. Ejecute el siguiente comando para hacerlo:

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*Ejemplo de salida*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
Puede comprobar el estado de la multivía:

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Ejemplo de salida*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== Problemas conocidos

La configuración de host NVMe/FC para AIX con ONTAP tiene los siguientes problemas conocidos:

[cols="10,30,30"]
|===
| ID de Burt | Título | Descripción 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | Tiempo de APD predeterminado de NVMe/FC de AIX que se modificará para admitir eventos de conmutación de sitios no planificados de MCC | De manera predeterminada, los sistemas operativos AIX utilizan un valor de tiempo de espera APD de 20sec para NVMe/FC.  Sin embargo, los flujos de trabajo de conmutación por error automática no planificada (AUSO) de ONTAP MetroCluster y los flujos de trabajo de conmutación iniciados por tiebreaker pueden tardar un poco más que la ventana de tiempo de espera APD, lo cual produce errores de I/O. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | NVMe/FC de AIX limita ANATT a 60s, en lugar de 120s, como anuncia ONTAP | ONTAP anuncia el tiempo de espera de transición de ANA (acceso asimétrico al espacio de nombres) en la identificación de la controladora en 120sec. Actualmente, con ifix, AIX lee el tiempo de espera de transición ANA desde el controlador Identify, pero lo sujeta efectivamente a 60sec si está por encima de ese límite. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | NVMe/FC de AIX detecta EIO después de la caducidad de ANATT | En cualquier evento de conmutación al nodo de respaldo de almacenamiento (SFO), si la transición ANA(acceso asimétrico al espacio de nombres) supera el límite de tiempo de espera de transición de ANA en una ruta determinada, el host NVMe/FC de AIX produce un error de I/O a pesar de tener rutas alternativas disponibles en buen estado para el espacio de nombres. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC espera a que el ANATT medio/completo caduque antes de reanudar las operaciones de I/O después de ANA AEN | NVMe/FC de IBM AIX no admite algunas notificaciones asíncronas (AENs) que publica ONTAP. Este manejo de ANA no óptimo dará como resultado un rendimiento subóptimo durante las operaciones de SFO. 
|===


== Solucionar problemas

Antes de solucionar problemas de algún fallo de NVMe/FC, compruebe que ejecute una configuración que cumpla con las especificaciones de la herramienta de matriz de interoperabilidad (IMT). Si aún tiene problemas, póngase en contacto con link:https://mysupport.netapp.com["Soporte de NetApp"^] para obtener más información sobre su clasificación.
