---
sidebar: sidebar 
permalink: nvme-aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Cómo configurar el host NVMe/FC para AIX con ONTAP 
---
= Configurar AIX con NVMe-oF para almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los hosts IBM AIX y Virtual I/O Server (VIOS)/PowerVM admiten el protocolo NVMe/FC con acceso asimétrico a espacios de nombres (ANA).  ANA es equivalente al acceso multirruta de unidad lógica asimétrica (ALUA) en entornos iSCSI y FCP.

Para obtener detalles adicionales sobre las configuraciones admitidas, consulte lalink:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad (IMT)"^] .

.Acerca de esta tarea
Puede utilizar el siguiente soporte y funciones con la configuración de host NVMe-oF para hosts AIX.  También debe revisar las limitaciones conocidas antes de comenzar el proceso de configuración.

* Soporte disponible:
+
** A partir de ONTAP 9.13.1, se agrega soporte NVMe/FC para IBM AIX 7.2 TL5 SP6, AIX 7.3 TL1 SP2 y VIOS 3.1.4.21 con soporte de arranque SAN para pilas físicas y virtuales.  Consulte la documentación de IBM para obtener más información sobre cómo configurar el soporte de arranque SAN.
** NVMe/FC es compatible con los servidores IBM Power9 y Power10.
** No se requiere un PCM (módulo de control de ruta) independiente, como Host Utilities para la compatibilidad con E/S multiruta SCSI (MPIO) de AIX, para los dispositivos NVMe.
** Se incluye la compatibilidad con la virtualización de NetApp (VIOS/PowerVM) con VIOS 3,1.4,21. Se admite _ONLY_ a través del modo de virtualización del almacenamiento NPIV (virtualización N_portID) utilizando el servidor IBM Power10.


* Limitaciones conocidas:
+
** Los HBA FC Qlogic/Marvel 32G en un host AIX no admiten NVMe/FC.
** El arranque SAN no es compatible con dispositivos NVMe/FC que utilizan el servidor IBM Power9.




.Antes de empezar
* Compruebe que tiene 32GB adaptadores FC Emulex (EN1A, EN1B, EN1L, EN1M) o adaptadores FC de 64GB Gb (EN1N, EN1P) con firmware del adaptador 12.4.257.30 y versiones posteriores.
* Si tiene una configuración de MetroCluster, NetApp recomienda cambiar el tiempo de APD predeterminado de NVMe/FC de AIX para admitir eventos de conmutación no planificada de MetroCluster a fin de evitar que el sistema operativo AIX aplique un tiempo de espera de I/O más corto. Para obtener más información y los cambios recomendados en la configuración predeterminada, consulte NetApp Bugs Online - link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/1553249["1553249"^].
* Dependiendo de su versión de AIX, el tiempo de espera de transición de acceso al espacio de nombres asimétrico (ANATT) para el sistema operativo host AIX es de 30 segundos o 60 segundos de manera predeterminada.  Si el valor predeterminado de ANATT para su host es 30 segundos, debe instalar una solución provisional de IBM (ifix) desde el sitio web de IBM que configure ANATT en 60 segundos para garantizar que todos los flujos de trabajo de ONTAP no causen interrupciones.
+
[NOTE]
====
Para obtener compatibilidad con NVMe/FC AIX, debe instalar un ifix en la versión GA del sistema operativo AIX.  El ifix no es necesario para el sistema operativo VIOS/PowerVM.

Debe instalar los ifixes en una versión de AIX que no tenga ifixes previamente instalados relacionados con `devices.pciex.pciexclass.010802.rte` en el sistema.  Los ifixes instalados previamente pueden entrar en conflicto con la nueva instalación.

====
+
[role="tabbed-block"]
====
.Establezca ANATT en 60 segundos
--
El ANATT predeterminado para las versiones AIX nivel 72-TL5-SP6-2320 y AIX nivel 73-TL1-SP2-2320 es 30 segundos.  IBM proporciona un ifix que establece el ANATT en 60 segundos.  El ifix está disponible a través del ID de caso de IBM TS018079082 y puede instalarlo para las siguientes versiones de AIX:

** Para AIX nivel 72-TL5-SP6-2320, instale el `IJ46710s6a.230509.epkg.Z` paquete.
** Para AIX nivel 73-TL1-SP2-2320, instale el `IJ46711s2a.230509.epkg.Z` paquete.


--
.El ANATT predeterminado es 60 segundos
--
El ANATT predeterminado es de 60 segundos para las siguientes versiones de AIX:

** Nivel AIX 73-TL2-SP3-2446
** Nivel AIX 73-TL2-SP2-2420
** AIX nivel 72-TL5-SP8-2420


--
.Opcionalmente, configure ANATT en 120 segundos
--
IBM proporciona un ifix que establece el ANATT en 120 segundos.  Cuando configura ANATT en 120 segundos, mejora el rendimiento durante los eventos de conmutación por error de almacenamiento de ONTAP .  El ifix está disponible a través del ID de caso de IBM TS012877410 y puede instalarlo para las siguientes versiones de AIX:

** Para el nivel AIX 73-TL3-SP0-2446, instale el `IJ53487s0a.250130.epkg.Z` paquete.
** Para el nivel AIX 72-TL5-SP9-2446, instale el `IJ53445s9a.250130.epkg.Z` paquete.


--
====
+
[NOTE]
====
La versión mínima del firmware del servidor para servidores Power9 para compatibilidad con NVMe/FC es FW 950.

La versión mínima del firmware del servidor para servidores Power10 para compatibilidad con NVMe/FC es FW 1010.

====
+
Para obtener más información sobre la gestión de ifixes, consulte link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Gestión de correcciones provisionales en AIX"^].





== Paso 1: Confirme la configuración de múltiples rutas para su host

Cuando instala el sistema operativo AIX, IBM MPIO utilizado para rutas múltiples NVMe se habilita de manera predeterminada.

.Pasos
. Verifique que la multirruta NVMe esté habilitada:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----
====




== Paso 2: Configurar NVMe/FC

Debe configurar NVMe/FC para los adaptadores Broadcom/Emulex en VIOS porque la compatibilidad del protocolo NVMe/FC está deshabilitada en el canal de fibra virtual (vFC) en VIOS.  La compatibilidad del protocolo NVMe/FC está habilitada en el FC físico de forma predeterminada.

.Pasos
. link:https://mysupport.netapp.com/matrix/["Verifique que esté utilizando el adaptador compatible"^] .
. Recupere una lista de adaptadores virtuales:
+
[source, cli]
----
lsmap -all -npiv
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
----
====
. Habilite la compatibilidad con el protocolo NVMe/FC en un adaptador ejecutando el `ioscli vfcctrl` Comando en el VIOS:
+
[source, cli]
----
vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
.Resultado de ejemplo
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Compruebe que el soporte se ha activado en el adaptador:
+
[source, cli]
----
lsattr -El vfchost0
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
====
. Habilite el protocolo NVMe/FC para todos los adaptadores:
+
.. Cambie el `dflt_enabl_nvme` valor de atributo de `viosnpiv0` pseudo dispositivo a. `yes`.
.. Ajuste la `enable_nvme` valor de atributo a. `yes` Para todos los dispositivos host VFC.
+
[source, cli]
----
chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[source, cli]
----
lsattr -El viosnpiv0
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----
====


. Habilite el protocolo NVMe/FC para los adaptadores seleccionados cambiando el `enable_nvme` Valor del atributo de dispositivo host de VFC a. `yes`.
. Compruebe que `FC-NVMe Protocol Device` se ha creado en el servidor:
+
[source, cli]
----
lsdev |grep fcnvme
----
+
.Ejemplo de salida
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Registre el NQN del host desde el servidor:
+
[source, cli]
----
lsattr -El fcnvme0
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
+
[source, cli]
----
lsattr -El fcnvme1
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
====
. Compruebe el NQN del host y compruebe que coincide con la cadena NQN del host correspondiente al subsistema correspondiente en la cabina de ONTAP:
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
.Resultado de ejemplo
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Compruebe que los puertos del iniciador están en funcionamiento y puede ver los LIF de destino.




== Paso 3: Validar NVMe/FC

Verifique que los espacios de nombres de ONTAP sean correctos para la configuración NVMe/FC.

.Pasos
. Verifique que los espacios de nombres de ONTAP se reflejen correctamente en el host:
+
[source, cli]
----
lsdev -Cc disk |grep NVMe
----
+
.Resultado de ejemplo
[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
. Opcionalmente, verifique el estado de rutas múltiples:
+
[source, cli]
----
lsmpio -l hdisk1
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----
====




== Paso 4: Revisar los problemas conocidos

La configuración del host NVMe/FC para AIX con almacenamiento ONTAP tiene los siguientes problemas conocidos:

[cols="10,30,30"]
|===
| ID de Burt | Título | Descripción 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1553249["1553249"^] | Tiempo de APD predeterminado de NVMe/FC de AIX que se modificará para admitir eventos de conmutación de sitios no planificados de MCC | De manera predeterminada, los sistemas operativos AIX utilizan un valor de tiempo de espera APD de 20sec para NVMe/FC.  Sin embargo, los flujos de trabajo de conmutación por error automática no planificada (AUSO) de ONTAP MetroCluster y los flujos de trabajo de conmutación iniciados por tiebreaker pueden tardar un poco más que la ventana de tiempo de espera APD, lo cual produce errores de I/O. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1546017["1546017"^] | NVMe/FC de AIX limita ANATT a 60s, en lugar de 120s, como anuncia ONTAP | ONTAP anuncia el tiempo de espera de transición de ANA (acceso asimétrico al espacio de nombres) en la identificación de la controladora en 120sec. Actualmente, con ifix, AIX lee el tiempo de espera de transición ANA desde el controlador Identify, pero lo sujeta efectivamente a 60sec si está por encima de ese límite. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541386["1541386"^] | NVMe/FC de AIX detecta EIO después de la caducidad de ANATT | En cualquier evento de conmutación al nodo de respaldo de almacenamiento (SFO), si la transición ANA(acceso asimétrico al espacio de nombres) supera el límite de tiempo de espera de transición de ANA en una ruta determinada, el host NVMe/FC de AIX produce un error de I/O a pesar de tener rutas alternativas disponibles en buen estado para el espacio de nombres. 


| link:https://mysupport.netapp.com/site/bugs-online/product/HOSTUTILITIES/BURT/1541380["1541380"^] | AIX NVMe/FC espera a que el ANATT medio/completo caduque antes de reanudar las operaciones de I/O después de ANA AEN | NVMe/FC de IBM AIX no admite algunas notificaciones asíncronas (AENs) que publica ONTAP. Este manejo de ANA no óptimo dará como resultado un rendimiento subóptimo durante las operaciones de SFO. 
|===


== Paso 5: Solucionar problemas

Antes de solucionar cualquier falla de NVMe/FC, verifique que esté ejecutando una configuración que cumpla con laslink:https://mysupport.netapp.com/matrix/["IMT"^] presupuesto.  Si continúa teniendo problemas, comuníquese conlink:https://mysupport.netapp.com["Soporte de NetApp"^] .
