---
sidebar: sidebar 
permalink: nvme_windows_2016.html 
keywords: nvme, windows, enterprise 
summary: 'Es posible configurar NVMe over Fibre Channel (NVMe/FC) en hosts que ejecutan Windows Server 2016 para operar con LUN de ONTAP.' 
---
= Configure Windows Server 2016 con NVMe/FC para ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es posible configurar NVMe over Fibre Channel (NVMe/FC) en hosts que ejecutan Windows Server 2016 para operar con LUN de ONTAP.

.Acerca de esta tarea
Es posible usar el siguiente soporte con la configuración de host de NVMe/FC para Windows 2016. También debe revisar las limitaciones conocidas antes de iniciar el proceso de configuración.


NOTE: Puede utilizar los ajustes de configuración proporcionados en este procedimiento para configurar los clientes de nube conectados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^]

* Soporte disponible:
+
A partir de ONTAP 9,7, se admite NVMe/FC para Windows Server 2016.

+
Si desea obtener una lista de los adaptadores y controladoras de FC compatibles, consulte la link:https://hwu.netapp.com/Home/Index["Hardware Universe"^]. Para obtener la lista actual de configuraciones y versiones compatibles, consulte la link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad"^].

* Limitaciones conocidas:
+
El clúster de conmutación al nodo de respaldo de Windows no es compatible con NVMe/FC, ya que ONTAP no admite reservas persistentes con NVMe/FC.

+

NOTE: Broadcom incluye un controlador externo para Windows NVMe/FC que es un controlador SCSI ⇄ NVMe traslacional y no un verdadero controlador NVMe/FC. La sobrecarga de transacción no afecta necesariamente al rendimiento, pero anula las ventajas en cuanto al rendimiento de NVMe/FC. Como resultado, el rendimiento de NVMe/FC y FCP es el mismo en los servidores Windows, a diferencia de otros sistemas operativos como Linux, donde el rendimiento de NVMe/FC es significativamente mejor que el de FCP.





== Habilite NVMe/FC

Habilite FC/NVMe en el host iniciador de Windows.

.Pasos
. Instale la utilidad Emulex HBA Manager en el host de Windows.
. En cada puerto de iniciador del HBA, establezca los siguientes parámetros del controlador del HBA:
+
** EnableNVMe = 1
** NVMEMode = 0


. Reinicie el host.




== Configure el adaptador de FC Broadcom

El iniciador de Broadcom puede ofrecer tráfico NVMe/FC y FCP a través de los mismos puertos adaptadores de FC de 32G Gb. Para FCP y FC/NVMe, debe usar el módulo específico del dispositivo (DSM) Microsft como la opción Microsoft Multipath I/O (MPIO).

A `+hostnqn+` se asocia con cada puerto de adaptador de bus de host (HBA) para el adaptador Broadcom con FC/NVMe en un entorno Windows. El tiene el formato del `+hostnqn+` que se muestra en el siguiente ejemplo:

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Habilite MPIO para dispositivos NVMe

Debe habilitar MPIO para los dispositivos NVMe para completar la configuración de NVMe en el host de Windows.

.Pasos
. Instale link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Kit de utilidades de host de Windows 7.1"] Para configurar los parámetros de controlador que son comunes a FC y NVMe.
. Abra las propiedades de MPIO.
. En la pestaña *Discover Multi-paths*, agregue el identificador de dispositivo indicado para NVMe.
+
MPIO detecta los dispositivos NVMe, que se ven bajo la gestión de discos.

. Abra *Administración de discos* y vaya a *Propiedades de disco*.
. En la pestaña *MPIO*, selecciona *Details*.
. Establezca los siguientes ajustes de Microsoft DSM:
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled: *Habilitar*
** Número de retryCount: *6*
** RetryInterval: *1*
** PDORemovedPeriod: *130*


. Seleccione la directiva MPIO *Round Robin with Subset*.
. Cambie los valores del Registro:
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Reinicie el host.




== Valide NVMe/FC

Compruebe que los subsistemas de NVMe se hayan detectado y que los espacios de nombres de ONTAP sean los correctos para la configuración de NVMe-oF.

.Pasos
. Compruebe que el tipo de puerto es `+FC+NVMe+`:
+
`listhba`

+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
*Port Type*      : *FC+NVMe*
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
====
. Compruebe que se han detectado los subsistemas NVMe/FC:
+
** `+nvme-list+`
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
====
** `nvme-list`
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
====


. Verifique que se han creado los espacios de nombres:
+
`+nvme-list-ns+`

+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----
====

