---
sidebar: sidebar 
permalink: nvme_windows_2019.html 
keywords: nvme, windows, enterprise 
summary: Configuración de host NVMe/FC para Windows Server 2019 con ONTAP 
---
= Configuración de host NVMe/FC para Windows Server 2019 con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Es posible configurar NVMe over Fibre Channel (NVMe/FC) en hosts que ejecutan Windows Server 2019 y ONTAP como destino.

NVMe/FC es compatible con ONTAP 9.7 o posterior para Windows Server 2019.

Tenga en cuenta que el iniciador de Broadcom puede servir tráfico NVMe/FC y FCP a través de los mismos puertos de adaptador de FC de 32 GB. En el caso de FCP y FC/NVMe, utilice MSDSM como opción de I/o multivía de Microsoft (MPIO).

Consulte link:https://hwu.netapp.com/Home/Index["Hardware Universe"^] Para obtener una lista de controladoras y adaptadores de FC admitidos. Para obtener la lista más actual de las configuraciones y versiones compatibles, consulte link:https://mysupport.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^].


NOTE: Puede utilizar los ajustes de configuración que se proporcionan en este documento para configurar los clientes de cloud conectados a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^].



== Limitaciones conocidas

El clúster de conmutación por error de Windows (WFC) no es compatible con NVMe/FC de ONTAP porque ONTAP no admite actualmente las reservas persistentes con NVMe/FC.


NOTE: El controlador externo que Broadcom para Windows NVMe/FC no es un controlador NVMe/FC real sino un controlador SCSI ⇄ NVMe traslacional. Esta sobrecarga traslacional no necesariamente afecta al rendimiento, pero reduce las ventajas en términos de rendimiento de NVMe/FC. Por tanto, en los servidores Windows, el rendimiento de NVMe/FC y FCP es el mismo, a diferencia de otros sistemas operativos como Linux, en los que el rendimiento de NVMe/FC es significativamente mejor que el de FCP.



== Habilite NVMe/FC en un host del iniciador de Windows

Siga estos pasos para habilitar FC/NVMe en el host del iniciador de Windows:

.Pasos
. Instale la utilidad OneCommand Manager en el host de Windows.
. En cada puerto de iniciador del HBA, establezca los siguientes parámetros del controlador del HBA:
+
** EnableNVMe = 1
** NVMEMode = 0
** LimTransferSize=1


. Reinicie el host.




== Configure el adaptador de FC de Broadcom en Windows para NVMe/FC

Con el adaptador de Broadcom para FC/NVMe en un entorno Windows, una `+hostnqn+` Se asocia con cada puerto del adaptador de bus de host (HBA). La `+hostnqn+` tiene el formato siguiente.

....
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9765
nqn.2017-01.com.broadcom:ecd:nvmf:fc:100000109b1b9766
....


=== Habilite MPIO para dispositivos NVMe en el host de Windows

. Instale link:link:https://docs.netapp.com/us-en/ontap-sanhost/hu_wuhu_71.html["Kit de utilidades de host de Windows 7.1"] Para configurar los parámetros de controlador que son comunes a FC y NVMe.
. Abra las propiedades de MPIO.
. En la pestaña *Discover Multi-paths*, agregue el identificador de dispositivo indicado para NVMe.
+
MPIO detecta los dispositivos NVMe, que se ven bajo la gestión de discos.

. Abra *Administración de discos* y vaya a *Propiedades de disco*.
. En la ficha *MPIO*, haga clic en *Detalles*.
. Establezca los siguientes valores de MSDSM:
+
** PathVerifiedPeriod: *10*
** PathVerifyEnabled: *Habilitar*
** Número de retryCount: *6*
** RetryInterval: *1*
** PDORemovedPeriod: *130*


. Seleccione la directiva MPIO *Round Robin with Subset*.
. Cambie los valores del Registro:
+
[listing]
----
HKLM\SYSTEM\CurrentControlSet\Services\mpio\Parameters\PathRecoveryInterval DWORD -> 30

HKLM\SYSTEM\CurrentControlSet\Services\mpio \Parameters\ UseCustomPathRecoveryInterval  DWORD-> 1
----
. Reinicie el host.
+
La configuración de NVMe ahora se completa en el host Windows.





== Valide NVMe/FC

. Valide que el tipo de puerto es FC+NVMe.
+
Ahora que NVMe está habilitado, debe ver el `+Port Type+` aparece como `+FC+NVMe+`, como se indica a continuación.

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd listhba

Manageable HBA List

Port WWN       : 10:00:00:10:9b:1b:97:65
Node WWN       : 20:00:00:10:9b:1b:97:65
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 0
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 0
Port Type      : FC+NVMe
Model          : LPe32002-M2

Port WWN       : 10:00:00:10:9b:1b:97:66
Node WWN       : 20:00:00:10:9b:1b:97:66
Fabric Name    : 10:00:c4:f5:7c:a5:32:e0
Flags          : 8000e300
Host Name      : INTEROP-57-159
Mfg            : Emulex Corporation
Serial No.     : FC71367217
Port Number    : 1
Mode           : Initiator
PCI Bus Number : 94
PCI Function   : 1
Port Type      : FC+NVMe
Model          : LPe32002-M2
----
. Validar que se han detectado subsistemas NVMe/FC.
+
La `+nvme-list+` El comando muestra los subsistemas NVMe/FC detectados.

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd nvme-list 10:00:00:10:9b:1b:97:65

Discovered NVMe Subsystems for 10:00:00:10:9b:1b:97:65

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:09:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0180
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:06:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0181
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available
Note: At present Namespace Management is not supported by NetApp Arrays.
----
+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\hbacmd nvme-list 10:00:00:10:9b:1b:97:66

Discovered NVMe Subsystems for 10:00:00:10:9b:1b:97:66

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:07:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0140
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

NVMe Qualified Name     :  nqn.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159
Port WWN                :  20:08:d0:39:ea:14:11:04
Node WWN                :  20:05:d0:39:ea:14:11:04
Controller ID           :  0x0141
Model Number            :  NetApp ONTAP Controller
Serial Number           :  81CGZBPU5T/uAAAAAAAB
Firmware Version        :  FFFFFFFF
Total Capacity          :  Not Available
Unallocated Capacity    :  Not Available

Note: At present Namespace Management is not supported by NetApp Arrays.
----
. Validar que se han creado espacios de nombres.
+
La `+nvme-list-ns+` Comando enumera los espacios de nombres para un destino NVMe especificado que enumera los espacios de nombres conectados al host.

+
[listing]
----
PS C:\Program Files\Emulex\Util\OCManager> .\HbaCmd.exe nvme-list-ns 10:00:00:10:9b:1b:97:66 20:08:d0:39:ea:14:11:04 nq
.1992-08.com.netapp:sn.a3b74c32db2911eab229d039ea141105:subsystem.win_nvme_interop-57-159 0


Active Namespaces (attached to controller 0x0141):

                                       SCSI           SCSI           SCSI
   NSID           DeviceName        Bus Number    Target Number     OS LUN
-----------  --------------------  ------------  ---------------   ---------
0x00000001   \\.\PHYSICALDRIVE9         0               1              0
0x00000002   \\.\PHYSICALDRIVE10        0               1              1
0x00000003   \\.\PHYSICALDRIVE11        0               1              2
0x00000004   \\.\PHYSICALDRIVE12        0               1              3
0x00000005   \\.\PHYSICALDRIVE13        0               1              4
0x00000006   \\.\PHYSICALDRIVE14        0               1              5
0x00000007   \\.\PHYSICALDRIVE15        0               1              6
0x00000008   \\.\PHYSICALDRIVE16        0               1              7

----

