---
sidebar: sidebar 
permalink: nvme-rhel-82.html 
keywords: nvme, linux, rhel, red hat, enterprise 
summary: Cómo configurar el host NVMe/FC para RHEL 8.2 con ONTAP 
---
= Configurar RHEL 8.2 para NVMe-oF con almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Los hosts Red Hat Enterprise Linux (RHEL) admiten los protocolos NVMe sobre canal de fibra (NVMe/FC) y NVMe sobre TCP (NVMe/TCP) con acceso asimétrico al espacio de nombres (ANA).  ANA proporciona una funcionalidad de múltiples rutas equivalente al acceso a unidad lógica asimétrica (ALUA) en entornos iSCSI y FCP.

Aprenda a configurar hosts NVMe over Fabrics (NVMe-oF) para RHEL 8.2.  Para obtener más información sobre soporte y funciones, consultelink:hu-nvme-index.html["Descripción general de NVME-oF"^] .

*NVMe-oF con RHEL 8.2 tiene las siguientes limitaciones conocidas:*

* Actualmente no se admite el arranque SAN mediante el protocolo NVMe-oF.
* La multiruta NVMe dentro del kernel está deshabilitada de manera predeterminada en los hosts NVMe-oF en RHEL 8.2; debe habilitarla manualmente.




== Paso 1: Opcionalmente, habilite el arranque SAN

Puede configurar su host para utilizar el arranque SAN para simplificar la implementación y mejorar la escalabilidad. Utilice ellink:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que su sistema operativo Linux, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admitan el arranque SAN.

.Pasos
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Cree un espacio de nombres NVMe y asígnelo al host"^] .
. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que está asignado el espacio de nombres de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host y verifique que el sistema operativo esté funcionando.




== Paso 2: Verifique la versión del software y la configuración de NVMe

Verifique que su sistema cumpla con los requisitos de software y verifique las instalaciones de paquetes NVMe y la configuración del host.

.Pasos
. Instalar RHEL 8.2 en el servidor.  Una vez completada la instalación, verifique que esté ejecutando el kernel RHEL 8.2 requerido:
+
[source, cli]
----
uname -r
----
+
Ejemplo de versión del kernel RHEL:

+
[listing]
----
4.18.0-193.el8.x86_64
----
. Instale el paquete nvme-cli:
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
El siguiente ejemplo muestra una versión del paquete nvme-cli:

+
[listing]
----
nvme-cli-1.9.5.el8.x86_64
----
. Habilitar multivía en el kernel NVMe:
+
[source, cli]
----
grubby –args=nvme_core.multipath=Y –update-kernel /boot/vmlinuz-4.18.0-193.el8.x86_64
----
. En el host RHEL 8.2, verifique la cadena NQN del host en `/etc/nvme/hostnqn` :
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
El siguiente ejemplo muestra una cadena hostnqn:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
. En el host RHEL 8.2, verifique la cadena hostnqn en `/etc/nvme/hostnqn` :
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_fcnvme_141
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
Vserver      Subsystem        Host           NQN
----------- --------------- ----------- ---------------
vs_fcnvme_141   nvme_141_1      nqn.2014-08.org.nvmexpress:uuid:9ed5b327-b9fc-4cf5-97b3-1b5d986345d1
----
====
+

NOTE: Si las cadenas NQN del host no coinciden, utilice el `vserver modify` Comando para actualizar la cadena NQN del host en el subsistema de matriz ONTAP correspondiente para que coincida con la cadena NQN del host `/etc/nvme/hostnqn` en el host.

. Reinicie el host.
. Si lo desea, actualice el `enable_foreign` ajuste.
+
[NOTE]
====
Para ejecutar tráfico NVMe y SCSI en el mismo host, NetApp recomienda utilizar la ruta múltiple NVMe en el kernel para espacios de nombres ONTAP y dm-multipath para LUN ONTAP .  Para evitar que dm-multipath reclame dispositivos de espacio de nombres ONTAP , exclúyalos agregando el `enable_foreign` Ajuste a la `/etc/multipath.conf` archivo:

[source, cli]
----
cat /etc/multipath.conf
defaults {
        enable_foreign     NONE
}
----
====
. Reinicie el daemon multipathd ejecutando un `systemctl restart multipathd`.




== Paso 3: Configurar NVMe/FC para Broadcom/Emulex

Puede configurar NVMe/FC para Broadcom/Emulex.

.Pasos
. Compruebe que está utilizando el modelo de adaptador admitido:
+
.. Mostrar los nombres de los modelos:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Debe ver la siguiente salida:

+
[listing]
----
LPe32002-M2
LPe32002-M2
----
.. Mostrar las descripciones del modelo:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Debería ver un resultado similar a este:

+
[listing]
----
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
Emulex LightPulse LPe32002-M2 2-Port 32Gb Fibre Channel Adapter
----


. Compruebe que la salida esperada de `lpfc_enable_fc4_type` está definida en `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Verifique que los puertos iniciadores estén en funcionamiento y puedan ver los LIF de destino:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
Debería ver un resultado similar a este:

+
[listing]
----
0x100000109b1c1204
0x100000109b1c1205
----
. Compruebe que los puertos de iniciador estén en línea:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Debe ver la siguiente salida:

+
[listing]
----
Online
Online
----
. Compruebe que los puertos de iniciador NVMe/FC estén habilitados y que los puertos de destino estén visibles:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000109b1c1204 WWNN x200000109b1c1204 DID x011d00 *ONLINE*
NVME RPORT WWPN x203800a098dfdd91 WWNN x203700a098dfdd91 DID x010c07 *TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x203900a098dfdd91 WWNN x203700a098dfdd91 DID x011507 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000f78 Cmpl 0000000f78 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002fe29bba Issue 000000002fe29bc4 OutIO 000000000000000a
abort 00001bc7 noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001e15 Err 0000d906

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000109b1c1205 WWNN x200000109b1c1205 DID x011900 *ONLINE*
NVME RPORT WWPN x203d00a098dfdd91 WWNN x203700a098dfdd91 DID x010007 *TARGET DISCSRVC ONLINE*
NVME RPORT WWPN x203a00a098dfdd91 WWNN x203700a098dfdd91 DID x012a07 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000fa8 Cmpl 0000000fa8 Abort 00000000
LS XMIT: Err 00000000 CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000002e14f170 Issue 000000002e14f17a OutIO 000000000000000a
abort 000016bb noxri 00000000 nondlp 00000000 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 00001f50 Err 0000d9f8
----
====




== Paso 4: Opcionalmente, habilite 1 MB de E/S para NVMe/FC

ONTAP informa un tamaño máximo de transferencia de datos (MDTS) de 8 en los datos del controlador de identificación.  Esto significa que el tamaño máximo de solicitud de E/S puede ser de hasta 1 MB.  Para emitir solicitudes de E/S de tamaño 1 MB para un host Broadcom NVMe/FC, debe aumentar el `lpfc` valor de la `lpfc_sg_seg_cnt` parámetro a 256 desde el valor predeterminado de 64.


NOTE: Estos pasos no se aplican a los hosts Qlogic NVMe/FC.

.Pasos
. Defina el `lpfc_sg_seg_cnt` parámetro en 256:
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Ejecute `dracut -f` el comando y reinicie el host.
. Compruebe que el valor de `lpfc_sg_seg_cnt` es 256:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Paso 5: Validar NVMe-oF

Verifique que el estado de multivía de NVMe en kernel, el estado de ANA y los espacios de nombres de ONTAP sean correctos para la configuración de NVMe-oF.

.Pasos
. Compruebe que la multivía NVMe en kernel esté habilitada:
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Debe ver la siguiente salida:

+
[listing]
----
Y
----
. Compruebe que la configuración NVMe-oF adecuada (como, por ejemplo, el modelo configurado en la controladora NetApp ONTAP y la política de balanceo de carga establecida en round-robin) en los respectivos espacios de nombres de ONTAP se reflejen correctamente en el host:
+
.. Mostrar los subsistemas:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Debe ver la siguiente salida:

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Mostrar la política:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Debe ver la siguiente salida:

+
[listing]
----
round-robin
round-robin
----


. Verifique que los espacios de nombres se hayan creado y detectado correctamente en el host:
+
[source, cli]
----
nvme list
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
Node         SN                   Model
---------------------------------------------------------
/dev/nvme4n1 81Ix2BVuekWcAAAAAAAB	NetApp ONTAP Controller


Namespace Usage    Format             FW             Rev
-----------------------------------------------------------
1                 21.47 GB / 21.47 GB	4 KiB + 0 B   FFFFFFFF
----
====
. Compruebe que el estado de la controladora de cada ruta sea activo y que tenga el estado de ANA correcto:
+
[source, cli]
----
nvme list-subsys /dev/nvme0n1
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
Nvme-subsysf0 – NQN=nqn.1992-08.com.netapp:sn.341541339b9511e8a9b500a098c80f09:subsystem.rhel_141_nvme_ss_10_0
\
+- nvme0 fc traddr=nn-0x202c00a098c80f09:pn-0x202d00a098c80f09 host_traddr=nn-0x20000090fae0ec61:pn-0x10000090fae0ec61 *live optimized*
+- nvme1 fc traddr=nn-0x207300a098dfdd91:pn-0x207600a098dfdd91 host_traddr=nn-0x200000109b1c1204:pn-0x100000109b1c1204 *live inaccessible*
+- nvme2 fc traddr=nn-0x207300a098dfdd91:pn-0x207500a098dfdd91 host_traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 *live optimized*
+- nvme3 fc traddr=nn-0x207300a098dfdd91:pn-0x207700a098dfdd91 host traddr=nn-0x200000109b1c1205:pn-0x100000109b1c1205 *live inaccessible*
----
====
. Confirmar que el complemento de NetApp muestra los valores correctos para cada dispositivo de espacio de nombres ONTAP:
+
[role="tabbed-block"]
====
.Columna
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device   Vserver  Namespace Path             NSID   UUID   Size
-------  -------- -------------------------  ------ ----- -----
/dev/nvme0n1   vs_nvme_10       /vol/rhel_141_vol_10_0/rhel_141_ns_10_0    1        55baf453-f629-4a18-9364-b6aee3f50dad   53.69GB
----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
   "ONTAPdevices" : [
   {
        Device" : "/dev/nvme0n1",
        "Vserver" : "vs_nvme_10",
        "Namespace_Path" : "/vol/rhel_141_vol_10_0/rhel_141_ns_10_0",
         "NSID" : 1,
         "UUID" : "55baf453-f629-4a18-9364-b6aee3f50dad",
         "Size" : "53.69GB",
         "LBA_Data_Size" : 4096,
         "Namespace_Size" : 13107200
    }
]
----
=====
--
====




== Paso 6: Revise los problemas conocidos

No hay problemas conocidos.
