---
sidebar: sidebar 
permalink: nvme_aix.html 
keywords: nvme, linux, rhel, red hat, enterprise, aix, ontap 
summary: Cómo configurar el host NVMe/FC para AIX con ONTAP 
---
= Configuración de host NVMe/FC para AIX con ONTAP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Puede habilitar NVMe/FC en hosts IBM AIX y VIOS/PowerVM utilizando almacenamiento ONTAP como destino. Si quiere más información sobre las configuraciones compatibles, consulte link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].

La siguiente compatibilidad está disponible para la configuración de host de NVMe/FC para un host AIX con ONTAP:

* A partir de ONTAP 9.13.1, se añade compatibilidad con NVMe over Fibre Channel (NVMe/FC) para las versiones IBM AIX 7,2 TL5 SP6, AIX 7,3 TL1 SP2 y VIOS 3.1.4.21 con soporte de arranque SAN para pilas físicas y virtuales. Consulte la documentación de IBM para obtener más información sobre la configuración del soporte de arranque SAN.
* NVMe/FC solo es compatible con los servidores Power9 y Power10 IBM.
* No se requiere ningún PCM (módulo de control de ruta) separado, como la compatibilidad con HUK para AIX, SCSI MPIO, para los dispositivos NVMe.
* Se incluye la compatibilidad con la virtualización de NetApp (VIOS/PowerVM) con VIOS 3,1.4,21. Se admite _ONLY_ a través del modo de virtualización del almacenamiento NPIV (virtualización N_portID) utilizando el servidor IBM Power10.


.Lo que necesitará
* Compruebe que tiene 32GB adaptadores FC Emulex (EN1A, EN1B, EN1L, EN1M) o adaptadores FC de 64GB Gb (EN1N, EN1P) con firmware del adaptador 12.4.257.30 y versiones posteriores.
* Si tiene una configuración de MetroCluster, NetApp recomienda cambiar el tiempo de APD (All Path Down) predeterminado de NVMe/FC de AIX para admitir eventos de conmutación de sitios no planificados de MetroCluster y evitar que el sistema operativo AIX aplique un tiempo de espera de I/O más corto. Para obtener más información y los cambios recomendados en la configuración predeterminada, consulte el informe público 1553249.
* De manera predeterminada, el valor ANATT para el SO host AIX es 30 segundos. IBM proporciona una solución provisional (ifix) que limita el valor ANATT a 60 segundos; debe instalar un ifix desde el sitio web de IBM para asegurarse de que todos los flujos de trabajo de ONTAP no sean disruptivos.
+

NOTE: Para la compatibilidad con NVMe/FC AIX, necesita instalar un ifix en las versiones GA del sistema operativo AIX. Esto no es necesario para el sistema operativo VIOS/PowerVM.

+
Los detalles de ifix son los siguientes:

+
** Para AIX nivel 72-TL5-SP6-2320, instale el `IJ46710s6a.230509.epkg.Z` paquete.
** Para AIX nivel 73-TL1-SP2-2320, instale el `IJ46711s2a.230509.epkg.Z` paquete.
+
Para obtener más información sobre la gestión de ifixes, consulte link:http://www-01.ibm.com/support/docview.wss?uid=isg3T1012104["Gestión de correcciones provisionales en AIX"^].

+

NOTE: Debe instalar los ifixes en una versión de AIX sin ifixes previamente instalados relacionados con `devices.pciex.pciexclass.010802.rte` en el sistema. Si estos ifixes están presentes, entrarán en conflicto con la nueva instalación.

+
En la siguiente tabla se muestran los HBA asignados a la pila AIX LPAR (partición lógica AIX) o física/nativa en modo no virtualizado:

+
[cols="10,10,10,10,10"]
|===
| SO del host | Arco de potencia | Versión FW de alimentación | Modo | Comentarios 


.2+| AIX 7,2 TL5 SP6 | Power9 | FW 950 o posterior | Pila física | ifix disponible a través de TS012877410. 


| Power10 | FW 1010 o posterior | Pila física | Es compatible con arranque SAN. ifix disponible a través de TS012877410. 


.2+| AIX 7,3 TL1 SP2 | Power9 | FW 950 o posterior | Pila física | ifix disponible a través de TS012877410. 


| Power10 | FW 1010 o posterior | Pila física y virtual | ifix disponible a través de TS012877410. 
|===
+
En la siguiente tabla se muestran los HBA asignados a VIOS con compatibilidad con NPIV en modo virtualizado:

+
[cols="10,10,10,10,10"]
|===
| SO del host | Arco de potencia | Versión FW de alimentación | Modo | Comentarios 


| VIOS/PowerVM 3.1.4.21 | Power10 | FW 1010 o posterior | Pila virtual | El soporte comienza desde AIX 7,3 TL1 SP2 para VIOCc 
|===






== Limitaciones conocidas

La configuración de host de NVMe/FC para AIX con ONTAP tiene las siguientes limitaciones conocidas:

* Los HBA FC de QLogic/Marvel 32G en un host AIX no admiten NVMe/FC.
* No se admite el arranque SAN para dispositivos NVMe/FC que utilizan el servidor IBM de Power9.




== Accesos múltiples

IBM MPIO (Multi Path I/O), utilizado para la multivía NVMe, se proporciona de forma predeterminada cuando se instala el sistema operativo AIX .

Puede utilizar el para comprobar que la multivía de NVMe está habilitada para un host AIX `lsmpio` comando:

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Ejemplo de salida*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8         Enabled  Sel,Opt       nvme12  fcnvme0, 9
hdisk1  9         Enabled  Sel,Non       nvme65  fcnvme1, 9
hdisk1  10        Enabled  Sel,Opt       nvme37  fcnvme1, 9
hdisk1  11        Enabled  Sel,Non       nvme60  fcnvme0, 9
----


== Configure NVMe/FC

Es posible usar el siguiente procedimiento para configurar NVMe/FC para adaptadores Broadcom/Emulex.

.Pasos
. Compruebe que está utilizando el adaptador compatible. Para obtener la lista más actual de adaptadores compatibles, consulte link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad de NetApp"^].
. De forma predeterminada, la compatibilidad con el protocolo NVMe/FC está habilitada en el FC físico; sin embargo, la compatibilidad con el protocolo NVMe/FC está deshabilitada en Virtual Fibre Channel (VFC) en Virtual I/O Server (VIOS). Recupere una lista de los adaptadores donde se deshabilita la compatibilidad con NVMe/FC:
+
[listing]
----
$ lsmap -all -npiv
----
+
*Ejemplo de salida*

+
[listing]
----
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost0      U9105.22A.785DB61-V2-C2                 4 s1022-iop-mcc- AIX
Status:LOGGED_IN
FC name:fcs4                    FC loc code:U78DA.ND0.WZS01UY-P0-C7-T0
Ports logged in:3
Flags:0xea<LOGGED_IN,STRIP_MERGE,SCSI_CLIENT,NVME_CLIENT>
VFC client name:fcs0            VFC client DRC:U9105.22A.785DB61-V4-C2
Name          Physloc                            ClntID ClntName       ClntOS
------------- ---------------------------------- ------ -------------- -------
vfchost1      U9105.22A.785DB61-V2-C3                 4
Status:NOT_LOGGED_IN
FC name:                        FC loc code:
Ports logged in:0
Flags:0x81<NOT_MAPPED,NOT_CONNECTED>
VFC client name:                VFC client DRC:
----
. Habilite la compatibilidad con el protocolo NVMe/FC en un adaptador ejecutando el `ioscli vfcctrl` Comando en el VIOS:
+
[listing]
----
$  vfcctrl -enable -protocol nvme -vadapter vfchost0
----
+
*Ejemplo de salida*

+
[listing]
----
The "nvme" protocol for "vfchost0" is enabled.
----
. Compruebe que el soporte se ha activado en el adaptador:
+
[listing]
----
# lsattr -El vfchost0
----
+
*Ejemplo de salida*

+
[listing]
----
alt_site_wwpn       WWPN to use - Only set after migration   False
current_wwpn  0     WWPN to use - Only set after migration   False
enable_nvme   yes   Enable or disable NVME protocol for NPIV True
label               User defined label                       True
limit_intr    false Limit NPIV Interrupt Sources             True
map_port      fcs4  Physical FC Port                         False
num_per_nvme  0     Number of NPIV NVME queues per range     True
num_per_range 0     Number of NPIV SCSI queues per range     True
----
. Habilitar el protocolo NVMe/FC para todos los adaptadores actuales o los adaptadores seleccionados:
+
.. Habilite el protocolo NVMe/FC para todos los adaptadores:
+
... Cambie el `dflt_enabl_nvme` valor de atributo de `viosnpiv0` pseudo dispositivo a. `yes`.
... Ajuste la `enable_nvme` valor de atributo a. `yes` Para todos los dispositivos host VFC.
+
[listing]
----
# chdev -l viosnpiv0 -a dflt_enabl_nvme=yes
----
+
[listing]
----
# lsattr -El viosnpiv0
----
+
*Ejemplo de salida*

+
[listing]
----
bufs_per_cmd    10  NPIV Number of local bufs per cmd                    True
dflt_enabl_nvme yes Default NVME Protocol setting for a new NPIV adapter True
num_local_cmds  5   NPIV Number of local cmds per channel                True
num_per_nvme    8   NPIV Number of NVME queues per range                 True
num_per_range   8   NPIV Number of SCSI queues per range                 True
secure_va_info  no  NPIV Secure Virtual Adapter Information              True
----


.. Habilite el protocolo NVMe/FC para los adaptadores seleccionados cambiando el `enable_nvme` Valor del atributo de dispositivo host de VFC a. `yes`.


. Compruebe que `FC-NVMe Protocol Device` se ha creado en el servidor:
+
[listing]
----
# [root@aix_server /]: lsdev |grep fcnvme
----
+
* Exmaple salida *

+
[listing]
----
fcnvme0       Available 00-00-02    FC-NVMe Protocol Device
fcnvme1       Available 00-01-02    FC-NVMe Protocol Device
----
. Registre el NQN del host desde el servidor:
+
[listing]
----
# [root@aix_server /]: lsattr -El fcnvme0
----
+
*Ejemplo de salida*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
[listing]
----
[root@aix_server /]: lsattr -El fcnvme1
----
+
*Ejemplo de salida*

+
[listing]
----
attach     switch                                                               How this adapter is connected  False
autoconfig available                                                            Configuration State            True
host_nqn   nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8 Host NQN (NVMe Qualified Name) True
----
+
.. Visualice el UUID de partición:
+
[listing]
----
[root@aix_server /]: lsattr -El sys0 -a partition_uuid
----
+
*Ejemplo de salida*

+
[listing]
----
partition_uuid 64e039bd-27d2-421c-858d-8a378dec31e8 Partition UUID False
----


. Compruebe el NQN del host y compruebe que coincide con la cadena NQN del host correspondiente al subsistema correspondiente en la cabina de ONTAP:
+
[listing]
----
::> vserver nvme subsystem host show -vserver vs_s922-55-lpar2
----
+
*Ejemplo de salida*

+
[listing]
----
Vserver         Subsystem                Host NQN
------- --------- ----------------------------------------------------------
vs_s922-55-lpar2 subsystem_s922-55-lpar2 nqn.2014-08.org.nvmexpress:uuid:64e039bd-27d2-421c-858d-8a378dec31e8
----
. Compruebe que los puertos del iniciador están en funcionamiento y puede ver los LIF de destino.




== Valide NVMe/FC

Es necesario verificar que los espacios de nombres de las ONTAP se reflejen correctamente en el host. Ejecute el siguiente comando para hacerlo:

[listing]
----
# [root@aix_server /]: lsdev -Cc disk |grep NVMe
----
*Ejemplo de salida*

[listing]
----
hdisk1  Available 00-00-02 NVMe 4K Disk
----
Puede comprobar el estado de la multivía:

[listing]
----
#[root@aix_server /]: lsmpio -l hdisk1
----
*Ejemplo de salida*

[listing]
----
name     path_id  status   path_status  parent  connection
hdisk1  8        Enabled  Sel,Opt      nvme12  fcnvme0, 9
hdisk1  9        Enabled  Sel,Non      nvme65  fcnvme1, 9
hdisk1  10       Enabled  Sel,Opt      nvme37  fcnvme1, 9
hdisk1  11       Enabled  Sel,Non      nvme60  fcnvme0, 9
----


== Problemas conocidos

La configuración de host de NVMe/FC para AIX con ONTAP tiene los siguientes problemas conocidos:

[cols="10,30,30"]
|===
| ID de Burt | Título | Descripción 


| 1553249 | Tiempo de APD predeterminado de NVMe/FC de AIX que se modificará para admitir eventos de conmutación de sitios no planificados de MCC | De manera predeterminada, los sistemas operativos AIX utilizan un valor de tiempo de espera APD (all path down) de 20 segundos para NVMe/FC.  Sin embargo, los flujos de trabajo de conmutación por error automática no planificada (AUSO) de ONTAP MetroCluster y los flujos de trabajo de conmutación iniciados por tiebreaker pueden tardar un poco más que la ventana de tiempo de espera APD, lo cual produce errores de I/O. 


| 1546017 | NVMe/FC de AIX limita ANATT a 60s, en lugar de 120s, como anuncia ONTAP | ONTAP anuncia el tiempo de espera de transición de ANA (acceso asimétrico al espacio de nombres) en la identificación de la controladora en 120sec. Actualmente, con ifix, AIX lee el tiempo de espera de transición ANA desde el controlador Identify, pero lo sujeta efectivamente a 60sec si está por encima de ese límite. 


| 1541386 | NVMe/FC de AIX detecta EIO después de la caducidad de ANATT | En cualquier evento de conmutación al nodo de respaldo de almacenamiento (SFO), si la transición ANA(acceso asimétrico al espacio de nombres) supera el límite de tiempo de espera de transición de ANA en una ruta determinada, el host NVMe/FC de AIX produce un error de I/O a pesar de tener rutas alternativas disponibles en buen estado para el espacio de nombres. 


| 1541380 | AIX NVMe/FC espera a que el ANATT medio/completo caduque antes de reanudar las operaciones de I/O después de ANA AEN | NVMe/FC de IBM AIX no admite algunas notificaciones asíncronas (AENs) que publica ONTAP. Este manejo de ANA no óptimo dará como resultado un rendimiento subóptimo durante las operaciones de SFO. 
|===


== Resolución de problemas

Antes de solucionar problemas con cualquier fallo de NVMe/FC, compruebe que esté ejecutando una configuración que cumpla con las especificaciones de IMT y continúe con los siguientes pasos para depurar cualquier problema en el host.



=== Active el registro detallado

Si tiene algún problema con la configuración, el registro detallado puede proporcionar información esencial para la solución de problemas.

.Pasos
El procedimiento para establecer el registro detallado para Qlogic (qla2xxx) es diferente del procedimiento para establecer el registro verbose LPFC.

[role="tabbed-block"]
====
.LPFC
--
.Pasos
. Ajuste la `lpfc_log_verbose` Configuración del controlador en cualquiera de los siguientes valores para registrar los eventos de NVMe/FC.
+
[listing]
----
#define LOG_NVME 0x00100000 /* NVME general events. */
#define LOG_NVME_DISC 0x00200000 /* NVME Discovery/Connect events. */
#define LOG_NVME_ABTS 0x00400000 /* NVME ABTS events. */
#define LOG_NVME_IOERR 0x00800000 /* NVME IO Error events. */
----
. Después de ajustar los valores, ejecute la `dracut-f` command y reinicie el host.
. Compruebe la configuración.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_log_verbose=0xf00083

# cat /sys/module/lpfc/parameters/lpfc_log_verbose
15728771
----


--
.qla2xxx
--
No hay ningún registro qla2xxx específico similar para NVMe/FC que para el `lpfc` controlador. Por lo tanto, puede establecer el nivel de registro general qla2xxx mediante los pasos siguientes:

.Pasos
. Añada el `ql2xextended_error_logging=0x1e400000` valor para el correspondiente `modprobe qla2xxx conf` archivo.
. Vuelva a crear el `initramfs` ejecutando `dracut -f` reinicie el host.
. Después de reiniciar, compruebe que el registro detallado se ha aplicado de la siguiente forma:
+
[listing]
----
# cat /etc/modprobe.d/qla2xxx.conf
options qla2xxx ql2xnvmeenable=1 ql2xextended_error_logging=0x1e400000
# cat /sys/module/qla2xxx/parameters/ql2xextended_error_logging
507510784
----


--
====


=== Errores y soluciones alternativas comunes de nvme-cli

Los errores mostrados por `nvme-cli` durante `nvme discover`, `nvme connect`, o. `nvme connect-all` las operaciones y las soluciones alternativas se muestran en la siguiente tabla:

[cols="20, 20, 50"]
|===
| Errores mostrados por `nvme-cli` | Causa probable | Solución alternativa 


| `Failed to write to /dev/nvme-fabrics: Invalid argument` | Sintaxis incorrecta | Compruebe que está utilizando la sintaxis correcta para el `nvme discover`, `nvme connect`, y. `nvme connect-all` comandos. 


| `Failed to write to /dev/nvme-fabrics: No such file or directory` | Varios problemas pueden desencadenar esto, por ejemplo, proporcionar argumentos incorrectos en los comandos NVMe es una de las causas comunes.  a| 
* Verifique que haya pasado los argumentos correctos (como, una cadena WWNN, una cadena WWPN correcta y otros) a los comandos.
* Si los argumentos son correctos, pero sigue viendo este error, compruebe si `/sys/class/scsi_host/host*/nvme_info` El resultado del comando es correcto, el iniciador de NVMe se muestra como `Enabled`, Y las LIF de destino NVMe/FC se muestran correctamente bajo las secciones de puertos remotos. Ejemplo:
+
[listing]
----

# cat /sys/class/scsi_host/host*/nvme_info
NVME Initiator Enabled
NVME LPORT lpfc0 WWPN x10000090fae0ec9d WWNN x20000090fae0ec9d DID x012000 ONLINE
NVME RPORT WWPN x200b00a098c80f09 WWNN x200a00a098c80f09 DID x010601 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000071 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a6 Outstanding 0000000000000001
NVME Initiator Enabled
NVME LPORT lpfc1 WWPN x10000090fae0ec9e WWNN x20000090fae0ec9e DID x012400 ONLINE
NVME RPORT WWPN x200900a098c80f09 WWNN x200800a098c80f09 DID x010301 TARGET DISCSRVC ONLINE
NVME Statistics
LS: Xmt 0000000000000006 Cmpl 0000000000000006
FCP: Rd 0000000000000073 Wr 0000000000000005 IO 0000000000000031
Cmpl 00000000000000a8 Outstanding 0000000000000001
----
* Si las LIF de destino no se muestran como arriba en la `nvme_info` resultado del comando, compruebe el `/var/log/messages` y.. `dmesg` Genera comandos para cualquier fallo sospechoso de NVMe/FC, y estos informan o corrigen la como corresponda.




| `No discovery log entries to fetch`  a| 
Generalmente observado cuando `/etc/nvme/hostnqn` No se ha añadido la cadena al subsistema correspondiente en la cabina de NetApp o una incorrecta `hostnqn` la cadena se ha agregado al subsistema correspondiente.
 a| 
Compruebe que el valor es exacto `/etc/nvme/hostnqn` La cadena se añade al subsistema correspondiente en la cabina de NetApp (compruebe mediante la `vserver nvme subsystem host show` ).



| `Failed to write to /dev/nvme-fabrics: Operation already in progress`  a| 
Se observa cuando las asociaciones de controladores o la operación especificada ya se han creado o se está creando. Esto podría suceder como parte de los scripts de conexión automática instalados anteriormente.
 a| 
Ninguno. Intente ejecutar el `nvme discover` comando de nuevo después de un tiempo. Para `nvme connect` y.. `connect-all`, ejecute el `nvme list` comando para verificar que los dispositivos de espacio de nombres ya se han creado y se muestran en el host.

|===


=== Cuándo ponerse en contacto con el soporte técnico

Si aún tiene problemas, recopile los siguientes archivos y resultados de comandos y póngase en contacto con el soporte técnico para realizar una evaluación más próxima:

[listing]
----
cat /sys/class/scsi_host/host*/nvme_info
/var/log/messages
dmesg
nvme discover output as in:
nvme discover --transport=fc --traddr=nn-0x200a00a098c80f09:pn-0x200b00a098c80f09 --host-traddr=nn-0x20000090fae0ec9d:pn-0x10000090fae0ec9d
nvme list
nvme list-subsys /dev/nvmeXnY
----