---
sidebar: sidebar 
permalink: nvme-ol-95.html 
keywords: nvme, oracle linux, 9.5, host configuration 
summary: Configuración de host de NVMe-oF para Oracle Linux 9,5 con ONTAP 
---
= Configurar Oracle Linux 9.5 con NVMe-oF para el almacenamiento ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las configuraciones de host SAN de NetApp admiten el protocolo NVMe over Fabrics (NVMe-oF) con acceso asimétrico al espacio de nombres (ANA). En entornos con NVMe-oF, ANA es equivalente a accesos múltiples asimétricos de unidad lógica (ALUA) en entornos iSCSI y FCP. ANA se implementa mediante la función multivía de NVMe interna.

.Acerca de esta tarea
Los siguientes servicios de compatibilidad y funciones están disponibles con la configuración de host de NVMe-oF para Oracle Linux 9,5 con almacenamiento ONTAP.

* Soporte disponible:
+
** Compatibilidad con NVMe sobre TCP (NVMe/TCP), además de NVMe sobre Fibre Channel (NVMe/FC). El plugin de NetApp en el paquete nvme-cli nativo muestra detalles de ONTAP para espacios de nombres NVMe/FC y NVMe/TCP.
** Ejecutando tráfico NVMe y SCSI en el mismo host. Por ejemplo, puede configurar dm-multipath en dispositivos SCSI mpath para LUN SCSI y usar NVMe multipath para configurar dispositivos de espacio de nombres NVMe-oF en el host.
** Oracle Linux 9.5 habilita la multiruta NVMe dentro del kernel para espacios de nombres NVMe de manera predeterminada, lo que elimina la necesidad de configuraciones explícitas.
** A partir de ONTAP 9.12.1, se incorpora la compatibilidad con la autenticación segura en banda para NVMe/TCP. Puede utilizar la autenticación segura en banda para NVMe/TCP con Oracle Linux 9.5.


+
--

NOTE: La NetApp  `sanlun` La utilidad de host no es compatible con NVMe-oF. En su lugar, puede usar el complemento de NetApp incluido en el entorno nativo.  `nvme-cli` para todos los transportes NVMe-oF.

Si quiere más información sobre las configuraciones compatibles, consulte la link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad"^].

--
* Características disponibles:
+
** No hay nuevas funciones en esta versión.


* Limitaciones conocidas:
+
** Evite emitir el  `nvme disconnect-all` comando en sistemas que arrancan desde SAN a través de espacios de nombres NVMe-TCP o NVMe-FC porque desconecta los sistemas de archivos raíz y de datos y podría generar inestabilidad en el sistema.






== Paso 1: Opcionalmente, habilite el arranque SAN

Puede configurar su host para que utilice el arranque SAN y simplificar la puesta en marcha y mejorar la escalabilidad.

.Antes de empezar
Utilice link:https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Linux, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.

.Pasos
. https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html["Cree un espacio de nombres de arranque SAN y asígnelo al host"^].
. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que está asignado el espacio de nombres de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Compruebe que la configuración se haya realizado correctamente. Para ello, reinicie el host y verifique que el sistema operativo esté activo y en ejecución.




== Paso 2: Validar las versiones del software

Utilice el siguiente procedimiento para validar las versiones mínimas compatibles del software Oracle Linux 9.5.

.Pasos
. Instale Oracle Linux 9.5 en el servidor. Una vez completada la instalación, verifique que esté ejecutando el kernel Oracle Linux 9.5 especificado.
+
[source, cli]
----
uname -r
----
+
El siguiente ejemplo muestra una versión del kernel de Oracle Linux:

+
[listing]
----
5.15.0-302.167.6.el9uek.x86_64
----
. Instale el `nvme-cli` paquete:
+
[source, cli]
----
rpm -qa|grep nvme-cli
----
+
El siguiente ejemplo muestra un  `nvme-cli` versión del paquete:

+
[listing]
----
nvme-cli-2.9.1-6.el9.x86_64
----
. Instale el `libnvme` paquete:
+
[source, cli]
----
rpm -qa|grep libnvme
----
+
El siguiente ejemplo muestra un  `libnvme` versión del paquete:

+
[listing]
----
libnvme-1.9-3.el9.x86_64
----
. En el host Oracle Linux 9,5, compruebe `hostnqn` la cadena en `/etc/nvme/hostnqn`:
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
+
El siguiente ejemplo muestra un  `hostnqn` versión:

+
[listing]
----
nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0050-3410-8035-c2c04f4a5933
----
. Compruebe que el `hostnqn` la cadena coincide con `hostnqn` Cadena para el subsistema correspondiente en la cabina de ONTAP:
+
[source, cli]
----
vserver nvme subsystem host show -vserver vs_213_36002
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
Vserver Subsystem Priority  Host NQN
------- --------- --------  ------------------------------------------------
vs_coexistence_LPE36002
        nvme1
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0050-3410-8035-c2c04f4a5933
        nvme2
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0050-3410-8035-c2c04f4a5933
        nvme3
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0050-3410-8035-c2c04f4a5933
        nvme4
                  regular   nqn.2014-08.org.nvmexpress:uuid:4c4c4544-0050-3410-8035-c2c04f4a5933
4 entries were displayed.
----
====
+

NOTE: Si `hostnqn` las cadenas no coinciden, puede usar `vserver modify` el comando para actualizar la `hostnqn` cadena en el subsistema de la cabina ONTAP correspondiente a fin de que coincida con la `hostnqn` cadena de `/etc/nvme/hostnqn` en el host.





== Paso 3: Configurar NVMe/FC

Configure NVMe/FC con adaptadores Broadcom/Emulex FC o Marvell/Qlogic FC.

[role="tabbed-block"]
====
.Broadcom/Emulex
--
Configuración de NVMe/FC para un adaptador Broadcom/Emulex.

.Pasos
. Compruebe que está utilizando el modelo de adaptador compatible:
+
.. Mostrar los nombres de los modelos:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Debe ver la siguiente salida:

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Mostrar las descripciones del modelo:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Compruebe que está utilizando la Broadcom recomendada `lpfc` firmware y controlador de bandeja de entrada:
+
.. Mostrar la versión del firmware:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
El siguiente ejemplo muestra las versiones de firmware:

+
[listing]
----
14.4.393.25, sli-4:6:d
14.4.393.25, sli-4:6:d
----
.. Mostrar la versión del controlador de la bandeja de entrada:
+
[source, cli]
----
cat /sys/module/lpfc/version
----
+
El siguiente ejemplo muestra una versión del controlador:

+
[listing]
----
0:14.4.0.2
----
+
Para obtener la lista actual de versiones de firmware y controladores de adaptador compatibles, consulte la link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad"^].



. Compruebe que `lpfc_enable_fc4_type` se establece en `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Compruebe que puede ver los puertos de iniciador:
+
[source, cli]
----
cat /sys/class/fc_host/host*/<port_name>
----
+
El siguiente ejemplo muestra las identidades del puerto:

+
[listing]
----
0x100000620b3c089c
0x100000620b3c089d
----
. Compruebe que los puertos de iniciador estén en línea:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Debe ver la siguiente salida:

+
[listing]
----
Online
Online
----
. Compruebe que los puertos de iniciador NVMe/FC estén habilitados y que los puertos de destino estén visibles:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc0 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc0 WWPN x100000620b3c089c WWNN x200000620b3c089c DID x081300 *ONLINE*
NVME RPORT       WWPN x2001d039eab0dadc WWNN x2000d039eab0dadc DID x080101 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2003d039eab0dadc WWNN x2000d039eab0dadc DID x080401 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 00000002e9 Cmpl 00000002e9 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 0000000000078742 Issue 0000000000078740 OutIO fffffffffffffffe
        abort 000000c2 noxri 00000000 nondlp 00000a23 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000000c2 Err 00000238

NVME Initiator Enabled
XRI Dist lpfc1 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc1 WWPN x100000620b3c089d WWNN x200000620b3c089d DID x081900 *ONLINE*
NVME RPORT       WWPN x2002d039eab0dadc WWNN x2000d039eab0dadc DID x080201 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2004d039eab0dadc WWNN x2000d039eab0dadc DID x080301 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 00000002d9 Cmpl 00000002d9 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000000007754f Issue 000000000007754f OutIO 0000000000000000
        abort 000000c2 noxri 00000000 nondlp 00000719 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000000c2 Err 0000023d
----
=====


--
.Marvell/QLogic
--
Configure NVMe/FC para un adaptador Marvell/QLogic.

.Pasos
. Compruebe que está ejecutando las versiones de firmware y controlador del adaptador compatibles:
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
El siguiente ejemplo muestra las versiones del controlador y del firmware:

+
[listing]
----
QLE2772 FW:v9.15.03 DVR:v10.02.09.300-k-debug
----
. Compruebe que `ql2xnvmeenable` está configurado. Esto permite que el adaptador Marvell funcione como iniciador NVMe/FC:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
El valor  `1` verifica que  `ql2xnvmeenable` está establecido



--
====


== Paso 4: Opcionalmente, habilite 1 MB de E/S para NVMe/FC

ONTAP informa de un MDT (tamaño de transferencia de MAX Data) de 8 en los datos Identify Controller. Esto significa que el tamaño máximo de solicitud de E/S puede ser de hasta 1MB TB. Para emitir solicitudes de I/O de tamaño 1 MB para un host Broadcom NVMe/FC, debe aumentar `lpfc` el valor `lpfc_sg_seg_cnt` del parámetro a 256 con respecto al valor predeterminado de 64.


NOTE: Estos pasos no se aplican a los hosts Qlogic NVMe/FC.

.Pasos
. Defina el `lpfc_sg_seg_cnt` parámetro en 256:
+
[source, cli]
----
cat /etc/modprobe.d/lpfc.conf
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
options lpfc lpfc_sg_seg_cnt=256
----
. Ejecute `dracut -f` el comando y reinicie el host.
. Compruebe que el valor de `lpfc_sg_seg_cnt` es 256:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_sg_seg_cnt
----




== Paso 5: Verificar los servicios de arranque NVMe

Con Oracle Linux 9.5, el  `nvmefc-boot-connections.service` y  `nvmf-autoconnect.service` Servicios de arranque incluidos en NVMe/FC  `nvme-cli` Los paquetes se habilitan automáticamente cuando se inicia el sistema.

Una vez finalizado el arranque, verifique que  `nvmefc-boot-connections.service` y  `nvmf-autoconnect.service` Los servicios de arranque están habilitados.

.Pasos
. Compruebe que `nvmf-autoconnect.service` está activado:
+
[source, cli]
----
systemctl status nvmf-autoconnect.service
----
+
.Muestra el resultado de ejemplo
[%collapsible]
====
[listing]
----
nvmf-autoconnect.service - Connect NVMe-oF subsystems automatically during boot
Loaded: loaded (/usr/lib/systemd/system/nvmf-autoconnect.service; enabled; preset: disabled)
Active: inactive (dead) since Wed 2025-07-02 16:46:37 IST; 1 day 3h ago
Main PID: 2129 (code=exited, status=0/SUCCESS)
CPU: 121ms

Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to write to /dev/nvme-fabrics: Invalid argument
Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to write to /dev/nvme-fabrics: Invalid argument
Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to write to /dev/nvme-fabrics: Invalid argument
Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to write to /dev/nvme-fabrics: Invalid argument
Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to write to /dev/nvme-fabrics: Invalid argument
Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to write to /dev/nvme-fabrics: Invalid argument
Jul 02 16:46:37 interop-13-175 nvme[2129]: Failed to open ctrl nvme0, errno 2
Jul 02 16:46:37 interop-13-175 nvme[2129]: failed to get discovery log: Bad file descriptor
Jul 02 16:46:37 interop-13-175 systemd[1]: nvmf-autoconnect.service: Deactivated successfully.
Jul 02 16:46:37 interop-13-175 systemd[1]: Finished Connect NVMe-oF subsystems automatically during boot.
----
====
. Compruebe que `nvmefc-boot-connections.service` está activado:
+
[source, cli]
----
systemctl status nvmefc-boot-connections.service
----
+
.Muestra el resultado de ejemplo
[%collapsible]
====
[listing]
----
nvmefc-boot-connections.service - Auto-connect to subsystems on FC-NVME devices found during boot
Loaded: loaded (/usr/lib/systemd/system/nvmefc-boot-connections.service; enabled; preset: enabled)
Active: inactive (dead) since Wed 2025-07-02 16:45:46 IST; 1 day 3h ago
Main PID: 1604 (code=exited, status=0/SUCCESS)
CPU: 32ms

Jul 02 16:45:46 interop-13-175 systemd[1]: Starting Auto-connect to subsystems on FC-NVME devices found during boot...
Jul 02 16:45:46 interop-13-175 systemd[1]: nvmefc-boot-connections.service: Deactivated successfully.
Jul 02 16:45:46 interop-13-175 systemd[1]: Finished Auto-connect to subsystems on FC-NVME devices found during boot.
----
====




== Paso 6: Configurar NVMe/TCP

El protocolo NVMe/TCP no admite `auto-connect` la operación. En su lugar, puede detectar los subsistemas y los espacios de nombres NVMe/TCP ejecutando manualmente las operaciones o `connect-all` NVMe/TCP `connect`.

.Pasos
. Compruebe que el puerto del iniciador pueda recuperar los datos de la página de registro de detección en las LIF NVMe/TCP admitidas:
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing, subs="+quotes"]
----
nvme discover -t tcp -w 192.168.165.3 -a 192.168.165.8
Discovery Log Number of Records 8, Generation counter 8
=====Discovery Log Entry 0======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  4
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.166.9
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 1======
trtype:  tcp
adrfam:  ipv4
subtype: current discovery subsystem
treq:    not specified
portid:  2
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.165.9
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 2======
trtype:  tcp
adrfam:  ipv4
subtype: current discovery subsystem
treq:    not specified
portid:  3
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.166.8
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 3======
trtype:  tcp
adrfam:  ipv4
subtype: *current discovery subsystem*
treq:    not specified
portid:  1
trsvcid: 8009
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:discovery
traddr:  192.168.165.8
eflags:  *explicit discovery connections, duplicate discovery information*
sectype: none
=====Discovery Log Entry 4======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  4
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.nvme
traddr:  192.168.166.9
eflags:  none
sectype: none
=====Discovery Log Entry 5======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  2
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.nvme
traddr:  192.168.165.9
eflags:  none
sectype: none
=====Discovery Log Entry 6======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  3
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.nvme
traddr:  192.168.166.8
eflags:  none
sectype: none
=====Discovery Log Entry 7======
trtype:  tcp
adrfam:  ipv4
subtype: *nvme subsystem*
treq:    not specified
portid:  1
trsvcid: 4420
subnqn:  nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.nvme
traddr:  192.168.165.8
eflags:  none
sectype: none
----
====
. Compruebe que las otras combinaciones de LIF iniciador-objetivo NVMe/TCP puedan recuperar correctamente los datos de la página del registro de detección:
+
[source, cli]
----
nvme discover -t tcp -w host-traddr -a traddr
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
nvme discover -t tcp -w 192.168.166.4 -a 192.168.166.8
nvme discover -t tcp -w 192.168.165.3 -a 192.168.165.8
nvme discover -t tcp -w 192.168.166.4 -a 192.168.166.9
nvme discover -t tcp -w 192.168.165.3 -a 192.168.165.9
----
. Ejecute el `nvme connect-all` Comando en todos los LIF objetivo iniciador NVMe/TCP admitidos entre los nodos:
+
[source, cli]
----
nvme connect-all -t tcp -w host-traddr -a traddr
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
nvme connect-all -t	tcp -w 192.168.165.3 -a 192.168.165.8
nvme connect-all -t	tcp -w 192.168.165.3 -a 192.168.165.9
nvme connect-all -t	tcp -w 192.168.166.4 -a 192.168.166.8
nvme connect-all -t	tcp -w 192.168.166.4 -a 192.168.166.9

----
+
[NOTE]
====
A partir de Oracle Linux 9.4, la configuración para NVMe/TCP  `ctrl_loss_tmo timeout` se establece automáticamente en "apagado". Como resultado:

** No hay límites en el número de reintentos (reintento indefinido).
** No es necesario configurar manualmente un elemento específico.  `ctrl_loss_tmo timeout` Duración al utilizar el  `nvme connect` o  `nvme connect-all` comandos (opción -l ).
** Los controladores NVMe/TCP no experimentan tiempos de espera en caso de una falla de ruta y permanecen conectados indefinidamente.


====




== Paso 7: Validar NVMe-oF

Verifique que el estado de multivía de NVMe en kernel, el estado de ANA y los espacios de nombres de ONTAP sean correctos para la configuración de NVMe-oF.

.Pasos
. Compruebe que la multivía NVMe en kernel esté habilitada:
+
[source, cli]
----
cat /sys/module/nvme_core/parameters/multipath
----
+
Debe ver la siguiente salida:

+
[listing]
----
Y
----
. Compruebe que la configuración NVMe-oF adecuada (como, por ejemplo, el modelo configurado en la controladora NetApp ONTAP y la política de balanceo de carga establecida en round-robin) en los respectivos espacios de nombres de ONTAP se reflejen correctamente en el host:
+
.. Mostrar los subsistemas:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/model
----
+
Debe ver la siguiente salida:

+
[listing]
----
NetApp ONTAP Controller
NetApp ONTAP Controller
----
.. Mostrar la política:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys*/iopolicy
----
+
Debe ver la siguiente salida:

+
[listing]
----
round-robin
round-robin
----


. Verifique que los espacios de nombres se hayan creado y detectado correctamente en el host:
+
[source, cli]
----
nvme list
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
Node          Generic       SN                   Model                     Namespace  Usage                   Format         FW Rev
------------- ------------- -------------------- ------------------------- ---------- ----------------------- -------------- --------
/dev/nvme1n1  /dev/ng1n1    81Mc4FXd1tocAAAAAAAC NetApp ONTAP Controller   0x1        0.00   B /  10.74  GB   4 KiB +  0 B   9.16.1
----
====
. Compruebe que el estado de la controladora de cada ruta sea activo y que tenga el estado de ANA correcto:
+
[role="tabbed-block"]
====
.NVMe/FC
--
[source, cli]
----
nvme list-subsys /dev/nvme4n5
----
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys7 - NQN=nqn.1992-08.com.netapp:sn.7d37987be3cb11ef8948d039eab0dadd:subsystem.nvme6
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:2831093d-fa7f-4714-a6bf-548796e82053
               iopolicy=round-robin
\
 +- nvme103 fc traddr=nn-0x202cd039eab0dadc:pn-0x202fd039eab0dadc,host_traddr=nn-0x200034800d767bb0:pn-0x210034800d767bb0 live optimized
 +- nvme153 fc traddr=nn-0x202cd039eab0dadc:pn-0x202ed039eab0dadc,host_traddr=nn-0x200034800d767bb1:pn-0x210034800d767bb1 live non-optimized
 +- nvme55 fc traddr=nn-0x202cd039eab0dadc:pn-0x202dd039eab0dadc,host_traddr=nn-0x200034800d767bb0:pn-0x210034800d767bb0 live non-optimized
 +- nvme7 fc traddr=nn-0x202cd039eab0dadc:pn-0x2030d039eab0dadc,host_traddr=nn-0x200034800d767bb1:pn-0x210034800d767bb1 live optimized
----
=====
--
.NVMe/TCP
--
[source, cli]
----
nvme list-subsys /dev/nvme1n1
----
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
nvme-subsys1 - NQN=nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.nvme
               hostnqn=nqn.2014-08.org.nvmexpress:uuid:9796c1ec-0d34-11eb-b6b2-3a68dd3bab57
               iopolicy=round-robin\
+- nvme1 tcp traddr=192.168.165.8,trsvcid=4420,host_traddr=192.168.165.3,
src_addr=192.168.165.3 *live optimized*
+- nvme2 tcp traddr=192.168.165.9,trsvcid=4420,host_traddr=192.168.165.3,
src_addr=192.168.165.3 *live non-optimized*
+- nvme3 tcp traddr=192.168.166.8,trsvcid=4420,host_traddr=192.168.166.4,
src_addr=192.168.166.4 *live optimized*
+- nvme4 tcp traddr=192.168.166.9,trsvcid=4420,host_traddr=192.168.166.4,
src_addr=192.168.166.4 *live non-optimized*

----
=====
--
====
. Confirmar que el complemento de NetApp muestra los valores correctos para cada dispositivo de espacio de nombres ONTAP:
+
[role="tabbed-block"]
====
.Columna
--
[source, cli]
----
nvme netapp ontapdevices -o column
----
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
Device           Vserver                   Namespace Path                                     NSID UUID                                   Size
---------------- ------------------------- -------------------------------------------------- ---- -------------------------------------- ---------
/dev/nvme1n1     vs_tcpinband              /vol/volpdc/ns1                                    1    80eec226-6987-4eb4-bf86-65bf48c5372d   10.74GB

----
=====
--
.JSON
--
[source, cli]
----
nvme netapp ontapdevices -o json
----
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
{
  "ONTAPdevices":[
    {
      "Device":"/dev/nvme1n1",
      "Vserver":"vs_tcpinband",
      "Namespace_Path":"/vol/volpdc/ns1",
      "NSID":1,
      "UUID":"80eec226-6987-4eb4-bf86-65bf48c5372d",
      "Size":"10.74GB",
      "LBA_Data_Size":4096,
      "Namespace_Size":2621440
    }
  ]
}
----
=====
--
====




== Paso 8: Configurar la autenticación segura en banda

A partir de ONTAP 9.12.1, se admite la autenticación segura en banda a través de NVMe/TCP entre un host Oracle Linux 9.5 y un controlador ONTAP.

Para configurar la autenticación segura, cada host o controladora debe estar asociado con a. `DH-HMAC-CHAP` Clave, que es una combinación de NQN del host o de la controladora NVMe y un secreto de autenticación configurado por el administrador. Para autenticar su par, un host o una controladora NVMe deben reconocer la clave asociada con el par.

Puede configurar la autenticación segura en banda mediante la interfaz de línea de comandos o un archivo config JSON. Si necesita especificar diferentes claves dhchap para diferentes subsistemas, debe utilizar un archivo JSON de configuración.

[role="tabbed-block"]
====
.CLI
--
Configure la autenticación segura en banda mediante la CLI.

.Pasos
. Obtenga el NQN del host:
+
[source, cli]
----
cat /etc/nvme/hostnqn
----
. Genere la clave dhchap para el host Linux.
+
En el siguiente resultado, se describen `gen-dhchap-key` los parámetros de los comandos:

+
[listing]
----
nvme gen-dhchap-key -s optional_secret -l key_length {32|48|64} -m HMAC_function {0|1|2|3} -n host_nqn
•	-s secret key in hexadecimal characters to be used to initialize the host key
•	-l length of the resulting key in bytes
•	-m HMAC function to use for key transformation
0 = none, 1- SHA-256, 2 = SHA-384, 3=SHA-512
•	-n host NQN to use for key transformation
----
+
En el siguiente ejemplo, se genera una clave dhchap aleatoria con HMAC establecido en 3 (SHA-512).

+
[listing]
----
# nvme gen-dhchap-key -m 3 -n nqn.2014-08.org.nvmexpress:uuid:9796c1ec-0d34-11eb-b6b2-3a68dd3bab57
DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:
----
. En la controladora ONTAP, añada el host y especifique ambas claves dhchap:
+
[source, cli]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -dhchap-host-secret <authentication_host_secret> -dhchap-controller-secret <authentication_controller_secret> -dhchap-hash-function {sha-256|sha-512} -dhchap-group {none|2048-bit|3072-bit|4096-bit|6144-bit|8192-bit}
----
. Un host admite dos tipos de métodos de autenticación: Unidireccional y bidireccional. En el host, conéctese a la controladora ONTAP y especifique claves dhchap según el método de autenticación elegido:
+
[source, cli]
----
nvme connect -t tcp -w <host-traddr> -a <tr-addr> -n <host_nqn> -S <authentication_host_secret> -C <authentication_controller_secret>
----
. Valide el `nvme connect authentication` comando mediante la verificación de las claves dhchap de host y controladora:
+
.. Verifique las claves dhchap del host:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_secret
----
+
.Mostrar ejemplo de salida para una configuración unidireccional
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys1/nvme*/dhchap_secret
DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:
DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:
DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:
  DHHC-  1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:
----
=====
.. Compruebe las claves dhchap del controlador:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/<nvme-subsysX>/nvme*/dhchap_ctrl_secret
----
+
.Mostrar ejemplo de salida para una configuración bidireccional
[%collapsible]
=====
[listing]
----
cat /sys/class/nvme-subsystem/nvme-subsys6/nvme*/dhchap_ctrl_secret
DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:
DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:
DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:
DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:
----
=====




--
.Archivo JSON
--
Cuando hay varios subsistemas NVMe disponibles en la configuración de la controladora ONTAP, se puede utilizar `/etc/nvme/config.json` el archivo con `nvme connect-all` el comando.

Utilice el  `-o` Opción para generar el archivo JSON. Consulte las páginas del manual de NVMe connect-all para obtener más opciones de sintaxis.

.Pasos
. Configure el archivo JSON:
+
.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
 cat /etc/nvme/config.json
[
  {
    "hostnqn":"nqn.2014-08.org.nvmexpress:uuid:9796c1ec-0d34-11eb-b6b2-3a68dd3bab57",
    "hostid":"9796c1ec-0d34-11eb-b6b2-3a68dd3bab57",
    "dhchap_key":"DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:",
    "subsystems":[
      {
        "nqn":"nqn.1992-08.com.netapp:sn.4f7af2bd221811f0afadd039eab0dadd:subsystem.nvme",
        "ports":[
          {
            "transport":"tcp",
            "traddr":"192.168.165.9",
            "host_traddr":"192.168.165.3",
            "trsvcid":"4420",
            "dhchap_key":"DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:",
            "dhchap_ctrl_key":"DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:"          },
          {
            "transport":"tcp",
            "traddr":"192.168.166.9",
            "host_traddr":"192.168.166.4",
            "trsvcid":"4420",
                        "dhchap_key":"DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:",
            "dhchap_ctrl_key":"DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:"
          },
          {
            "transport":"tcp",
            "traddr":"192.168.166.8",
            "host_traddr":"192.168.166.4",
            "trsvcid":"4420",
                        "dhchap_key":"DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:",
            "dhchap_ctrl_key":"DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:"
          },
          {
            "transport":"tcp",
            "traddr":"192.168.165.8",
            "host_traddr":"192.168.165.3",
            "trsvcid":"4420",
                        "dhchap_key":"DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:",
            "dhchap_ctrl_key":"DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:"
          }
        ]
      }
    ]
  }
]
----
=====
+

NOTE: En el ejemplo anterior, `dhchap_key` corresponde a `dhchap_secret` y `dhchap_ctrl_key` corresponde a `dhchap_ctrl_secret` .

. Conéctese a la controladora ONTAP mediante el archivo JSON de configuración:
+
[source, cli]
----
nvme connect-all -J /etc/nvme/config.json
----
. Verifique que se hayan activado los secretos dhchap para las respectivas controladoras de cada subsistema:
+
.. Verifique las claves dhchap del host:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_secret
----
+
El siguiente ejemplo muestra una clave dhchap:

+
[listing]
----
DHHC-1:03:Y5VkkESgmtTGNdX842qemNpFK6BXYVwwnqErgt3IQKP5Fbjje\/JSBOjG5Ea3NBLRfuiAuUSDUto6eY\/GwKoRp6AwGkw=:
----
.. Compruebe las claves dhchap del controlador:
+
[source, cli]
----
cat /sys/class/nvme-subsystem/nvme-subsys0/nvme0/dhchap_ctrl_secret
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
DHHC-1:03:frpLlTrnOYtcWDxPzq4ccxU1UrH2FjV7hYw5s2XEDB+lo+TjMsOwHR\/NFtM0nBBidx+gdoyUcC5s6hOOtTLDGcz0Kbs=:
----




--
====


== Paso 9: Revise los problemas conocidos

No hay problemas conocidos.
