---
sidebar: sidebar 
permalink: overview.html 
keywords: ontap, san, host, rhel, red, hat, linux, sles, suse, esxi, nvme, oracle, linux, windows, enterprise, fc, fcp, isci, aix, powervm, vios, centos, citrix, hp-ux, solaris, veritas, cvo, cloud, volume, ontap, clients, configuration, FSx, instance, netapp 
summary: Este contenido proporciona una guía específica para la distribución sobre cómo configurar clientes de cloud conectados a Cloud Volumes ONTAP y Amazon FSX para hosts ONTAP y SAN conectados al almacenamiento ONTAP local. 
---
= Información general de la configuración de hosts SAN
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


Este contenido proporciona las prácticas recomendadas específicas para el host y la versión con el fin de configurar rápidamente hosts SAN conectados al almacenamiento de ONTAP.

Sus hosts SAN y el almacenamiento ONTAP pueden residir en las instalaciones, en el cloud, o en ambos.


NOTE: En un entorno cloud, los hosts se denominan clientes normalmente. Toda la información específica sobre hosts de este contenido también se aplica a los clientes cloud.

Por ejemplo, puede configurar el almacenamiento ONTAP en las instalaciones para conectarse a hosts SAN en las instalaciones o para conectarse a clientes de cloud SAN. También puede configurar link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] o. link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^] Para conectarse a hosts SAN en las instalaciones o para conectarse a clientes cloud SAN.

Una configuración adecuada es importante para un mejor rendimiento y para una correcta conmutación por error.

.Información relacionada
* La link:https://docs.netapp.com/us-en/ontap/san-config/index.html["Configuración de SAN ONTAP"^] Para su versión de ONTAP
* La link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Guía de administración de SAN de ONTAP"^] Para su versión de ONTAP
* La link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notas de la versión de ONTAP"^] Para su versión de ONTAP
* La link:https://docs.netapp.com/us-en/e-series/index.html["Documentación de E-Series"^] Para encontrar documentación relacionada de SANtricity.

