= 
:allow-uri-read: 


. Si su configuración de almacenamiento incluye sincronización activa de MetroCluster o SnapMirror , cambie la configuración predeterminada:
+
[role="tabbed-block"]
====
.MetroCluster
--
De forma predeterminada, el sistema operativo AIX aplica un tiempo de espera de E/S más corto cuando no hay rutas disponibles a un LUN.  Esto podría ocurrir en configuraciones que incluyen una estructura SAN de un solo conmutador y en configuraciones de MetroCluster que experimentan conmutaciones por error no planificadas.  Para obtener información adicional y cambios recomendados en la configuración predeterminada, consulte el artículo de la Base de conocimientoslink:https://kb.netapp.com/on-prem/ontap/mc/MC-KBs/What_are_AIX_Host_support_considerations_in_a_MetroCluster_configuration["¿Cuáles son las consideraciones de soporte de host AIX en una configuración de MetroCluster ?"^] .

--
.Sincronización activa de SnapMirror
--
SnapMirror active sync es compatible con un host AIX. El comportamiento de soporte difiere según la versión de ONTAP:

** A partir de ONTAP 9.19.1, SnapMirror active sync es compatible con la configuración Active/Active, lo que permite realizar operaciones de SnapMirror active sync sin interrupciones. Consulta el artículo de base de conocimientos link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/SnapMirror_active_sync_support_for_AIX%3A_behavior_by_ONTAP_release_and_migration_guidance["SnapMirror compatibilidad de active sync con AIX: comportamiento por versión de ONTAP y guía de migración"^].
** Para ONTAP 9.11.1 a 9.18.1, SnapMirror active sync es compatible en la configuración Active/Standby. Consulta el artículo de base de conocimientos link:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_to_configure_AIX_Host_for_SnapMirror_active_sync_in_ONTAP["Cómo configurar un host AIX para SnapMirror active sync en ONTAP 9.11.1 a 9.18.1"^].


--
====

