= 
:allow-uri-read: 


.Pasos
Dependiendo de su configuración, seleccione la pestaña UEK 3 o UEK 4.

[role="tabbed-block"]
====
.UEK 3
--
La configuración de Oracle Linux UEK 3 con y sin ALUA se actualiza automáticamente. Tras la actualización, debe habilitar el "Manejador ALUA":

. Cree una copia de seguridad de la imagen initrd.
. Para que ALUA y no ALUA funcionen, anexe el siguiente valor del parámetro al kernel:
+
[source, cli]
----
rdloaddriver=scsi_dh_alua
----
+
.Resultado de ejemplo
[listing]
----
kernel /vmlinuz-3.8.13-68.1.2.el6uek.x86_64 ro root=/dev/mapper/vg_ibmx3550m421096-lv_root rd_NO_LUKSrd_LVM_LV=vg_ibmx3550m421096/lv_root LANG=en_US.UTF-8 rd_NO_MDSYSFONT=latarcyrheb-sun16 crashkernel=256M KEYBOARDTYPE=pc KEYTABLE=us rd_LVM_LV=vg_ibmx3550m421096/lv_swap rd_NO_DM rhgb quiet rdloaddriver=scsi_dh_alua
----
. Recrear la imagen initrd:
+
[source, cli]
----
dracut -f
----
. Reinicie el host.
. Revisar la salida del  `cat /proc/cmdline` Comando para verificar que la configuración esté completa.


--
.UEK 4
--
Para Oracle Linux UEK 4, verifique que  `/etc/multipath.conf` El archivo está definido y las configuraciones recomendadas de NetApp están configuradas para sus LUN de ONTAP.

. Verifique que el `/etc/multipath.conf` archivo salga. Si el archivo no existe, cree un archivo vacío de cero bytes:
+
[source, cli]
----
touch /etc/multipath.conf
----
. La primera vez que `multipath.conf` se crea el archivo, es posible que deba habilitar e iniciar los servicios multivía para cargar la configuración recomendada:
+
[source, cli]
----
chkconfig multipathd on
----
+
[source, cli]
----
/etc/init.d/multipathd start
----
. Cada vez que arranca el host, el archivo de cero bytes vacío `/etc/multipath.conf` carga automáticamente los parámetros multivía de host recomendados por NetApp como configuración predeterminada. No debería ser necesario realizar cambios en `/etc/multipath.conf` el archivo para el host ya que el sistema operativo está compilado con los parámetros multivía que reconocen y gestionan correctamente las LUN de ONTAP.
+
.Muestra la configuración de los parámetros
[%collapsible]
=====
[cols="2"]
|===
| Parámetro | Ajuste 


| detect_prio | sí 


| dev_loss_tmo | "infinito" 


| conmutación tras recuperación | inmediata 


| fast_io_fail_tmo | 5 


| funciones | "2 pg_init_retries 50" 


| flush_on_last_del | "sí" 


| manipulador_hardware | "0" 


| no_path_retry | cola 


| comprobador_de_rutas | "tur" 


| política_agrupación_ruta | "group_by_prio" 


| selector_de_rutas | "tiempo de servicio 0" 


| intervalo_sondeo | 5 


| prioridad | "ONTAP" 


| producto | LUN 


| retain_attached_hw_handler | sí 


| rr_weight | "uniforme" 


| nombres_descriptivos_usuario | no 


| proveedor | NETAPP 
|===
=====
. Compruebe la configuración de parámetros y el estado de la ruta de sus LUN de ONTAP:
+
[source, cli]
----
multipath -ll
----
+
Los parámetros multiruta predeterminados admiten configuraciones AFF y FAS. En estas configuraciones, una única LUN de ONTAP no debería necesitar más de cuatro rutas. Si existen más de cuatro rutas, se pueden producir problemas con las rutas durante un fallo de almacenamiento.

+
Una configuración de AFF o FAS debe tener dos grupos de rutas con prioridades superiores e inferiores. La controladora donde se encuentra el agregado ofrece rutas activas/optimizadas de mayor prioridad. Las rutas de prioridad más baja están activas pero no optimizadas debido a que se sirven con una controladora diferente. Las rutas no optimizadas solo se usan cuando las rutas optimizadas no están disponibles.

+
Los siguientes ejemplos de salida muestran la configuración de parámetros y el estado de ruta correctos para los LUN de ONTAP en una configuración AFF o FAS con dos rutas activas/optimizadas y dos rutas activas/no optimizadas:

+
.Muestra el ejemplo
[%collapsible]
=====
[listing]
----
multipath -ll
3600a0980383036347ffb4d59646c4436 dm-28 NETAPP,LUN C-Mode
size=10G features='3 queue_if_no_path pg_init_retries 50' hwhandler='1 alua' wp=rw
|-+- policy='service-time 0' prio=50 status=active
| |- 16:0:6:35 sdwb  69:624  active ready running
| |- 16:0:5:35 sdun  66:752  active ready running
`-+- policy='service-time 0' prio=10 status=enabled
  |- 15:0:0:35 sdaj  66:48   active ready running
  |- 15:0:1:35 sdbx  68:176  active ready running
----
=====


--
====