= 
:allow-uri-read: 


Asegúrate de que iSCSI está configurado correctamente para tu host.

.Acerca de esta tarea
Realizas los siguientes pasos en el host iSCSI.

.Pasos
. Verifica que el paquete iniciador iSCSI (open-iscsi) esté instalado:
+
[source, cli]
----
$apt list |grep open-iscsi
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
open-iscsi/stable,now 2.1.11-1+deb13u1 amd64
----
. Verifica el nombre de nodo del iniciador iSCSI, que se encuentra en el archivo  `/etc/iscsi/initiatorname.iscsi`:
+
[source, cli]
----
InitiatorName=iqn.YYYY-MM.com.<vendor>:<host_name>
----
. Configura el parámetro de tiempo de espera de la sesión iSCSI que se encuentra en el archivo  `/etc/iscsi/iscsid.conf`:
+
[source, cli]
----
node.session.timeo.replacement_timeout = 5
----
+
El parámetro iSCSI `replacement_timeout` controla cuánto tiempo la capa iSCSI debe esperar a que una ruta o sesión con tiempo de espera se restablezca antes de fallar cualquier comando en ella. Debes establecer el valor de `replacement_timeout` en 5 en el archivo de configuración de iSCSI.

. Activa el servicio iSCI:
+
[source, cli]
----
$systemctl enable iscsid
----
. Inicia el servicio iSCI:
+
[source, cli]
----
$systemctl start iscsid
----
. Verifica que el servicio iSCI está en funcionamiento:
+
[source, cli]
----
$systemctl status iscsid
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/usr/lib/systemd/system/iscsid.service; disabled; preset: enabled)
     Active: active (running) since Fri 2026-02-20 22:14:34 IST; 2 days ago
 Invocation: 37a44a6ebd3a4e3898dcc6c408b85bec
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 4985 ExecStartPre=/usr/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 4988 ExecStart=/usr/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 4991 (iscsid)
      Tasks: 2 (limit: 151112)
     Memory: 12.5M (peak: 15.5M)
        CPU: 2.438s
     CGroup: /system.slice/iscsid.service
             ├─4990 /usr/sbin/iscsid
             └─4991 /usr/sbin/iscsid

----
====
. Descubre los objetivos iSCSI:
+
[source, cli]
----
$iscsiadm --mode discovery --op update --type sendtargets --portal <target_IP>
----
+
.mostrar ejemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode discovery --op update --type sendtargets --portal
192.168.166.70
192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5
----
====
. Inicia sesión en los objetivos:
+
[source, cli]
----
$iscsiadm --mode node -l all
----
. Configura iSCSI para que inicie sesión automáticamente cuando el host se inicie:
+
[source, cli]
----
$iscsiadm --mode node -T <target_name> -p <ip:port> -o update -n node.startup -v automatic
----
+
Reemplaza `<target_name>` por el nombre del destino al que quieres iniciar sesión automáticamente cuando arranque el host. Reemplaza `<ip:port>` por la dirección IP y el número de puerto del destino. Por ejemplo:

+
[source, cli]
----
iscsiadm --mode node -T iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 -p 192.168.166.70:3260 -o update -n node.startup -v automatic
----
. Verifica las sesiones iSCSI:
+
[source, cli]
----
$iscsiadm --mode session
----
+
.Muestra el ejemplo
[%collapsible]
====
[listing]
----
iscsiadm --mode session
tcp: [1] 192.168.166.71:3260,1043 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [2] 192.168.165.71:3260,1045 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [3] 192.168.165.70:3260,1044 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
tcp: [4] 192.168.166.70:3260,1042 iqn.1992-08.com.netapp:sn.c770be5d934811f0b624d039eac809ba:vs.5 (non-flash)
----
====

