= 
:allow-uri-read: 


El paquete de software de utilidades del host Linux de NetApp está disponible en https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^] un archivo .rpm de 32 o 64 bits.

NetApp recomienda encarecidamente la instalación de las utilidades del host Linux, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Pasos
. Si tiene una versión de Linux Host Utilities actualmente instalada, utilice el siguiente comando para eliminarla:
+
`rpm -e netapp_linux_unified_host_utilities-7-1`

+
Para obtener versiones anteriores de Linux Host Utilities, vaya al directorio donde está instalado el software de la utilidad host e introduzca `uninstall` el comando.

. Descargue el paquete de software de Linux Host Utilities de 32 o 64 bits en el link:https://mysupport.netapp.com/site/products/all/details/hostutilities/downloads-tab/download/61343/7.1/downloads["Sitio de soporte de NetApp"^]al host.
. Vaya al directorio en el que ha descargado el paquete de software y utilice el comando siguiente para instalarlo:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm`

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Compruebe la instalación:
+
`sanlun version`

+
[listing]
----
sanlun version 7.1.386.1644
----

