= 
:allow-uri-read: 


El archivo multipath.conf debe existir para que se inicie el daemon de multivía, pero puede crear un archivo vacío de cero bytes con el comando:
`touch /etc/multipath.conf`La primera vez que se crea este archivo, es posible que deba habilitar e iniciar los servicios multivía.

[listing]
----
# chkconfig multipathd on
# /etc/init.d/multipathd start
----
No es necesario añadir nada directamente a multipath.conf, a menos que disponga de dispositivos que no desee gestionar mediante multivía o de una configuración existente que anule los valores predeterminados. Puede agregar la siguiente sintaxis al archivo multipath.conf para excluir los dispositivos no deseados.


NOTE: Reemplace el <DevId> por la cadena WWID del dispositivo que desea excluir. Se debe usar el siguiente comando para determinar el WWID:

....
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
....
.Ejemplo
En este ejemplo, sda es el disco SCSI local que necesitamos agregar a la lista negra.

. Ejecute el siguiente comando para determinar el WWID:
+
....
# /lib/udev/scsi_id -gud /dev/sda
360030057024d0730239134810c0cb833
....
. Añada este WWID a la stanza "blacklist" en /etc/multipath.conf:
+
....
blacklist {
     wwid   360030057024d0730239134810c0cb833
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
....


Siempre debe comprobar su `/etc/multipath.conf` archivo para la configuración heredada, especialmente en la sección de valores predeterminados, que puede estar reemplazando la configuración predeterminada. La siguiente tabla muestra el valor crítico `multipathd` Parámetros para las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y alguno de estos parámetros se anula, deberán corregirse posteriormente stanzas en `multipath.conf` Que se aplican específicamente a LUN de ONTAP. Si esto no se hace, es posible que las LUN de ONTAP no funcionen según se espera. Estos valores predeterminados solo se deben anular consultando con NetApp o con el proveedor de sistemas operativos y únicamente cuando se haya comprendido completamente el impacto.
