= 
:allow-uri-read: 


El paquete de software NetApp Linux Unified Host Utilities está disponible en la link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Sitio de soporte de NetApp"^] en un archivo .rpm de 32 bits o 64 bits.

NetApp recomienda encarecidamente la instalación de Linux Unified Host Utilities, pero no es obligatorio. Las utilidades no cambian ninguna configuración en el host Linux. Las utilidades mejoran la gestión y ayudan al soporte al cliente de NetApp a recopilar información sobre la configuración.

.Pasos
. Si tiene una versión de Linux Unified Host Utilities instalada actualmente, utilice el siguiente comando para eliminarla:
+
`rpm -e netapp_linux_unified_host_utilities-7-1`

+
Para versiones anteriores de Linux Host Utilities, vaya al directorio donde se instaló el software de la utilidad de host e introduzca el `uninstall` comando.

. Descargue el paquete de software Linux Unified Host Utilities de 32 o 64 bits desde el link:https://mysupport.netapp.com/NOW/cgi-bin/software/?product=Host+Utilities+-+SAN&platform=Linux["Sitio de soporte de NetApp"^] al host.
. Vaya al directorio en el que ha descargado el paquete de software y utilice el comando siguiente para instalarlo:
+
`rpm -ivh netapp_linux_unified_host_utilities-7-1.x86_xx.rpm`

+
[listing]
----
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:netapp_linux_unified_host_utiliti################################# [100%]
----
. Compruebe la instalación:
+
`sanlun version`

+
[listing]
----
sanlun version 7.1.386.1644
----

