= 
:allow-uri-read: 


 `multipath.conf`El archivo debe existir para que se inicie el daemon multivía. Si este archivo no existe, puede crear un archivo vacío de cero bytes con el `touch /etc/multipath.conf` comando.

La primera vez que crea el `multipath.conf` archivo, es posible que deba habilitar e iniciar los servicios multivía mediante los siguientes comandos:

[listing]
----
chkconfig multipathd on
/etc/init.d/multipathd start
----
No es necesario agregar nada directamente al `multipath.conf` archivo a menos que tenga dispositivos que no desee que se gestionen con acceso multivía o que tenga una configuración existente que anule los valores predeterminados. Para excluir dispositivos no deseados, agregue la siguiente sintaxis al `multipath.conf` archivo y reemplace <DevId> por la cadena de identificador mundial (WWID) del dispositivo que desea excluir:

[listing]
----
blacklist {
        wwid <DevId>
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^hd[a-z]"
        devnode "^cciss.*"
}
----
El siguiente ejemplo determina el WWID de un dispositivo y lo agrega al `multipath.conf` archivo.

.Pasos
. Determine el WWID:
+
[listing]
----
/lib/udev/scsi_id -gud /dev/sda
----
+
[listing]
----
3600a098038314c4a433f5774717a3046
----
+
`sda` Es el disco SCSI local que desea agregar a la lista negra.

. Añada el `WWID` a la lista negra stanza en `/etc/multipath.conf`:
+
[source, cli]
----
blacklist {
     wwid   3600a098038314c4a433f5774717a3046
     devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
     devnode "^hd[a-z]"
     devnode "^cciss.*"
}
----


Compruebe siempre el `/etc/multipath.conf` archivo, especialmente en la sección de valores predeterminados, para ver la configuración heredada que podría estar anulando la configuración predeterminada.

La siguiente tabla muestra `multipathd` los parámetros críticos de las LUN de ONTAP y los valores necesarios. Si un host está conectado a LUN de otros proveedores y cualquiera de estos parámetros se anula, deben corregirse mediante estrofas más adelante en `multipath.conf` el archivo que se aplican específicamente a las LUN de ONTAP. Sin esta corrección, es posible que las LUN de ONTAP no funcionen como se espera. Solo debe sobrescribir estos valores predeterminados en consulta con NetApp, el proveedor del sistema operativo o ambos, y solo cuando se comprenda completamente el impacto.
