= 
:allow-uri-read: 


Puede configurar NVMe/FC con adaptadores FC Broadcom/Emulex o Marvell/Qlogic. También debe descubrir manualmente los subsistemas y espacios de nombres NVMe/TCP.

[role="tabbed-block"]
====
.Broadcom/Emulex
Configuración de NVMe/FC para un adaptador Broadcom/Emulex.

--
.Pasos
. Compruebe que está utilizando el modelo de adaptador admitido:
+
.. Mostrar los nombres de los modelos:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modelname
----
+
Debe ver la siguiente salida:

+
[listing]
----
LPe36002-M64
LPe36002-M64
----
.. Mostrar las descripciones del modelo:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/modeldesc
----
+
Debería ver un resultado similar al siguiente ejemplo:

+
[listing]
----
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
Emulex LightPulse LPe36002-M64 2-Port 64Gb Fibre Channel Adapter
----


. Compruebe que está utilizando la Broadcom recomendada `lpfc` firmware y controlador de bandeja de entrada:
+
.. Mostrar la versión del firmware:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/fwrev
----
+
El siguiente ejemplo muestra las versiones de firmware:

+
[listing]
----
14.4.317.10, sli-4:6:d
14.4.317.10, sli-4:6:d
----
.. Mostrar la versión del controlador de la bandeja de entrada:
+
[source, cli]
----
cat /sys/module/lpfc/version`
----
+
El siguiente ejemplo muestra una versión del controlador:

+
[listing]
----
0:14.4.0.2
----


+
Para obtener la lista actual de versiones de firmware y controladores de adaptador compatibles, consulte la link:https://mysupport.netapp.com/matrix/["Herramienta de matriz de interoperabilidad"^].

. Compruebe que la salida esperada de `lpfc_enable_fc4_type` está definida en `3`:
+
[source, cli]
----
cat /sys/module/lpfc/parameters/lpfc_enable_fc4_type
----
. Compruebe que puede ver los puertos de iniciador:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_name
----
+
El siguiente ejemplo muestra las identidades del puerto:

+
[listing]
----
0x100000109bf044b1
0x100000109bf044b2
----
. Compruebe que los puertos de iniciador estén en línea:
+
[source, cli]
----
cat /sys/class/fc_host/host*/port_state
----
+
Debe ver la siguiente salida:

+
[listing]
----
Online
Online
----
. Compruebe que los puertos de iniciador NVMe/FC estén habilitados y que los puertos de destino estén visibles:
+
[source, cli]
----
cat /sys/class/scsi_host/host*/nvme_info
----
+
.Muestra el ejemplo
[%collapsible]
=====
[listing, subs="+quotes"]
----
NVME Initiator Enabled
XRI Dist lpfc2 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc2 WWPN x100000109bf044b1 WWNN x200000109bf044b1 DID x022a00 *ONLINE*
NVME RPORT       WWPN x202fd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x021310 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x202dd039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020b10 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000810 Cmpl 0000000810 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007b098f07 Issue 000000007aee27c4 OutIO ffffffffffe498bd
        abort 000013b4 noxri 00000000 nondlp 00000058 qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000013b4 Err 00021443

NVME Initiator Enabled
XRI Dist lpfc3 Total 6144 IO 5894 ELS 250
NVME LPORT lpfc3 WWPN x100000109bf044b2 WWNN x200000109bf044b2 DID x021b00 *ONLINE*
NVME RPORT       WWPN x2033d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x020110 *TARGET DISCSRVC ONLINE*
NVME RPORT       WWPN x2032d039eaa7dfc8 WWNN x202cd039eaa7dfc8 DID x022910 *TARGET DISCSRVC ONLINE*

NVME Statistics
LS: Xmt 0000000840 Cmpl 0000000840 Abort 00000000
LS XMIT: Err 00000000  CMPL: xb 00000000 Err 00000000
Total FCP Cmpl 000000007afd4434 Issue 000000007ae31b83 OutIO ffffffffffe5d74f
        abort 000014a5 noxri 00000000 nondlp 0000006a qdepth 00000000 wqerr 00000000 err 00000000
FCP CMPL: xb 000014a5 Err 0002149a
----
=====


--
.Marvell/QLogic
--
Configure NVMe/FC para un adaptador Marvell/QLogic.


NOTE: El controlador de bandeja de entrada nativo qla2xxx incluido en el kernel Rocky Linux tiene las últimas correcciones. Estas correcciones son esenciales para la compatibilidad con ONTAP.

.Pasos
. Compruebe que está ejecutando las versiones de firmware y controlador del adaptador compatibles:
+
[source, cli]
----
cat /sys/class/fc_host/host*/symbolic_name
----
+
El siguiente ejemplo muestra las versiones del controlador y del firmware:

+
[listing]
----
QLE2742 FW:v9.14.00 DVR:v10.02.09.200-k
QLE2742 FW:v9.14.00 DVR:v10.02.09.200-k
----
. Compruebe que `ql2xnvmeenable` está configurado. Esto permite que el adaptador Marvell funcione como iniciador NVMe/FC:
+
[source, cli]
----
cat /sys/module/qla2xxx/parameters/ql2xnvmeenable
----
+
La salida esperada es 1.



--
====