= 
:allow-uri-read: 


Después de ejecutar `mbralign` En discos para corregir la alineación de MBR con el kit de herramientas PowerShell en sistemas operativos invitados Linux mediante el cargador de arranque GRUB, debe reinstalar GRUB para asegurarse de que el sistema operativo «guest» se arranque correctamente.

.Acerca de esta tarea
El cmdlet de PowerShell Toolkit se ha completado en el archivo VHD de la máquina virtual. Este procedimiento se aplica sólo a los sistemas operativos invitados Linux que utilizan la Loader de inicio de GRUB y `SystemRescueCd`.

.Pasos
. Monte la imagen ISO del disco 1 de los CD de instalación para la versión correcta de Linux para la máquina virtual.
. Abra la consola de la máquina virtual en Hyper-V Manager.
. Si la VM se está ejecutando y congelando en la pantalla de GRUB, haga clic en el área de visualización para asegurarse de que está activa, luego seleccione el icono de la barra de herramientas *Ctrl-Alt-Delete* para reiniciar la VM. Si la máquina virtual no está en ejecución, inícielo y, a continuación, haga clic inmediatamente en el área de visualización para asegurarse de que esté activa.
. Tan pronto como vea la pantalla de bienvenida del BIOS de VMware, pulse la tecla *Esc* una vez. Aparece el menú de inicio.
. En el menú de inicio, seleccione *CD-ROM*.
. En la pantalla de inicio de Linux, introduzca: `linux rescue`
. Tome los valores predeterminados de Anaconda (las pantallas de configuración azul/roja). Las redes son opcionales.
. Inicie GRUB introduciendo: `grub`
. Si sólo hay un disco virtual en esta máquina virtual, o si hay varios discos y el primero es el disco de inicio, ejecute los siguientes comandos de GRUB:
+
[listing]
----
root (hd0,0)
setup (hd0)
quit
----
+
Si tiene varios discos virtuales en el equipo virtual, y el disco de arranque no es el primer disco, o está solucionando GRUB arrancando desde el disco duro virtual de backup mal alineado, introduzca el comando siguiente para identificar el disco de arranque:

+
[listing]
----
find /boot/grub/stage1
----
+
Después, ejecute los siguientes comandos:

+
[listing]
----
root (boot_disk,0)
setup (boot_disk)
quit
----
+

NOTE: En `setup (boot_disk)`, `boot_disk` es un marcador de posición para el identificador de disco real del disco de inicio.



. Pulse *Ctrl-D* para cerrar la sesión.
+
El rescate de Linux se cierra y luego se reinicia.


