= 
:allow-uri-read: 


Después de ejecutar `mbralign` En discos para corregir la alineación de MBR con el kit de herramientas PowerShell en sistemas operativos invitados Linux mediante el cargador de arranque GRUB, debe reinstalar GRUB para asegurarse de que el sistema operativo «guest» se arranque correctamente.

El cmdlet de PowerShell Toolkit se ha completado en el archivo VHD de la máquina virtual. Este tema se aplica sólo a los sistemas operativos invitados Linux que utilizan el gestor de arranque GRUB y. `SystemRescueCd`.

. Monte la imagen ISO del disco 1 de los CD de instalación para la versión correcta de Linux para la máquina virtual.
. Abra la consola de la máquina virtual en Hyper-V Manager.
. Si la VM se está ejecutando y se cuelga en la pantalla de GRUB, haga clic en el área de visualización para asegurarse de que está activa y, a continuación, haga clic en el icono de la barra de herramientas *Ctrl-Alt-Delete* para reiniciar la VM. Si la máquina virtual no está en ejecución, inícielo y, a continuación, haga clic inmediatamente en el área de visualización para asegurarse de que esté activa.
. Tan pronto como vea la pantalla de bienvenida del BIOS de VMware, pulse la tecla *Esc* una vez. Aparece el menú de inicio.
. En el menú de inicio, seleccione *CD-ROM*.
. En la pantalla de inicio de Linux, introduzca: `linux rescue`
. Tome los valores predeterminados de Anaconda (las pantallas de configuración azul/roja). Las redes son opcionales.
. Inicie GRUB introduciendo: `grub`
. Si sólo hay un disco virtual en esta VM, o si hay varios discos, pero el primero es el disco de arranque, ejecute los siguientes comandos de GRUB:


[listing]
----
root (hd0,0)
setup (hd0)
quit
----
Si tiene varios discos virtuales en la VM y el disco de arranque no es el primer disco, o si está reparando GRUB arrancando desde el disco duro virtual de copia de seguridad mal alineado, introduzca el siguiente comando para identificar el disco de arranque:

[listing]
----
find /boot/grub/stage1
----
Después, ejecute los siguientes comandos:

[listing]
----
root (boot_disk,0)
setup (boot_disk)
quit
----

NOTE: Tenga en cuenta que `boot_disk`, arriba, es un marcador de posición para el identificador de disco real del disco de arranque.

. Pulse *Ctrl-D* para cerrar la sesión.


El rescate de Linux se cierra y luego se reinicia.
