= 
:allow-uri-read: 


Puede iniciar el sistema operativo Windows mediante un arranque local o un arranque SAN. NetApp recomienda utilizar un arranque SAN si es compatible con su configuración.

[role="tabbed-block"]
====
.Arranque local
--
Realice un inicio local instalando el sistema operativo Windows en el disco duro local (SSD, SATA, RAID, etc.).

--
.Arranque SAN
--
Si elige usar arranque SAN, debe ser compatible con su configuración.


NOTE: Puede utilizar los ajustes de configuración proporcionados en este procedimiento para configurar los clientes de nube conectados a link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^] y.link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html["Amazon FSX para ONTAP"^]

.Antes de empezar
Utilice https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Windows, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.

.Pasos
. Asignar el LUN de arranque SAN al host.
+
Consulte link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestión del almacenamiento san"^].

. Verifique que haya varias rutas disponibles.
+

NOTE: Las rutas múltiples solo quedan disponibles cuando el sistema operativo del host está activo y en ejecución en las rutas.

. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Reinicie el host para verificar que el inicio se ha realizado correctamente


--
====