= Paso 1: Opcionalmente, habilite el arranque SAN
:allow-uri-read: 




== Paso 1: Opcionalmente, habilite el arranque SAN

Puede arrancar el sistema operativo Windows utilizando un arranque local o un arranque SAN.  NetApp recomienda utilizar un arranque SAN para simplificar la implementación y mejorar la escalabilidad.

[role="tabbed-block"]
====
.Arranque SAN
--
Si elige usar arranque SAN, debe ser compatible con su configuración.

.Antes de empezar
Utilice https://mysupport.netapp.com/matrix/#welcome["Herramienta de matriz de interoperabilidad"^] para verificar que el sistema operativo Windows, el adaptador de bus de host (HBA), el firmware del HBA, el BIOS de arranque del HBA y la versión de ONTAP admiten el arranque SAN.

.Pasos
. link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Cree un LUN de arranque SAN y asígnelo al host"^].
. Habilite el arranque SAN en el BIOS del servidor para los puertos a los que se asigna la LUN de arranque SAN.
+
Para obtener información acerca de cómo activar el BIOS HBA, consulte la documentación específica de su proveedor.

. Compruebe que la configuración se haya realizado correctamente. Para ello, reinicie el host y verifique que el sistema operativo esté activo y en ejecución.


--
.Arranque local
--
Realice un arranque local instalando el sistema operativo Windows en el disco duro local, por ejemplo, en una unidad SSD, SATA o RAID.

--
====